### ISSUE TITLE
Add possibility to manually update if you have previously opted out of auto-updates

### ISSUE THREAD

**Issue by leenamba** [kontena/lens#3794]
Add possibility to manually update from Lens if you have previously dismissed of auto-updates.

**Why is this needed**:
If you have previously dismissed auto-updates then you will no longer receive update possibilities. Within Lens you will not be notified if there are new versions available.

**Environment you are Lens application on:**
Lens 4.0.x, 4.1.x, 4.2.x

**Comment by Nokel81** [comment]
That sounds like a bug, what is wrong with the "check for updates" button in the tray menu or restarting lens?
