### ISSUE TITLE
Blue screen of death when trying to connect

### ISSUE THREAD

**Issue by HarelM** [kontena/lens#3796]
**Describe the bug**
When trying to connect using lens 5.2 Windows crashes to BSOD mode with kernel mode heap corruption.

**To Reproduce**
1. Go to a cluster and connect
2. Wait for crash

**Expected behavior**
No BSOD.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2 - downloaded it today
- OS: [e.g. OSX] windiws 10
- Installation method (e.g. snap or AppImage in Linux): exe file

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
This config works well with version 4.2.5
```
your kubeconfig here
```

**Additional context**
Upgraded from 4.2.5 since I had connection problems in 5.1 version. Hoped they will be solved in 5.2 version and they were, but I still can't use latest version...
Related to: #3226

**Comment by wanjuntham** [comment]
> kernel mode heap corruption.

I have the same BSOD as you, and then I did a reinstall for Lens and now the BSOD issue is gone.

Can you give it a try?

**Comment by HarelM** [comment]
I didn't see it in Windows add or remove programs. Simply run the installer again? Or did you delete the old installation?

**Comment by wanjuntham** [comment]
> I didn't see it in Windows add or remove programs. Simply run the installer again? Or did you delete the old installation?

I simply ran the installer again without uninstalling the existing (problematic) Lens.

**Comment by JanSchep** [comment]
I have the same issue. Got now three BSODs this week. But it will obviously not happen every time. I had two BSODs with v5.2.0 and one also with v5.2.1.

**Comment by HarelM** [comment]
After reinstall I still get it when trying to connect :-(

**Comment by wanjuntham** [comment]
BSOD is happening again for me as well even after reinstalling. 😢

**Comment by JanSchep** [comment]
Just as a side note, I added my kubeconfig via copy&paste instead of using an already existing kubeconfig file.
For me this behavior is a blocker 😢

**Comment by ymesika** [comment]
Also experiencing this BSOD after connecting to a cluster. Happen since `5.2.0` and with the recent `5.2.2`.
I've been try uninstalling with total cleanup of any Lens leftover but still BSOD after few seconds when listing pods.

**Comment by DougTrajano** [comment]
I'm facing this issue as well.

**Comment by wanjuntham** [comment]
Anyone looking into this issue?

**Comment by Nokel81** [comment]
5.2.4 has not been released, would anyone mind checking if that version resolved this issue?

**Comment by ymesika** [comment]
@Nokel81 `5.2.4` seems like resolves this after few minutes working with my cluster. In previous version Windows crashed after few seconds.

**Comment by HarelM** [comment]
I think I can confirm this is now solved in 5.2.4 which I just downloaded this morning.
If a blue screen will happen I'll report back here, the scenario that reproduced this easily in the previous version seems to be working as expected.

**Comment by Nokel81** [comment]
Excellent. I will close this issue then. Hopefully we won't have to reopen.

**Comment by wanjuntham** [comment]
Actually this happens again to me once, when I exit Lens via Files > Exit
