### ISSUE TITLE
5.2 release don't work in OS X El Capitan

### ISSUE THREAD

**Issue by TaeHyunChi** [kontena/lens#3805]
**Describe the bug**
Not starting kubeproxy after updating recent 5.2 release
MacBook Pro (Retina, 15-inch, Late 2013) OS X El Capitan

I want to know how to reinstall older version...

<img width="363" alt="Lens 2021-09-15 15-17-36" src="https://user-images.githubusercontent.com/4789710/133380704-0b453c32-187e-4ea2-9507-221595b72407.png">

**Comment by ericlebail** [comment]
Hello,
The error also happen on MacOs Catalina version 10.15.7
The app starts but cannot connect to any cluster. (Timeout error)

**Comment by Nokel81** [comment]
Are you able to provide any logs? https://docs.k8slens.dev/main/faq/#where-can-i-find-application-logs

**Comment by TaeHyunChi** [comment]
Can you provide where i can find the log files ?
If you can, I could send the logs

**Comment by Nokel81** [comment]
The link has the file paths for each of the major OS's

**Comment by TaeHyunChi** [comment]
[Lens-App-Log.zip](https://github.com/lensapp/lens/files/7175110/Lens-App-Log.zip)

@Nokel81 This is the application logs
Please check it.

**Comment by ericlebail** [comment]
[Lens-log.zip](https://github.com/lensapp/lens/files/7175737/Lens-log.zip)

Application Logs for MacOs Catalina

**Comment by yueyangtian** [comment]
![image](https://user-images.githubusercontent.com/25261548/133777055-9eb7bc0f-4418-4233-bc95-4add4eb166a6.png)
I think is a seam question :(
I can't get any dashboard and pending in "Authentication proxy started"
here is some debug info
info:    ┏ [CLUSTER]: refresh +16s
info:    ┃ [1] {
info:    ┃ [2]   id: '9ce947d17651b4a65f51e9674657ffa8',
info:    ┃ [3]   name: 'minikube',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +14s
info:    ┃ [1] {
info:    ┃ [2]   id: '4f16509c077fa76ea10360cf9d887a1d',
info:    ┃ [3]   name: 'cls-69xgyyvt-100019422326-context-default',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +16s
info:    ┃ [1] {
info:    ┃ [2]   id: '9ce947d17651b4a65f51e9674657ffa8',
info:    ┃ [3]   name: 'minikube',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +14s
info:    ┃ [1] {
info:    ┃ [2]   id: '4f16509c077fa76ea10360cf9d887a1d',
info:    ┃ [3]   name: 'cls-69xgyyvt-100019422326-context-default',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +16s
info:    ┃ [1] {
info:    ┃ [2]   id: '9ce947d17651b4a65f51e9674657ffa8',
info:    ┃ [3]   name: 'minikube',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
info:    ┏ [CLUSTER]: refresh +14s
info:    ┃ [1] {
info:    ┃ [2]   id: '4f16509c077fa76ea10360cf9d887a1d',
info:    ┃ [3]   name: 'cls-69xgyyvt-100019422326-context-default',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }

Mac OS info
Big Sur 11.5.2

**Comment by Nokel81** [comment]
If you try the latest beta is this resolved? https://k8slens.slack.com/archives/CDR6AHSCC/p1637267945129200?thread_ts=1637250200.128700&cid=CDR6AHSCC
