### ISSUE TITLE
the left icon is not displayed after opening a cluster

### ISSUE THREAD

**Issue by iyuhptop** [kontena/lens#3806]
**Describe the bug**
the left icon is not displayed after opening a cluster

**To Reproduce**
1.  open your cluster with lens
2. left menu not shown a icon

**Expected behavior**
an icon should show in left menu

**Screenshots**
![image](https://user-images.githubusercontent.com/14036170/133382683-9e91e723-531c-46d0-99fb-20508038b241.png)

**Environment (please complete the following information):**
- Lens Version:   
Lens: 5.2.0-latest.20210908.1
Electron: 12.0.17
- OS:  macOS Big Sur. 11.5.2
- Installation method (e.g. snap or AppImage in Linux): download from official website

I also reinstalled and the bug still here

**Comment by aleksfront** [comment]
Thanks for reporting this! The issue is closed here https://github.com/lensapp/lens/pull/3765 and will be available soon.
