### ISSUE TITLE
Refactor entity details menu

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#3808]
There are too many icons located in the details panel without quick explanation, it's necessary to hover to see some meaningful tooltip. All those options can be moved to dropdown menu.

![too many icons](https://user-images.githubusercontent.com/9607060/133398182-eeeed191-1467-47cf-b181-4dacba2e2ad5.png)

**Comment by Nokel81** [comment]
Is this really necessary, the tooltips appear very fast and the icons are quite descriptive (except for settings, which I propose we change to the standard icon in #4425 )
