### ISSUE TITLE
Pin Icon on left hand side menu (next to name / icon)

### ISSUE THREAD

**Issue by msa0311** [kontena/lens#3811]
Let's add a hotbar pin icon next to the cluster (catalog) name / icon on left hand side menu.

e.g. next to minikube:
![image](https://user-images.githubusercontent.com/26629812/133435653-fab07005-2598-419d-bbc1-affcd784c8f5.png)

**Comment by Nokel81** [comment]
Discussed with @aleksfront, decided that having it part of the context menu would be best. Due to space constraints.
