### ISSUE TITLE
Not able to load information for one cluster

### ISSUE THREAD

**Issue by Irmius** [kontena/lens#3829]
**Describe the bug**
Trying to open cluster UI shows a blank page, if I trying to reconnect it shows connecting forever
It is only with one cluster. Cluster name "geo-project-test"
It started to happen After release 5.2.1 

**To Reproduce**
1. Open cluster

**Expected behavior**
It should open the cluster

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.1
- OS: [Linux Manjaro]
- Installation method (AppImage in Linux):

**Logs:**
![Screenshot_20210917_113026](https://user-images.githubusercontent.com/67007713/133751345-d40a17be-24db-494c-9f1c-6e15de6ca6e1.png)
![Screenshot_20210917_113232](https://user-images.githubusercontent.com/67007713/133751517-05228cda-11d5-4fd3-8ec1-22918cc37246.png)
.
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
Add any other context about the problem here

**Comment by trombini77** [comment]
In the new release Lens Setup 5.2.1-latest.20210916.2.exe (Windows version) I had the same issue, before it was working normaly and after the update to version 5.2.1 it can´t read more the .kube/config without issue.
I really don´t guess is a .kube/config malformaed because it was not changed because of lens upgrade and my kubectl is working normally.

**Comment by trombini77** [comment]
Thanks!
I got the fix 5.2.2-latest.20210917.1.exe (Windows version) and now it works fine.

**Comment by Irmius** [comment]
For me it still doesn't work

**Comment by Irmius** [comment]
> For me it still doesn't work

Works! just needed to try login to the cluster again!

**Comment by Irmius** [comment]
It was wrong cluster sorry!

**Comment by msa0311** [comment]
@Irmius means you are still seeing the issue described above?

**Comment by Irmius** [comment]
> @Irmius means you are still seeing the issue described above?

Yes

**Comment by Lp-Francois** [comment]
Hello, 
Same problem here nothing is displayed, it happens since yesterday.
in the console:
`[mobx] uncaught error in 'Reaction[Reaction]' ReferenceError: Cannot access 'activeEntityDisposer' before initialization`

Other clusters are loading.

OS: Mac Catalina
build lens:  5.2.2-latest.20210917.1

**Comment by dq-vizy** [comment]
I had this same issue with one specific cluster not loading (but loading with previous Lens versions). After nuking `~/.kube` , `~/.k8slens`, and `~/Library/Application Support/Lens` directories I am now able to load the cluster again.

**Comment by Lp-Francois** [comment]
Exactly the same as @dq-vizy 
On mac I deleted this repo: `~/Library/Application Support/Lens`, and the `~./kube/config`
And it started to work again. 
1h later it did the same bug. Doing `rm -r ~/Library/Application Support/Lens` solved it (without the need to delete `.kube/config`)

PS: _That made me realize how much Lens is useful in my day-to-day work, I love the tool_

**Comment by vudzero** [comment]
I get the same problem, could connect once to my cluster and now it does not load anymore, I get a blank screen.

Lens: 5.2.3-latest.20210921.1 (Apple M1 version)
MacOS: Big Sur 11.3 / Apple M1

Removing the folder `rm -r ~/Library/Application\ Support/Lens` does fix the issue

**Comment by hazim1093** [comment]
Having the same problem with version `5.2.3-latest.20210921.1` on MacOS with an Intel chipset. Also with version 5.2.2 (i.e. upgrading didn't help)  
It suddenly stops loading information for one cluster. 

Happened before on an older version, deleting the application and `~/Library/Application Support/Lens` worked then. But none of that seems to make a difference now. 

The logs, when running lens with `DEBUG=true`, seem happy and able to refresh the cluster, but nothing is displayed on the UI.

**Comment by florianb** [comment]
Same issue here – happens repeatable after restarting Lens, only nuking `~/.config/Lens` helps.

```json
{
    "error": "Error: Could not call remote method 'send'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: TypeError: Object has been destroyed
    at Object.b.send (electron/js2c/browser_init.js:161:2461)
    at /opt/Lens/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:454:71
    at IpcMainImpl.<anonymous> (/opt/Lens/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:313:27)
    at IpcMainImpl.emit (events.js:315:20)
    at IpcMainImpl.EventEmitter.emit (domain.js:467:12)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.emitter.emit (/opt/Lens/resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)\n"
}
```

OS: Ubuntu 20.04.3 LTS

I guess adding sentry.io to this project is no option?

**Comment by Nokel81** [comment]
Could anyone try turning on the "Use Bundled kubectl" option and then fully quit lens (including the tray icon and all residual processes). Fire up lens again and try and connect. Does that solve the issue?

**Comment by florianb** [comment]
Thank you for your quick response @Nokel81 – as far as i can tell for now switching 

![Bildschirmfoto vom 2021-09-23 15-36-31](https://user-images.githubusercontent.com/983507/134517074-fffa5871-7604-4674-84d2-9b64c9f52a8b.png)

`off`, trying to connect, then switching it `on` again fixed it for now.

I did only some Lens restarts though, i will have an eye on it and report as soon as i have a longer user experience.

**Comment by hazim1093** [comment]
No luck turning it on and off, and I don't have `~/.config/Lens` directory on Mac. 
Apparently now I am having the same "blank" issue for all my clusters in Lens (from before turning binary download on and off)

**Comment by florianb** [comment]
Still running (after reboot).

@hazim1093 – sorry to hear, i guess you'll havat to delete `rm -r ~/Library/Application\ Support/Lens` on a mac, as mentiioned before:

> I get the same problem, could connect once to my cluster and now it does not load anymore, I get a blank screen.
> 
> Lens: 5.2.3-latest.20210921.1 (Apple M1 version)
> MacOS: Big Sur 11.3 / Apple M1
> 
> Removing the folder `rm -r ~/Library/Application\ Support/Lens` does fix the issue

**Comment by Nokel81** [comment]
I actually meant leaving it off...

**Comment by hazim1093** [comment]
@florianb Yes even after that. 

It's quite random for me, happens every other day. I need to delete `~/Library/Application\ Support/Lens`, `~/.k8slens` and the application and then reinstall it again. 
But that doesn't work everytime either, sometimes I need to do that multiple times

**Comment by gfviegas** [comment]
Still happenning and it's always with one particular cluster. Removed the folders mentioned above multiple times and resinstalled the application but nothing happens.


```
Lens: 5.2.4-latest.20210923.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.

on MacOS Big Sur v11.6 with intel chipset
```

**Comment by Nokel81** [comment]
Just to clarify the symptom is when you click on the cluster is says "connecting" and then that disappears and nothing else is show? Would you be able to attach some renderer logs by copying them from the devtools clusters.

**Comment by gfviegas** [comment]
Exactly.


Somehow it loaded 10min ago and Im afraid of not loading again so I'm gonna get a little work done before trying to reproduce the issue again hah...

But I saw the logs when I was investigating earlier today and I recall the logs saying the cluster is ready and no error at all was shown.

If I recall correctly it showed exactly as this screenshot
![image](https://user-images.githubusercontent.com/6178801/135477391-af66776a-125e-41a1-af02-1d71191093d8.png)


Later today I will try to reproduce the issue but it's happening randomly. Sometimes is this cluster A, sometimes is this cluster B, sometimes the cluster C, but always only one at time.

**Comment by Nokel81** [comment]
By that screenshot do you mean that that is what you saw when it didn't work?

**Comment by gfviegas** [comment]
> By that screenshot do you mean that that is what you saw when it didn't work?

Yes, and nothing else

**Comment by Nokel81** [comment]
Ah so you never see a log line for the form `[LENS-VIEW]: loaded from http://6bd6b...localhost:<port>`?

**Comment by christhomas** [comment]
> I had this same issue with one specific cluster not loading (but loading with previous Lens versions). After nuking `~/.kube` , `~/.k8slens`, and `~/Library/Application Support/Lens` directories I am now able to load the cluster again.

Deleting the `~/.k8slens`, and `~/Library/Application Support/Lens` folder mentioned here was enough to fix it for me. Thanks!

**Comment by shaneiseminger** [comment]
I had the same thing happen too after renaming a few clusters and deleting one cluster in GKE that was no longer in use (I had removed it from Lens first). Deleting those directories fixed it for me as well.

**Comment by Irmius** [comment]
Deleting folders helps to solve issue,  wrong is that you are losing configuration workspaces etc.
And it doesn't prevent recurring the issue. As I'm facing the same issue again. Using lates version 5.2.5

**Comment by Nokel81** [comment]
Duplicate of (newer) #4018
