### ISSUE TITLE
Container state block color difficult for colorblind person

### ISSUE THREAD

**Issue by iammoen** [kontena/lens#3843]
**What would you like to be added**:
I would love if the little boxes that denote status of containers in a pod were either customizable or the color difference a little greater as I have a hard time distinguishing.

**Why is this needed**:
I am red green colorblind.

**Environment you are Lens application on:**

MacOS

**Comment by iammoen** [comment]
Burned me again today.

**Comment by amajot** [comment]
+1

**Comment by ryangood** [comment]
+1

**Comment by poelstra-sioux** [comment]
As an example of how red/green colorblind people experience the difference between the colors:
![image](https://user-images.githubusercontent.com/86651328/231392191-3e2abbde-4314-4ca6-b1d3-6508485020a1.png)

(pulled through a similator)

What would already help a great deal, is if the luminance (gray-scale value) of the indicator differs. 

Practically speaking: **making the orange a bit darker** and/or the **green a bit lighter** will make a huge difference.
