### ISSUE TITLE
Material Icons font flickering on load

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#3850]
There is a noticeable flickering of material icon font happening on app load and then on cluster iframe load. This caused annoying layout shift.

Material Icons should be preloaded before app/cluster load or replaced by svg versions.

https://user-images.githubusercontent.com/9607060/134121591-94784aec-8cb6-42cf-a723-af0b3222e6f1.mov

**Comment by Nokel81** [comment]
I would prefer using svg versions.

**Comment by jweak** [comment]
> I would prefer using svg versions.

I tried converting all the material icons to SVG versions but there are few issues with that.

1. Not all of the font icons that are used in the app are in the `@material-ui/icons 4.x` package which we import now and it hasn't been updated in 10 months so I don't think they will backported. They are in the version 5.
2. The new icons from Material icons 5 depends on material-ui-core version 5. So it they need to updated at the same time.
3. SVG's need to be imported one-by-one `import WarningIcon from "@mui/icons-material/Warning"` which means the user can't just add a string to our icon component and be sure that it works. We could also import all of the icons SVG's but the package size is like 10MB and it might slow loading the app considerably. The good thing about would be that we could making the `Icon.material` prop type safe.

So I feel like we should postpone this to after updating the Material UI to version 5. 

Created an issue https://github.com/lensapp/lens/issues/3945 for updating the material UI.
