### ISSUE TITLE
Pod memory usage is always double the value of "kubectl top pod"

### ISSUE THREAD

**Issue by rscanesilva** [kontena/lens#3855]
When looking at the pod Memory usage, the numbers are different than in  kubectl top pod,

1. Go to the pod
2. Click on it
3. See the Memory usage
4. Compare it with ```kubectl top pod```

**Expected behavior**
The cpu usage is the same

**Screenshots**
<center><img src="https://i.ibb.co/j8bmSkk/lens.png"></center>
<center><img src="https://i.ibb.co/stMCcjH/toppods.png"></center>

**Environment (please complete the following information):**
- Lens Version: 5.2.o0
- OS: windows 10
- Installation method .exe

**Comment by Nokel81** [comment]
Do you have multiple metric providers feeding into prometheus?

**Comment by rscanesilva** [comment]
I'll check
