### ISSUE TITLE
Kernel Mode Heap Corruption

### ISSUE THREAD

**Issue by georgeanderson** [kontena/lens#3859]
**Describe the bug**
Started getting Kernel Mode Heap Corruption BSOD on Windows 10 today. I was using 5.2.* version and after getting the error I updated to version 5.2.3-latest20210921.1. The error is still happening though.

**To Reproduce**
1. Go to an existing 'Cluster'
2. Go to Charts
2. Click on a Chart (in my case Redis)
3. Click on Install and select version
3. A screen will open at the bottom (same place as the terminal window) with options to select namespace, name etc.

**Expected behavior**
The steps above were what I did the first 2 times the error occurred. After that I upgrade to latest version and saw the issue just navigating in the Lens and trying to click on namespaces.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
  - ![image](https://user-images.githubusercontent.com/571682/134215695-cb19c8b3-14ff-43d3-99eb-ea25eb6e12d1.png)
- OS: Windows 10
- Installation method: chocolatey

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
{
  "preferences": {},
  "apiVersion": "v1",
  "kind": "Config",
  "current-context": "redis-lab-npdp1-pks",
  "contexts": [
    {
      "context": {
        "cluster": "redis-lab-npdp1-pks",
        "user": "ddd3e101-2e6d-4faa-ab00-da24cab1847d"
      },
      "name": "redis-lab-npdp1-pks"
    }
  ],
  "clusters": [
    {
      "cluster": {
        "server": "https://10.146.252.203:8443",
        "certificate-authority-data": "REDACTED"
      },
      "name": "redis-lab-npdp1-pks"
    }
  ],
  "users": [
    {
      "name": "ddd3e101-2e6d-4faa-ab00-da24cab1847d",
      "user": {
        "token": "REDACTED"
      }
    }
  ]
}
```

**Additional context**
Never had any issues with Lens until this morning. Thanks for the great tool you guys provide and I hope this bug report can help finding this nasty bug.

**Comment by Nokel81** [comment]
What build of windows are you running?

**Comment by georgeanderson** [comment]
By coincidence my machine got updated this morning. It turns out the issue is no longer happening. I'm sad I haven't saved this information from yesterday but I am happy the issue is gone. I know it's no longer useful but here is the current version anyways. You can close this. Thank you so much!

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363

**Comment by Nokel81** [comment]
I will close this then as it might have been a electron/windows interaction bug.

However, what do you mean by "installed lens via chocolaty"?

**Comment by georgeanderson** [comment]
I installed with `choco install lens` provided by https://chocolatey.org/. Just realized this option is not listed in the documentation. I not only installed that way as I also do upgrades from time to time using the same method (`choco upgrade lens`).
