### ISSUE TITLE
Upgrading to 5.x via home-brew breaks lens

### ISSUE THREAD

**Issue by steebchen** [kontena/lens#3870]
**Describe the bug**

I'm getting this after upgrading lens to 5.x via brew.

![image](https://user-images.githubusercontent.com/5013932/134385924-24df74ee-fb9c-4253-bbaa-96f1c2fffd5d.png)

I get this message occasionally after revoking from standby, but closing the app fully and re-opening always fixed the issue, but it doesn't now.

**To Reproduce**
I guess this could be tricky, I used 4.x via brew, then upgraded to 5.x, then ran into that issue.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens-5.2.3-latest.20210921.1.dmg
- OS: macOS Big Sur
- Installation method: HomeBrew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

If I remove my kubeconfig the error still occurs, so I assume it does not have anything to do with that.

**Additional context**

**Comment by Nokel81** [comment]
Could you try renaming your `/Library/Application Support/Lens` folder and then trying to launch lens again?

**Comment by MattMencel** [comment]
For me all it took was opening "Activity Monitor" and stopping any running Lens processes. Then Lens launched fine.

**Comment by Nokel81** [comment]
Sounds good, could be related to how homebrew does upgrades (which I don't know how since the homebrew is community provided). That not all the processes were stopped before the upgrade.

**Comment by steebchen** [comment]
> Could you try renaming your /Library/Application Support/Lens folder and then trying to launch lens again?

I did try that, but that didn't solve the issue.

I ended up uninstalling it and manually downloading and running the .dmg.

I also uninstalled it and re-installed via brew and now it magically works (maybe because it was now closed properly as per Matt's idea) 😅

**Comment by Nokel81** [comment]
Yeah that probably is it. If an old process is still around then trying to open lens will start that one and it is certainly trying to communicate on the wrong port.

**Comment by Nokel81** [comment]
Closing as this is about an older version of Lens
