### ISSUE TITLE
Slack workspace invite link expired

### ISSUE THREAD

**Issue by worldofgeese** [kontena/lens#3871]
The Slack workspace invite link is broken as of the 22nd of September:

![billede](https://user-images.githubusercontent.com/59834693/134417288-f2ba4f60-a965-4b82-8b50-2f4e4ca6b06b.png)

**Comment by Nokel81** [comment]
Which link are you talking about? All the slack URLs that I could find in our repo and on our website all seem to work.

**Comment by alexifm** [comment]
Any slack link I hit (in the app, on the website) hits that inactive page.

**Comment by babs** [comment]
https://k8slens.dev/ Community > Slack link leads to an invite error also but the link works if you already have joined the slack community.
[use private mode to reproduce]
https://k8slens.slack.com/join/shared_invite/zt-1cw4vfjkx-962UYNgdQILW7qdbp2GVhA#/shared-invite/error
