### ISSUE TITLE
No longer seeing a blue 'LED' on connected clusters in the Hotbar

### ISSUE THREAD

**Issue by alex-hempel** [kontena/lens#3872]
**Describe the bug**
Since 5.2.2 I am no longer seeing a blue 'LED' in the Hotbar on clusters that I have connected to.

**To Reproduce**
1. Open Lens
2. Click a pinned cluster to connect
3. Observe that the black dot in the top left of the cluster icon remains black

**Expected behavior**
Previously the black dot would turn blue when a cluster was connected.

**Screenshots**
![image](https://user-images.githubusercontent.com/6581307/134427866-57ce0d2f-5f60-4c7e-92b2-7f6e4875f329.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.3 (observed since 5.2.2)
- OS: Windows 10 21H1

**Comment by Nokel81** [comment]
If you go to the catalog does that entity's status show as `"connected"`?

**Comment by alex-hempel** [comment]
No, all clusters show as disconnected, even the ones I just connected to.

**Comment by Nokel81** [comment]
Would you be able to provide some logs? Please fully stop lens, clear out all the old log files, and then fire up lens. 

https://docs.k8slens.dev/main/faq/?h=logs#where-can-i-find-application-logs

**Comment by alex-hempel** [comment]
Please see log attached. Includes two clusters being connected to.
[lens.log](https://github.com/lensapp/lens/files/7248562/lens.log)

**Comment by Nokel81** [comment]
Can you do the same with the env var `LOG_LEVEL` set to `silly`?

**Comment by alex-hempel** [comment]
Here are all the logs created from a single app start and cluster connect.
[logs.zip](https://github.com/lensapp/lens/files/7255312/logs.zip)

**Comment by Laurens-W** [comment]
Continuing from @Nokel81 's mention above:  Good info to know that docker-desktop does work. Both my rancher clusters don't.

**Comment by Nokel81** [comment]
@Laurens-W What version are you running?

**Comment by agomez-infoblox** [comment]
@Nokel81 I am adding my logs as I am not seeing the proxy error
[lens.log](https://github.com/lensapp/lens/files/8514541/lens.log)

**Comment by Nokel81** [comment]
I think I have tracked down the source of this issue. Do you have multiple kubeconfig sync options (under preferences)?

**Comment by starudream** [comment]
@Nokel81

**Comment by starudream** [comment]
@Nokel81 
For me, when I deleted the duplicate(Specifying a folder also specifies the files in that folder) SYNCED ITEMS, the LED showed up normally.

**Comment by Nokel81** [comment]
@starudream Excellent. That probably means that I have found the bug. Thanks for the feedback.
