### ISSUE TITLE
k8slens.dev intel download is throwing s3 permission error

### ISSUE THREAD

**Issue by jonassteinberg1** [kontena/lens#3879]
<img width="889" alt="Screen Shot 2021-09-23 at 9 45 54 AM" src="https://user-images.githubusercontent.com/62478198/134530237-ed9ab315-bd68-4a9a-964f-1d0c23dc9d69.png">
**Describe the bug**
issue subject says it all

**To Reproduce**
1. go to k8slens.dev
2. Click on the mac intel download

**Expected behavior**
dmg downloads

**Screenshots**
see attached

**Additional Context**
I'm not on a VPN
Have no proxies running
Have a functional internet connection
Have no conflicting AWS tools that might cause this

**Comment by jonassteinberg1** [comment]
both macs are dead, but the others seem to work.

**Comment by Nokel81** [comment]
This has been resolved. We know that we have a bug with the website that this can happen if one of the builds fails.

**Comment by saurabhsksharma** [comment]
This is happening again. Please look into this issue. I am trying to download Silicon Chip build.

**Comment by Nokel81** [comment]
It is not yet ready, we know this
