### ISSUE TITLE
kubeconfig bug in lens

### ISSUE THREAD

**Issue by AkakievKD** [kontena/lens#3880]
error: error loading config file "C:\Users\Михаил\AppData\Roaming\Lens\kubeconfigs\bd6b82c7-dcc5-4334-84d3-535e973096e1": v1.Config.Contexts: []v1.NamedContext: Clusters: []v1.NamedCluster: v1.NamedCluster.Name: Cluster: v1.Cluster.Server: CertificateAuthorityData: decode base64: illegal base64 data at input byte 171, error found in #10 byte of ...|Gb1hEVE1$","server":|..., bigger context ...|KY201bGRHVnpNQjRYRFRJeE1Ea3lNekUxTXprek9Gb1hEVE1$","server":"https://192.168.250.165:6443"},"name":"|...

proxy exited with code: 1

I tried to delete and create a cluster from absolute zero, I tried to clear the cache, I tried to delete the lens, but it still gives this error even if it is a new cluster with a different name. Please solve this problem with caching, which prevents it from working properly. Due to this problem, I cannot continue to use your product. Until then, the problem will not be solved - I will use another tool. Thanks in advance for the action taken.

This problems with the latest versions

**Comment by Nokel81** [comment]
That looks like an issue with your data since that error seems to be coming from kubectl (v1.NamedContext is a golang type error).

I see what looks like a `$` character in your data line. Which is an invalid base64 character.

**Comment by AkakievKD** [comment]
This problems with the latest versions. I installed version 5.1 and this work good. But if i use version 5.2 >= i have this problem
I even tried to create a new claster and no matter what, i have the same

**Comment by AkakievKD** [comment]
i understood where the problem. The latest versions of lens - change the end of lines in kubeconfig. i have seen right now both kubeconfig in lens 5.1 and 5.2 >= . And lens 5.2 >= add  this  ---> $ <----- at the and of kubeconfig then i add this in lens. May be it changes not only the end of kubeconfig.  PLEASE CHECK IT. Thank`s

**Comment by Nokel81** [comment]
Would you be willing to post your whole (or maybe only part) kubeconfig? I do not see where Lens would be adding a `$` to the end of a field's string value.

**Comment by AkakievKD** [comment]
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3lNekUxTXprek9Gb1hEVE1$
    server: https://192.168.250.165:6443
  name: kubespay.local
contexts:
- context:
    cluster: kubespay.local
    user: kubernetes-admin
  name: kubernetes-admin@kubespay.local
current-context: kubernetes-admin@kubespay.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRFZSaTd1eDZnRHd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNU1qTXhOVE01TX$
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbEpENDk1c1REaCtPREhOOS8ycUQxYUVZSC92eFNkZ1lyRENLaU9JSlNEdEQ5eGxTCmRCeGVXcTNsQ1MyeWtIbkt6TWdqc3lwZmZ4eU1pZWMrZ2E1cGMxOE$



This kubeconfig are changed in version 5.2>= i added this from console remoteNG.  But ! When i add kubeconfig from console remoteNG in version 5.1 this add in lens good and correct

**Comment by AkakievKD** [comment]
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bG...
    server: https://192.168.250.163:6443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: kubernetes-admin@cluster.local
current-context: kubernetes-admin@cluster.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRTBrV3JuQVAxTHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp...
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBc3Y1cDNFRmlUejhSY01UdWtaSzFoNHoyMVVSUHZ0VUlGR0x6THZiMGlPSzNWOUF5CmNNYk1tUVhrc...


THIS KUBECONFIG FROM LENS 5.1 ADDED FROM CONSOLE REMOTENG AND WORK CORRECT

Edit: @Nokel81 has removed some of the certificate data

**Comment by Nokel81** [comment]
If you add it again does the problem manifest itself immediately?

**Comment by AkakievKD** [comment]
apiVersion: v1
kind: Config
clusters:
  - name: cluster.local
    cluster:
      server: https://192.168.250.163:6443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1Ea3dOVEV6TXpneE9Wb1hEVE1$
      insecure-skip-tls-verify: false
users:
  - name: kubernetes-admin
    user:
      client-certificate-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJRTBrV3JuQVAxTHN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBNU1EVXhNek00TV$
      client-key-data: >-
        LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBc3Y1cDNFRmlUejhSY01UdWtaSzFoNHoyMVVSUHZ0VUlGR0x6THZiMGlPSzNWOUF5CmNNYk1tUVhrc2RRdXo0bnNYeHRsYVdNaEkrL1B2QWFKeks2Q0JSa2$
contexts: []
preferences: {}
current-context: kubernetes-admin@cluster.local


Yes, some time it change like this. I have not this problem in version 5.1

**Comment by AkakievKD** [comment]
you can create 100 clasters and to add 100 kubeconfigs and in versions more then 5.2.1 you will get this.

**Comment by AkakievKD** [comment]
i know why this kubeconfig like this. Because lens cut this kubeconfig. It doesn`t change. It just cuts, if you add from console remoteNG in version lens more 5.2.1. But if you add in version 5.1 lens doesn`t cut kubeconfig and add correct from remoteNG. But if you add kubeconfig from file - lens 5.2.4 add correct but despite this. Please fix this bug. Thank`s

**Comment by Nokel81** [comment]
what do you mean by cut? I know that some terminals instead of handling wrapping correctly actually insert newlines instead. So you copy a config from that then it would include the newlines.

Are you able to use kubeconfig sync instead? or maybe upload a video of this happening? As I am unable to reproduce it.

**Comment by AkakievKD** [comment]
Yes, you are right, i solved this problem. i understood why this happend. Excuse for troubling. You can close this tiket. The problem is solved. The version work is good. Thank`s for help))))
