### ISSUE TITLE
Does not open in Ubuntu 21.10

### ISSUE THREAD

**Issue by luizjr** [kontena/lens#3896]
**Describe the bug**
When I open the program it just closes, I tried to open it through the terminal and it shows this error that is in the screenshot.

**To Reproduce**
1. Open Lens

**Expected behavior**
Opening normaly

**Screenshots**
![image](https://user-images.githubusercontent.com/1474563/134794910-a08ae115-6caa-4db1-af94-2d65c4d68728.png)
![image](https://user-images.githubusercontent.com/1474563/134794915-0fe73310-69f7-45b6-ab38-686eba3e1806.png)

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (.deb file in Linux):
Ubuntu 21.10

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
 /usr/bin/lens  
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +9ms
info:    ▪ 🚀 Starting Lens from "/opt/Lens/lens" +100ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ▪ 💾 Loading stores +208ms
info:    ▪ [BS]: LOADED from /home/luizjr/.config/Lens/lens-user-store.json +26ms
info:    ▪ [DA]: LOADED from /home/luizjr/.config/Lens/lens-cluster-store.json +33ms
info:    ▪ [NU]: LOADED from /home/luizjr/.config/Lens/lens-hotbar-store.json +4ms
info:    ▪ [MT]: LOADED from /home/luizjr/.config/Lens/lens-extensions.json +1ms
info:    ▪ [C]: LOADED from /home/luizjr/.config/Lens/lens-filesystem-provisioner-store.json +1ms
info:    ▪ [KA]: LOADED from /home/luizjr/.config/Lens/lens-weblink-store.json +2ms
info:    ▪ 🔌 Starting LensProxy +11ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:46237 +3ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ ⚡ LensProxy connection OK +123ms
info:    ▪ 🖥️  Starting WindowManager +1ms
APPIMAGE env is not defined, current application is not an AppImage
info:    ▪ 🧩 Initializing extensions +28ms
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/luizjr/.config/Lens +1ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
info:    ▪ [EXTENSION-INSTALLER] installing dependencies at /home/luizjr/.config/Lens +151ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[51827:0926/022529.445906:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
info:    ▪ [EXTENSION-INSTALLER] dependencies installed at /home/luizjr/.config/Lens +656ms
info:    ▪ [EXTENSION-DISCOVERY] watching extension add/remove in /home/luizjr/.k8slens/extensions +6ms
Failed to generate minidump.[1]    51827 illegal hardware instruction (core dumped)  /usr/bin/lens

```

**Comment by Nokel81** [comment]
What version of Lens did you try this with?

**Comment by luizjr** [comment]
> What version of Lens did you try this with?
v5.2.4 for Ubuntu.
I'm using Ubuntu Impish now


I've been doing some searching.
and when I call through the terminal with the parameters below, the Open Program:
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/6

It seems to me that it has already been solved on electron:
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/15

**Comment by Nokel81** [comment]
Ah thank you very much @luizjr! We will upgrade to the latest version of electron 13 then
