### ISSUE TITLE
Initial load after installation show error dialog

### ISSUE THREAD

**Issue by HarelM** [kontena/lens#3897]
**Describe the bug**
When opening lens for the first time after upgrade from 5.1.x the following error dialog shows up:
`static://splash.html` seems to be missing according to the error.
![image](https://user-images.githubusercontent.com/3269297/134798204-69cffd42-4eee-4272-b08b-1649b5b3be55.png)

**To Reproduce**
1. Open lens after installation

**Expected behavior**
No error dialog

**Screenshots**
See above

**Environment (please complete the following information):**
Lens: 5.2.4-latest.20210923.1
Electron: 12.0.17
Chrome: 89.0.4389.128
Node: 14.16.0
- OS: [e.g. OSX] : Windows 10
- Installation method (e.g. snap or AppImage in Linux): exe file

**Additional context**
This doesn't happen on second launch, it happened to me only the first time I opened the app.
I haven't tried to reproduce it by uninstalling and installing again though, might be a single time glitch

**Comment by jeremy-degroot** [comment]
I just installed on Mac OS X and I'm seeing this every time I try to run the app. I get a dialog with that same error message and then lens fails.

Error: ERR_FAILED (-2) loading 'static://splash.html'

**Comment by Nokel81** [comment]
Was that the first time you installed lens? @jeremy-degroot

**Comment by jeremy-degroot** [comment]
@Nokel81 no, I'd had it before. I upgraded to the latest to try and stop the error, but it didn't work.

**Comment by Nokel81** [comment]
Can you try any of the attempts here https://github.com/lensapp/lens/issues/3870?

**Comment by jeremy-degroot** [comment]
@Nokel81 

> Could you try renaming your /Library/Application Support/Lens folder and then trying to launch lens again?

I don't seem to have this folder. Should I?

I did manually uninstall, and then try the Brew installation. Same result.

Lens is not currently showing up in Activity Monitor

**Comment by Nokel81** [comment]
You will only have that folder visible I'd you turn on seeing it in finder.

If you run `ps -A l grep lens` does anything show up?

**Comment by jeremy-degroot** [comment]
```
jeremy.degroot@MBP-174173.local:~$ ps -A | grep lens
 7529 ttys000    0:00.00 grep lens

```

When I do ` ls -al /Library/Application\ Support/` Lens is not there, I wasn't looking in Finder

**Comment by Nokel81** [comment]
If you run `/Applications/Lens.app/Contents/MacOS/Lens` from the command line does the problem still persist?

**Comment by jeremy-degroot** [comment]
Yes, here's the output

```
error:   ┏ Loading main window failed +47ms
error:   ┃ [ 1] {
error:   ┃ [ 2]   error: Error: ERR_FAILED (-2) loading 'static://splash.html'
error:   ┃ [ 3]       at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
error:   ┃ [ 4]       at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
error:   ┃ [ 5]       at Object.emit (events.js:315:20)
error:   ┃ [ 6]       at Object.EventEmitter.emit (domain.js:467:12)
error:   ┃ [ 7]       at Object.emitter.emit (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25) {
error:   ┃ [ 8]     errno: -2,
error:   ┃ [ 9]     code: 'ERR_FAILED',
error:   ┃ [10]     url: 'static://splash.html'
error:   ┃ [11]   }
error:   ┗ [12] }

```

**Comment by Nokel81** [comment]
So the folder should actually be `/Users/<user>/Library/Application Support/Lens`. If that doesn't exist, can you try creating it and running lens again?

**Comment by jeremy-degroot** [comment]
Yep, I found it now that I looked in the right place.

I renamed it to Lens.bak to see what would happen, and when I ran Lens it recreated the folder (I now have Lens and Lens.bak), per the instructions in the issue you linked.

It still gave the same error though.

**Comment by Nokel81** [comment]
Does the folder `/Application/Lens.app/Contents/Resources` exist and is readable?

**Comment by jeremy-degroot** [comment]
Yes, it exists and it's readable.
I just noticed another error occuring in the output from the previous comamnd line run:

```
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:50344 +3ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
error:   ▪ 🛑 LensProxy: failed connection test: RequestError: Error: getaddrinfo ENOTFOUND localhost +130ms
```

**Comment by Nokel81** [comment]
That probably is the source of the problem then. Have you modified `/etc/hosts`? That error should only occur if `localhost` is not defined in that file.

**Comment by jeremy-degroot** [comment]
Well, I hadn't modified it but somehow a bunch of binary garbage wound up at the top of my `/etc/hosts` file. I was also unable to ping localhost.

Once I removed the garbage, Lens starts again.

Thanks for your help!

**Comment by Nokel81** [comment]
Ya! you are very welcome. Maybe we should just use 127.0.0.1 directly though...

**Comment by balazstbb** [comment]
I have the same problem, I do have 127.0.0.1 localhost in my host file and I do not have anything else there
MacOS

**Comment by Nokel81** [comment]
Do you have PROXY or NO_PROXY env vars set up?

**Comment by balazstbb** [comment]
Yes, I do have

**Comment by Nokel81** [comment]
You need to have 127.0.0.1 in NO_PROXY for lens to work

**Comment by balazstbb** [comment]
Yes, I do have, and still does not work. I start from the command line and it tries to connect through the proxy. I tried to unset all of my shell variables but does not help.

**Comment by balazstbb** [comment]
`unset ALL_PROXY HTTP_PROXY HTTPS_PROXY FTP_PROXY RSYNC_PROXY http_proxy https_proxy ftp_proxy rsync_proxy; export no_proxy=127.0.0.1; /Applications/Lens.app/Contents/MacOS/Lens
`
and still, try to go through the proxy.... a silly question but why is it even try to use the proxy, this is an electron app, the service will run on the local so no proxy needed?

**Comment by Nokel81** [comment]
That is in deed a fair question, I know that `request` by default uses those proxy env vars which is why it looks for them. Also we do a shell sync so that might be bringing those env vars back... Can you just try `NO_PROXY=127.0.0.1,localhost /Applications/Lens.app/Contents/MacOS/Lens`?

**Comment by balazstbb** [comment]
ok, so the no_proxy=localhost solved, the 127.0.0.1 does not matter but if the no_proxy contains the localhost the application starts

Thank you!

**Comment by Nokel81** [comment]
Sounds good, I think we should just make sure that we have that always set for ourselves probably would be best.

**Comment by balazstbb** [comment]
Yes, that would be great, another hand I would suggest just ignore the proxy settings as is and connect with localhost IP.... then you would not have issues related to host file, DNS or proxy settings

**Comment by Nokel81** [comment]
Probably a better solution

**Comment by ryanbrainard** [comment]
I was also facing this same problem, and it turned out to be something with my VPN connection blocking traffic to localhost. I disconnected and reconnected from the VPN and Lens worked again.

In case it helps anyone else, what I did to troubleshoot this was first run ` /Applications/Lens.app/Contents/MacOS/Lens` and got the same `LensProxy: failed connection test: RequestError: Error: getaddrinfo ENOTFOUND localhost` as others did above. I then tried to connect to something else on localhost (just used `redis-cli` to connect to my local Redis) and that failed, so knew it was something with the localhost network. Took a guess at VPN acting up and that worked.

**Comment by LaysDragon** [comment]
I upgrade Lens to latest version via the installer (Lens Setup 5.2.5-latest.20211001.2.exe) download directly from official website today ,and bump into the same problem here. Install the old installer(Lens Setup 5.2.3-latest.20210921.1.exe) didn't solve the problem.   
But its works again as soon as I uninstall the Lens then reinstall the Lens again with the latest installer. 🤷‍♂️  

OS: windows 10
![image](https://user-images.githubusercontent.com/10185394/136692405-c0a1a735-ba29-45e6-bf30-f9d8acd4f0e6.png)

**Comment by Nokel81** [comment]
@LaysDragon Did you try any of the proxy debugging above?
