### ISSUE TITLE
aws credential_process with gsts doesn't work

### ISSUE THREAD

**Issue by yuranos** [kontena/lens#3898]
**Describe the bug**
I'm using `gsts` to auth into my AWS account via Google IDP.
It works for all my tools like kubectl, aws, etc, but Lens is complaining with:
![image](https://user-images.githubusercontent.com/11991425/134822046-84413691-3c64-44f5-98dc-d485d825aeef.png)

My `~/aws/config` looks like:
```
[profile sts]
region = eu-west-1
credential_process =  gsts --json --idp-id xxxx --sp-id xxxx --username xxxx@xxxx.xx --aws-shared-credentials-file /home/xxxx/.aws/gsts_credentials
```

**To Reproduce**
1. Configure your aws/config just like I configured mine;
2. Launch Lens.

**Expected behavior**
I should be able to connect to my Kuberbetes/EKS cluster.

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/11991425/134822136-cbce4271-41e6-40b6-9b1b-834aa960dba7.png)
$ whereis gsts
gsts: /home/xxxx/.nvm/versions/node/v10.15.3/bin/gsts

**Comment by Nokel81** [comment]
You are using a older version of lens... However, we use `kubectl` to connect to the cluster using `kubectl proxy`. What happens if you manually run `kubectl proxy` for this cluster.

Also, if you start lens from the terminal does the issue go away?

**Comment by yuranos** [comment]
HI @Nokel81 
Starting the older one from the terminal didn't help, but installing 5.2.5 worked like a charm!
Thanks!

**Comment by yuranos** [comment]
Oh, taking my words back. 5.2.5 works, but only when started from the terminal.

**Comment by Nokel81** [comment]
Is the error the same as above?

**Comment by yuranos** [comment]
Ok, another update. Sorry for being ambiguous. It doesn't work at all. Neither console nor UI. It works on the very first start. Then I closed it and now I'm getting:
```
[Errno 2] No such file or directory: 'gsts'

E1025 22:32:56.739695 286897 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws failed with exit code 255

getting credentials: exec: executable aws failed with exit code 255
```
On that initial successful run my console had a lot of output starting with:
```
$ lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +8ms
Gtk-Message: 22:14:22.643: Failed to load module "unity-gtk-module"
Gtk-Message: 22:14:22.645: Failed to load module "unity-gtk-module"
info:    ▪ 🚀 Starting Lens from "/opt/Lens/lens" +388ms
info:    ▪ 🐚 Syncing shell environment +0ms
info:    ▪ 💾 Loading stores +1s
Running 5.0.0-alpha.3 migration for /home/yuranos/.config/Lens/lens-user-store.json
Running 5.0.3-beta.1 migration for /home/yuranos/.config/Lens/lens-user-store.json
Skipping 1a07af48-9dcf-4f4d-92ed-4e860590ff1e because kubeConfigPath is already being synced
Skipping c491f11f-9a60-439a-9ee6-0f205ad06f9d because kubeConfigPath is already being synced
Final list of synced paths [ { filePath: '/home/yuranos/.kube' } ]
```
The subsequent runs look  a lot less chatty:
```
yuranos@xps-9570:~/Downloads $ lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +10ms
yuranos@xps-9570:~/Downloads $ /opt/Lens/lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +8ms
yuranos@xps-9570:~/Downloads $ /opt/Lens/lens
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
info:    ▪ 📟 Protocol client register failed ❗ +8ms

```

**Comment by Nokel81** [comment]
So that is because `kubectl` as a child process cannot find `gsts`. We try to sync as if we were run in from the terminal.

If you start up `node` and run `os.userInfo()` what shell appears. Is that the same one as you have set up your PATH modification in?

**Comment by yuranos** [comment]
Another update:
I've just purged the app and re-installed it from scratch.
I can successfully open/close the app multiple times via console.
However, if I at least once start it via UI, that's it. I am not able to access the cluster from either console nor UI from that moment onward.

**Comment by Nokel81** [comment]
Do you close the tray icon before attempting to start the app from the console?

**Comment by yuranos** [comment]
Yes, I did.

**Comment by yuranos** [comment]
Answering your previous question:
```
$ node
> os.userInfo()
{ uid: 1000,
  gid: 1000,
  username: 'yuranos',
  homedir: '/home/yuranos',
  shell: '/bin/bash' }
> 
$ echo "$SHELL"
/bin/bash
$ ps -p $$
  PID TTY          TIME CMD
 303398 pts/2    00:00:00 bash

```

**Comment by yuranos** [comment]
Ok, my bad. The app was still running in the backgroud.
So, I can at least use console without reinstalling it.
But would be nice to be able to run in via UI as well.

**Comment by Nokel81** [comment]
Yes it would be nice, let me do some testing...
