### ISSUE TITLE
Ctrl+W close the window in Windows

### ISSUE THREAD

**Issue by sanarena** [kontena/lens#3902]
**Describe the bug**
In terminal, open nano. try to search for a word (i.e. Ctrl+W) and boom. whole Lens is close!

**To Reproduce**
1. Go to 'terminal'
2. Press Ctrl+W
3. Boom

**Expected behavior**
It should pass Ctrl+W to terminal so search dialog open

**Environment (please complete the following information):**
- Lens Version: 5.2.4
- OS: Windows

**Comment by jakolehm** [comment]
Fixed in #3849 .
