### ISSUE TITLE
Can't load helm chart info

### ISSUE THREAD

**Issue by nvthuong1996** [kontena/lens#3903]
**Describe the bug**
lensapp can't load chart info when i installed cert-manager from https://cert-manager.io/docs/installation/helm/

other chart still working normal, only cert-manager error

![image](https://user-images.githubusercontent.com/24992586/135054966-5e1f59d0-5d77-4910-af27-eea9b7fd93b0.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.4-latest.20210923.1
- OS: OSX

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
release-details.tsx:102 Uncaught (in promise) JsonApiErrorParsed {error: "", messages: Array(1), isUsedForNotification: false}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by nvthuong1996** [comment]
please check lens when it working with certmanager.
when i install cert-manager. lens can't load custom resource that certmanager create

![image](https://user-images.githubusercontent.com/24992586/136175805-2e69441c-bdfa-47e3-90fb-07cfbbd3fbdf.png)


![image](https://user-images.githubusercontent.com/24992586/136175659-a31c9eb1-ea02-476c-a971-1e9fd08fc00a.png)

**Comment by Nokel81** [comment]
@nvthuong1996 I tried to install v1.6.0-alpha.1 too and my install failed to install, has yours succeeded?

**Comment by nvthuong1996** [comment]
> @nvthuong1996 I tried to install v1.6.0-alpha.1 too and my install failed to install, has yours succeeded?

I have installed it successfully. I have to wait a long time.
you try install chart with values:
```
installCRDs: true
```

![image](https://user-images.githubusercontent.com/24992586/136247110-2b0c2057-aa5f-4cc1-a8a8-1ce91c48a364.png)
