### ISSUE TITLE
Lens metrics not working after upgrade to 5.1.3

### ISSUE THREAD

**Issue by FischlerA** [kontena/lens#3917]
**Describe the bug**
We recently made the upgrade of lens from 4.2.5 to Lens 5.1.3.
Before the upgrade we were able to view metrics from our cluster in lens. After the upgrade we get "Metrics not available at the moment".

We have Prometheus installed via helm chart in the prometheus namespace, as such we have set the metrics configuration as follows:

Prometheus: Helm
Prometheus Service Address: prometheus/prometheus-server:80

Now the strange part is, using our admin user (full access) we are able to retrieve the metrics. With a user login we are not able to receive the metrics. Our users have restricted access, but were granted the following permissions for the prometheus namespace

Resources: services, services/proxy
Verbs: get, list, watch
Api Groups: ''

I just verified after reinstalling Lens 4.2.5 this still works, but not with the Lens 5.1.3 version.

**To Reproduce**
1. Restrict access to prometheus namespace as seen above
2. Assign the ClusterRole via Rolebinding to current user
3. Set Metrics to Helm with corresponding address
4. Install Lens 5.1.3 -> Missing Metrics
5. Install Lens 4.2.5 -> Metrics available

**Expected behavior**
The Metrics should be available the same as it was in 4.2.5

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: Win10

**Comment by Nokel81** [comment]
Did you set `prometheus/prometheus-server:80` in settings or did you let Lens auto-detect it? For auto-detect to work you need to have permissions to list `services` for all namespaces, not just the namespace that it is in.

**Comment by marcbachmann** [comment]
Maybe we can close this too after the fixes in #3653 land on master.
It's using the default [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) setup

**Comment by FischlerA** [comment]
> Did you set `prometheus/prometheus-server:80` in settings or did you let Lens auto-detect it? For auto-detect to work you need to have permissions to list `services` for all namespaces, not just the namespace that it is in.

I tried it both ways, both didn't work but this issue is specfically for the setting option.

**Comment by FischlerA** [comment]
> Maybe we can close this too after the fixes in #3653 land on master. It's using the default [`kube-prometheus-stack`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) setup

It certainly is worth a try, i will update you as soon as the new version is out.

**Comment by Nokel81** [comment]
@FischlerA Do you see any logs when you run lens from the terminal?

**Comment by FischlerA** [comment]
@Nokel81 good idea. the logs actually exactly tell me what the issue is:

```
error: [Metrics]: metrics not available {"error":{"name":"StatusCodeError","statusCode":403,"message":"403 - {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"services \\\"prometheus-server:80\\\" is forbidden: User \\\"crossfunctions_admin\\\" cannot create resource \\\"services/proxy\\\" in API group \\\"\\\" in the namespace \\\"prometheus\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"prometheus-server:80\",\"kind\":\"services\"},\"code\":403}","error":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"prometheus-server:80\" is forbidden: User \"crossfunctions_admin\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"prometheus\"","reason":"Forbidden","details":{"name":"prometheus-server:80","kind":"services"},"code":403},"options":{"timeout":0,"resolveWithFullResponse":false,"json":true,"method":"POST","form":{"query":"sum(rate(container_network_transmit_bytes_total{pod=~\"auftrag-backend-dev-7fcb4bf78b-9zxq9\",namespace=\"auftrag\"}[5m])) by (pod, namespace)","start":"1633436160","end":"1633439760","step":"60","kubernetes_namespace":"auftrag"},"headers":{"Host":"aa693ab55fe6c22143d4b688dca2b1c8.localhost:54879"},"uri":"http://localhost:54879/api-kube/api/v1/namespaces/prometheus/services/prometheus-server:80/proxy/api/v1/query_range","simple":true,"transform2xxOnly":false},"response":{"statusCode":403,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"prometheus-server:80\" is forbidden: User \"crossfunctions_admin\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"prometheus\"","reason":"Forbidden","details":{"name":"prometheus-server:80","kind":"services"},"code":403},"headers":{"access-control-allow-origin":"*","audit-id":"10398190-68e6-46a1-87fa-473e2ae11268","cache-control":"no-cache, private","content-length":"343","content-type":"application/json","date":"Tue, 05 Oct 2021 13:16:46 GMT","x-content-type-options":"nosniff","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"localhost:54879","port":"54879","hostname":"localhost","hash":null,"search":null,"query":null,"pathname":"/api-kube/api/v1/namespaces/prometheus/services/prometheus-server:80/proxy/api/v1/query_range","path":"/api-kube/api/v1/namespaces/prometheus/services/prometheus-server:80/proxy/api/v1/query_range","href":"http://localhost:54879/api-kube/api/v1/namespaces/prometheus/services/prometheus-server:80/proxy/api/v1/query_range"},"method":"POST","headers":{"Host":"aa693ab55fe6c22143d4b688dca2b1c8.localhost:54879","content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":255}}}}}
```

So basically the user needs create permissions for services/proxy. I can try this tomorrow morning. 
Did i miss this information somewhere or is this missing from the documentation?

**Comment by Nokel81** [comment]
@FischlerA I don't think you missed anything, we don't have terribly good docs about prometheus setup. It probably would be better to try and make such errors more visible.

**Comment by marcbachmann** [comment]
Here's the minimal configuration to get the metrics working: https://github.com/lensapp/lens/issues/787#issuecomment-922541339

**Comment by Nokel81** [comment]
@marcbachmann wrong link?

**Comment by marcbachmann** [comment]
no, should be correct .

Summary: `pods/portforward` and `services/proxy` are required.
```yaml
---
# Provides the required permissions for readonly users
# to get metrics working in lens
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: port-forward-lens
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods/portforward", "services/proxy"]
  verbs: ["create"]
```

**Comment by Nokel81** [comment]
Weird, it seemed to link back to this issue

**Comment by ghost** [comment]
Hello, I have same problem with "metrics not available" after upgrade. I am using "sumologic" stack where is included prometheus... how I can fix this?

**Comment by marcbachmann** [comment]
No support requests in old issues please. Please create an issue with a detailed isolated reproduction and expected behavior.
There's also a slack org you can join for support requests.
