### ISSUE TITLE
Unable to see Openshift Routes 

### ISSUE THREAD

**Issue by ankit-jha** [kontena/lens#3920]
**Describe the bug**
Unable to see Openshift Routes 

**To Reproduce**
1. Go to Lens IDE
2. Add Openshift Cluster
3. Scroll down to Network
4. No `Routes` show up

**Expected behavior**
Openshift Cluster should show routes

**Screenshots**
![image](https://user-images.githubusercontent.com/6148327/135519907-e99bbb5f-443b-4eb1-b1e4-0daeabfe878b.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.4-latest.20210923.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): Homebrew

**Additional context**
Routes seems to be Openshift specific concept
https://cloud.redhat.com/blog/kubernetes-ingress-vs-openshift-route

**Comment by fkajerry** [comment]
The OpenShift `Route` is OpenShift self define Resource, it's not well-known K8S built-in resources, So, Lens don't know it.

Maybe, in CRD's panel.
If not, you maybe right a extension to help display `Route` info

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/310 but thanks for the request. This certainly could be an extension.
