### ISSUE TITLE
With v5.2.4 can't find pod log window

### ISSUE THREAD

**Issue by kahmad07** [kontena/lens#3929]
**Describe the bug**
With v5.2.4 can't find pod log window

**To Reproduce**

**Expected behavior**
Ideally should be able to see pod logs the way it used to work for earlier version

**Screenshots**

**Environment (please complete the following information):**
- v5.2.4 
- Mac OS
- Download through the lens website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Would you be able to fill out your description a bit more? BTW I think this is a duplicate of https://github.com/lensapp/lens/issues/3548

**Comment by this-username-is-taken** [comment]
Run into the same issue in 5.3.3 where the "Logs" icon is now showing up.

![image](https://user-images.githubusercontent.com/2354636/146466662-a559ecf0-c3b7-4a3c-8dc2-f3c63e79504f.png)

One thing I noticed is that when I launch Lens, I get the error message shown below:

![image](https://user-images.githubusercontent.com/2354636/146466726-038f12ad-ef33-4123-83d3-00e4d0f61624.png)

So I changed the permission for the folder in question, restarted Lens, and the error message disappeared, and I'm also able to see the "Logs" icon in pods.
