### ISSUE TITLE
Lens use too much memory

### ISSUE THREAD

**Issue by nvthuong1996** [kontena/lens#3940]
**Describe the bug**

**To Reproduce**
1. go to Cluster page
2. Click on 'sync kubeconfig'
3. Select folder Download
4. Click sync

i think the problem occurs when i accidentally click sync a folder 'Download' . but I can't find these unsync folders

![image](https://user-images.githubusercontent.com/24992586/135710976-feb97628-d32e-423c-9acf-157ea3670b2d.png)

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: OSX

**Comment by Nokel81** [comment]
What do you mean "but I can't find these unsync folders"? If you remove the sync from within the settings panel (which a button to which should have shown up in the confirmation notification after you synced the download folder) then that will stop the syncing.

**Comment by nvthuong1996** [comment]
i understand. thank you
