### ISSUE TITLE
Scanning massive files on startup leads to 100% memory consumption and crash

### ISSUE THREAD

**Issue by ghost** [kontena/lens#3959]
**Describe the bug**
Lens on Linux will consume all memory after loading and then crash if the user home directory has massive files in it.  

For whatever reason Lens tries to read ALL files in the users home directory indiscriminately.  When it reaches a very large file it tries to read it into memory so it can parse it.  I had a 200g disk image file that was in my home directory.  After trying several Lens versions I was able to solve my issue by moving the file out of the home directory and into a subfolder.

**To Reproduce**
Place a very large (50g+) file in the home directory.  Name it "diskimage" to completely reproduce my setup.
Launch Lens and watch all of your system memory quickly be consumed.

**Expected behavior**
Lens in general probably should not be reading files in the home directory that it has no business accessing.  It should discriminate by file type and/or at least enforce a size limit before attempting to do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/13294361/136277754-395d0fda-4734-46b9-844f-968cca49f839.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: Linux Mint  20
- Installation method (e.g. snap or AppImage in Linux):  Tested with both the deb package and AppImage installations.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
The "log" contains sensitive information such as the contents of .bash_history because it was in fact trying to parse those types of files and was generating format errors for them.  So I won't include it here.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
Never had a chance to create a kubeconfig file because the crash prevented it.
```

**Additional context**

**Comment by Nokel81** [comment]
Would you mind pasting your screenshot directly?

So Lens, by default, scans files within `~/.kube` and that is it. If you run lens from the command line with `DEBUG=true` enabled is your home directory listed? I do think that we probably should abort the read if we find a file larger than say 100 MB.

**Comment by ghost** [comment]
I think this screenshot of the console output demonstrates that it's reading the home directory.
![image](https://user-images.githubusercontent.com/13294361/136278244-fd0a4b3e-d2d6-4aef-b7bd-80f405b2e480.png)

Mind you this was run without any program arguments.
And I didn't change any settings.  It was like this out of the box.

**Comment by Nokel81** [comment]
Did you upgrade from a previous version of lens? If you go to `~/Library/Logs/Lens` there should be some logs in one of the files that starts with "Migrating lens-user-store.json 5.0.3-beta.1" or something similar. Is your home directory shown there?

I am asking because that is the only places that we add syncs automatically and it is done off of the list of clusters that was added in 4.X and 3.X

**Comment by ghost** [comment]
I only upgraded in the hope that it would fix the crash I was getting.  I have no such directory `~/Library/Logs/Lens` on my system.
The version I upgraded from was only days older than the version I'm running now.  I only heard about Lens about a week ago.
Like I said in the original post, I was able to solve my problem by moving out the large file from my home directory to a subdirectory within my home directory.  If you take my steps to reproduce the problem then you should see the effects of the bug directly.

**Comment by Nokel81** [comment]
Yes I have observed the bug and plan to make a fix that aborts reading files that are "too large". I was trying to figure out how your home directory was included.

Sorry, I missed that you are on linux. The files should be at `~/.config/Lens/logs/`

**Comment by ghost** [comment]
There's 15 logs in the log directory.  Sorry, none of them make any mention of migrating.  Probably because there wasn't anything to really migrate as a new enough user.

**Comment by Nokel81** [comment]
I am sorry that your home directory was added. I cannot find anywhere in code that we even try to add just the home directory into the list of syncs.

I have now made a PR that skips files larger than 16MiB (since that should be a good maximum for a text file). Hopefully that fixes it for anyone else in the future.

**Comment by ghost** [comment]
Thank you for your efforts. :)  This should fix the problem for others either way.
