### ISSUE TITLE
XHR calls is not showing in the developer tools Nework tab

### ISSUE THREAD

**Issue by gautam7730** [kontena/lens#3967]
**Describe the bug**
Hi,
with the latest Lens application (Lens: 5.2.x) , i am not able to see the xhr calls in the network tab of developer tools.
Though the following info has been added in console :
`[JSON-API] request POST http://127.0.0.1:49742/api/stack `

But, this doesn't help much during dubugging and making postman calls for debugging.
Please share if there is any workaround or i need to make any change  to get the xhr network calls?

**To Reproduce**
1. Open Lens application
2. Open developer tools
3. Go to networks tab
4. on changing the extension tab you will not see xhr requests made

**Expected behavior**
On the Developer tools networks tab, xhr calls should show like it was showing in the older versions (e.g 5.1.3 etc)

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5
- OS: OSX
- Installation method : used latest dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
This is because the renderer is now use node-fetch to make its requests.

**Comment by jakolehm** [comment]
Closing this because we are now using node-fetch which cannot log requests to network tab (since 5.2.0).
