### ISSUE TITLE
Helm repo versions not updated (cached?)

### ISSUE THREAD

**Issue by dominch** [kontena/lens#3970]
**Describe the bug**
Few hours ago I got notification about helm chart update, when I wanted to update it via lens - I can't find new version of chart there. Package is longhorn/longhorn and it should be now at 1.2.1 but it's 1.2.0 :(
![image](https://user-images.githubusercontent.com/10815109/136214084-a8f334f4-916b-44d4-a2f1-720e298e65e7.png)
Interestingly whan I try same thing from command line it's ok: 
![image](https://user-images.githubusercontent.com/10815109/136214301-ea98474e-e6cd-4d82-93ad-f92d3f69a42e.png)

**To Reproduce**
I nothing special, I'm using latest lens version and added longhorn some time ago, later upgraded it via lens from 1.1.2 to 1.2.0 and now expect same thing with 1.2.1 

**Expected behavior**
It should find new version. Of course I made few repo updates via command line. 

**Screenshots**
here it's one moe: 
![image](https://user-images.githubusercontent.com/10815109/136214936-0744e7d2-5a15-4df9-b0d7-f17f76a70976.png)

**Environment (please complete the following information):**
- Lens Version: 
![image](https://user-images.githubusercontent.com/10815109/136215021-58deeea7-dd7a-4de9-8ad8-0f499a7703a1.png)

- OS: windows
- Installation method (e.g. snap or AppImage in Linux): installer

**Additional context**
I was able to update from previous version but don't know how much time passed since release to cache update in lens. I tried to update repos and restart lens few times, nothing helped. Also I don't know if there is any button to force update repo informations straight from lens. On preferences there is a list, but still no button to update. Should it use same information as on command line?

**Comment by Nokel81** [comment]
Yes we cache them, this is a duplicate of https://github.com/lensapp/lens/issues/691. Did you close the tray icon when you restarted lens?

**Comment by dominch** [comment]
> Yes we cache them, this is a duplicate of #691. Did you close the tray icon when you restarted lens?

I'm not sure now if tray was closed or not :/ I will pay extra attention next time that happens. Right now it seems to be duplicate of #691

**Comment by timsamart** [comment]
Same problem a restart from lens and also closing the app icon -> exit lens. does not fix the problem. In the last Version of lens this worked. Does Lens use a custom chaching folder independent of the local helm installation?

**Comment by Nokel81** [comment]
@timsamart It does not, we read directly from the helm cache files (and then store them in memory)

**Comment by timsamart** [comment]
Ok so there could be a possibility that there are multiple installations of helm or something sikilar with different locations for the charts?

**Comment by Nokel81** [comment]
We always use our bundled version of helm (currently v3.6.3) which we then call `helm env` and use the results of that to find its cache files.
