### ISSUE TITLE
Display current hotbar name

### ISSUE THREAD

**Issue by LFrobeen** [kontena/lens#3982]
**What would you like to be added**:
Display the name of the currently active hotbar somewhere.

**Why is this needed**:
I think a common use-case for grouping clusters in a hotbar is to separate staging from prod clusters or to create a separation between different environments. Since it might not always be immediately clear from the clusters in a hotbar which environment one is in, it would be really nice if Lens displayed the hotbar name somewhere (e.g. the window title bar or lower status bar).

**Environment you are Lens application on:**

- Kubernetes distribution: EKS, GKE, Rancher / k3s / k3d
- Desktop OS: MacOS Big Sur 11.2.3

**Comment by sujith0408** [comment]
What was the solution for this problem. Can someone guide me on this? Not able to identify the solution from the issue that has been closed.

**Comment by Nokel81** [comment]
@sujith0408 It was decided after we initially implemented it that having it in the status bar wasn't a good fit. We moved it to a tooltip in https://github.com/lensapp/lens/pull/4679 but with trying it I see that it doesn't work on 5.5.2 either. So I will open an issue for that.

**Comment by Nokel81** [comment]
I have opened https://github.com/lensapp/lens/issues/5517
