### ISSUE TITLE
Promotheus fails to install in AKS - Azure Kubernetes Service

### ISSUE THREAD

**Issue by thomastvedt** [kontena/lens#3996]
**Describe the bug**
Promotheus fails to install in AKS - Azure Kubernetes Service

**To Reproduce**
1. Connect to a AKS - Azure Kubernetes Service cluster created with default settings
2. Settings -> Metrics -> Add
3. Persisted Volume Claim is stuck in "pending" state in Kubernetes

**Expected behavior**
The installation uses `storageClassName: default`, which has "late binding" or something. The "default" storageClass doesnt work in azure, and I need to change this to `azure-file`. It is not possible to edit the PVM yaml, this is immutable after creation

**Screenshots**
![image](https://user-images.githubusercontent.com/4746639/136533278-6a5abbf9-5d76-4223-bcdb-5d6645b59a6f.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.5-latest.20211001.2
Electron: 12.2.1
Chrome: 89.0.4389.128
Node: 14.16.0
© 2021 Mirantis, Inc.
- OS: osx

**Question**
- Is it possible to change storageClassName when adding this?
- Can I install this manually somehow?

**Comment by Nokel81** [comment]
> Can I install this manually somehow?

You should be able to use the helm install of prometheus and it should work just a well.

**Comment by thomastvedt** [comment]
Thanks @Nokel81 , the installation initiated from the UI got "stuck" waiting for a PV claim using default azure settings. It's not possible to change PV claims either. Resolved by:
- manually deleting all resources 
- installed using helm using tutorial here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
