### ISSUE TITLE
Broken logs after upgrading to 5.* from 4.*

### ISSUE THREAD

**Issue by elderapo** [kontena/lens#4003]
**Describe the bug**
The following logs:
```bash
[LOG]  [WalletEngineService(initializeLocalBlocks)] Current best block: {
  hash: '000000000000000004f3788b10ca6a16bfd19f3bbf12b17fc3bd11b169d4831f',
  height: 708989,
  previousBlockHash: '0000000000000000035338138b8b61c2b5b5047c0046fa2b3c84f24427ca4b2e'
}!
[LOG]  [WalletEngineService(initializeLocalBlocks)] Done scanning blocks because nextBlockHeight(708990) > bestBlockHeight(708989)!
[LOG]  [WalletEngineService(initialize)] Initialized local blocks!
```
get rendered like this in lens:
![image](https://user-images.githubusercontent.com/10766808/136693146-6bd0bad8-f1c7-4a1b-8f28-2220a4eb6efa.png)

**Expected behavior**
Log lines shouldn't overlap.

**Additional context**
I think it might have to do something with the fact that my logger is replacing `\n` with `\r` and new lens doesn't seem to handle `\r` well? Something like this:

```ts
const logMessage = "first line\n second line!";
const prepared = logMessage.replace(/\n/g, "\r");
process.stdout.write(`${replaced}\n`);
```

**Comment by elderapo** [comment]
Any update on this?

**Comment by elderapo** [comment]
I think it's still the case (tested version: `5.4.3`, downloaded from https://api.k8slens.dev/binaries/Lens-5.4.3-latest.20220317.1.x86_64.AppImage).

![image](https://user-images.githubusercontent.com/10766808/158919030-2b308059-05cb-4b8a-98c3-0d83b54248c3.png)

```
[LOG]  [WalletEngineService(cb)] Received event for block(height: 731783, hash: 0000000000000000042b6ab91d3f619e8518e37432b5dc5c343db18afcc7a39b, previousBlockHash: 00000000000000000134fbabffd4f2e023bb109f74b9e57010ad2eca9e942ac9)! Starting scan...
[LOG]  [WalletEngineService(synchronizeBlock)] Syncing block({
  hash: '0000000000000000042b6ab91d3f619e8518e37432b5dc5c343db18afcc7a39b',
  previousBlockHash: '00000000000000000134fbabffd4f2e023bb109f74b9e57010ad2eca9e942ac9'
})... Fetching block info from blockchain with transactions(true)...
```

**Comment by Nokel81** [comment]
That screenshot says that you aren't running the latest version

**Comment by aleksfront** [comment]
@elderapo Please confirm the issue is fixed for you in 5.4.3.

**Comment by elderapo** [comment]
@aleksfront Appears to be fixed! Sorry about the false alarm :laughing:

**Comment by aleksfront** [comment]
Thanks for checking this out!
