### ISSUE TITLE
Spaces not working

### ISSUE THREAD

**Issue by BrunoGabrielGodoi** [kontena/lens#4011]
**Describe the bug**
After logging in, you can not create a new space or invite anyone.

**To Reproduce**
1. Enter your cluster
2. Log in
3. Click on share 
4. Try to create a space or invite anyone

**Expected behavior**
The share menu should come with informations and let me create a space or invite someone to an already created one.

**Screenshots**
![image](https://user-images.githubusercontent.com/20050537/136951679-5bb469e2-0688-4a4c-8eab-ebc0f3de994d.png)
![image](https://user-images.githubusercontent.com/20050537/136951732-e2e4eea5-74be-4bd6-8778-e590c7a6f31f.png)

This will never load, and i can't click on any buttons

**Environment (please complete the following information):**
- Lens Version: 5.2.0-latest.20210908.1
- OS: Linux
- Installation method: .deb

**Additional context**
This happened to me and a friend of mine in two clusters

**Comment by chenhunghan** [comment]
@BrunoGabrielGodoi This can be our sever response 503 (temporarily unavailable), which should be back soon when it recovers, please try again.

**Comment by BrunoGabrielGodoi** [comment]
@chenhunghan no luck.
I had this issue first time last week, tried again yesterday and today. Any ideas?

**Comment by Nokel81** [comment]
Closing as old, if you still run into issues please re open.
