### ISSUE TITLE
Issue for running the Integration tests  for Lens Extension in docker container

### ISSUE THREAD

**Issue by gautam7730** [kontena/lens#4025]
**Describe the bug**
HI,
while running the integration tests for Lens Extension in docker container, I am facing below issue:

When Playwright opens the Lens instance and tries to connect to cluster it takes much time (from  3 minutes to 7 minutes and fails intermittently with `Error : spawn kubectl enoent` ), but in the same environment without Playwright it connects within seconds.

Please find below the resources (Dockerfile and entrypoint.sh file content) used for this:

lens-web for visualization:
https://github.com/supervisor-com/lens-web

Dockerfile:

> FROM ubuntu:20.04
> ARG LENS_VERSION
> 
> ENV DISPLAY=:0
> ENV PORT=8080
> ENV DEBIAN_FRONTEND=noninteractive
> 
> COPY --from=mattipaksula/wait-for:sha-2a34cde /wait-for /usr/bin
> 
> RUN apt-get update && apt-get install -y \
>   curl git \
>   xvfb x11vnc \
>   libnss3 libglib2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libx11-xcb1 libasound2 libxss1 libgbm1 \
>   && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
>   && apt-get update && apt-get install -y nodejs
> 
> WORKDIR /opt
> RUN git clone https://github.com/novnc/websockify-js.git \
>   && cd websockify-js/websockify && npm install
> 
> 
> RUN curl -LO https://api.k8slens.dev/binaries/Lens-5.2.5-latest.20211001.2.x86_64.AppImage \
>   && chmod +x Lens-5.2.5-latest.20211001.2.x86_64.AppImage\
>   && ./Lens-5.2.5-latest.20211001.2.x86_64.AppImage --appimage-extract \
>   && rm -rf Lens-5.2.5-latest.20211001.2.x86_64.AppImage \
>   && mv /opt/squashfs-root /opt/lens
> 
> RUN export PATH=$PATH:/opt/lens/lens
> 
> WORKDIR /app
> COPY app .
> 
> ENTRYPOINT [ "/app/entrypoint.sh"]

entrypoint.sh 

> #!/usr/bin/env bash
> set -euo pipefail
> 
> _term() {
>   echo "bye"
>   exit 0
> }
> 
> trap _term TERM INT
> 
> mkdir -p /root/.kube
> 
> (
>   >/dev/null 2>&1 rm /tmp/.X0-lock || true
>   exec Xvfb :0 -screen 0 1366x768x24 -ac -listen tcp
> ) >/tmp/xvfb.log 2>&1 &
> echo $! >/tmp/xvfb.pid
> 
> export ELECTRON_DISABLE_SANDBOX=1
> 
> (
>   wait-for localhost:6000
>   exec x11vnc -display :0 -shared -nopw -forever
> ) >/tmp/x11vnc.log 2>&1 &
> echo $! >/tmp/x11vnc.pid
> 
> (
>   wait-for localhost:5900
>   exec node /opt/websockify-js/websockify/websockify.js  --web /app/public ":$PORT" 127.0.0.1:5900
> ) >/tmp/websockify.js 2>&1 &
> websockify_pid=$!
> 
> 
> (
>   cd /opt/lens
>   while true; do
>     ./lens --no-sandbox
>   done
> ) >/tmp/lens.log 2>&1 &
> echo $! >/tmp/lens.pid
> 
> echo "listening at port :$PORT"
> tail -f /dev/null &
> wait $!

**To Reproduce**
1. Build the image using above Dockerfile and run it using below command:
    `docker run -it --volume $HOME/.kube/config:/root/.kube/config -p 8080:8080 <image>`
2. Go to browser and hit the url `http://localhost:8080/ ` , Lens web will be available , connect you cluster from here , it will connect within seconds.
3. try connecting the cluster using integration tests from Playwright using the below steps

- go to container bash using `docker exec -it <continer_id> /bin/bash`
- run the commands `export ELECTRON_DISABLE_SANDBOX=1` and `export PATH=$PATH:/opt/lens/lens`
- run your extension test cases using npm command , it will get stuck at cluster connection statge and gives `Error : spawn kubectl enoent`.

4. Test case used for this step:

> it('Add cluster', async () => {
>       await window.waitForSelector("div >> text='Clusters'");
>       await window.click("div >> text='Clusters'");
>       await window.waitForSelector("div >> text='local'");
>       await window.click(".TableRow>div.TableCell.menu");
>       await window.waitForSelector("li.MenuItem >> text='Connect'");
>       await window.click("li.MenuItem >> text='Connect'");
>       await window.waitForTimeout(300000);
>     });

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): AppImage in docker

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by gautam7730** [comment]
attaching the screenshot:

connection happens within seconds for Lens:
<img width="998" alt="connection_without_playwright" src="https://user-images.githubusercontent.com/39006076/137054187-75f22904-6292-44d4-9fd2-b8579032358b.png">

Connection does not happen in the Lens instance opened by Playwright :

<img width="1792" alt="connection_time_from_playwright" src="https://user-images.githubusercontent.com/39006076/137054209-a5408cb3-93f3-4445-90ae-bc1bbf8ca5ed.png">

**Comment by Nokel81** [comment]
We don't support this use case of running integration tests in a separate container. We run integration tests either locally or completely in a VM on our CI. The probable reason that playwright cannot connect is because it expects the actual electron process.
