### ISSUE TITLE
Can't login to my account from Mac

### ISSUE THREAD

**Issue by alexander-potemkin** [kontena/lens#4027]
**Describe the bug**
Can't login to my Lens account

**To Reproduce**
1. Go to the app, Profile icon at the Lens app
2. Click on the app, get the browser window, offering to login (via Google in my case)
3. Pass Google authentication, allow the page to open Lens (url: `lens://extension/lenscloud-lens-extension`)
4. Lens opens, but still not logged it; tried to restart the app, but with no luck.

**Expected behavior**
App to login, like it does on Linux.

**Screenshots**
<img width="265" alt="Screenshot 2021-10-13 at 14 32 18" src="https://user-images.githubusercontent.com/2323840/137125264-b19c74b7-b954-45de-8bef-c5ad8608d043.png">

<img width="396" alt="Screenshot 2021-10-13 at 14 35 18" src="https://user-images.githubusercontent.com/2323840/137125254-ec2751b8-3dfd-4649-a8bf-a044f6555257.png">
<img width="1552" alt="Screenshot 2021-10-13 at 14 35 02" src="https://user-images.githubusercontent.com/2323840/137125260-60ec926a-f164-4f79-a9fc-1a331c10f089.png">

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: latest OS X (11.6)
- Installation method (e.g. snap or AppImage in Linux): DMG from the site.

**Logs:**
N/A

**Kubeconfig:**
N/A

**Additional context**
Fresh MacOS, fresh Lens.

**Comment by alexander-potemkin** [comment]
Not Safari specific; downloaded fresh Chrome & got the same issue.

**Comment by chenhunghan** [comment]
@alexander-potemkin would you mind try again now, I can log in using Google account (same on Mac, using Chrome, latest Lens), no issue found.

**Comment by alexander-potemkin** [comment]
Fixed after I found a Lens icon on menu and exit Lens from there as well.
Two questions, thought:
* can I remove the icon?
* shouldn't clusters sync between the computers, when I'm using it?

**Comment by chenhunghan** [comment]
> Fixed after I found a Lens icon on menu and exit Lens from there as well. Two questions, thought:
> 
> * can I remove the icon?
> * shouldn't clusters sync between the computers, when I'm using it?

The icon is there because Lens is running but with main window closed. On mac you can `CMD+Q` to do a "full quit" which close both the window and the tray icon.

The clusters can't be synced because they are from you kubeconfig, and there might be private keys in your kubeconfig (or it's depending on external authentication like `aws-cli`), we might add features to provide end-to-end encryption to sync kubeconfig and protect private keys, but it's not supported yet.

**Comment by alexander-potemkin** [comment]
Got it, thank you. That sounds like a very nice feature, especially for the team, especially if you could somehow manage the kubeconfig auto-expiring.
At the meantime, if you could sync the clusters information, that would be nice already.

For the menu icon - yes, I found how to get rid of it, but I don't want it there at all, if possible? =)

And, just in case - the original issue was valid, somehow sorted out by a full app restart.

**Comment by alexander-potemkin** [comment]
Same issue happens today - after the latest update I can't login to the lens IDE, and I can't access none of my clusters, my work is blocked.

**Comment by alexander-potemkin** [comment]
full app restart doesn't help
Lens: 5.3.2-latest.20211201.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0

**Comment by Nokel81** [comment]
Closing as old, if you are still running into this issue please reopen.
