### ISSUE TITLE
Can't select multiple namespaces from the dropdown on mac

### ISSUE THREAD

**Issue by benonymus** [kontena/lens#4047]
**Describe the bug**
On version 5.2.5 seems like it is not possible to select more than 1 option from the drop down for namespaces.
This works on 5.0.2 on linux.

**To Reproduce**
Go to pods
Click on namespace drop down and try to select additional namespaces form the list, it only select the last selected list item.

**Comment by Nokel81** [comment]
You can click several by pressing ⌥ (option) on macos and Control on windows and linux. This was implemented in https://github.com/lensapp/lens/pull/2919 for 5.1
