### ISSUE TITLE
Auto-update failed 5.1.3 -> 5.2.5

### ISSUE THREAD

**Issue by Nuru** [kontena/lens#4049]
I launched Lens 5.1.3, got the message to update to 5.2.5, clicked "Yes". Lens quit, but did not update. Attempting to run Lens again produces the system error `The application "Lens" is not open anymore.`

`ps` shows the following process running:
```
/Applications/Lens.app/Contents/Frameworks/Squirrel.framework/Resources/ShipIt com.electron.kontena-lens.ShipIt /Users/nuru/Library/Caches/com.electron.kontena-lens.ShipIt/ShipItState.plist
```

Killing that process did not help. Attempting to re-install from DMG failed with "The operation can’t be completed because the item “Lens” is in use". Looks like I'm going to have to reboot the machine to clear the problem.

**Environment (please complete the following information):**
- Lens Version: 5.1.3 -> 5.2.5
- OS: macOS 10.15.7 (intel)
- Installation method (e.g. snap or AppImage in Linux): DMG

**Comment by Nokel81** [comment]
Thanks I believe that this will be fixed by #4248
