### ISSUE TITLE
/var/run/netns

### ISSUE THREAD

**Issue by AkakievKD** [kontena/lens#4056]
Hello, sometimes when i delete pods or daemonset or statefullset, i have this massage in events of pod - error determining status: rpc error: code = Unknown desc = failed to get sandbox ip: check network namespace closed: remove netns: unlinkat /var/run/netns/cni-b95837c6-ae48-a889-7760-84b91b7af749: device or resource busy
And pods lives in status "terminating" untill you don`t reboot all nodes, but i use lens and manage kubernetes with it, i try delete in lens.
may be there is a bug in lens. I use 1.21.4 version of kubernetes

**Comment by Nokel81** [comment]
This is almost certainly a bug with either kubernetes or with the configuration of these kube nodes and not a lens bug.
