### ISSUE TITLE
MacBook Crash attributed to Lens Helper (Renderer)

### ISSUE THREAD

**Issue by jgrasett** [kontena/lens#4103]
**Description**
MAcBook crashed, crash report stats Lens Helper (renderer) as source of Panic

**To Reproduce**
Running Lens
MacBook Crashes

**Expected behavior**
MacBook does not crash

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.5-latest.20211001.2
- OS: macOS Big Sur 11.6
- Installation method (e.g. snap or AppImage in Linux): Mac Package and updates

**Logs:**
Macbook Crash Log:
Panic(CPU 2, time 103013451203727): NMIPI for spinlock acquisition timeout, spinlock: 0xffffff86aa152550, spinlock owner: 0xffffff869aab6b20, current_thread: 0xffffff869aab6b20, spinlock_owner_cpu: 0x2
RAX: 0xffffff86aae36280, RBX: 0xffffff9361820c88, RCX: 0x00000000000002d2, RDX: 0x0000110600000000
RSP: 0xffffffb0ccafb520, RBP: 0xffffffb0ccafb560, RSI: 0xffffff869aab6b20, RDI: 0xffffff9361820c88
R8:  0xffffffb0ccafb6e0, R9:  0xffffff8005ce2fb0, R10: 0x0000000000ffffff, R11: 0x0000000000000444
R12: 0xffffff869aab6b20, R13: 0x0000000000000000, R14: 0x0000110695e8818a, R15: 0xffffff86aae36280
RFL: 0x0000000000000017, RIP: 0xffffff8005c9fee7, CS:  0x0000000000000008, SS:  0x0000000000000010
Backtrace (CPU 2), Frame : Return Address
0xffffffa05881ef80 : 0xffffff8005dc3d6b 
0xffffffa05881efd0 : 0xffffff8005c31bdd 
0xffffffb0ccafb560 : 0xffffff8005ca0004 
0xffffffb0ccafb590 : 0xffffff8005ce1800 
0xffffffb0ccafb5b0 : 0xffffff8005ce2fe9 
0xffffffb0ccafb660 : 0xffffff8005ce34e2 
0xffffffb0ccafb6d0 : 0xffffff8005ce255a 
0xffffffb0ccafb790 : 0xffffff8005ce6465 
0xffffffb0ccafb7d0 : 0xffffff80061f85c4 
0xffffffb0ccafb7f0 : 0xffffff80061f86ae 
0xffffffb0ccafb830 : 0xffffff800628877d 
0xffffffb0ccafb870 : 0xffffff80060df128 
0xffffffb0ccafbba0 : 0xffffff80060c7d07 
0xffffffb0ccafbbf0 : 0xffffff80060c905f 
0xffffffb0ccafbd10 : 0xffffff8005fdb0bc 
0xffffffb0ccafbd40 : 0xffffff8005fa4049 
0xffffffb0ccafbd60 : 0xffffff8005f94241 
0xffffffb0ccafbd90 : 0xffffff8005f93d8a 
0xffffffb0ccafbf30 : 0xffffff8005f953d3 
0xffffffb0ccafbfa0 : 0xffffff8005c3113e 

Process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20G165

Kernel version:
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
Kernel UUID: C2591F4E-EE82-33CC-8C59-DB81D9AD80DD
KernelCache slide: 0x0000000005a00000
KernelCache base:  0xffffff8005c00000
Kernel slide:      0x0000000005a10000
Kernel text base:  0xffffff8005c10000
__HIB  text base: 0xffffff8005b00000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Hibernation exit count: 6

System uptime in nanoseconds: 103013451230960
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00005db0b02af11b
  Sleep   : 0x0000564d31686021 0x00000001fda3c36e 0x0000564ba817a1e7
  Wake    : 0x0000564d3c097134 0x00000000628ca0b4 0x0000564d3973e469
last started kext at 225509211215: com.google.drivefs.filesystems.dfsfuse	45.3.0 (addr 0xffffff7fa2824000, size 86016)
last stopped kext at 191281595264: >!AFIVRDriver	4.1.0 (addr 0xffffff7f9f251000, size 8192)
loaded kexts:
com.google.drivefs.filesystems.dfsfuse	45.3.0
org.virtualbox.kext.VBoxNetAdp	6.1.22
org.virtualbox.kext.VBoxNetFlt	6.1.22
org.virtualbox.kext.VBoxUSB	6.1.22
org.virtualbox.kext.VBoxDrv	6.1.22
>!APlatformEnabler	2.7.0d0
>AGPM	122.1
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@fileutil	20.036.15
>AudioAUUC	1.70
>!ATopCaseHIDEventDriver	4050.1
>!AHIDALSService	1
@kext.AMDFramebuffer	4.0.6
@kext.AMDRadeonX4000	4.0.6
@kext.AMDRadeonServiceManager	4.0.6
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.3.5
>!A!IKBLGraphics	16.0.5
>!AMuxControl2	6.3.5
>AGDCBacklightControl	6.3.5
>!AMCCSControl	1.14
>BridgeAudioCommunication	140.4
@AGDCPluginDisplayMetrics	6.3.5
@kext.AMD9500!C	4.0.6
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AGFXHDA	100.1.433
>!AAVEBridge	6.1
|IO!BSerialManager	8.0.5d7
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!A!ICFLGraphicsFramebuffer	16.0.5
>!AThunderboltIP	4.0.3
>!ABridgeAudio!C	140.4
>!A!IPCHPMC	2.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>Core!SFsck	554.140.2
>usb.!UHostBillboardDevice	1.0
|SCSITaskUserClient	436.140.1
>BCMWLANFirmware4378.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4355.Hashstore	1
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.100.11
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ABCMWLANBusInterfacePCIeMac	1
@filesystems.apfs	1677.141.2
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	311
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
|IOUSBUserClient	900.4.2
@kext.triggers	1.0
>!AHIDKeyboard	224
>!AActuatorDriver	4440.3
>!AMultitouchDriver	4440.3
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4050.1
>IO!BHIDDriver	8.0.5d7
@kext.AMDRadeonX4100HWLibs	1.0
@kext.AMDRadeonX4000HWServices	4.0.6
>!AGraphicsControl	6.3.5
>!ABacklightExpert	1.1.0
>!ASMBus!C	1.0.18d1
>X86PlatformPlugin	1.0.0
|IO!BHost!CUARTTransport	8.0.5d7
|IO!BHost!CTransport	8.0.5d7
>!UMergeNub	900.4.2
@kext.AMDSupport	4.0.6
|IOAVB!F	940.4
|IOEthernetAVB!C	1.1.0
|IONDRVSupport	585.1
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
@plugin.IOgPTPPlugin	985.2
|IOAccelerator!F2	442.9
>!AThunderboltDPOutAdapter	8.1.4
>!UAudio	405.39
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>IOPlatformPlugin!F	6.0.0d8
@!AGPUWrangler	6.3.5
@!AGraphicsDeviceControl	6.3.5
|IOGraphics!F	585.1
|IOSlowAdaptiveClocking!F	1.0.0
>Core!S	554.140.2
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.IOUSBHostHIDDevice	1.2
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AThunderboltPCIDownAdapter	4.1.1
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssI2C	3.0.60
>!A!ILpssDmac	3.0.60
>!ABSDKextStarter	3
|IOSurface	290.8.1
@filesystems.hfs.encodings.kext	1
>!ABCMWLANCoreMac	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
>corecapture	1.0.4
>!AXsanScheme	3
>!AThunderboltNHI	7.2.8
|IOThunderbolt!F	9.3.2
>usb.!UVHCIBCE	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCI	1.2
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOTimeSync!F	985.2
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.5d7
|IOReport!F	47
|IO!BPacketLogger	8.0.5d7
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.141.1
|IOUSBMass!SDriver	184.140.2
|IOSCSIBlockCommandsDevice	436.140.1
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.140.1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1
panic(cpu 10 caller 0xffffff80064a0afd): "Spinlock acquisition timed out: lock=0xffffff86aa152550, " "lock owner thread=0xffffff869aab6b20, current_thread: 0xffffff86aae36280, " "lock owner active on CPU 0x2, current owner: 0xffffff869aab6b20, time: 103013451251176"@/System/Volumes/Data/SWE/macOS/BuildRoots/38cf1d983f/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.141.6/osfmk/i386/locks_i386.c:541
Backtrace (CPU 10), Frame : Return Address
0xffffffa078e2cad0 : 0xffffff8005c8cfdd 
0xffffffa078e2cb20 : 0xffffff8005dd3fd3 
0xffffffa078e2cb60 : 0xffffff8005dc45ca 
0xffffffa078e2cbb0 : 0xffffff8005c31a2f 
0xffffffa078e2cbd0 : 0xffffff8005c8c7fd 
0xffffffa078e2ccf0 : 0xffffff8005c8caf3 
0xffffffa078e2cd60 : 0xffffff800649cdca 
0xffffffa078e2cdd0 : 0xffffff80064a0afd 
0xffffffa078e2ce10 : 0xffffff8005db8f95 
0xffffffa078e2ce30 : 0xffffff8005cade16 
0xffffffa078e2ce60 : 0xffffff8005cdcb6f 
0xffffffa078e2cf20 : 0xffffff8005dafe13 
0xffffffa078e2cf60 : 0xffffff8005dcd64a 
0xffffffa078e2cf80 : 0xffffff8005dc3d6b 
0xffffffa078e2cfd0 : 0xffffff8005c31bdd 
0xffffffa0b995bda0 : 0xffffff8005ce624e 
0xffffffa0b995be00 : 0xffffff800624f33f 
0xffffffa0b995bf00 : 0xffffff800624e3b6 
0xffffffa0b995bf40 : 0xffffff800633f1de 
0xffffffa0b995bfa0 : 0xffffff8005c321f6 

Process name corresponding to current thread: Lens Helper (Renderer)

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
This issue may be a one off, I run Lens against 3 clusters all day every day, and this is only occurrence.

**Comment by Nokel81** [comment]
I would recommend doing a hardware test https://support.apple.com/en-ca/HT202731.

From what I can tell this doesn't seem to be an issue with Lens. It is either an issue with your hardware, or electron.

Either way I don't see how we would be able to debug this from a JS perspective. Sorry about the inconvenience.
