### ISSUE TITLE
I can't read the Custom Resource Definition yaml in Lens

### ISSUE THREAD

**Issue by csantanapr** [kontena/lens#4180]
**Describe the bug**
I need to read the CRD, I usually read if with `kubectl edit crd <CRD>` or `kubectl explain`
When I try to click or right-click a Definition I can't see the yaml of the CRD.

I can see the yaml of a CR, but not the yaml of the CRD

**To Reproduce**
1. Go to Custom Resources
2. Click on any of the Definitions
3. Try to right-click on a Definition
4. Can't see the yaml of the CRD.

**Expected behavior**
Be able to read the documentation for a CRD

**Screenshots**
![image](https://user-images.githubusercontent.com/1094878/139363466-e3c91a53-ffc3-44e0-9020-ada4a18df02b.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.5
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): download dmg

**Comment by Nokel81** [comment]
If you go to `Defenitions` and click on the name there, you should be able to "Edit" it and see its yaml.

**Comment by Nokel81** [comment]
Closing this as it is possible to view that YAML from Lens. I have opened #4211 as an enhancement issue about making it more obvious.

**Comment by csantanapr** [comment]
Hi @Nokel81 I don't see the "Edit" on this screenshot.
I repeat again I want to edit the CRD and not the CR
![image](https://user-images.githubusercontent.com/1094878/140207113-d38f7cb0-100c-4a73-8ada-ced8ad07076a.png)
This is the yaml I want to view, it can't be edited but it should be able to read it.
Like
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
  creationTimestamp: "2021-10-27T16:21:48Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: knative-operator
    app.kubernetes.io/version: 20211027-f28261ba
    operator.knative.dev/release: v20211027-f28261ba
  name: knativeservings.operator.knative.dev
  resourceVersion: "1878115"
  uid: 459d5f1f-ef22-4986-9e7e-6dbf403fb900
spec:
  conversion:
    strategy: None
  group: operator.knative.dev
```

**Comment by Nokel81** [comment]
![Screen Shot 2021-11-04 at 8 43 04 AM](https://user-images.githubusercontent.com/8225332/140315404-9e706a10-1b3f-4976-8369-d3e474f75319.png)
![Screen Shot 2021-11-04 at 8 43 21 AM](https://user-images.githubusercontent.com/8225332/140315446-1a4bdfa4-3f22-41bd-a9d4-5cfc8bc9ad77.png)
![Screen Shot 2021-11-04 at 8 45 20 AM](https://user-images.githubusercontent.com/8225332/140315690-340bcc05-24d4-4c84-b1a2-608292903c59.png)

**Comment by csantanapr** [comment]
Thanks @Nokel81 for the screenshot.

Now I see that you need to click "Definitions" and then the other problem is.
If you click on the CRD name it takes to the table but if you click any where in the row then it shows the details.
![image](https://user-images.githubusercontent.com/1094878/140450775-e5957b0a-cbec-4a05-9212-ebba9a1f2bac.png)
![image](https://user-images.githubusercontent.com/1094878/140450892-134a7f02-2e35-409b-8c32-483d5f388078.png)
