### ISSUE TITLE
One inaccessible namespace blocks resource list for all namespaces

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4192]
If a namespace that is not actually accessible for a user is added to the accessible namespaces list then, when filtering a resource listing, if that namespace is selected the resource list shows "Failed to load items", even if other, accessible namespaces are selected as well.

https://user-images.githubusercontent.com/40840436/139463368-d95b2622-94a9-49bb-8f7b-e13a991606a5.mov

Expected behaviour: show resources for all selected namespaces that are accessible, post a notification or some error indicator that says "Failed to load items" for any namespaces that aren't accessible.

**Comment by Nokel81** [comment]
Is this also the case if the namespaces are shown without accessibleNamespaces being involved?

**Comment by jim-docker** [comment]
Yes:

https://user-images.githubusercontent.com/40840436/139483950-49505ec6-1cd3-4e12-ae06-e0279a601e55.mov

user here only has permissions to get pods in the default namespace (Accessible Namespaces setting is empty)

**Comment by Nokel81** [comment]
That is good to know, thanks for verifying that.
