### ISSUE TITLE
Pods filter by Status

### ISSUE THREAD

**Issue by josepowera** [kontena/lens#4202]
**What would you like to be added**:
On Workloads->Pods allow to filter by status.

That would help user to filter any pending or "non running" pods.

**Why is this needed**:
We run > 200 pods and finding anything not running takes time and is error prone.

**Environment you are Lens application on:**
non enviorment specific
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- k3s
- Desktop OS: <the OS Lens app runs on in your case>
windows

**Comment by Nokel81** [comment]
FYI the search field does search the status message on the pods.

**Comment by Nokel81** [comment]
Closing as duplicate of https://github.com/lensapp/lens/issues/2069
