### ISSUE TITLE
Add Cluster Button is Disabled

### ISSUE THREAD

**Issue by suadev** [kontena/lens#4210]
I can't add any kube config to Lens. It's just disabled.  I also tried to sycnc the folder that contains my configs. It didm't worked. I sync the folder and nothing happens

![image](https://user-images.githubusercontent.com/5918811/139636002-24ba5a7b-fa98-4786-a532-8fdf08c32f9e.png)

**Comment by suadev** [comment]
Between, I re-installed Lens but it didn't worked.

**Comment by Nokel81** [comment]
You have no contexts to add which is why nothing shows up while syncing and why the button is disabled.

**Comment by suadev** [comment]
@Nokel81  thank you for the reply. But, How can i create a context, i didn't get it. Can you explain it please?

**Comment by Nokel81** [comment]
your kubeconfig is a YAML file (or JSON) which has a `contexts` field. Currently it is empty for you. I would recommend reading https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

Given the rest of your file I would make that section the following:

```yaml
contexts:
 - context:
     user: kubernetes-admin
     cluster: listing-k8s-as
   name: listing-k8s-as
```
