### ISSUE TITLE
to see CRD updates need to disconnect and reconnect 

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#4227]
**Describe the bug**
to see CRD updates need to disconnect and reconnect from the cluster. 

**To Reproduce**
1. add a CRD
2. look for it
3. cant find it? disconnect
4. reconnect. there it is!
5. delete a CRD
6. its still there!
7. disconnect and reconnect.
8. its gone!

**Expected behavior**
- expecting the lens app to update the CRD list and shows us what is the actual state of the cluster

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: [e.g. OSX] 11.6.1
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here... 
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Do you have watch permissions on CRDs?

**Comment by marafa-sugarcrm** [comment]
> Do you have watch permissions on CRDs?

yes i set up the cluster myself and have 100% admin over everything

**Comment by Nokel81** [comment]
What sort of cluster is it?

**Comment by marafa-sugarcrm** [comment]
> What sort of cluster is it?

kops managed cluster in AWS (ec2 instances)
