### ISSUE TITLE
Not possible to write unit tests for components that import Monaco editor 

### ISSUE THREAD

**Issue by jansav** [kontena/lens#4239]
**Describe the bug**

We weren't able to write unit tests for components that used some component that imported Monaco editor. Screenshot attached. 

**To Reproduce**
1. Create new unit test
2. Import eg. `kube-object-menu.tsx`
3. Try rendering the component (or even console.log)

**Expected behavior**
Shouldn't crash fatally.

**Screenshots**

**Environment**
- Lens Version: from master
- OS: OSX
- Running tests using `make test -- --watch`

<img width="1066" alt="Screen Shot 2021-11-03 at 12 44 20" src="https://user-images.githubusercontent.com/3083083/140047500-289f8cfb-6a57-45ff-a9d1-2084e46e3c87.png">

**Comment by Nokel81** [comment]
For the time being I think you need to use `jest.mock("react-monaco-editor", () => null);` until this is fixed by #4225
