### ISSUE TITLE
App resize on MacOS

### ISSUE THREAD

**Issue by jer0m** [kontena/lens#4257]
**What would you like to be added**:  Be able to fit the Lens app to the screen by clicking on the top bar on MacOS.

**Why is this needed**: On MacOS, almost all apps can adapt to the screen size by double clicking on the top bar. MacOS users are used to this.

**Comment by Nokel81** [comment]
This will be difficult to implement because of https://bugs.chromium.org/p/chromium/issues/detail?id=229330
