### ISSUE TITLE
Lens frequently stuck at "Authentication proxy started"

### ISSUE THREAD

**Issue by bruno-brant** [kontena/lens#4260]
**Describe the bug**
When trying to connect to a cluster, sometimes Lens get stuck at the _connecting_ screen.

This bug is not deterministic (AFAICT) - sometimes it works, sometimes it gets stuck. I can confirm that when the issue arises, I'm still able to consult the cluster using `kubectl`. 

**To Reproduce**
Try to connect to a cluster.

**Expected behavior**
The cluster screen shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/1890900/140396943-06194195-b114-4e47-a2b1-4c0e0e5118a5.png)

**Environment (please complete the following information):**
- Lens Version: 5.2.5-latest.20211001.2
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):
scoop.sh

**Comment by Nokel81** [comment]
Does it get stuck for more than 10s?

**Comment by bruno-brant** [comment]
> 
> 
> Does it get stuck for more than 10s?

It does! I can't attest it for sure but I think that sometimes it get stuck on that screen eternally, and sometimes it errors out after a very long time.

I think I found some relationship between closing Lens screen and issue. It seems that it's at least more prone to occur after I've opened Lens, closed it so that it minimizes to the system tray icon, and then reopened it from that icon. 

I can also tell you that this has been happening for a long time - actually, maybe ever since I started using Lens on my current work machine.

----

And on that note, the underlying cause could be (probably is) another issue. From time to time, when connecting to k8s via kubectl I get a certificate error. This again is very non-deterministic; sometimes it happens once or twice in a row and then works, all I have to do is repeat the command. Other times, it simply refuses to work and I need to logoff from my Windows account and login again.

Now, this last issue is certainly related to a number of "security" tools that my company installs on my machine (crap like Tanium, something called edpa, BeyondTrust, etc.). I think at least one of those tools might be creating a proxy or interfering with my certificates in some way. 

If that's the case, then the issue is on my machine, and not with Lens, but I do think that at the very least the connection attempt should timeout earlier.

**Comment by maartengo** [comment]
It almost seems like what happened with #3226 at some point. I have to first get to the 'authentication proxy started' part, then navigate to any other item (e.g. the catalog) and then select the original connection to get it to work.
I only got this problem after the last update, was working fine just a few days ago.

![image](https://user-images.githubusercontent.com/46345801/141312752-efcbcd68-e5d0-45d5-8619-efbaf28a8c0a.png)

**Comment by Nokel81** [comment]
There are several PRs that should help address this, but they aren't out yet as part of any release. They should be part of 5.3.0-alpha.11 though

**Comment by d2k-klin** [comment]
even with the latest version the issue still persist:
![image](https://user-images.githubusercontent.com/71728742/144753158-5590dcfe-3f3b-45cf-afe6-a754864aa440.png)
Lens doesn't work with EKS.....

**Comment by bruno-brant** [comment]
Just checking in to confirm that the issue is completely related to my (work) machine. I've been using my personal desktop for the last 4 weeks and I haven't seem this come up once. 

I still believe it has something to do with the security daemons I'm forced to run by my employer, but I unfortunately can't disable them to find out which.

So, while Lens is not to blame on this issue, better user feedback seems to be the problem here. When communication fails with the cluster for some reason, Lens should alert the user (possibly informing the reason for the issue) instead of being stuck on a login screen forever (or even for a really long time).

**Comment by Nokel81** [comment]
@bruno-brant Do you eventually see `Refreshing connection status ...` or `Proxy port failed to be used within timelimit, restarting...`?
