### ISSUE TITLE
helm charts are outdated

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#4263]
**Describe the bug**
the helm charts available are outdated and most are deprecated. randomly clicking on the charts available show 
``` $  helm install . --generate-name
Error: template: deprecation/templates/NOTES.txt:10:3: executing "deprecation/templates/NOTES.txt" at <fail "\n*******************************************************\n* This chart location is deprecated. Learn more here: *\n* https://helm.sh/blog/charts-repo-deprecation/       *\n*******************************************************\n">: error calling fail:
*******************************************************
* This chart location is depreacted. Learn more here: *
* https://helm.sh/blog/charts-repo-deprecation/       *
*******************************************************
```

**To Reproduce**
1. Go to cluster
2. Click on apps
3. click on any chart
4. see error above

**Expected behavior**
just works!

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.5-latest.20211001.2
- OS: [e.g. OSX] 11.6.1
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

also https://github.com/lensapp/artifact-hub-repositories/releases/ has not been updated in 5 months

**Comment by Nokel81** [comment]
related https://github.com/lensapp/artifact-hub-repositories/issues/1

**Comment by Nokel81** [comment]
Can you give a clear example of which charts are deprecated. Because the `artifact-hub-repositories/releases` is only for adding new repos, not the charts themselves. We call `helm update` on startup and after https://github.com/lensapp/lens/pull/3973 (which will be 5.3.0) if you run `helm update` yourself.

**Comment by marafa-sugarcrm** [comment]
all in the picture (home page of charts) even the ones without the word `deprecated` in the title have it in their description (also i updated to this morning's version)
![Screen Shot 2021-11-05 at 11 55 25 AM](https://user-images.githubusercontent.com/69474017/140540180-da66e0cf-d9bc-4502-bd6d-af9f7dd651ac.png)

**Comment by Nokel81** [comment]
That is because the `stable` repo has been completely deprecated. You can safely remove that repo and use `bitnami` instead. We switched the default one from `stable` to `bitnami` in https://github.com/lensapp/lens/pull/1479 which was nearly a year ago.
