### ISSUE TITLE
Monaco resource window cursor position resetting and not remembered

### ISSUE THREAD

**Issue by doug-shontz** [kontena/lens#4296]
**Describe the bug**
This *MIGHT* be an enhancement but it seems to work differently than pre v5 versions, so I'm thinking bug over feature.

I did not notice this behavior before the Monaco update, so I'm thinking Monaco might have something to do with this.  When you are working in resource windows (looking at the YAML configs) and have multiple tabs open, the cursor position always seems to reset to line 1 position 1 whenever the tab loses focus and then gains focus again.  This makes it very difficult to compare two configurations or copy/paste sections of configurations.

Before Monaco, I knew I had to actually click in the YAML where I wanted the cursor to "stick", but, once I actually clicked on a line, switching back and forth between tabs always behaved by remembering the cursor position in each tab.  Now, it seems to reset to line 1 position 1 each time switching between tabs.

**To Reproduce**
- Open multiple edit windows for resources (create multiple tabs).  This is better shown if you open YAML configs that are very long.
- In "window 1", scroll to a position in one window that is far below the top and click on a particular line
- Switch to "window 2".  Note that you are at the top position of the YAML.
- Scroll to a position below the top and click in the YAML.
- Flip back to "window 1" and notice that you are "reset" to line 1 position 1 (there is a slight lag almost like the window is completely reloading the configuration in case anything changed).
- Switch to "window 2" and notice that you are at line 1 position 1 (again with the same lag).

**Expected behavior**
I get it can be argued either way that the windows reload in case something has changed since the last time you viewed the window, but that's not exactly what I would expect.  I would expect the YAML to stay in memory as it was when it was loaded into the tab.  I would particularly expect that the position of the cursor be remembered so flipping back and forth between tabs would not necessitate me having to find my position over and over.

**Environment (please complete the following information):**
- Lens Version:  Lens: 5.2.6-latest.20211104.1
- OS: MacOS Big Sur 11.6.1
- Installation method (e.g. snap or AppImage in Linux): Direct DMG install from https://k8slens.dev/

**Comment by Nokel81** [comment]
This was fixed by #4225 and is part of 5.3.0-alpha.9
