### ISSUE TITLE
Support Port-Forwarding

### ISSUE THREAD

**Issue by Danny-m08** [kontena/lens#4306]
**What would you like to be added**:
We should be able to use Lens IDE to create and manage port-forwarding.

**Why is this needed**:
Port forwarding is tedious to manage as they need to run in the background to avoid blocking shell sessions. It would be incredibly convenient if we can use lens to manage port forwarding processes by starting and stopping them at our discretion. 

**Environment you are Lens application on:**
MacOS but should be supported across all platforms

**Comment by Nokel81** [comment]
Lens already has basic port forwarding support, but managing port forwards was implemented in #3922 and will be part of 5.3.0
