### ISSUE TITLE
discrepancy in node view - delete or remove?

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#4312]
**Describe the bug**
in the nodes view .. clicking on a nodes hamburger menu says "remove" yet when you click on the node itself the toolbar menu has the trash can icon title "delete" . which is it?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
It is the same, but I agree they should read the same as well.
