### ISSUE TITLE
Pods list on Deployment details page doesn't update

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4314]
This is happening on master:

https://user-images.githubusercontent.com/40840436/141183468-e72f1d40-f3ea-4554-80c9-2e9cf101eed5.mov

Even if you close the details page or show a different deployment's details page and then reopen the details page, the pods list is stale. If you click to a different dashboard page and then back to deployments and reopen, then the pods list is up-to-date. Missing watch on pods for deployments?

**Comment by Nokel81** [comment]
Regression from #4089
