### ISSUE TITLE
Terminal leaks processes on reload (or network disconnect/connect)

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#4318]
**Describe the bug**
Regression from https://github.com/lensapp/lens/pull/4258 . Frame reload (or network disconnect/connect) does spawn a new shell and leaves existing process running in the background.

**To Reproduce**
1. Open terminal
2. Run `top`
3. Reload frame
4. See the issue

**Expected behavior**

Terminal should connect to existing process and not leak processes to background.

**Environment (please complete the following information):**
- Lens Version: 5.3.10-alpha.10

**Comment by jim-docker** [comment]
Noticed that the process leak does not happen on linux
