### ISSUE TITLE
AutoUpdate Lens but it only uninstalls the old version

### ISSUE THREAD

**Issue by zqr95518** [kontena/lens#4324]
**Describe the bug**
Update Lens but he uninstall himself.

**To Reproduce**
1. When I see a new version notice, I click yes and he uninstall himself.

**Expected behavior**
Success update

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.2.5 5.2.6
- OS: win10 19043.1320
- exe

**Additional context**
It seems lens download new file failed, and didn't check the broken file and can't install by himself.

**Comment by pkExec** [comment]
Can confirm, just happened to me too.

**Comment by Nokel81** [comment]
Did you install Lens for "All Users" or just "Current User"?

**Comment by pkExec** [comment]
> Did you install Lens for "All Users" or just "Current User"?

All Users.
UAC is turned off.

**Comment by agronholm** [comment]
The .rpm and .appimage both have the same problem. I supposedly installed 5.2.7 but then the "about" menu shows that I am in fact running 5.2.6 and it's constantly asking me to update. "Updating" does nothing however.

**Comment by Nokel81** [comment]
AppImage updating is fixed in 5.3.0.

I don't think that rpm supports auto update

**Comment by agronholm** [comment]
> I don't think that rpm supports auto update

It doesn't, so it shouldn't be asking to update. But it does.

**Comment by agronholm** [comment]
Is there an ETA for 5.3.0?

**Comment by Nokel81** [comment]
Yes this week, the 5.3.0-beta.1 should be released today.

Note: auto update is fixed in that version, but since you will still have the broken version you will need to do so manually.

**Comment by agronholm** [comment]
Gotcha.

**Comment by Nokel81** [comment]
> > Did you install Lens for "All Users" or just "Current User"?
> 
> All Users. UAC is turned off.

I believe that electron-updater currently is broken surrounding all user installs on windows. Will investigate.
