### ISSUE TITLE
Lens 5.2.6+ crd problem

### ISSUE THREAD

**Issue by sergeyshaykhullin** [kontena/lens#4328]
**Describe the bug**
More details: https://k8slens.slack.com/archives/CDR6AHSCC/p1636723013105500

**To Reproduce**

**Expected behavior**
Tabs showing

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
@sergeyshaykhullin Would you mind filling out the issue more?
