### ISSUE TITLE
Namespace selection changes on its own

### ISSUE THREAD

**Issue by bizzbizz** [kontena/lens#4336]
Sometimes when I destroy and create my stack, after I refresh Lens I notice some of my pods are missing, then I notice that the namespace selection was changed on its own. I always choose "All Namespaces" and it sometimes changes to the "first four"

![image](https://user-images.githubusercontent.com/6141716/141761211-29407f75-32c7-40b9-afd9-558a39fae702.png)

**Comment by Nokel81** [comment]
This should be fixed by #3983 in the 5.3.0-alpha's.
