### ISSUE TITLE
Check for updates option in the top menu

### ISSUE THREAD

**Issue by ixrock** [kontena/lens#4380]
Would be nice to have an option for manual checking for updates as `vscode` does:

<img width="355" alt="Screenshot 2021-11-18 at 16 17 39" src="https://user-images.githubusercontent.com/6377066/142432731-90fd3d0c-f83b-4b78-88d4-537012788878.png">
<img width="333" alt="Screenshot 2021-11-18 at 16 17 21" src="https://user-images.githubusercontent.com/6377066/142432728-57a536da-6a64-4fdb-940e-7e5094af3b93.png">

In addition we could auto-check new version when opening `About Lens` similarly as done in `chrome`:
<img width="339" alt="Screenshot 2021-11-18 at 16 22 28" src="https://user-images.githubusercontent.com/6377066/142433261-035ce1e5-74f6-4258-8ab5-d1dd5100b376.png">
<img width="612" alt="Screenshot 2021-11-18 at 16 24 23" src="https://user-images.githubusercontent.com/6377066/142433530-aaf9627b-2b20-4f9c-a9d1-9f82f695cd9a.png">

**Comment by Nokel81** [comment]
We already have this in the tray icon

**Comment by ixrock** [comment]
> We already have this in the tray icon

Argh, just realized that we have it only in production version..
So, what _about_ auto-checking on opening _about_?

![image](https://user-images.githubusercontent.com/6377066/142440397-fdbf393f-d347-449a-8afb-3b229089a608.png)
_(development version)_

**Comment by Nokel81** [comment]
It is only active in the tray icon if the auto updater is active (has a connection to the server, is signed, etc...)

So you want it to check for updates when clicking on "About OpenLens" as well?

**Comment by ixrock** [comment]
> So you want it to check for updates when clicking on "About OpenLens" as well?

Yes, would be convenient as this UX good aligns with other apps + might help with some issues when update is stuck for some reasons, etc. Wdyt?

**Comment by Nokel81** [comment]
I don't see how this would help if the update is stuck but if other apps do it too, it doesn't sound too bad.

**Comment by ixrock** [comment]
> I don't see how this would help if the update is stuck

You can handle this update-check (e.g. from _about ->_) differently and run some kinda force-update? No?
I remember the case when I should re-download `Lens.app` since updating stucked forever at some point.

**Comment by Nokel81** [comment]
I think you are referring to when `electron-updater` (the package we use) was broken on macOS and linux (fixed by #4248 and #4256). I don't quite see how we could bypass it without completely rewriting all that logic.
