### ISSUE TITLE
Cluster Dashboard navigation compromised

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4398]
This is how I reproduced this, there are probably other ways. ~~I think it just needs to involve a spaces cluster (not a local cluster)~~ reproduced with local cluster (that is at least shared through spaces)

1. For a spaces cluster add kube-prometheus helm chart (via Apps -> Charts)
2. go to releases tab
3. click on other tabs/drawers (in the following video Cluster was clicked on, which brings up the cluster details, not the cluster metrics overview).
4. Clicking on Nodes does nothing, then clicking workload -> overview brings up the Remove Cluster dialog (second video)

https://user-images.githubusercontent.com/40840436/142698692-ed8815b1-0182-424c-866d-9c863231fdd9.mov

https://user-images.githubusercontent.com/40840436/142698699-c665b0b3-8db8-4137-8359-9a1bc2de5ecb.mov

Actually it may be that the cluster title dropdown menu is reacting to clicks (even though the dropdown menu is not visible)??

5.3.0-beta.2, tried on Windows and Linux

**Comment by Nokel81** [comment]
I have run into this on macOS as well.

**Comment by aleksfront** [comment]
Relates to https://github.com/lensapp/lens/issues/4075

When you quickly jump off the cluster iframe with opened menu, `Animate` component (which is wrapped around `Menu`) doesn't have time to close menu, because it waits for `onTransitionEnd` event which is never triggers.

**Comment by Nokel81** [comment]
Would it be better to do that with css instead of js?
