### ISSUE TITLE
Docs for deploying lens on a server?

### ISSUE THREAD

**Issue by johannkm** [kontena/lens#4403]
I'm considering using Lens as a way to make it easy for team members to check in on clusters. Is it reasonable to deploy lens on a server for this? Are there any examples of making this work?

**Comment by Nokel81** [comment]
Lens is a desktop application only. It does not support being installed on a server. However, [Lens Spaces](https://docs.k8slens.dev/main/spaces/) sounds a lot like what you might be after.

**Comment by johannkm** [comment]
Yep, thanks. We'll evaluate this.

For what it's worth, before asking here I searched around a little bit on the site hoping there would be a paid service that solves this issue, and couldn't find it. I also tried to join the Slack to ask, but it looks like that's not open to new members?

**Comment by Nokel81** [comment]
The slack link: https://join.slack.com/t/k8slens/shared_invite/zt-wcl8jq3k-68R5Wcmk1o95MLBE5igUDQ should work. It is open for everyone

**Comment by johannkm** [comment]
Ah looks like the issue is with the link at the bottom of the docs site: http://k8slens.slack.com/
