### ISSUE TITLE
When updating it uninstalls itself

### ISSUE THREAD

**Issue by davidnalbandyan1** [kontena/lens#4423]
**Describe the bug**
After getting notified for an update and trying to update it uninstalls the program without a trace.
I checked the installation folder on my machine on "C:\Program Files\Lens" and it was completely empty. 
**To Reproduce**
1. my installed version was before the current "v5.3.0" one
2. when starting get the notification for the update
3. click on it
4. and it uninstalls itself

**Expected behavior**
An update should be an update.

**Environment (please complete the following information):**
- Lens Version: one before the current one "v5.3.0"
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): from the official website https://k8slens.dev/

**Comment by Nokel81** [comment]
This is a known issue, that was fixed by #4390. There is nothing we could do with previously installed versions.
