### ISSUE TITLE
5.3.0-latest.2021125.2 crash frequently on win10

### ISSUE THREAD

**Issue by usernameisnull** [kontena/lens#4430]
windows version:  win10 20H2 19042.985

**Comment by usernameisnull** [comment]
Where can I download the old version？

**Comment by usernameisnull** [comment]
![image](https://user-images.githubusercontent.com/3390414/143544233-d0087f9c-5a36-4ff2-a699-d38803b396bb.png)
too many crashes...

**Comment by usernameisnull** [comment]
some one here?

**Comment by jim-docker** [comment]
Can you provide more details on the crashes?

**Comment by usernameisnull** [comment]
> Can you provide more details on the crashes?

The UI interface is very easy to freeze, and then the above screenshot appears.I have to kill the process, by the way, where can I download the older version? not found on your download page

**Comment by jim-docker** [comment]
Can you translate the message? Do you see this right on startup? Or are you able to navigate the UI somewhat? Connect to a cluster?

The previous version is [here](https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.2.7-latest.20211110.1.exe)

**Comment by usernameisnull** [comment]
> Can you translate the message? Do you see this right on startup? Or are you able to navigate the UI somewhat? Connect to a cluster?
> 
> The previous version is [here](https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.2.7-latest.20211110.1.exe)

not on startup, I can see the UI, click somewhere especially type in shell when I use chinese  input method,very easy to crash。
I think the picture like this:
https://appuals.com/wp-content/uploads/2019/04/microsoft_windows_not_responding.png

**Comment by Asi1l** [comment]
Dear all - note this version is bugged  - Do NOT install or upgrade to this version....
I've tried already few upgrades and all of them just make the Lens App stuck on the task manager with 3 processes and no UI opened. indeed if you upgrade by mistake use the former one and it works like a charm (https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.2.7-latest.20211110.1.exe)

**Comment by Nokel81** [comment]
If you run 5.3.0 lens from CMD, do you see any error logs?

**Comment by idaia** [comment]
same problem
On eventviewer:
Application Hang
Hang type: Cross-process

Nothing else

**Comment by willymwai** [comment]
+1

**Comment by usernameisnull** [comment]
5.3.2-latest.20211201.1 have the same problem

**Comment by usernameisnull** [comment]
The mouse keeps turning in circles
![image](https://user-images.githubusercontent.com/3390414/144392899-47a617c5-74f5-43ae-a91a-6f49af6e4831.png)

**Comment by alex-hempel** [comment]
I have a similar problem with all versions since 5.3.0. It often manifests when I close several terminal windows that have opened due to pod interactions. Lens goes unresponsive without recovery, and has to be killed through the task manager.

**Comment by Nokel81** [comment]
I wonder if this is the same as https://github.com/lensapp/lens/issues/4490

**Comment by Nokel81** [comment]
I was able to reproduce this on windows, but #4501 seems to fix this
