### ISSUE TITLE
CSS displayed on top of application, and display problem

### ISSUE THREAD

**Issue by pcotte** [kontena/lens#4439]
Since I upgraded Lens to version **5.3.0-latest.20211125.2** as soon as I open the app, I see some CSS displayed on top of the application. Also the overall display of the application is wrong, size of columns, drop boxes, etc.

**To Reproduce**
1. Upgrade the application to version **5.3.0-latest.20211125.2** following the automatic upgrade process
2. Open the application
3. See some CSS code displayed on top of the application and erratic display within the application

**Expected behavior**
No CSS code displayed on top of the application.  And columns and drop box to display properly in the application

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.3.0-latest.20211125.2
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Upgrade process proposed by application at startup

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    Γû¬ ≡ƒôƒ Setting Lens as protocol client for lens:// +0ms
info:    Γû¬ ≡ƒôƒ Protocol client register succeeded Γ£à +9ms
info:    Γû¬ [APP-PATHS]: initializing +1ms
```

**ScreenShots:**
![Clipboard01](https://user-images.githubusercontent.com/1153925/143613836-d0102137-0179-4639-80a4-983209f39266.jpg)

![Clipboard02](https://user-images.githubusercontent.com/1153925/143624190-49277fca-1a60-4f71-9c99-56099beb4392.jpg)

**Comment by matthewhartstonge** [comment]
For those needing to downgrade 🙃 

https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens%20Setup%205.2.7-latest.20211110.1.exe

**Comment by pcotte** [comment]
Installed version 5.3.3-latest.202111223.1 and noticed the issue is now fixed
