### ISSUE TITLE
Not able to select namespace by typing the exact name if the permissions are not granted to list all namespaces

### ISSUE THREAD

**Issue by karanintouch** [kontena/lens#4448]
**Describe the bug**
Not able to select namespace by typing the exact name if the permissions are not granted to list all namespaces

**To Reproduce**
1. Go to 'deployment section'
2. Click on 'search box'
3. Type the name of the namespace to which I have access but don't have access to list namespaces in that cluster
4. Nothing happens.

**Expected behavior**
I expect to switch to that namespace.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.3.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
> Click on 'search box'

Do you mean the namespace selector or the "Search Deployments..." input?

Have you set up accessible namespaces under cluster settings?

**Comment by karanintouch** [comment]
Thanks for the quick reply. 

I'm referring to workload->deployment tab-> Namespace: dropdown

If I got to namespace i get the warning "namespaces is forbidden: <user> cannot list resources "namespace" in API group at the cluster scope.

Hope I answered your question correctly.

Can you please share more details about what your meant by "set up accessible namespaces"? (Actually the namespaces are created by someone else and we are only given access to selective namespaces, in case this helps)

**Comment by Nokel81** [comment]
So if you do not have `list namespace` permissions then what do you see in the namespace dropdown? Did you not get a notification about adding "accessible namespaces"? 

As to that setting "accessible namespaces" it is in the cluster settings (which you can get to by right clicking the cluster icon). This setting is a way to declare what namespaces you have access to.

**Comment by karanintouch** [comment]
Thanks a lot for the response. I wasn't aware of the cluster settings available via right click. Thanks for it.
