### ISSUE TITLE
Impossible to SKIP Lens Space Login

### ISSUE THREAD

**Issue by Zifiv** [kontena/lens#4450]
**Describe the bug**
Are you serious by forcing your users to create an account on your "Lens Spaces" system?
The SKIP button at the bottom was disabled... this is frankly not good...

**To Reproduce**
1. Install (for all users) for the first time Lens to your computer

**Environment (please complete the following information):**
- Lens Version: 5.3.0-latest.20211125.2
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): x64 .exe Installer from website

**Comment by jweak** [comment]
It should never be disabled. Could you provide a screenshot?

**Comment by Zifiv** [comment]
![image](https://user-images.githubusercontent.com/833854/143861044-d29db3fc-a7df-45f3-b41c-d2ffc217692d.png)
The SKIP label isn't clickable.

**Comment by Zifiv** [comment]
By the way, I choose the "For all users" option while installing, and when I accept a new update, it re-install Lens only for me not with the "For all users" option, so I've two Lens installed.

I'll create a new issue about it I think, your update app should be care about the type of installation (and the location so) to install the new version.

**Comment by jweak** [comment]
Interesting. It is a button and it is always enabled in the code. Are you able to click other UI elements in the for example "Forgot Password?" Or "Create an account" links?

Sorry you are having this issue. This modal should be only shown once on startup and skip should never be disabled. If you are not able to skip it by clicking that you can remove this feature by workaround,

There should be `Lens/extension-store/lenscloud-lens-extension/` in %appdata% 
and there is a `startup-store.json` there. You can edit that file and make it

```
{
        "skipSignup": true
}
```

**Comment by Zifiv** [comment]
Yes I can use others links/button.

It's a bit strange, but after I resized the window, I can click on the "SKIP" label.

**Comment by jweak** [comment]
> Yes I can use others links/button.
> 
> It's a bit strange, but after I resized the window, I can click on the "SKIP" label.

Okay good to know. I'll still take a look if there are some way I can reproduce and fix this.

**Comment by Zifiv** [comment]
> Okay good to know. I'll still take a look if there are some way I can reproduce and fix this.

Ok, thanks for fast reply. Have a nice day.

**Comment by geogeim** [comment]
why was this closed? i have the same issue
also it's funny how you need to scroll to get to get to the skip button instead of making it an option like google or github login. some dark ui patterns in here...

**Comment by santoro80** [comment]
Same issue here, only difference is skip button is not visible anymore on v. 5.5.0 (Mac) and v. 5.4.6 (Mac). are we now obliged to sign in? Resize did not work, editing startup-store.json did not work.
