### ISSUE TITLE
Metrics from sidecar?

### ISSUE THREAD

**Issue by dominikjeske** [kontena/lens#4458]
I'm not sure is this possible to configure in lensapp but we have pods with monitoring sidecar that expose metrics in prometheus format. Can we use this endpoint in UI?

**Comment by Nokel81** [comment]
If the API is the same then you should be able to manually specify the connection URL under cluster settings. Does that work?

**Comment by dominikjeske** [comment]
I'm not sure I'm understand this right but cluster settings provide option to one prometheus address but I have sidecar in each pod so how can I define this in kluster settings?

**Comment by Nokel81** [comment]
Thanks for the information. I think that metrics aggregation is outside the scope of Lens. If you could provide a single endpoint that aggregates the Prometheus style API then Lens could use it.

**Comment by dominikjeske** [comment]
Thanks for info
