### ISSUE TITLE
Latest versions in snap or other repositories

### ISSUE THREAD

**Issue by Unichron** [kontena/lens#4460]
Hi!

Version 5 is not available in snap, even though it's been quite some time since it was released. What's the holdback?

Other question is if it's planned/considered to distribute the app in conventional linux repositories like apt? If not why?

**Comment by Nokel81** [comment]
Snap is currently hosted on k8slens.dev. We are not planning to release it onto snapcraft. We have not considered yet hosting a third party apt registry yet.

**Comment by devopsmash** [comment]
related https://github.com/lensapp/lens/issues/3273

**Comment by ruckc** [comment]
@Nokel81 - is there any movement on publishing the packages to yum/apt/snap repositories?  Just want to automate the upgrade process, which is currently pretty painful to do compared to everything else.
