### ISSUE TITLE
lens 5.3.2 ingress cant edit & cant open

### ISSUE THREAD

**Issue by minimaco** [kontena/lens#4482]
environment

1. lens 5.3.2
2. Windows 21h2

i cant open a ingress rule and cant edit it
pls

**Comment by mih-kopylov** [comment]
@Nokel81 could you please prioritize this?

**Comment by Nokel81** [comment]
What is your kubernetes cluster version? I tried with v1.22.1 and was able to both open and edit an ingress within lens 5.3.2. Going to try 1.14.0 now

**Comment by Nokel81** [comment]
I have reproduced this on 1.14.0, found the place where the bug occurs. PR should be up shortly.

**Comment by mih-kopylov** [comment]
I face this with Kubernetes v1.18

**Comment by Nokel81** [comment]
> I face this with Kubernetes v1.18

You will face this with any kube version that uses the older version of ingresses

**Comment by entekpartners** [comment]
How do I apply this patch as I'm having the same issue with version Lens: 5.3.2-latest.20211201.1?  Thanks

**Comment by mih-kopylov** [comment]
You probably have to wait for the next patch release

**Comment by minimaco** [comment]
> What is your kubernetes cluster version? I tried with v1.22.1 and was able to both open and edit an ingress within lens 5.3.2. Going to try 1.14.0 now

v1.18.5 pls,now this issue still exists

**Comment by Nokel81** [comment]
What version of lens are you using?
