### ISSUE TITLE
Button to upload profile picture does nothing

### ISSUE THREAD

**Issue by Iku-turso** [kontena/lens#4484]
**Describe the bug**
In profile, Button to upload profile picture does nothing.

**To Reproduce**
1. Go to 'Profile'
2. Click on button 'Upload'
3. See that nothing happens

**Expected behavior**
Select file to upload, etc.

**Environment (please complete the following information):**
- Lens Version:
- OS: OSX

**Comment by Nokel81** [comment]
Moved to spaces extension backlog

**Comment by superff** [comment]
I had the same issue

**Comment by Sn-Kinos** [comment]
@Nokel81 It was solved? I had the same issue now on GitHub account.

![image](https://user-images.githubusercontent.com/26380261/171589233-7dc16ca4-bc7d-498f-a730-e65bc9c0d831.png)

Upload button and Remove button was disabled.

**Comment by Nokel81** [comment]
That feature is currently not supported. We will look into prioritisation of this shortly.
