### ISSUE TITLE
Cannot view workload after upgrading to Lens 5.3.2-latest.20211201.1 with restricted permissions

### ISSUE THREAD

**Issue by JonathanLachapelle** [kontena/lens#4493]
**Describe the bug**
After upgrading Lens from 5.2.x the Workloads section and most of the resources in the sidebar no longer load. We had allowed permissions so that users could list namespaces specifically so that they did not have to input the list of accessible namespaces manually.

**To Reproduce**
- No full read access on the cluster
- Permissions to get/list/watch on all namespaces
- Full permissions on workloads in a specific namespace

**Expected behavior**
I am expecting to be able to see resources in namespaces that I have access to, like in previous Lens versions

**Screenshots**
Without specifying an accessible namespace in the cluster settings. Notice how almost all the resources are not loaded on the sidebar:

![image](https://user-images.githubusercontent.com/68385072/144510975-76884337-a9c0-4cb8-8dd9-506640f051f8.png)

After specifying an accessible namespace in the cluster settings (this is the behavior that we were seeing in a previous version of Lens without having to specify the namespace), all the resources to which we have access are now back as it was prior to the update :

![image](https://user-images.githubusercontent.com/68385072/144512799-950aa9b8-3022-4c6a-8bd8-ee79b1140c00.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.2-latest.20211201.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): installed from executable on Lens website, updated to latest through auto-update mechanism.

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
There are no relevant logs (no errors/warning) that show any kind of exception we would be encountering.
With developer tools, there are also no errors/warnings, everything seems fine.
```

**Kubeconfig:**
This is not Kubeconfig related as this was working prior to upgrading Lens.

**Additional context**
We had somewhat figured out the required RBAC through trial and error in previous versions as there is no clear Lens documentation on that topic. We do not want to give everyone full read access to the cluster.

**Comment by pushkinilia** [comment]
I've the same problem after update. 
![image](https://user-images.githubusercontent.com/55360465/144540613-cc840333-b0e0-455f-8d5e-a5246490c3dc.png)
![image](https://user-images.githubusercontent.com/55360465/144540807-4dea4417-726a-4802-9b77-88506ee27e56.png)

**Comment by Nokel81** [comment]
> Full permissions on workloads in a specific namespace

I believe this is an unfortunate duplicate of the main issue behind https://github.com/lensapp/lens/issues/1700

Namely we optimize for the first 10 namespaces, maybe the ordering changed?

**Comment by JonathanLachapelle** [comment]
> > Full permissions on workloads in a specific namespace
> 
> I believe this is an unfortunate duplicate of the main issue behind #1700
> 
> Namely we optimize for the first 10 namespaces, maybe the ordering changed?

When you say the ordering changed, you mean in our cluster?

If so no, and all users are affected by this, no issue in lens 5.2 or even 5.3.0 but completely broken in 5.3.2

**Comment by Nokel81** [comment]
> If so no, and all users are affected by this, no issue in lens 5.2 or even 5.3.0 but completely broken in 5.3.2

You mean, some of the users are affected? Namely the ones using 5.3.2 but not the ones using 5.2.X?

**Comment by JonathanLachapelle** [comment]
> > If so no, and all users are affected by this, no issue in lens 5.2 or even 5.3.0 but completely broken in 5.3.2
> 
> You mean, some of the users are affected? Namely the ones using 5.3.2 but not the ones using 5.2.X?

Exactly

**Comment by trungklam** [comment]
> I've the same problem after update. ![image](https://user-images.githubusercontent.com/55360465/144540613-cc840333-b0e0-455f-8d5e-a5246490c3dc.png) ![image](https://user-images.githubusercontent.com/55360465/144540807-4dea4417-726a-4802-9b77-88506ee27e56.png)

I got exactly this problem on my Mac. Have you found the solution for it ?

**Comment by trungklam** [comment]
Okay So I rolled back to 5.2.7 and works fine
![image](https://user-images.githubusercontent.com/17236895/145933023-849e8e45-5057-4efe-9b2b-f82b04b07e86.png)

@Nokel81 can you please have to acknowledge this issue ? Thanks a lot

**Comment by Nokel81** [comment]
@Happin3ss Your metrics issue is not the same as the one mentioned in the OP. Please open a new issue.

**Comment by Nokel81** [comment]
@JonathanLachapelle I cannot reproduce this unfortunately. I made myself a cluster with a user account with a role-binding with the ability to `list, get, watch` all the workloads in the `default` ns and the cluster-role-binding to `get, list, watch` namespaces.
