### ISSUE TITLE
Replace document.execCommand('copy') with Clipboard API

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#4529]
Currently, we're using `document.execCommand('copy')` command to copy text to clipboard. This is marked as `deprecated` and will be removed from the chrome soon. https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#browser_compatibility

Instead, `Clipboard API` should be used https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

Thanks @stefcameron for spotting this!

**Comment by stefcameron** [comment]
My pleasure!
