### ISSUE TITLE
Ingresses are not showing up the details page

### ISSUE THREAD

**Issue by Moskovych** [kontena/lens#4531]
**Describe the bug**
Looks like it is continues problem from #4443.
Ingresses are shown but the details page or options (three dots menu) doesn't work.
Works for K8s 1.20, but not for K8s 1.13.x.

**To Reproduce**
1. Go to `Network -> Ingresses`
2. Click on any of Ingress
3. Observe the details of Ingress (or not showing up)

**Expected behavior**
Ingress details shown as usually for other objects, no matter which version of cluster is.

**Screenshots**
Nothing to screen, as no details page.

**Environment (please complete the following information):**
- Lens Version: 5.3.2
- OS: MacOS 11.6 Big Sur
- Installation method (e.g. snap or AppImage in Linux): `brew`
- Kubernetes version: `1.13.5` / `1.13.10`

**Logs:**
Nothing in DEBUG mode.

**Kubeconfig:**
N/A

**Additional context**
N/A

**Comment by Nokel81** [comment]
Duplicate of #4482

**Comment by Moskovych** [comment]
It is sad that bug report with all the details (following the template) closing as duplicate instead of 2 lines of bug, reported previously. IMHO.

**Comment by Nokel81** [comment]
@Moskovych Did you notice that the other one is already closed because the PR that fixes it has been merge?

**Comment by Moskovych** [comment]
@Nokel81 , 5.3.3 is coming?
