### ISSUE TITLE
Not able to access any clusters in a Lens Space

### ISSUE THREAD

**Issue by nscriptdotgo** [kontena/lens#4532]
I am not able to access any cluster connect clusters that are shared to a lens space. If I open the dev console while trying to browse the catalog I see these errors.
<img width="579" alt="Screen Shot 2021-12-08 at 10 30 23 AM" src="https://user-images.githubusercontent.com/8535225/145246010-9da4dd17-932b-4123-a4ee-2bac4e506226.png">
I

**Comment by Nokel81** [comment]
What version of lens are you using?

**Comment by Nokel81** [comment]
https://twitter.com/k8slens/status/1468625914539876353
