### ISSUE TITLE
Cluster icon does not update

### ISSUE THREAD

**Issue by Nuru** [kontena/lens#4540]
**Describe the bug**
Setting a new cluster icon does not take effect until restarting the app

**To Reproduce**
1. Go to Cluster Settings -> General
2. Click on '...' and select "Upload Icon"
3. Select an icon (`.png`) and click "Open"
 

**Expected behavior**
- Selected icon should be shown in place of previous icon for the cluster
- Dropdown menu from `...` (Upload Icon, Clear) should disappear

**Actual behavior**
- Icon not changed
- Dropdown menu still present

**Environment (please complete the following information):**
- Lens Version: 5.3.2-latest.20211201.1
- OS: [e.g. OSX] macOS 10.15.7
- Installation method (e.g. snap or AppImage in Linux): DMG

**Additional context**
New icon appears after quitting and relaunching Lens

**Comment by Nokel81** [comment]
This is a regression of https://github.com/lensapp/lens/pull/3928 because of https://github.com/lensapp/lens/issues/3841
