### ISSUE TITLE
can not download the binary file at website

### ISSUE THREAD

**Issue by csimplestring** [kontena/lens#4550]
**Describe the bug**
when I go to the official website of Lens app, I can not download the binary.

**To Reproduce**
1. Go to https://k8slens.dev/
2. Click on 'Download Lens Desktop'
3. See error: "no healthy upstream"

**Expected behavior**
I should download the pre-built binary file.

**Screenshots**
<img width="407" alt="Screenshot 2021-12-10 at 10 39 06" src="https://user-images.githubusercontent.com/5042273/145552352-13239988-644b-4a5c-8542-5ef7927ea2fe.png">

**Environment (please complete the following information):**
- Lens Version: Latest
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): download from website

**Logs:**
No logs

**Kubeconfig:**

**Additional context**

**Comment by msa0311** [comment]
There was an outage to Lens backends this morning between 9-12am UTC. We apologise for the inconvenience this may have caused. Download should be available again now!
