### ISSUE TITLE
Button for image tag (version) change

### ISSUE THREAD

**Issue by librucha** [kontena/lens#4561]
**What would you like to be added**:

It would be nice to have button for change image version on deployment (sts,ds,...)

**Why is this needed**:
Our Kube users (developers) leaving Kubernetic app finds this functionality useful.
For people, which are not familiar with kuberntes manifest yaml structure is little bit painful to search image version location.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: MacOs, Windows, Linux

Best place for "image version" button:
![image](https://user-images.githubusercontent.com/1335068/145779468-8e95fbf0-3b52-4450-9283-a4bad113a934.png)

**Comment by Nokel81** [comment]
Thanks for the suggestion but we do not see this today as part of the core of OpenLens. However, this could also be a very good example of an extension for Lens. 

Some documentation for the development of extensions: https://api-docs.k8slens.dev/.

**Comment by kubav182** [comment]
This functionality is the only one I really miss in the Lens. Other tools support this without plugins.

**Comment by mmoriani** [comment]
> This functionality is the only one I really miss in the Lens. Other tools support this without plugins.

Hi, you can try this: https://github.com/ottimis/lens-version-update

**Comment by kubav182** [comment]
In new lens there are no extensions anymore.
