### ISSUE TITLE
Make Hotbar Names Visible without hovering. 

### ISSUE THREAD

**Issue by philnielsen** [kontena/lens#4572]
**What would you like to be added**:
Currently, I need to hover the hotbar page number to see the name of the hotbar i'm currently on. I would like to have the hotbar names visible without hovering. The page number tells me nothing, I propose changing showing that to showing the hotbar name (abbreviated if it doesn't fit).

**Why is this needed**:
it is slightly annoying to scroll through hotbars until you find the right one, if you have a large number of them, because you have to stop and hover over each one to find them. 

**Environment you are Lens application on:**

- Kubernetes distribution: Self-rolled K8s
- Desktop OS: Windows

Thanks for the great tool, i've been loving using it!

**Comment by Nokel81** [comment]
Duplicate of #3982

**Comment by philnielsen** [comment]
oh weird, I searched for "hotbar name" and that didn't pop up because it was already closed! thanks @Nokel81
