### ISSUE TITLE
SSH tunnel to a remote cluster

### ISSUE THREAD

**Issue by assafey** [kontena/lens#4585]
I am trying to reach my cluster through Lens with a SSH tunnel.

Commands like this will work fine from the terminal
`kubectl --context=my-context --server=https://localhost:8443 --insecure-skip-tls-verify command [flags] [options]`

But configuring a proxy for the cluster (https://localhost:8443) will return the next error:
`malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x04\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x04\x00\x00"`

Any reason why?

Lens: 5.3.3-latest.20211214.2
Kubectl version:
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}`

![image](https://user-images.githubusercontent.com/4359007/146456132-1563c217-6a18-4c03-99f0-ac5c148cc100.png)

**Comment by Nokel81** [comment]
So the way that Lens communicates with the clusters is to run `kubectl proxy` for each cluster. That preference sets the `HTTPS_PROXY` environment variable for that process. If you want more details you can run Lens from the command line with the `DEBUG_PROXY=true` env var it might give you more details.

**Comment by jim-docker** [comment]
I believe the only way to get it to work is to modify the kubeconfig to point to your local host.

**Comment by Nokel81** [comment]
@assafey Does this solve your issue?
