### ISSUE TITLE
Windows installer command line arguments

### ISSUE THREAD

**Issue by absmith82** [kontena/lens#4620]
**What would you like to be added**:
There needs to be command line installer arguments.  things like 
/quiet 
This would be used in the case that we want an install with no user interaction

/system
this would be needed if we want the application installed system wide instead of for the user only

/user
this would be needed in the case of default being system wide install but needs to be installed for the user instead

/directory
change the directory that lens is being installed

/uninstall
used to uninstall via command line

**Why is this needed**:
I have an environment we are trying to deploy laptops with Microsoft Intune.  I would like all the software that is used to be installed via Intune so that we don't have to have admin users on laptops but users can still install the applications they want to use, or so that we can run a factory reset on a laptop and depending on the user Intune will automatically install all the software needed for them.

This would be good for many other mobile device management software as well as you need to have cli arguments in order to run installers on many of these types of systems.

**Environment you are Lens application on:**

- Desktop OS: Windows, MacOS

**Comment by DmitriyNoa** [comment]
@absmith82 Can you please check if the following works for you https://docs.k8slens.dev/main/getting-started/#installing-with-cli?
