### ISSUE TITLE
Bring back selecting multiple namespaces

### ISSUE THREAD

**Issue by madianas21** [kontena/lens#4624]
**What would you like to be added**:
Please allow selecting multiple namespaces, without needing to hold `ctrl` or other buttons. 

**Why is this needed**:
I would argue that for most users, it is not an intuitive behavior of a drop down multi-select with check marks. I have not seen a multi-select dropdown where a user has to hold an extra button to select multiple items. Having to hold an extra button is cumbersome. As proof, there is even a bug issue #4047, a user thought it is a bug. I personally spent a month with new Lens 5 and only now found out the multiple-select feature.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, Linode, On-Premise]
- Desktop OS: Ubuntu

**Comment by Nokel81** [comment]
While we do not plan on reverting the change, we completely agree that the UX around multi-select could be better and will work to make it so.

We are working on making this better.

**Comment by madianas21** [comment]
Great to hear that! Thank you!
