### ISSUE TITLE
Silent auto update / update on close

### ISSUE THREAD

**Issue by ghost** [kontena/lens#4652]
The current update mechanism sucks in terms of usability.

I open Lens because I need it urgently. I get an update pop, I can choose between (now or on next start). I deny it and forget it. Story repeats.

Please implement at least one of the two:
* silent updates (a small update pending notification as you can get on Chrome would be great)
* option to execute the update after I close Lens.

Thanks

**Comment by Nokel81** [comment]
Interesting that you understood "Update, Later" as "on next start". What it actually means is "on quit". 

We will be changing the default to update on quit though, so that tidbit is mostly historical now.
