### ISSUE TITLE
Allow saving cluster name by tapping esc key while on cluster name text box

### ISSUE THREAD

**Issue by Liad-n** [kontena/lens#4669]
In the current lens app when adding a cluster and trying to change its name, you must click outside the cluster name text box in order for the change to take place.
Tapping esc goes back to the previous screen without making any changes.

Everytime I add a cluster I must click outside the text box in order to save my change which means it takes a longer time to rename it and it's not quite intuitive.

OS: Ubuntu 20.04.3

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

Thanks.

**Comment by ndrscodes** [comment]
I think this is a good idea for all input fields, not just the cluster name setting. I'm a react beginner, but i'd like to give this a try. May i?

**Comment by Nokel81** [comment]
@ndrscodes Sure go ahead

**Comment by ndrscodes** [comment]
@Nokel81 should this also work using the Enter key? As of now, pressing the Enter key while an Input is focussed will practically do the same thing, the only difference being that Escape won't unfocus the Input after it was pressed. Maybe we don't even need the Escape key, everything could be handled by pressing Enter?

**Comment by Nokel81** [comment]
Enter is a good option too. Probably better as you say.
