### ISSUE TITLE
Unable to Cluster Connect to our Team Space

### ISSUE THREAD

**Issue by wheres-baldo** [kontena/lens#4672]
## Description:
We've been unable to cluster connect our local kubernetes config to our team space. We see an `Invalid Credentials` error in the UI:
![image](https://user-images.githubusercontent.com/66707252/148965545-7a8229b4-c7af-44ed-9fa1-184fe8425ab6.png)

We see three distinct messages in the logs over and over again:
```
error: [CLUSTER]: Failed to connect to "Default": StatusCodeError: 403 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"wheres-baldo\" cannot get path \"/version\"","reason":"Forbidden","details":{},"code":403}
info: [CLUSTER]: refresh {"id":"ce964668-cdbf-4f2c-8025-66ea814e4571","name":"Default","ready":false,"online":false,"accessible":false,"disconnected":false}
error: [CLUSTER]: Failed to connect to "Default": RequestError: Error: ESOCKETTIMEDOUT
```

### Solutions we have tried:
- Remove/Re-add the cluster to our space.

## Questions?
- This cluster is on Kubernetes v1.1 - is this version compatible with cluster connect?
- Should we try the steps mentioned in Manually Install Cluster Agent under spaces settings>tokens?
- Is there anything else we can provide to help you help us troubleshoot?

**Comment by jim-docker** [comment]
What OS are you running Lens on?

**Comment by msa0311** [comment]
Are you actually running K8s Version "**1.1**" or is this a typo?

**Comment by wheres-baldo** [comment]
@jim-docker - Mac OSX Monterey 12.1 

@msa0311 - confirmed - this is a legacy cluster that is very much due to be upgraded. Guessing this is our issue. Going to close this out.

**Comment by msa0311** [comment]
We are using Kubernetes Impersonation Headers to authenticate Lens Spaces Users, it seems they were introduced somewhere around v1.4 looking at k8s release notes... but probably there are further things missing in those older versions.
