### ISSUE TITLE
Triggering a cronjob from lens does not set annotation `cronjob.kubernetes.io/instantiate manual` on the job

### ISSUE THREAD

**Issue by AndrewSav** [kontena/lens#4681]
**Describe the bug**
When you run `kubectl create job --from=cronjob/mycronjob myjob`, an annitation is set on the newly created job: `cronjob.kubernetes.io/instantiate: manual`. When you use "trigger" functionality on a CronJob from Lens, the newly created job does not have that annotation.

**To Reproduce**
1. Go to CronJobs section in Lens
2. Click on the three vertical dots and then on Trigger, 
3. Give your job a name and click Trigger.
4. Examine newly created job, observe that the annothation is absent

**Expected behavior**
`cronjob.kubernetes.io/instantiate: manual` annotation is present on the new job.

**Environment (please complete the following information):**
- Lens Version: 5.3.3
- OS: Windows 10

**Comment by krlosmederos** [comment]
Hi @Nokel81, I would like to work on this issue.

**Comment by Nokel81** [comment]
@krlosmederos go for it!
