### ISSUE TITLE
Replace deprecated String.substr() usage

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#4683]
`String.substr()` method is deprecated for now and should be replaced .

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

`String.prototype.slice()` can be an alternative.

**Comment by gauravagrwal** [comment]
Hi @aleksfront, I like to work on this.

**Comment by aleksfront** [comment]
@gauravagrwal Feel free to take this one.

**Comment by sanba-anass** [comment]
substr actually can be useful in some situations

**Comment by Nokel81** [comment]
Yes but it is deprecated and can be removed in future updates. All the functionality of `substr` can be replicated using `slice` and `substring`

**Comment by VFDouglas** [comment]
An easy replacement for `substr` is to replace the second condition of `subtr` with the sum of the first condition with the second. Example:

```
const str = 'abcdefghijklmnopqrstuvwxyz';

console.log(str.substr(0, 5));
console.log(str.slice(0, 5));

console.log(str.substr(3, 5));
console.log(str.slice(3, 3 + 5));

console.log(str.substr(str.length - 4, 4));
console.log(str.slice(str.length - 4, (str.length - 4) + 4));
```
