### ISSUE TITLE
Unable to connect to cluster

### ISSUE THREAD

**Issue by guy-frontegg** [kontena/lens#4701]
**Describe the bug**
In the new version, when trying to connect to any cluster the following message appear 

> E0117 10:23:14.389788 15885 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

While both kubectl and aws cli are installed

**To Reproduce**
1. Go to any cluster
2. Click on connect
3. See error

**Expected behavior**
Connect to the cluster

**Screenshots**
![image](https://user-images.githubusercontent.com/61701142/149734453-85699092-ac07-4fcf-80be-dbf0f596f13f.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.3
- OS: MacOS 12.1

**Comment by guy-frontegg** [comment]
For some reason after restarting my computer it worked

**Comment by unioncube** [comment]
same issue, restart not help me back to normal

**Comment by stakach** [comment]
I fixed the issue by going to the folder specified: `C:\Program Files\Lens\resources\extensions\lenscloud-lens-extension\dist` (might be in your home folder, see the error message)

There were two files in there:
* `lens-spaces-authenticator-arm64.exe`
* `lens-spaces-authenticator-x64.exe`

For me I renamed `lens-spaces-authenticator-x64.exe` to `lens-spaces-authenticator.exe` and this fixed everything.

So it looks like the installation needs to detect the architecture windows is being installed on and renaming the appropriate exe or creating a hard symlink etc

**Comment by galtonova** [comment]
I followed @stakach 's method and it worked. But this needs to be fixed though.

**Comment by w4-jake** [comment]
Chiming in in 2023. A restart worked on my Mac for this issue.
Thanks

**Comment by sophos-rickc** [comment]
Chiming in. Multiple restarts have not fixed this issue for me on MacBook Pro M1 Max running macOS 14.2.1. Off to try @stakach's workaround...
