### ISSUE TITLE
gcloud is executed without any PATH information

### ISSUE THREAD

**Issue by djvs** [kontena/lens#4726]
**Describe the bug**
See title

**To Reproduce**
Open Lens, connect to cluster (?)

**Expected behavior**
Connection should succeed

**Screenshots**
![2022-01-20T12:09:22,115956559-05:00](https://user-images.githubusercontent.com/2954343/150387642-195a9f3f-14a7-4a47-ba8c-1ca5f50f41ea.png)

**Environment (please complete the following information):**
- Lens Version: 5.3.4
- OS: [e.g. OSX] Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
See screenshot

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
n/a
```

**Additional context**
I dumped PATH in /opt/google-cloud-sdk/bin/gcloud to a log file and indeed it was empty.  It certainly is not empty in my environment.  Hack fix was to quickly define 

```PATH=$PATH:/usr/bin:/opt/google-cloud-sdk/bin/```

inside the gcloud script.

**Comment by djvs** [comment]
P.S. normal gcloud execution works

**Comment by Emyrk** [comment]
You need to update your `~/.kube/config` to use the new path of your `gcloud`. Each cluster has a `cmd-path` field which has the old binary location.

**Comment by Nokel81** [comment]
We recently made some fixes to our shell syncing code, does upgrading to the latest version fix this for you?
