### ISSUE TITLE
High CPU usage after Lens starts, and is idle

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4732]
**Describe the bug**
It was noted that after Lens had started and was left idling, within ~10s CPU usage hit 97%.
JS usage was minimal, so Electron may be implicated.
This occurred during the time when a new release was being built but failed for macos.
It has not been observed since the macos release was successfully built.

The suspicion is that electron-updater is not behaving well when the update file does not exist.

- Lens Version: 5.3.3
- OS: OSX

**Comment by Nokel81** [comment]
Closing as old
