### ISSUE TITLE
Custom Category Views CSS 

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#4735]
**Describe the bug**
When a custom category view is registered for a specific category and it is only a small height. The default list view should shrink to make it so that the views are scrollable always.

However, if enough views are added then the whole page should be scrollable.

Follow up to #4733

**Comment by jim-docker** [comment]
Do you mean to say the default list view should shrink so that the views are always visible? (If I add a small custom view below the list I'd want to see that whole view without having to scroll (list would shrink accordingly)

**Comment by Nokel81** [comment]
@jim-docker Yes, but only to a point. If several small views or one medium/large view are/is added then scrolling should still be done.
