### ISSUE TITLE
devCluster stuck in terminating state

### ISSUE THREAD

**Issue by dirien** [kontena/lens#4743]
**Describe the bug**
DevCluster stuck in terminating state for ages

![image](https://user-images.githubusercontent.com/38325136/150879530-0c8488c1-4bcf-49ed-b532-21fa9ed6dc7a.png)

**Expected behavior**
Create a new DevCluster

**Environment (please complete the following information):**
- Lens Version: Lens: 5.3.4-latest.20220120.1
- OS: macos 10.15.7 
- Installation method (e.g. snap or AppImage in Linux): DMG

**Comment by panuhorsmalahti** [comment]
Can you try to "Reset" it again?

**Comment by dirien** [comment]
Unfortunatly, it did not help! :(

**Comment by dirien** [comment]
ok, guess DevCluser cost money now. Maybe thats the reason the devCluster is not comming back! :(
