### ISSUE TITLE
Selected items are cleared when filtering KubeObjectItemList

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4744]
https://user-images.githubusercontent.com/40840436/150874879-7d8e7fb1-e7b6-446a-989b-7a022edc8f4b.mov

This is a regression and may be related to https://github.com/lensapp/lens/pull/4653#issuecomment-1012457220

Happens on master

**Comment by Nokel81** [comment]
This has been fixed on master, noticed while working on #4798
