### ISSUE TITLE
ctrl + v or right mouse click no paste function under bshell 

### ISSUE THREAD

**Issue by deeplon** [kontena/lens#4747]
**What would you like to be added**:
ctrl + v or right mouse click no paste function under bshell 

**Why is this needed**:
Long commands or complex password input cannot be pasted, which is very inconvenient 

**Environment you are Lens application on:**
windows 10
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by jim-docker** [comment]
Did you try with "terminal copy and paste" enabled? (Preferences -> Application)
