### ISSUE TITLE
bored-agent should have system cluster critical priorityclass

### ISSUE THREAD

**Issue by matti** [kontena/lens#4751]
I just scaled a lot of pods --> bored-agent got kicked out. lost access to the cluster.

**Comment by kc-dot-io** [comment]
@matti - question about this. I have one cluster where this is working, another where I'm getting...

`Error creating: pods "bored-agent-cc7bc8f67-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in lens-platform namespace`

When I edit the deployment from the one that show this error and reomve the system cluster critical priority class, the deployment is able to complete. If I added it back, I get a `ReplicatsetFailure` - Any thoughts on why I'd see different behaviors? Both are EKS clusters. The one that is failing is quite old (1.16). The one that is working is 1.21.

**Comment by matti** [comment]
sorry I'm not from the lens team ping @jakolehm

**Comment by jakolehm** [comment]
@kc-dot-io it seems that `system-cluster-critical` pods can be scheduled only to `kube-system` namespace on older (< 1.17) versions, see: https://github.com/kubernetes/kubernetes/issues/60596 for details.

**Comment by kc-dot-io** [comment]
Thanks @jakolehm - any suggestions for a work around until we can get this cluster upgraded? This seems like a hard blocker for older clusters.

**Comment by matti** [comment]
imo not creating own priorityclass which would be < system-cluster-critical is wrong as bored is not cluster critical

**Comment by matti** [comment]
(changed my opinion re: #4765 )

**Comment by jakolehm** [comment]
> imo not creating own priorityclass which would be < system-cluster-critical is wrong as bored is not cluster critical

Maybe we need to create custom priorityclass but the only reason for that are those old k8s versions. Otherwise cluster-critical should be fine here.

**Comment by jakolehm** [comment]
@kc-dot-io you could just remove (or change) priorityclass from the bored-agent deployment. You probably also should pause bored-agent-updater CronJob because otherwise auto-update will change it back (until we have fixed this issue).
