### ISSUE TITLE
Extension Installation Issue 

### ISSUE THREAD

**Issue by ifqamar** [kontena/lens#4766]
Lens gets stuck on the extension installation 
While trying to install the extension installation lens stucks after pasting the .tgz file or @mirantis/lens-extension-cc 

I had to go to Lens status bar icon and quit app and then restart the app and the extension was there. This is missing from the installation guide.

Environment
- Lens Version: 5.3.4
- OS: Windows 64 
- Installation method (e.g. snap or AppImage in Linux):  npm pack @mirantis/lens-extension-cc

**Comment by Nokel81** [comment]
This seems to be the case when that extension was previously installed into the `~/.k8slens/extensions` folder.

**Comment by Nokel81** [comment]
The bug that I can reproduce is that an extension fails to install if only the folder is left behind.
