### ISSUE TITLE
Better way to display NodeGroup/Role info in UI

### ISSUE THREAD

**Issue by mlasevich** [kontena/lens#4767]
Ability to see roles set via `node.kubernetes.io/role` label instead of only `kubernetes.io/role`

The code currently only supports `kubernetes.io/role` or `node-roles.kubernetes.io/<value>`

https://github.com/lensapp/lens/blob/589472c2b53a0e65e452d36078a71ce4f642d1b7/src/common/k8s-api/endpoints/nodes.api.ts#L168-L182

Since 1.16 neither of these can be set on join, so any auto-scaled nodes show up as blank until manually updated. `node.kubernetes.io/role`  is set, but is ignored. When working with multiple nodegroups, it is very useful to be able to
which nodegroup is which, and it is obvious based on `role`

If there is a solid reason for not allowing that, perhaps an alternative feature may be of more value - allow adding arbitrary columns from the Node's labels

**Environment you are Lens application on:**

- Kubernetes distribution: EKS 1.19
- Desktop OS: MacOS

**Comment by Nokel81** [comment]
I am marking this a bug, since the label seems to have been changed and we can just add it to the list of role labels.
