### ISSUE TITLE
license file formatting is off (Windows)

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4782]
![Screen Shot 2022-01-31 at 8 01 32 PM](https://user-images.githubusercontent.com/40840436/151899703-ed192425-c944-45a9-a44a-214b34a41e4b.png)

5.4.0-alpha.0

**Comment by jim-docker** [comment]
5.4.0-beta.0, on windows still has a problem:

![Screen Shot 2022-02-03 at 5 11 43 PM](https://user-images.githubusercontent.com/40840436/152438425-683ee477-d2bb-4764-b92e-4322a6faa268.png)

**Comment by Nokel81** [comment]
That is because the sync cron job has not run again. If will run in the morning.

**Comment by jim-docker** [comment]
> That is because the sync cron job has not run again. If will run in the morning.

ah, ok, I'll confirm then reclose this

**Comment by jim-docker** [comment]
Still seeing the same problem when running `Lens+Setup+5.4.0-beta.0.20220203.1.exe`

**Comment by Nokel81** [comment]
The license file is embedded within the executable, so this cannot be verified until we make a new release.

**Comment by jim-docker** [comment]
all good in 5.4.0-beta.1
