### ISSUE TITLE
Cannot find "Download All Logs" button for pod logs

### ISSUE THREAD

**Issue by jinnypark9393** [kontena/lens#4803]
I'm using Lens v.5.3.4. I would like to download(or search) entire pod log but Lens can only download logs that is retrieved on the screen. So I have not choice but to scroll up to top of the logs manually.

On #1722, it says Lens has "Download All Logs" button for pod logs but I couldn't find it.

Could you help me navigate to "Download All Logs" or retrieve all available logs at once?

**Comment by jaakkoraut** [comment]
I have the exact same issue. Have never found that mysterious button and seriously doubting it exists. I'm using newest Lens for Intel Mac 5.4.5-latest.20220405.1

**Comment by AykutCevik** [comment]
With latest version of `Lens: 5.4.6-latest.20220428.1` on MacOS Monterey still an issue, can't find the button to download the full log of a pod.
