### ISSUE TITLE
Sleep deprivation

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4823]
I am seeing some very strange behaviour when returning to Lens after the computer wakes from sleep:

![Screen Shot 2022-02-04 at 11 11 38 AM](https://user-images.githubusercontent.com/40840436/152563936-332e2352-34a1-4be4-86dc-a6809b778f95.png)

Should look like this:

![Screen Shot 2022-02-04 at 11 13 55 AM](https://user-images.githubusercontent.com/40840436/152564168-f16e6ffb-f6f4-4893-b7b0-1e9f0a38a0cf.png)

Observed on 5.4.0-beta.0, macos

I will try to narrow down the issue

**Comment by jim-docker** [comment]
Also see this, not after sleep (though screen saver probably kicks in), but after leaving Lens open for a while, connected to a cluster:

![Screen Shot 2022-02-04 at 4 46 15 PM](https://user-images.githubusercontent.com/40840436/152608917-8618886d-8334-4adf-9c39-711e966e8de4.png)

on Windows, beta.0

**Comment by Nokel81** [comment]
Not again :(

**Comment by jim-docker** [comment]
After resuming from sleep (overnight, so may involve some long timeouts):
- all spaces clusters (whether connected or not just before sleep) error out with ESOCKETTIMEDOUT
- local clusters that were connected just before sleep seem to be connected but the dashboard content is incomplete (see below). Looks like watches are failing ("network timed out at: ...")
- local clusters that were not connected before sleep appear to connect fine after resuming.

macos:
![Screen Shot 2022-02-11 at 9 12 46 AM](https://user-images.githubusercontent.com/40840436/153608391-7add9b6e-5c42-4ef2-96a5-f651a78671e7.png)
![Screen Shot 2022-02-11 at 9 17 02 AM](https://user-images.githubusercontent.com/40840436/153608397-f4aeba9f-ef7f-4fdf-9bf9-982e1fcb70f2.png)

Windows:
![Screen Shot 2022-02-11 at 9 37 52 AM](https://user-images.githubusercontent.com/40840436/153611482-d1e5fb1e-dde8-4633-8c9e-5c837b81605e.png)
