### ISSUE TITLE
Can't open CRD list

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/lens#4829]
**Describe the bug**
If a CRD definition is opened, the list of CRD objects is not displayed. Instead, the search input is focued.

**To Reproduce**
1. Connect to a cluster
2. Click on 'Custom Resources', and click on any CRD

**Expected behavior**
List of those CRs should be displayed.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: v5.4.0-beta.1 (in master)

**Comment by Nokel81** [comment]
Fixed by #4831
