### ISSUE TITLE
Can't open extension clusterPage

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4833]
It appears that a single item drawer that is a clusterPage is rendered as a drawer heading. Clicking on it opens/closes the (empty) drawer:

https://user-images.githubusercontent.com/40840436/152910071-5206a26f-ba30-456d-8c99-2a196e4f2f99.mov

Resource Map used to show the cluster wide map but now it just opens/closes the drawer.

happens on master

**Comment by Nokel81** [comment]
Fixed by #4835
