### ISSUE TITLE
In namespace search single selected namespace with unique name selects ALL the namespaces

### ISSUE THREAD

**Issue by DarkoZivic** [kontena/lens#4860]
**Describe the bug**
In namespace search namespace with a unique name on a cluster, when clicked in results, selects ALL the namespaces in the cluster. The problem with this is when you click the "-" (the remove) option - it will try to delete ALL the namespaces!

**To Reproduce**
1. Go to 'Namespaces'
2. Click on 'Search Namespaces'
3. Search a namespace with a unique name on the cluster (returned results have to be only 1)
4. Click the square box next to the name of the found namespace (has to be just 1 returned result available to select)
5. Observe that this will indeed select a checkbox above the results list, meaning everything  (should mean everything selected from search, instead ALL the namespaces on the cluster will be selected, as evident below)
5. Click the "-" round option in the lower right corner
6. Bam!  Deletion of all the namespaces on the cluster is performed

**Expected behavior**
Lens should only attempt to delete the 1 selected namespace from the search, and not extend the selection to all the namespaces.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: Lens: 5.3.4-latest.20220120.1
Electron: 13.6.1
Chrome: 91.0.4472.164
Node: 14.16.0
- OS: OSX = Ma OS Monterey
- Installation method (e.g. snap or AppImage in Linux): Mac OS Apple Silicon .dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```

```

**Additional context**

**Comment by Nokel81** [comment]
Fixed by #4798 and will be 5.4.
