### ISSUE TITLE
Resource removal not always detected

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#4897]
Resource deletion outside of Lens not always observed by Lens

1. Open Create resource
2. pick Deployment from templates
3. Create
4. go to Deployments tab, observe nginx-deployment was created
5. go to another tab (like Namespaces)
6. In the terminal run `kubectl delete deployment/nginx-deployment`
7. go to Deployments tab, observe nginx-deployment is still there

https://user-images.githubusercontent.com/40840436/154582906-6b96dd92-bad5-4f01-9d8f-2ea7f9d7593e.mov

The deleted deployed pods also remain in the pods list in some situations

happens on 5.4.0-beta.2 and 5.3.4

reload or disconnect/reconnect fixes the issue. Also if the resource watch detects another change (i.e. create another deployment) the deleted resource disappears from the list.

**Comment by Nokel81** [comment]
Related issues:

- https://github.com/lensapp/lens/issues/2460

**Comment by jim-docker** [comment]
@Nokel81 thanks, didn't see this one. In fact I discovered this issue while removing a helm release, but found here that it is not specific to helm releases. Likely this is a duplicate issue.

**Comment by Nokel81** [comment]
Does it get removed if you stay on the deployments screen?

**Comment by fungiboletus** [comment]
I also see this behaviour, not only with helm and not only with deployments and pods but also custom resources.

**Comment by msa0311** [comment]
Just observed that it seems that this only happens if it is the last existing deployment on the list. If there are other deployments existing everything updates properly!

https://user-images.githubusercontent.com/26629812/162891392-ef11a9ca-3c1e-42af-a040-dff64a382ff0.mov

**Comment by aleksfront** [comment]
Small note in addition to previous comment. It happens only with last deployments on list within the namespace.

**Comment by vj6** [comment]
observing in `5.4.6-latest.20220428.1` too
