### ISSUE TITLE
Error in extension onActivate stops app from booting properly

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#4907]
**Describe the bug**
An exception within extension `onActivate` can cause app to not load properly. User will see just splash screen forever.

**Comment by Nokel81** [comment]
@jakolehm Any extension or a bundled extension?

**Comment by jakolehm** [comment]
@Nokel81 it happened with a non-bundled extension so I would assume any extension.

**Comment by Nokel81** [comment]
Okay thanks, will investigate

**Comment by Nokel81** [comment]
@jakolehm I cannot reproduce this on master.

My extension code is:

`renderer.ts`:
```
import { Renderer } from "@k8slens/extensions";

export default class RendererExtension extends Renderer.LensExtension {
  protected onActivate(): void {
    throw new Error("this is an error");
  }
}
```

`main.ts`:
```
import { Main } from "@k8slens/extensions";

export default class MainExtension extends Main.LensExtension {
  onActivate(): void {
    throw new Error("an error");
  }
}
```

And if it the extension is enabled then I do eventually see the main window.

**Comment by jakolehm** [comment]
@Nokel81 ok, I'll verify this again with latest master.

**Comment by jakolehm** [comment]
Cannot reproduce this with current master.
