### ISSUE TITLE
Enable left-click in the terminal

### ISSUE THREAD

**Issue by 64J0** [kontena/lens#4916]
**What would you like to be added**:

I would like to left-click selected code and appear the options to copy the piece of information. Currently, I could just copy using C-c.

**Why is this needed**:

For safer usage, C-c is also used to stop programs from executing.

**Environment you are Lens application on:**

- Kubernetes distribution: AKS
- Desktop OS: Ubuntu 20.04

**Comment by Nokel81** [comment]
Have you tried turning on the option in user settings?

**Comment by 64J0** [comment]
Did not see it, thanks for the suggestion @Nokel81, I'll try to find it there

**Comment by 64J0** [comment]
Well, don't know where this option is, on my editor configuration I only have those options:

![image](https://user-images.githubusercontent.com/50725287/155230155-6142d9eb-208a-4a61-a077-cd93dd4158ab.png)

**Comment by 64J0** [comment]
Ok, now I found the option you mentioned, it is not what I want initially but this is pretty cool, thanks for the help @Nokel81. I'll close this issue now.

For other people that are interested in this feature, just click on File (top left menu) -> Preferences -> Application ->
![image](https://user-images.githubusercontent.com/50725287/155230472-81711c55-8da1-4571-99a9-23a40bbce263.png)
