### ISSUE TITLE
Are there any plans to support Chinese?

### ISSUE THREAD

**Issue by joesdu** [kontena/lens#4917]
**What would you like to be added**:

**Why is this needed**:

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/3151, please upvote the other ticket.
