### ISSUE TITLE
Cluster menu error: TypeError: instance of IpcRenderer is not created

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#4934]
When clicked cluster sidebar menu, the error appeared in console:

```
Uncaught (in promise) TypeError: instance of IpcRenderer is not created
```

https://user-images.githubusercontent.com/9607060/155716926-64e21ff3-b265-43a3-8ff1-672b3954a007.mov

However, all menu items work okay - `Remove from hotbar`, `Delete`, `Disconnect` etc.

**Comment by Nokel81** [comment]
This is an extension issue, closing to move.
