### ISSUE TITLE
helm binary download

### ISSUE THREAD

**Issue by Hcreak** [kontena/lens#4953]
**What would you like to be added**:

Similar to `KUBECTL BINARY DOWNLOAD` option. can add helm binary to download automatically.

**Why is this needed**:

In many cases I need to use the helm CLI in the terminal.

**Environment you are Lens application on:**

- Kubernetes distribution: TKE, kubeadm build
- Desktop OS:  Windows & MacOS

**Comment by Nokel81** [comment]
Helm is currently bundled with Lens and is provided to the environment PATH within the shell tabs.

**Comment by Hcreak** [comment]
> Helm is currently bundled with Lens and is provided to the environment PATH within the shell tabs.

Thanks!
