### ISSUE TITLE
5.4.0-latest.20220301.1 There is a long delay in getting pod logs

### ISSUE THREAD

**Issue by usernameisnull** [kontena/lens#4958]
**Describe the bug**
There is a long delay in getting pod logs，sometimes very long
**To Reproduce**
1. Go to 'workload->pods'
2. Click on 'logs'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3390414/156480715-3783ecb8-8270-4fb0-aee8-fc2e1b9d42de.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.0-latest.20220301.1
- OS: Win10
- Installation method (e.g. snap or AppImage in Linux): download exe then install

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by jinnypark9393** [comment]
Same happens to me as well.

It takes to long to get pod logs and it appears only when I manually select Pod name from the dropdown list. For example here:
![image](https://user-images.githubusercontent.com/54494811/156503713-c399ef37-b62a-4a30-a45e-1f8d211c388a.png)

**Comment by austin1howard** [comment]
Also seeing this, for the first time on 5.4.0. For me at least, it happens consistently when opening the logs of a second pod. First time I open logs, all is good, second time I have to do @jinnypark9393's trick to make them load, then they pop up instantly.

I'm on MacOS, installed through homebrew cask.

**Comment by usernameisnull** [comment]
I have a suggestion, can you put the links of the old version of the installation package on your official website, when there is a problem with the new version, users can use the old version。

This is the second time I have encountered a problem with the new version and there is no way to go back to the old version. I can't find a place to download the old version installation package on your official website.

**Comment by paul-bell** [comment]
Yup; same here; not cool.

I second @usernameisnull's experience ("second time...") and recommendation (make links to previous versions readily available).

thank you.

**Comment by MartyB-007** [comment]
Just chiming in to say I am also experiencing the same issue. On a Mac with the intel chip.

**Comment by nevidimov** [comment]
Confirm this bug in a Mac with M1 chip, Lens version 5.4.0. Only the first pod logs are loading, second and other pod logs are not loading at all. Previous release worked fine.

**Comment by alexmg** [comment]
I have noticed that if you check and then uncheck the `Show previous terminated container` checkbox in the tabs that fail to load the logs are displayed. It at least allows for multiple tabs to be kept open at the same time.

![image](https://user-images.githubusercontent.com/131293/156704237-fa3c67c1-e727-4513-ab51-4112bd3273b4.png)
