### ISSUE TITLE
Allow extensions to toggle the entity details panel

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#4963]
**What would you like to be added**:
A way for an extension to toggle or view the entity details panel.

**Why is this needed**:
Some extensions would like that to be able to do so.

**Comment by Nokel81** [comment]
cc @stefcameron

**Comment by stefcameron** [comment]
Thank you! Some of the custom items we're adding in https://github.com/Mirantis/lens-extension-cc don't have a logical "open" action. They are meant to be viewed only. So it actually makes more sense to view details on click (i.e. the old Lens behavior) than it does to invent something to "open" on click, or to do nothing (and doing nothing will likely make our users think something's broken).

**Comment by Nokel81** [comment]
One question that should be answered is what should happen if a user pins said item to a hotbar, would you expect clicking on them to just open the details panel or also navigate to the catalog view?

**Comment by stefcameron** [comment]
Good question. I think it could be really useful if the Details Panel would appear on top of whatever I'm currently looking at in Lens. For example, if I'm looking at a cluster, and I've pinned a custom Credential item to the Hotbar, maybe I need to refer to that Credential _while I'm looking at the cluster_. So I can click that pinned item, and the Details panel swipes-in and partially covers the cluster. I can refer to its details, and then somehow close the Details panel, and get right back to my cluster -- without switching context.

And then if the Catalog itself happens to be active when you click on that credential item (whether pinned or in the Catalog list), the Catalog is the thing that the Details panel gets displayed over.

Seems consistent, and also very handy.

**Comment by Nokel81** [comment]
Cool thanks for the feedback

**Comment by aleksfront** [comment]
So item details for some non-standart entities needs to be opened? I've just noticed that `kube-resource-map` extension successfully opens any workload details:

https://user-images.githubusercontent.com/9607060/180999821-e3d4804d-771c-4b3a-ae19-d5a61dc21664.mov

https://www.npmjs.com/package/@nevalla/kube-resource-map

**Comment by Nokel81** [comment]
@aleksfront This isn't a request to open details for kube objects to to open the CatalogEntityDetails panel

**Comment by stefcameron** [comment]
Disappointing that this keeps getting bumped...

**Comment by Nokel81** [comment]
@stefcameron You can try your hand at implementing it yourself if you have the time

**Comment by stefcameron** [comment]
> @stefcameron You can try your hand at implementing it yourself if you have the time

I think this is a case of what would take me days would likely take one of you hours or minutes. If it's so complex it would take one of you days or weeks, then I'm looking at weeks or months, and perhaps that should be stated here to show the complexity of adding what seems like a trivial feature from the outside looking in.

I also see this as an easy issue on the Lens side to provide support to one of Mirantis' own extensions. Why would Lens not put some priority on that? Why would Lens not want one of its very own extensions to be the best that it can be and to show the community that it's willing to support its extension authors who bring additional value to Lens (at no cost to Lens, I might add)? I'm sure other extensions would benefit from this too, not just ours.
