### ISSUE TITLE
Crash app on macOS

### ISSUE THREAD

**Issue by anagornyy** [kontena/lens#4967]
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/80522969/156757642-a60d7b5e-a79f-43b4-98b8-8c71f035c46e.png">

**Comment by anagornyy** [comment]
Monterey 12.2.1

**Comment by anagornyy** [comment]
Latest Version: v5.4.0-latest.20220301.1 (01.03.2022)

**Comment by jim-docker** [comment]
Do you see this on startup? Or when you try to connect to a cluster?

**Comment by anagornyy** [comment]
When I try to connect to a cluster

**Comment by anagornyy** [comment]
Work
