### ISSUE TITLE
lens on startup _always_ asks for login 

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#4968]
**Describe the bug**
whenever lens is started up there is an annoying window that first pops up asking the user to log in
even for those users who do not have accounts.

even after dismissing the window i see the ads. this is somewhat better as i can select my desired clusters (as opposed to the log in screen) 

however, this does not take us to the "home" screen. there is an icon which looks like a house and it is the home screen which is actually the catalog. this too is much better than the unneeded log in screen on startup

**Comment by Nokel81** [comment]
There is a toggle preference (in Lens 5.4) for showing that login popup on startup.

**Comment by marafa-sugarcrm** [comment]
thank you!
