### ISSUE TITLE
The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#4972]
A lot of electron warnings pop up after app compilation.
![nativeWindowOpen](https://user-images.githubusercontent.com/9607060/156873096-ec2ca39a-f8d0-4771-b235-4d92c46be989.png)

```
[0] (node:22721) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
```

**Comment by aleksfront** [comment]
Seems that completely remove this warning impossible until this is open https://github.com/electron/electron/issues/31784

We're using `<webview/>` tag which causes warning to appear no matter what `nativeWindowOpen` setting we have.

**Comment by Nokel81** [comment]
Closing in favour of https://github.com/lensapp/lenscloud-lens-extension/issues/1660, which is a blocker for #5369
