### ISSUE TITLE
Custom Resource age sort not working

### ISSUE THREAD

**Issue by OneCricketeer** [kontena/lens#4989]
**Describe the bug**

**To Reproduce**
1. Go to 'Custom Resources > Definitions'
2. Click on 'Age' column

**Expected behavior**
Expecting a sort

**Screenshots**
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/1930631/157698587-5a1e123b-6eb7-466b-9bd3-cbbebc344c43.png">
**Environment (please complete the following information):**
- Lens Version:  5.4.1
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): brew

**Comment by OneCricketeer** [comment]
Seems to be here 
https://github.com/lensapp/lens/blob/v5.4.1/src/renderer/components/+custom-resources/crd-list.tsx#L66-L71

**Comment by Nokel81** [comment]
This will be fixed by https://github.com/lensapp/lens/pull/4990
