### ISSUE TITLE
Events are not showing in Worloads Overview

### ISSUE THREAD

**Issue by kesavkolla** [kontena/lens#4996]
The Workloads Overview bottom screen is Events which is showing blank

**To Reproduce**
1. Click on Workloads-
2. Click on Overview

**Expected behavior**
The events should show in the bottom pane

**Screenshots**
![image](https://user-images.githubusercontent.com/274645/157817721-cdce10ba-c895-47a9-b896-cccfaca3399b.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.1-latest.20220304.1
- OS: Linux]
- Installation method (AppImage in Linux):

**Comment by aleksfront** [comment]
Fixed in https://github.com/lensapp/lens/pull/4983
