### ISSUE TITLE
UI inconsistent with actual cluster state

### ISSUE THREAD

**Issue by ghost** [kontena/lens#5018]
**Describe the bug**
UI shows an inconsistent view of cluster object state.
In this particular case, it is a Pod, though I've also seen this inconsistency with ConfigMaps and Secrets.

**To Reproduce**
It's inconsistent and intermittent.

In this particular case it was as simple as:
1. start jupyter notebook
2. see notebook start with `kubectl get pods --watch`
3. log in to jupyter notebook
4. notice that Lens has an incorrect view of the Pod status, with the only solution being to disconnect/reconnect from the cluster

**Expected behavior**
Consistent state, possibly with some small amount of lag in a high update environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/80796566/158517517-b8453b2f-5d91-4cab-af45-2608e24ed813.png)

Combined screenshot showing output of `kubectl get pods --watch` and the transition of the notebook Pod into full `Running` state, alongside Lens UI showing Pod in `Pending` state

**Environment (please complete the following information):**
- Lens Version: occurring for at least the past 18 months, currently Lens: 5.4.2-latest.20220314.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): at this point, self update mechanism

**Logs:**
N/A

**Kubeconfig:**
N/A
Has been experienced across EKS, AKS, k3s and minikube.
The screenshot above is an EKS 1.21 cluster using standard IAM access

**Comment by ghost** [comment]
Half an hour later, no change .. I either have to disconnect/reconnect to the cluster, or quit/restart Lens completely:
![image](https://user-images.githubusercontent.com/80796566/158518166-169cb9fd-8896-4b0c-873a-f39a58525209.png)

**Comment by Nokel81** [comment]
Marking as duplicate of https://github.com/lensapp/lens/issues/4897, please subscribe to that issue.
