### ISSUE TITLE
RobotoMono font not loaded when terminal opened first time

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5019]
To reproduce:
1. If located in cluster view, choose "Cluster" -> "Disconnect" from the sidebar menu
2. Open cluster again.
3. Open terminal tab.

![fonts not loaded](https://user-images.githubusercontent.com/9607060/158570895-7dbc2e5b-e8dd-40f5-be4a-d0b13c9f1bb0.png)

Firstly, this issue occurred within webpack 5 update: 
* https://github.com/lensapp/lens/pull/4867
* https://github.com/lensapp/lens/pull/4725#issuecomment-1040158630

**Comment by aleksfront** [comment]
Still happened sometimes on windows.

**Comment by Nokel81** [comment]
Probably as some form of race condition

**Comment by ixrock** [comment]
Confirming, sometimes still happens on Mac too, first time opening cluster with previously opened terminal tab:

<img width="1749" alt="Screenshot 2022-12-19 at 15 29 45" src="https://user-images.githubusercontent.com/6377066/208437398-850056d0-4c79-4739-a6cc-56dcf639b7d6.png">
