### ISSUE TITLE
Frozen spinner in pod logs

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5020]
It is reported that sometimes spinner stays forever without loading pod logs content:

> I did notice some times when clicking on a pod's logs that the "spinner" would just spin forever. Reselecting container using the new "Pod" menu seemed to solve the problem.

from https://github.com/lensapp/lens/issues/4855#issuecomment-1039597847

**Comment by aleksfront** [comment]
@[danielbprice](https://github.com/danielbprice) Can you please post video here?

**Comment by Nokel81** [comment]
Was this not fixed by #4964 ?

**Comment by danielbprice** [comment]
I have been running the beta release, and I have not seen this problem recur for a while.  I just tried a dozen or so container logs and did not see this recur.  Overall the situation seems to be much better.  Thanks for your responsiveness, I know it's not easy.

**Comment by Nokel81** [comment]
I think that we can close this then. For the time being.
