### ISSUE TITLE
catalog link to slack workspace is "no longer active"

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5025]
**Describe the bug**

go to the catalog. click on the link called "lens community slack" . be greeted with "this link is no longer active"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
What version are you on? Please fill out the whole template next time.

**Comment by marafa-sugarcrm** [comment]
the latest version on mac 5. 4. 2

**Comment by aleksfront** [comment]
I can't reproduce it on latest `master`. Link seems to be working and it was changed last time 8 months ago.

@marafa-sugarcrm Can you provide a screenshot or a video showing the bug?

**Comment by marafa-sugarcrm** [comment]
![Screen Shot 2022-03-22 at 8 38 39 AM](https://user-images.githubusercontent.com/69474017/159483792-5a192163-7771-4c27-aa86-218c62da4c15.png)
