### ISSUE TITLE
Check for updates cached 

### ISSUE THREAD

**Issue by dominch** [kontena/lens#5039]
**Describe the bug**
I'm monitoring few programs for current releases, lens is one of them. I expect that when Lens is released it should display notification about new version and prompt for update. It may check sometimes for new version but I should be able to force update from menu or tray. Right now something is cached. With new version I have no prompt and manually checking for new version does not find anything. If I leave it it will display upgrade dialog sooner or later, I never checked how long does it take to refresh it's cache. If I exit lens on tray icon and relaunch it finds new version perfectly. 

**To Reproduce**
1. Leave it running on background, use sleep for night 
2. on next day when there is new release try to update it from menu or tray - it would not find new version
3. relaunch including tray - now it will find new version OR leave it and measure when information about new version will be displayed

**Expected behavior**
I expect that when new version comes it should find it ASAP, when it was released at night then it should display dialog soon after app is active. For sure when I know about new version it should not cache when I manually check for new version using menu or tray. 

**Environment (please complete the following information):**
- Lens Version: 5.4.3 after morning upgrade 
- OS: Win10 
- Installation method (e.g. snap or AppImage in Linux): installer 

**Additional context**
If You don't use sleep or maybe hibernation then You won't notice that - checking for update works and lens starts with upgrade dialog. I intentionally left it once and it took it about one day to refresh this cache. I think that it cached to much and it should not cache manual update checks.

**Comment by Nokel81** [comment]
Related to #4948 

The reason why it doesn't show something immediately might be because it is downloading the update so you don't have to wait after clicking "yes"

**Comment by Nokel81** [comment]
Lens now checks for updates every hour so this should be resolved then.
