### ISSUE TITLE
Connecting to docker-desktop fails authentication

### ISSUE THREAD

**Issue by Iku-turso** [kontena/lens#5042]
Important: connecting to eg. minikube works just fine.
Edit: Important2: 5.4.3 does not have this problem. Missing hot fix?

**To Reproduce**
1. Go to Catalog -> Clusters -> docker-desktop.
2. Witness crash.

**Expected behavior**
No crash.

**Screenshots**
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4487805/159018824-0d5713bd-cbf0-4581-a9a9-40d505020996.png">

**Environment (please complete the following information):**
- Lens Version: master branch
- OS: MacOs
- Installation method (e.g. snap or AppImage in Linux): make dev

**Logs:**
```[LENS-PROXY]: http proxy errored for cluster: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: kubernetes.docker.internal. is not in the cert's altnames: DNS:localhost, IP Address:127.0.0.1```

**Comment by jakolehm** [comment]
Probably a regression from https://github.com/lensapp/lens/pull/4941

**Comment by Nokel81** [comment]
~~Given that 5.4.3 doesn't have this, does this happen on master?~~

**Comment by jakolehm** [comment]
It seems we need to create certs per cluster to make this problem go away.
