### ISSUE TITLE
Update to 5.4.3 from 5.4.2 doesn't work for some

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#5044]
A few people reported that the update  to 5.4.3 from 5.4.2 did not work:

From 5.4.2
Started Lens. Automated update check failed to find the update.
Then I clicked the "Check for updates" in the menu to have it check again. Found the update, said it was 5.4.3-something. Clicked yes to download and install and restart.
Then nothing happened.
I restarted Lens manually just to see. Still 5.4.2

3 incidences, 2 on mac, 1 on windows

**Comment by Nokel81** [comment]
Closing as old
