### ISSUE TITLE
The latest version is not published to The Snap Store

### ISSUE THREAD

**Issue by nsg** [kontena/lens#5093]
**Describe the bug**
I have Lens installed from the Snap store, the latest version is not published.

**To Reproduce**
1. Go to https://snapcraft.io/kontena-lens or Search for "Lens" in the built in store on Ubuntu
2. Follow the instructions and install Lens
3. Version `4.2.5` is installed

**Expected behavior**
Version `5.4.3` is installed

**Additional context**

I got a popup informing me that my installation is old. This was news to me, because I assumed that package would be kept up to date, and automatically updated in the background. I checked [your webpage](https://k8slens.dev/) and see that you actually build a [unsigned snap package](https://api.k8slens.dev/binaries/Lens-5.4.3-latest.20220317.1.amd64.snap) already. Why is it not published?

**Comment by Nokel81** [comment]
This has now been resolved
