### ISSUE TITLE
Expose Lens Monaco Editor component to public

### ISSUE THREAD

**Issue by hansiemithun** [kontena/lens#5094]
At present we are not able to use the Monaco Editor used by Lens. We were trying to use this since long time back but unfortunately with lens when we try to add this dependency and use, syntax highlighting was not working. So we have `js-yaml` 

W.r.to the latest lens CRD definitions, we see Monaco Editor used inside side panel. Can this be exposed for easy integration for us? This helps everyone.

**Comment by hansiemithun** [comment]
When can we expect this to be released?

**Comment by hansiemithun** [comment]
May I have the update on this ticket?

**Comment by ixrock** [comment]
> May I have the update on this ticket?

Works in progress.

**Comment by hansiemithun** [comment]
TS2339: Property 'MonacoEditor' does not exist on type 'typeof import("/Users/mshreevatsa/Documents/projects/cn2/ui/lens/node_modules/@k8slens/extensions/dist/src/extensions/renderer-api/components")'.

**The dependencies updated to:** 
    "@k8slens/extensions": "^5.4.6",

Am i missing anything to update?

**Comment by hansiemithun** [comment]
TS2339: Property 'MonacoEditor' does not exist on type 'typeof import("/Users/mshreevatsa/Documents/projects/cn2/ui/lens/node_modules/@k8slens/extensions/dist/src/extensions/renderer-api/components")'.

**The dependencies updated to:** 
    "@k8slens/extensions": "^5.4.6",

Am i missing anything to update?

**Comment by ixrock** [comment]
Probably it's not yet released in production. 
I guess it should be available from `v5.5.+`. @Nokel81 am I right?

**Comment by Nokel81** [comment]
@ixrock You are correct.
