### ISSUE TITLE
Allow extensions to hide 'Edit' and 'Remove' while using KubeObjectDetails component

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5105]
Now we check for store methods in https://github.com/lensapp/lens/blob/master/src/renderer/components/kube-object-menu/kube-object-menu.tsx#L43 which is not always the best approach.
![edit remove buttons](https://user-images.githubusercontent.com/9607060/160122273-ca33c169-7cf3-49b3-9b1c-283c52b05f47.png)

**Comment by jakolehm** [comment]
> Now we check for store methods in https://github.com/lensapp/lens/blob/master/src/renderer/components/kube-object-menu/kube-object-menu.tsx#L43 which is not always the best approach.

That approach is currently broken because it's not possible to have KubeObjectStore without those methods.
