### ISSUE TITLE
#4968 is back

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5116]
**Describe the bug**

the issue in https://github.com/lensapp/lens/issues/4968 is back.
over the weekend, lens released a new version 5.4.4 and when i started lens this morning. i was greeted by the login screen. i had previously disabled this in the preferences. now i see it is back. checking preferences i see that it is enabled

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Thanks for the report. This will be fixed in 5.4.5
