### ISSUE TITLE
Feature Request: Option to bring back menu bar?

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#5135]
I would like to see an option to bring back the 'normal' menu bar.

It recently changed so there's no longer "File, Edit, View, Help"...now there's a "hamburger menu" that you have to click to see "File, Edit, View, Help".

It's a minor inconvenience, but it adds an extra click to the process and I use it somewhat frequently.

**Comment by Nokel81** [comment]
cc @aleksfront

**Comment by Nokel81** [comment]
FYI for some of those options there should be keyboard shortcuts that you can use instead.

**Comment by darkpixel** [comment]
Dupe of #8015.
It's been over two years.
