### ISSUE TITLE
Extension API for Catalog Category badge

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/lens#5146]
Allow extension to specify a badge component to be displayed after the Category label in the Catalog Category menu.

Example usage in extension:
```
export default class extends Renderer.LensExtension {
  customCategoryViews = [
    {
      group: "entity.k8slens.dev",
      kind: "KubernetesCluster",
      priority: 10,
      components: {
        View: MyKubernetesClusterView,
        Badge: MyBadge
      },
    },
  ];
}
```

**Comment by msa0311** [comment]
@jakolehm should we do it this way or just allow components and strings for the name?

**Comment by jakolehm** [comment]
This does not really make sense to me. CatalogCategory metadata should contain just data, no logic (especially no UI logic).

**Comment by panuhorsmalahti** [comment]
Lets add the badge as a method instead.

```
class ManagedDevClusterCategory extends Common.Catalog.CatalogCategory {
  getBadge() {
      return (<DevClusterBadge />);
  }

  // ..
```

**Comment by jweak** [comment]
Could we have a general `render` function which the Category could use(/override) adding a badge with the text or something else? Could be useful in other situations.

**Comment by panuhorsmalahti** [comment]
@jweak see the updated description, I realized that adding a method (with React) code to the class is problematic, as the class needs to also work in main (where React code can't be loaded).

**Comment by jweak** [comment]
@panuhorsmalahti Yeah, I think that's a better approach.

That could work although I still think it could a be more general component like a `<CategoryListItem metadata={} />` rendered by Lens if available (and on default it could render the title and icon, if it's not available). The list item then could render the badge or something else if it wants.

Maybe some category wants to change background, change icon depending on state, or something else.

**Comment by Nokel81** [comment]
My concern with a registry pattern style is that explicitly allowed multiple different extensions to add badges, which makes the design of the implementation more complex.

**Comment by panuhorsmalahti** [comment]
I went back to the getBadge method after discussion with @Nokel81. It's not that generic, though..

**Comment by Nokel81** [comment]
It needs to be generic?

**Comment by panuhorsmalahti** [comment]
@Nokel81 it doesn't, I referred to @jweak's idea that it _could_ be generic, but the implementation at this time is not that generic. By generic I meant that it could do other things, not just modify the badge.
