### ISSUE TITLE
Monaco editor gets mounted every time drawer opened

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5154]
Relates to https://github.com/lensapp/lens/issues/2243

This take some CPU time while opening Drawer and doesn't seem to be necessary.

https://user-images.githubusercontent.com/9607060/161057037-1bd7e907-adc8-4a66-b55a-c31e8a73d96e.mov

**Comment by ixrock** [comment]
This is expected behavior.. every react component does this.
Please provide more specific numbers about CPU usage in this case if it really matter. 
Then we need to figure out if it's possible to optimize without uglifying & complicating component too much.

**Comment by Nokel81** [comment]
Yeah this is expected because `PodDetails` -> `PodDetailsAffinities` -> `MonacoEditor`
