### ISSUE TITLE
Network unit

### ISSUE THREAD

**Issue by dungeon2567** [kontena/lens#5169]
Are network units on lens using bytes or bits?

![image](https://user-images.githubusercontent.com/31074903/161270761-3c581d6f-9013-4b89-bdbc-558b6a29b30e.png)

**Comment by Nokel81** [comment]
Bytes, we try and display all memory related using the multiple byte IEC binary format (IEC 60027-2). So bytes. I guess we should add `B` so it is not confusing.

**Comment by Nokel81** [comment]
Actually, I don't know if we can clear that up. It is whatever unit your Prometheus configuration is using.

**Comment by Nokel81** [comment]
We know that they are bytes because that is what the Prometheus queries state
