### ISSUE TITLE
Must upgrade immediately modal

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#5208]
**What would you like to be added**:
If Lens has been running for a long time with an update downloaded and pending then a modal should be displayed requiring the user to quit so that the update can be applied.

**Comment by PhilippKuntschik** [comment]
how would this perform if I build the binary from scratch? see discussion [#5444 ](https://github.com/lensapp/lens/issues/5444#issuecomment-1173742061)

**Comment by Nokel81** [comment]
@PhilippKuntschik Nothing will happen. This only affects instances that have a configured update source which isn't configured in this repo at all.

**Comment by PhilippKuntschik** [comment]
it would probably be good to have https://github.com/lensapp/lens/releases/latest as an update source once https://github.com/lensapp/lens/pull/5772 is merged

**Comment by disconn3ct** [comment]
> @PhilippKuntschik Nothing will happen. This only affects instances that have a configured update source which isn't configured in this repo at all.

Why is this being added to a repo that it is explicitly not used in? Can we add other unrelated stuff?
