### ISSUE TITLE
update check occurs hours after launch

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5231]
**Describe the bug**
i started my instance of lens on friday. this morning about an hour and a half after i resumed from sleep , lens decided to check for updates. 
i was under the impression this was only at startup and not a regular thing.

why ? the notifications produced by the update system need to be cleared manually

**Comment by Nokel81** [comment]
We are working to improve this. Related to #4948. Stay tuned for 5.5.0

**Comment by Nokel81** [comment]
Update check now happens every hour.
