### ISSUE TITLE
Custom Resources are not listed in the Command Palette

### ISSUE THREAD

**Issue by neerajjose** [kontena/lens#5242]
**What would you like to be added**:
##### Custom Resources are not listed in the Command Palette
![image](https://user-images.githubusercontent.com/11937332/163321124-810e234c-a207-4945-8a21-4c6e6a0af20e.png)

**Why is this needed**:
It'll be good to have an option to search the custom resources from `command palette`, rather than scrolling the huge list of custom resources that we have in the left pane.  
eg: `ScaledObject` or `VirtualService`

**Environment you are Lens application on:**
- Ubuntu 20.04: `lens:5.2.3-latest.20210921.1`

**Comment by Nokel81** [comment]
This was resolved by https://github.com/lensapp/lens/pull/4424 and released in 5.4.0. Please upgrade to 5.4.5
