### ISSUE TITLE
Error handling in better ways

### ISSUE THREAD

**Issue by hansiemithun** [kontena/lens#5253]
**What would you like to be added**:
A better way of error handling instead of whole app crash and restart.

Image Ref: https://imgur.com/Ehyjb5U

Though there is a Back Button below, it won't work for the first time, the user needs to click two times to go back.

**Why is this needed**:

 Right now, if there is any console. error found the whole page is filled with that message and the user cannot go back, do anything. There should be a pleasant way to handle this and get rid of that error and users should be able to navigate easily.

Instead of app Crash, can we display such errors in a bar with a close icon or toasters? Just a suggestion.

**Environment you are Lens application on:**

It is applicable for all versions.

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>

**Comment by Nokel81** [comment]
Our position is that we do not sweep fatal errors away but instead require that they be fixed. This display is not intended for end users (though they might see it anyway) and thus if it is a tad annoying then it is by design.

Thank you anyway
