### ISSUE TITLE
Include the appimage in the release

### ISSUE THREAD

**Issue by faan11** [kontena/lens#5255]
As the title suggests, can you include the Appimage in the release section? 
I use the zap package manager which downloads the last image from the release section.
This mechanism can be used by zap to update the application ( it can check the github releases and download the latest one if needed).

Thank you in advance

**Comment by Nokel81** [comment]
Unfortunately, due to legal reasons this is not possible. Sorry about that. 

The good news is that AppImage supports auto-update anyway so you shouldn't need to use `zap`.
