### ISSUE TITLE
Helm Releases sometimes do not refresh

### ISSUE THREAD

**Issue by MartinGolding515** [kontena/lens#5269]
**What would you like to be added**:
~Helm repos are not auto updated and have to close lens from icon tray and then repoen.~

Helm releases are not auto updated and have to disconnect from cluster and come back to see them.

The latter is more important IMO.

Please either auto update or add a refresh button.

**Why is this needed**:
Slows down workflow.

**Environment you are Lens application on:**

- Kubernetes distribution: [ AKS,.]
- Desktop OS: <win10 with kubeconfig in ubuntu 20.04 WSL2 on >

**Comment by Nokel81** [comment]
Thanks for the report. This might be related to #3821
