### ISSUE TITLE
Build fqdn for a pod and list it in the pod details

### ISSUE THREAD

**Issue by Daxcor69** [kontena/lens#5316]
**What would you like to be added**:
I know I can build my fqdn for the pod but I would like to see a string in the pod details window.

**Why is this needed**:
It makes it much easier to c/p the string for testing and debugging purposes.  It could even be  clickable to make sure the cluster dns is resolving it correctly.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
on bare metal using kubeadm 1.23.6

- Desktop OS: <the OS Lens app runs on in your case>
Windows 10

**Comment by Nokel81** [comment]
Would you be able to give more information, what is a `fqdn`?

**Comment by Daxcor69** [comment]
A picture is worth a 1000 words.

![image](https://user-images.githubusercontent.com/61804230/166554106-ee6fc0ca-053d-415a-b8c7-cb7c911501b4.png)

**Comment by Nokel81** [comment]
Since that is not a core kubernetes functionality, that sounds like a great idea for an extension.

**Comment by Daxcor69** [comment]
OK, I guess I will have to learn how to write an extension.
