### ISSUE TITLE
Switching dark/light theme automatically with the macOS' dark/light mode

### ISSUE THREAD

**Issue by persus** [kontena/lens#5325]
**What would you like to be added**:
Please implement the feature that Lens ist switching between dark and light theme automatically accordingly to the operating system (when macOS goes to its dark or light mode).

**Why is this needed**:
Usability.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: macOS Monterey (12.3.1)

**Comment by Nokel81** [comment]
Already slated for 5.5.0, fixed in https://github.com/lensapp/lens/pull/4973
