### ISSUE TITLE
Please add HELM_DRIVER=configmap support

### ISSUE THREAD

**Issue by madianas21** [kontena/lens#5332]
**What would you like to be added**:
Support for multiple/different Helm storage backends. Right now only `HELM_DRIVER=secret` can be used with no option to change it or use multiple backends at the same time. 

**Why is this needed**:
We have to use `HELM_DRIVER=configmap` as our storage backend, hence using Apps-->Releases in Lens is not possible

**Environment you are Lens application on:**
- Kubernetes distribution: EKS
- Desktop OS: Ubuntu 21.04

**Comment by Nokel81** [comment]
Is this because you are migrating from helm2?

**Comment by mchandler-plato** [comment]
+1 to this issue, the main reason we are using configmap is to allow read only user that cant dump secrets but still do a helm diff

**Comment by panuhorsmalahti** [comment]
Configuration option for HELM_DRIVER has been implemented and will be included in the near future in Lens.
