### ISSUE TITLE
stale/stuck bug repro 100% success rate

### ISSUE THREAD

**Issue by matti** [kontena/lens#5353]
```
git clone https://github.com/matti/kung
cd kung
./test
```

https://user-images.githubusercontent.com/3893/167472594-aac842b8-fbde-4da4-a86b-796f1fa0d41f.mp4

**Comment by Nokel81** [comment]
Is this on 5.4.6? We have some fixes for this coming in 5.5.0 (first beta is already out, next beta should be out tomorrow)

**Comment by Nokel81** [comment]
I cannot run that example as `xargs` does not have a `-r` option (nor can I find documentation of a platform that has a version of `xargs` that does).

**Comment by matti** [comment]
version: 5.4.6-latest.20220428.1

@Nokel81 gnu xargs has -r, but dont worry, you can just remove them like I do here where this still reproes 100%

https://user-images.githubusercontent.com/3893/167923453-907367e1-9cbd-47a7-92da-612d2183fc3c.mp4

**Comment by Nokel81** [comment]
Interesting... I can no longer reproduce against master (6.4.0-alpha.3)

**Comment by Nokel81** [comment]
Marking this a closed as we can reproduce this on 6.2.5 but not on 6.4.0
