### ISSUE TITLE
stuck at refreshing connection status: Error: Parse Error: Expected HTTP/

### ISSUE THREAD

**Issue by lusson-luo** [kontena/lens#5357]
**Describe the bug**
Connects to a k8s cluster, can't connect it, it gets stuck at connection status.
kubeconfig is ok, use kubectl --kubeconfig=xx is working.

**To Reproduce**
1. file -> add Clusters from Kubeconfig
2. connects to the cluster, failed
3. It gets stuck at Parse Error: Expected HTTP/

**Expected behavior**
Shall be connected and move the next screen to Workloads, network, & Apps

**Screenshots**
lens
<img width="444" alt="image" src="https://user-images.githubusercontent.com/19859400/167613357-43b5055f-ccac-4ee8-ba56-e59cc2a5df41.png">

log
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/19859400/167613253-5f2d1113-1be6-4109-bf6b-3c42175a2527.png">

**Environment (please complete the following information):**
- Lens Version: 5.4.6
- OS: [e.g. OSX] macOS
- Installation method (e.g. snap or AppImage in Linux):.dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [WINDOW-MANAGER]: Main window loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [KUBECONFIG-SYNC]: starting requested syncs
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"/Users/lusson/Library/Application Support/Lens/kubeconfigs"}
info: [KUBECONFIG-SYNC]: starting sync of file/folder {"filePath":"/Users/lusson/.kube"}
info: [KUBECONFIG-SYNC]: ignoring '/Users/lusson/Library/Application Support/Lens/kubeconfigs/.DS_Store' due to ignore glob: .DS_Store
info: [CLUSTER]: activate {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: bind events {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":true}
info: [CLUSTER]: reconnect {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":true}
error: [CLUSTER]: Failed to connect to "local": RequestError: Error: Parse Error: Expected HTTP/
info: [CLUSTER]: refresh {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":false}
error: [CLUSTER]: Failed to connect to "local": RequestError: Error: Parse Error: Expected HTTP/
info: [CLUSTER]: refresh {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":false}
error: [CLUSTER]: Failed to connect to "local": RequestError: Error: Parse Error: Expected HTTP/
info: [CLUSTER]: refresh {"id":"819b9ed23449293560f6599f37133a8b","name":"local","ready":false,"online":false,"accessible":false,"disconnected":false}
error: [CLUSTER]: Failed to connect to "local": RequestError: Error: Parse Error: Expected HTTP/
```

**Comment by Nokel81** [comment]
Sounds like your kube server is returning a malformed return packet. From what I can tell it is probably that the `content-length` header is "too short".

**Comment by jakolehm** [comment]
@lusson-luo is there some kind of HTTP(S) proxy between your computer and the target kubernetes cluster?

**Comment by lusson-luo** [comment]
@jakolehm yes，it have some HTTP(S) proxy between computer and the target kubernetes cluster, proxy and kubernetes cluster is ok. cause use kubectl --kubeconfig=xx is working.
should i  provide more info? For example each lens server http request and response and how to get it
![image](https://user-images.githubusercontent.com/19859400/167763510-71624047-1a54-4bcc-97c9-1011cc7780af.png)

**Comment by Nokel81** [comment]
If you run `kubectl proxy` against that cluster and that Kube config, can you reach through using curl?

**Comment by jakolehm** [comment]
@lusson-luo does it work if you configure proxy in the cluster settings?

**Comment by lusson-luo** [comment]
@Nokel81 run command `kubectl proxy --api-prefix=/k8s-api get po --kubeconfig=/Users/marxluo/.kube/config-010`?
exec `curl http://127.0.0.1:8001/api/` return 404
![image](https://user-images.githubusercontent.com/19859400/168244575-fc0463ca-a9c5-494e-8e1d-6f664fe2f03f.png)
![image](https://user-images.githubusercontent.com/19859400/168244609-0899c419-6dda-436d-a47d-b7971322a7b8.png)

**Comment by lusson-luo** [comment]
> 

yes, now i can run kubectl proxy against that cluster and that Kube config，and curl has response。but lens also not working
![image](https://user-images.githubusercontent.com/19859400/174022137-a9e2b4b0-ccca-43c6-b91b-345ed93f78ee.png)
![image](https://user-images.githubusercontent.com/19859400/174022249-30971f14-7f39-4a86-b663-3699580583c7.png)

@Nokel81 how can i do next?

**Comment by Nokel81** [comment]
If you run the following command does the curl still work?

```
KUBECONFIG=/Users/marxluo/.kube/config-nocalhost /Applications/Lens.app/Contents/Resources/x64/lens-k8s-proxy
```

**Comment by lusson-luo** [comment]
> lens-k8s-proxy

not find lens-k8s-proxy file

the file int /Applications/Lens.app/Contents/Resources/x64/ is kubectl

![image](https://user-images.githubusercontent.com/19859400/176127302-ff743e55-a079-467d-927b-2b8f76ea3eeb.png)

find lens-k8s-proxy not has any file
`find /Applications/Lens.app -name "lens-k8s-proxy"`
`find /Applications/Lens.app -name "*lens-k8s-proxy*"`
`find /Applications/Lens.app -name "*proxy*"`

**Comment by lusson-luo** [comment]
len version: 5.4.6
![image](https://user-images.githubusercontent.com/19859400/176127972-25d3d07c-e654-4cf3-891b-b7b06aff6d32.png)

**Comment by Nokel81** [comment]
Ah, that was added in 5.5.

In 5.4.6 the other CLI flags that we were using were:
- `--context` (cluster context name)
- `--accept-hosts` (hostname of the cluster server URL)
- `--reject-paths='^[^/]'`
