### ISSUE TITLE
Blank Screen when accessing cluster

### ISSUE THREAD

**Issue by HakunMatat4** [kontena/lens#5375]
**Describe the bug**
Lens does not show anything in the view when it connects. It shows the message "No issues found" to indicate that it is connected, but the screen is blank..

**To Reproduce**
1. Open Lens
2. Connect to cluster

**Expected behavior**
I expect to be able to see the cluster..

**Screenshots**
[Blank Dashboard](https://i.imgur.com/bor3D6h.png)

**Environment (please complete the following information):**
- Lens Version: 5.4.6-latest.20220428.1
- OS: Windows 10 Pro
- Installation method (e.g. snap or AppImage in Linux): Lens Setup 5.4.6-latest.20220428.1.exe

**Additional context**
I've checked other reports like this, https://github.com/lensapp/lens/issues/4323 and https://github.com/lensapp/lens/issues/4018, I have done as suggested:

- del: \AppData\Roaming\Lens\lens-local-storage

There are no errors under Developer Tools.
I can see the Nodes even so a lot of information is missing like CPU, Mem, etc.
Overall, It is as if I can access 1% of that cluster.

I cannot test this with Linux, my main OS, the company requires Windows.

Thank you

**Comment by Nokel81** [comment]
What you have described is not the "blank dashboard" issue previously reported. That display just means that Lens cannot access any Prometheus installation in the cluster that you might have.

I assume that you can navigate around to view "Pods" and such.

**Comment by dsuresh-ap** [comment]
I have the same issue on `Lens: 5.5.1-latest.20220526.1` only on one of my 10+ clusters. It loads to a blank screen. I tried all of the deleting of directories in the other issue and even re-installed Lens. I tried to delete the kubeconfig and re-merge it but still same issue. I am able to view the cluster via CLI and others are able to view it through Lens so it is just my IDE. Any help is appreciated

All I see is: 
![image](https://user-images.githubusercontent.com/21132682/170563296-6b5ade78-2575-4c00-bb5b-6f7bc798d4cd.png)

**Comment by Nokel81** [comment]
Is the one cluster that didn't work using a service account?

**Comment by dsuresh-ap** [comment]
I am not sure what you mean. All the clusters have their KubeConfig merged though the K8 VSCode extension + AKS Cloud provider. For this cluster that is not working, I even tried using AZ CLI to merge the config.

**Comment by Nokel81** [comment]
Yes, but to authenticate with a cluster the kubeconfig needs a `user` field in the kubeconfig.

**Comment by Nokel81** [comment]
@dsuresh-ap You seem to be running into https://github.com/lensapp/lens/issues/5462

**Comment by Nokel81** [comment]
This issue is about something else.

**Comment by dsuresh-ap** [comment]
I see, didn't see that issue. Thanks!
