### ISSUE TITLE
Command palette hotkey does not work on Linux

### ISSUE THREAD

**Issue by pdf** [kontena/lens#5411]
**Describe the bug**
The command palette hotkey `Ctrl+Shift+P` does not appear to work on Linux. However, pressing `Ctrl+Shift+E` does work for extensions.

**To Reproduce**
1. Press `Ctrl+Shift+P` on Linux
2. No command palette is displayed

**Expected behavior**
Hotkeys should function on Linux

**Environment (please complete the following information):**
- Lens Version: 5.4.6
- OS: Linux (Arch)
- Installation method (e.g. snap or AppImage in Linux): AppImage (AUR: lens-bin)

**Logs:**
No logs produced on pressing key combo

**Kubeconfig:**
N/A

**Additional context**
Not sure if this is related or Linux-specific, but `Esc` does not work if a text field is selected (e.g. on entering the `Extensions` screen, the search field is auto-selected, and `Esc` refuses to close the page unless the field is unfocused).

Also unsure if there is meant to be a quit hotkey (tried `Ctrl+q`, `Ctrl+w`, `Ctrl+Shift+w` with no effect), or if it also just isn't working for Linux.

**Comment by Nokel81** [comment]
Verified on ubuntu and on windows

**Comment by pcgeek86** [comment]
I'm on Windows 11 Dev Preview and K8S Lens 5.4.6, and I cannot use the Command Palette. I didn't even realize this feature existed until I came upon this issue report! 😆 

![image](https://user-images.githubusercontent.com/466713/169859802-3b2d3e84-dd0d-4034-ad83-76a2a51126d4.png)
