### ISSUE TITLE
UI hangs completely when the highchart export is called 

### ISSUE THREAD

**Issue by tashigarg** [kontena/lens#5421]
**Describe the bug**

A blank screen covers the entire UI and there is no way to do any action when the highcharts default export is invoked.

**To Reproduce**

1. Go to Hello World page
2. Click on export menu on the chart
3. Click on 'Download PNG'

The UI hangs completely while the file is being saved.

**Expected behavior**
UI should not hang.

**Screenshots**
Screenshot, screen recording, and sample app attached to reproduce it

**Environment (please complete the following information):**
Lens: 5.4.6-latest.20220428.1
Electron: 14.2.4
Chrome: 93.0.4577.82
Node: 14.17.0
© 2021 Mirantis, Inc.
- MacOS: 12.3.1

https://user-images.githubusercontent.com/38350
[helloworld-sample.zip](https://github.com/lensapp/lens/files/8721138/helloworld-sample.zip)
997/169162907-e37ea11a-e427-4a6c-a485-47e03e2aed38.mov

**Comment by tashigarg** [comment]
https://user-images.githubusercontent.com/38350997/169165426-fdcf9395-5bcd-4f48-85b3-3ff368e4914c.mov

**Comment by Nokel81** [comment]
Where did you get that sample code from? That entire component does not appear in https://github.com/lensapp/lens-extension-samples/tree/master/helloworld-sample at all

**Comment by tashigarg** [comment]
Hi Sebastian,

I am using the same sample app
https://github.com/lensapp/lens-extension-samples/tree/master/helloworld-sample
with little changes to include highcharts.

I have attached the patch of changes on git also here.
[lens-patch-highcharts.patch.zip](https://github.com/lensapp/lens/files/8743959/lens-patch-highcharts.patch.zip)

Thanks,
Tashi

**Comment by Nokel81** [comment]
We have run into a similar symptom a few times. Maybe it is related to a CSS rule that is "display: none". 

Though further request for debugging help about extensions, please use the public slack.
