### ISSUE TITLE
Why make lens id mandatory?

### ISSUE THREAD

**Issue by andrew-vdb** [kontena/lens#5443]
![image](https://user-images.githubusercontent.com/12871379/170274769-07bf1344-e5b2-4cf8-a515-6b4e131d9854.png)

Expected: Skip create lens id
Actual: No option to skip

**Comment by kallisti5** [comment]
Here's a workaround.  Add the following to your /etc/hosts file:

```
127.0.0.1       app.k8slens.dev
```

That will break the login page, and let you click the skip button on version 5.4.x.  The workaround doesn't work on 5.5.x

I love lens, and would pay for it... but I *really* don't want to be forced into logging into it without reason. That smells really bad and makes me think the community should fork it if it was on purpose.

**Comment by jhoelzel** [comment]
that workaround is not working for me on windows 11 with the current version it only changes the screen to this:
![image](https://user-images.githubusercontent.com/30208763/170279215-01b88f55-d871-4065-acf9-193e424829e1.png)

**Comment by andrew-vdb** [comment]
Lets use one issue, follow up here 
https://github.com/lensapp/lens/issues/5444

**Comment by DanyHenriquez** [comment]
Disgusting
