### ISSUE TITLE
Unable to group Lens version v5.5.0-latest.20220525.1 - all previous versions work great.

### ISSUE THREAD

**Issue by dbrewer-exp** [kontena/lens#5447]
**Describe the bug**
I use StarDock Groupy to group similar applications together on my windows desktop. Each application gets its own tab so I can easily switch between applications. I have used Lens for something like 2 years now, I upgrade every release. All versions have been compatible with Groupy. Version v5.5.0-latest.20220525.1 is the only version that doesn't work. I don't know what specifically changed, but I cannot get it to group with my other applications. I have not tried any of the beta releases.

**To Reproduce**
1. Install Groupy. They have a free trial available. https://www.stardock.com/products/groupy/
2. Try and group Lens version v5.5.0-latest.20220525.1 with any other application. It simply doesn't work. There are no other applications I know of that are unable to group. To group applications together, you drag the headers together and groupy will automatically add them to a group, with each application getting its own tab. You can add additional applications to the group by dragging their header into the tabs of an existing group.
3. Revert to any previous version of Lens (I didn't try beta versions) and you can group them as normal.

**Expected behavior**
Lens will be added as a new tab in a group with other applications.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: v5.5.0-latest.20220525.1
- OS: [e.g. OSX] Windows 11
- Installation method (e.g. snap or AppImage in Linux): Direct download of 64 bit installer from k8slens.dev

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
What is your previous version of Lens? Was it 5.4.6?

**Comment by dbrewer-exp** [comment]
yes, 5.4.6 works.

**Comment by dbrewer-exp** [comment]
WIth Lens v6.0.0-latest.20220728.2 this is no longer an issue, Lens works with Groupy as expected.
