### ISSUE TITLE
Accesible namespaces not working after update 

### ISSUE THREAD

**Issue by clglavan** [kontena/lens#5459]
**Describe the bug**
After updating to lens Lens: 5.5.0-latest.20220525.1 when adding a cluster via kubeconfig directly from Lens, and defining Accessible Namespaces for it, it loads a blank page.

**To Reproduce**
1. Update to 5.5.0-latest.20220525.1
2. Add kubeconfig with a user with limited access to specific namespaces
3. Add accessible namespaces for that cluster
4. The cluster loads a blank page

**Expected behavior**
Like in the previous version, use the cluster only on the accessible namespaces

**Environment (please complete the following information):**
- Lens Version: 5.5.0-latest.20220525.1
- OS: macOS Monterey 12.3.1 (21E258)
- Installation method (e.g. snap or AppImage in Linux): update from lens

The kubeconfig works fine from cli with kubectl, so you can exclude misconfiguration inside the cluster.
Also using a kubeconfig with ClusterAdmin rights for the user also works fine in Lens.
Thus the issue seems to be with using a kubeconfig with accesible namespaces defined.

**Comment by Nokel81** [comment]
What do you mean by blank page? Is this a duplicate of #5462 or do you mean that no pods show up?

**Comment by jim-docker** [comment]
@clglavan Is this what you're seeing:

https://user-images.githubusercontent.com/40840436/170584898-809621e3-1612-4f90-a23e-9849654e3aed.mov

The dashboard is initially blank after connecting, but you can still view the various pages (i.e. Pods, etc.)

The Cluster Overview page is missing (this happens when the user does not have list permission for nodes).

**Comment by clglavan** [comment]
Hello, this is what I am seeing
![Screenshot 2022-05-27 at 11 09 46](https://user-images.githubusercontent.com/5683691/170658968-ec3fc409-0ceb-42c5-aa80-c56682483e8d.png)

This is a cluster with a user that has permissions assigned per namespace. ( Accesible namespaces are set corectly, as they were working before the update )
This works fine if we downgrade to lens 5.3.4 

This is not a general issue, other clusters in the latest verions work fine, the above printscreen only happens for user with access restricted to namespaces

**Comment by Nokel81** [comment]
Are you using a non-default service account for that cluster connection?

**Comment by Moersity** [comment]
I meet the same probrom,  this is the log

```sh
StatusCodeError: 403 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"u-tmzlnmrw4k\" cannot get path \"/k8s/clusters/c-9gjgf/version\"","reason":"Forbidden","details":{},"code":403}
```
This is a cluter with a user that has permission of specific namespace.

**Comment by clglavan** [comment]
@Nokel81 yes, I am using a custom csr for the user.

**Comment by Nokel81** [comment]
@Moersity Is that log from the devtools or from the console?
