### ISSUE TITLE
unable to use lens 5.4.6 coz of "lens id" login

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#5463]
**Describe the bug**

i just did a brew update of lens and now when i start lens it is asking me for lens id to login. 

i do not have a lens id. i have no intention of using lens id. nor do i intend to sign up for one.

so i looked for the "x" to close the log in page. i tried to load the preference page. i tried restarting lens.

all useless. i really did enjoy using lens. this is very sad for me

![Screen Shot 2022-05-26 at 8 16 42 AM](https://user-images.githubusercontent.com/69474017/170486105-77126606-f52f-4014-b3a0-31aa6549a011.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by george2asenov** [comment]
same problem here. Probably it is desired behavior. They try to force us to register to their cloud, and probably the next step is to make it paid. 
This is the moment when we will start searching for alternatives. 
This is very disappointing. NO one will give access to a production on premises cluster to their platform NO ONE.

**Comment by marafa-sugarcrm** [comment]
closing in favour of #5444 (see fix in comments)

**Comment by phardelain-kouassi** [comment]
I have created a Lens ID, but I still have the same problem here on my windows. 
Also the documentation is not helping enough with the process to create a Lens ID (like links)

I had to figure out that it is here https://app.k8slens.dev/
