### ISSUE TITLE
Why does Lens need Login before accessing the personal cluster?

### ISSUE THREAD

**Issue by abhishek-ch** [kontena/lens#5475]
**Describe the bug**
The new version of Lens is forcing us to log in for accessing the cluster

**To Reproduce**
1. Install new Lens
2. Open Lens

**Expected behavior**
Skip login 

**Environment (please complete the following information):**
- Lens Version:  v5.5.0-latest.20220525.1
- OS: OSX

**Comment by TilmannBach** [comment]
as lens doesnt support our proxy pac file settings, i'm not able to access lensId server and thus not able to use Lens at all (since the last update)

**Comment by jakolehm** [comment]
@TilmannBach have you tried `/Applications/Lens.app/Contents/MacOS/Lens --proxy-pac-url=<url>` ?

**Comment by josepowera** [comment]
#5444

**Comment by matrix-spec** [comment]
https://github.com/lensapp/lens/issues/5444#issuecomment-1139684024

**Comment by abhishek-ch** [comment]
https://github.com/lensapp/lens/issues/5444 covers the details, so closing.
