### ISSUE TITLE
Cannot open resources detail side panel

### ISSUE THREAD

**Issue by daper** [kontena/lens#5476]
**Describe the bug**
When clicking a resource the program crashes.

**To Reproduce**
1. Go to Pods
2. Click on any pod
4. See the crash

**Expected behavior**
See the pod details

**Screenshots**
<img width="1353" alt="imagen" src="https://user-images.githubusercontent.com/5327718/170659724-e72921ef-2e51-4cf3-9aa7-be2b2e72849d.png">

**Environment (please complete the following information):**
- Lens Version: 5.5.1-latest.20220526.1
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): brew

**Comment by tctctctc** [comment]
I'm having same issue while opening Helm release


Steps to reproduce the behavior:
1. Go to Helm -> Releases
2. Click on any release
3. See the crash

![Снимок экрана 2022-05-27 в 12 00 17](https://user-images.githubusercontent.com/13472535/170668047-d97376e2-a3e6-4252-b764-0e7d21165f60.png)

Environment (please complete the following information):
Lens: 5.5.1-latest.20220526.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0
OS: macOS 11.6.6 (20G624)
Kernel:	Darwin 20.6.0
Installation method (e.g. snap or AppImage in Linux): brew

**Comment by Nokel81** [comment]
fixed by https://github.com/lensapp/lens/pull/5479
