### ISSUE TITLE
Performance Issue MacOS

### ISSUE THREAD

**Issue by marcheyer** [kontena/lens#5478]
Describe the bug
After updating to version 5.5.1-latest.20220526.1 Lens has a performance Issue when using the edit function.
It takes minutes until the terminal opens. Most times the app crashes completely.
EDIT: this only occurs when a edit session is open already

To Reproduce

    Go to 'Workloads > pod'
    Click on POD 
    Click on edit Button.

Expected behavior
Edit Terminal opens immediately.

Environment:
    
    Lens: 5.5.1-latest.20220526.1
    Electron: 14.2.9
    Chrome: 93.0.4577.82
    Node: 14.17.0
    © 2021 Mirantis, Inc.

    OS: MacOS Monterey (version : 12.4)

Can anyone reproduce this?

**Comment by Nokel81** [comment]
Probably fixed by https://github.com/lensapp/lens/pull/5479 as that PR fixes issues related to the editor. Closing, please reopen if 5.5.2 won't fix your problem (once it is released).
