### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by kelvinbg** [kontena/lens#5489]
I am facing this error after upgrading Len to the latest version. Before Version was working with issues. And I would like to revert back to that if possible.
<img width="953" alt="noconnection-lens" src="https://user-images.githubusercontent.com/98049461/170796668-03259bb5-46bf-4bb2-bf68-2c9f4a5e9886.PNG">

**Comment by StevDa86** [comment]
Same Problem here. Please Fix!  :(

**Comment by Mo7amed178** [comment]
@StevDa86 @kelvinbg 
I was facing this issue this moening , just downgrading to 5.1.3 version , and its working now

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/5482
