### ISSUE TITLE
Trash/edit reference incorrect resource

### ISSUE THREAD

**Issue by ahkui** [kontena/lens#5492]
**Describe the bug**
trash/edit reference incorrect resource

**To Reproduce**
1. select a node 
2. select pod from the node panel
3. click trash or edit
4. it's show remove node

![image](https://user-images.githubusercontent.com/14049597/170816899-95d722ea-b0bd-4763-995f-67fa7fa5ca9d.png)

![image](https://user-images.githubusercontent.com/14049597/170816853-08210434-b8f3-449d-9b3f-a863e639b03e.png)

**Comment by Nokel81** [comment]
Closing because the PR to fix this issue has been merged to the release branch.
