### ISSUE TITLE
Too High CPU usage and crash

### ISSUE THREAD

**Issue by iyuhptop** [kontena/lens#5495]
**Describe the bug**

Lens crashes when i click pod item(or other items such as crd)
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/14036170/170848593-e1ded05f-9b21-4d91-8e18-c2c5497315cd.png">

Got these:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/14036170/170848548-3040099e-8c10-45b0-a2e5-16ec9a7e97e0.png">

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/14036170/170848556-df3ac4ed-8d5b-487a-9823-95cb3a2f424d.png">

**Environment (please complete the following information):**
- Lens Version: 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/14036170/170848645-67db6859-46aa-4bcd-aebc-168efd3eadde.png">

- OS:  macOS Monterey 12.4

Best Regards

**Comment by vothanhkiet** [comment]
I also have the same experience. Access the Edit pod button it will crash.

**Comment by chenhunghan** [comment]
The crash should be fixed in https://github.com/lensapp/lens/pull/5479

**Comment by agronholm** [comment]
Let's hope we get v5.5.2 soon. Lens has been crashing constantly for me since I upgraded to 5.5.0/1.

**Comment by Nokel81** [comment]
Release will be out today with that bug fix.
