### ISSUE TITLE
Lense id confirmation email address spam filter

### ISSUE THREAD

**Issue by micgruber** [kontena/lens#5496]
I tried to register for lense id. Unfortunately can't receive the email because I think our gloabal spam filter is blocking the email from lense. Can you tell me the email from where I receive the confirmation link, so I can except the email.

**Comment by chenhunghan** [comment]
Should be from `no-reply@k8slens.dev`, let use know if you need more information.

**Comment by micgruber** [comment]
@chenhunghan thanks.
