### ISSUE TITLE
very Slow and crash when open editor for two resource

### ISSUE THREAD

**Issue by anhtung19x9** [kontena/lens#5499]
1. Go to 'Ingress'
2. Click on 'First Resource'
3. Open another resource, the time to open the second edit tab very long, sometimes crash IDE

**Environment (please complete the following information):**
- Lens Version: 5.5.1-latest.20220526.1
- OS: OSX
- Installation method: DKG file

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/5479, will be out as part of a patch release later today.
