### ISSUE TITLE
Lens stays on blank screen after start

### ISSUE THREAD

**Issue by andrei-dascalu** [kontena/lens#5511]
**Describe the bug**
When Lens loads after update to latest version, it remains on a blank screen with no menu items or anything (after a very brief loader that appears sometimes for less than a second)

**To Reproduce**
1. Start lens (either via Applications or CLI)

**Expected behavior**
Lens loads with existing clusters, etc

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ [MENU]: autoUpdateDisabled=false +47ms
error:   ┏ Loading main window failed +26ms
error:   ┃ [ 1] {
error:   ┃ [ 2]   error: Error: ERR_FAILED (-2) loading 'static://splash.html'
error:   ┃ [ 3]       at rejectAndCleanup (electron/js2c/browser_init.js:161:7486)
error:   ┃ [ 4]       at Object.stopLoadingListener (electron/js2c/browser_init.js:161:7861)
error:   ┃ [ 5]       at Object.emit (events.js:388:22)
error:   ┃ [ 6]       at Object.emit (domain.js:470:12)
error:   ┃ [ 7]       at Object.emitter.emit (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:121:20) {
error:   ┃ [ 8]     errno: -2,
error:   ┃ [ 9]     code: 'ERR_FAILED',
error:   ┃ [10]     url: 'static://splash.html'
error:   ┃ [11]   }
error:   ┗ [12] }
```

**Additional context**
Appeared after upgrade from 5.5.1 to 5.5.2
OS: MacOS (Intel)

**Comment by swAucxis** [comment]
We have the same issue

**Comment by Nokel81** [comment]
If you fully quit the app and then relaunch does that solve the issue?

**Comment by fxp0** [comment]
same issue. fully quit and relaunch didn't help. downgraded to `5.5.1`

**Comment by jhughesjha** [comment]
We have the same issue also

**Comment by Nokel81** [comment]
I have not been able to reproduce, do you have some sort of local proxy? Would you be able to provide some more logs?

**Comment by jhughesjha** [comment]
@Nokel81 , can I email you the log file?

**Comment by Nokel81** [comment]
Yup. smalton@mirantis.com

**Comment by Nokel81** [comment]
@fxp0 Would you be able to provide a video clip of what you are seeing?

**Comment by piavgh** [comment]
I have the same problem, just blank screen

**Comment by PascalGiessler** [comment]
Same for me

**Comment by jiangxiaoqiang** [comment]
same issue. this is the version info:


```
Lens: 5.5.1-latest.20220526.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0
© 2021 Mirantis, Inc.
```

**Comment by jotedia** [comment]
Same for me.

**Comment by fxp0** [comment]
@Nokel81 Sent you the link with the screen record.

**Comment by PolarAir** [comment]
same blank screen for me here.


```
Lens: 5.5.2-latest.20220530.1
Electron: 14.2.9
Chrome: 93.0.4577.82
Node: 14.17.0
© 2021 Mirantis, Inc.
```

```
macOS Monterey
Version 12.4

MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 16 GB
```

**Comment by daniel-hirvonen** [comment]
Same issue here for me. Blank screen on start.

**Comment by orengimel** [comment]
same here - blank on startup.

MacBook Pro 16-inch 2021
Apple M1 Pro
Monterey 12.3.1

Does anyone have a downloadable link to previous version ?

**Comment by jiangxiaoqiang** [comment]
> same issue. fully quit and relaunch didn't help. downgraded to `5.5.1`

how did you downgrade?

**Comment by fxp0** [comment]
> how did you downgrade?

Yesterday it was yet available on the Lens website as a version for download, but as I can see they updated it there as well.
Here is the direct link to the MacOS Intel package: https://api.k8slens.dev/binaries/Lens-5.5.1-latest.20220526.1.dmg
I believe you can get the same version for other OS by simply changing the file extension in the link.

**Comment by daniel-hirvonen** [comment]
> > how did you downgrade?
> 
> Yesterday it was yet available on the Lens website as a version for download, but as I can see they updated it there as well. Here is the direct link to the MacOS Intel package: https://api.k8slens.dev/binaries/Lens-5.5.1-latest.20220526.1.dmg I believe you can get the same version for other OS by simply changing the file extension in the link.

Worked for me also to downgrade. Was this the apple silicon dmd img? or intel one?

**Comment by plevart** [comment]
Here's the link for AppImage for Linux x64:
https://downloads.k8slens.dev/ide/Lens-5.5.1-latest.20220526.1.x86_64.AppImage

**Comment by andrei-dascalu** [comment]
I switched between my initial install (via dmg) to install via brew cask, reinstall via dmg after brew remove worked.
Fully exiting and restarting did not work.

Unfortunally I was pressed to just make it work so I wasn't able to gain additional info. Removing my initial install (done via dmg) by deleting Lens from Applications and reinstalling via brew did not help. Removing the new install via brew and re-iinstalling latest version via dmg afterwards did work.

**Comment by Nokel81** [comment]
@fxp0 Thanks for the recording. I think you are seeing the issue when our IDP servers are down (they should be back up and running now). However, I think that the OP was talking about seeing the following

![image](https://user-images.githubusercontent.com/8225332/171420137-ffdd23a8-6eb8-4002-831f-e7c76c275847.png)

**Comment by Nokel81** [comment]
Closing because the PR to fix this issue has been merge to the release branch.
