### ISSUE TITLE
Error on starting container: [dumb-init] -e: No such file or directory

### ISSUE THREAD

**Issue by jamesbmorris92** [kontena/lens#5516]
Hi All,

I'm attempting to follow the install guide here: https://docs.lenses.io/5.0/installation/docker/ I've managed to pull the most recent version of the lenses image. When I try to start up a container using the command in the install guide (with the tag changed from 5.0 to latest):
docker run --name lenses lensesio/lenses:latest -e LENSES_PORT=9991 -e LENSES_SECURITY_USER=admin -e LENSES_SECURITY_PASSWORD=sha256:8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918

I get the following error:
[dumb-init] -e: No such file or directory

i've tried pulling and starting version 5.0 and got the same issue. I've also tried starting the container with sudo. 

Apologies if i'm missing any other information, this is my first time reporting an issue on github

**Comment by Nokel81** [comment]
Sorry for your troubles but that is not this repo. I think you are looking for https://github.com/lensesio/lenses-docker
