### ISSUE TITLE
Ability to view POD logs and Shell exec disappeared after upgrading to 5.5.2

### ISSUE THREAD

**Issue by JiriZidek** [kontena/lens#5530]
There is no Logs or Exec option in PODs context menu or when in detail no button in toolbar. Only Edit and Delete.

1. Go to Workoloads/Pods
2. Click on any POD's three dots on very right.
3. There is no Logs or Execute (or ShelleExec)

It used to work, at least in 5.5.0. Just a bug or this feature has been dropped ?

Screenshots
![image](https://user-images.githubusercontent.com/8578952/171365012-bce49478-177e-4016-8d90-3b667d0baa58.png)

Environment:
- Lens Version: 5.5.2-latest.20220530.1
- OS: Windows 10
- Installation method: autoupdate

Kubeconfig:
Not touched... log ins VSCode or by kubectl work well.

Additional context:
After autoupgrading to 5.5.2 it forced me to login by Github account... now there is nothing like that (see printscreen).

**Comment by Nokel81** [comment]
This is certainly a bug.

**Comment by Nokel81** [comment]
If you quit from the tray icon and then restart does that fix the issue? If not Can you run the application via powershell and post the logs?

**Comment by JiriZidek** [comment]
Found that after restarting computer it works and the account info appear now:
![image](https://user-images.githubusercontent.com/8578952/171416578-8d8ade5b-a1ab-4d22-b923-e30227ff0dab.png)

So it looks like one-stop-problem with no repro. I guess we might close the issue.. Thanks.

**Comment by JiriZidek** [comment]
![image](https://user-images.githubusercontent.com/8578952/171416890-c884eb42-49be-4e79-ac12-7171a0191108.png)
