### ISSUE TITLE
Crash in attempting to edit a pod

### ISSUE THREAD

**Issue by dwgillies-bluescape** [kontena/lens#5536]
**Describe the bug**
crash while trying to edit a pod (cmt-xyz...) in my cluster.  I clicked on the edit button and there was a huge delay (~20) and then this.

<img width="1271" alt="Screen Shot 2022-06-01 at 11 21 31 AM" src="https://user-images.githubusercontent.com/83255730/171475495-bc349732-8470-4225-9fce-10efeb5bd474.png">

second crash when trying to click on a different pod (browser-client-xyz...).  I clicked on Pod > Status, then the green "Running" word, then nothing, a few seconds later i clicked the hamburger icon on the same pod, and 10-20s later, a 2nd crash.

<img width="1260" alt="Screen Shot 2022-06-01 at 11 31 57 AM" src="https://user-images.githubusercontent.com/83255730/171477280-b3cac274-48ca-4051-8d05-e2107f84500c.png">

**To Reproduce**
(unknown)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
installed with helm,  think, upgraded via a popup dialogue for lens : 
<img width="256" alt="Screen Shot 2022-06-01 at 11 25 36 AM" src="https://user-images.githubusercontent.com/83255730/171475954-c89a78ab-6b5e-4a14-b708-aef295b16535.png">

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
This has been fixed in version 5.5.2, please upgrade.
