### ISSUE TITLE
Can't connect to any pod's shell on windows 10

### ISSUE THREAD

**Issue by iRyoka** [kontena/lens#5563]
I can connect to a cluster, read logs and do all the general stuff with pods, but whenever I open a pod's shell I only shows 'connecting ...' and nothing ever happens after. The same cluster/config/connection works perfectly fine with a linux version of Lens.

**To Reproduce**
1. open 'pods'
2. open pod's menu and click on 'shell'

**Expected behavior**
functional shell logged into a pod

**Screenshots**
![2022-06-06_12-26-55](https://user-images.githubusercontent.com/795201/172134815-a4563816-6673-46df-8763-de682acdaac2.png)
![2022-06-06_12-26-38](https://user-images.githubusercontent.com/795201/172134819-ea4c9d5a-37ce-4b30-81a8-4500d81aa387.png)

**Environment:**
- Lens Version: 5.4.6 (I had to downgrade since 5.5.* barely works; This problem is still present in 5.5.3 anyways)
- OS: Windows 10
- Installation method: windows installer

**Logs:**
```
info:  Setting Lens as protocol client for lens:// +0ms
info:    Protocol client register succeeded +3ms
info:    [EXTENSIONS-STORE]: LOADING from  ... +6ms
info:    [EXTENSIONS-STORE]: LOADED from C:\Users\Ryoka\AppData\Roaming\Lens\lens-extensions.json +11ms
info:    [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +2ms
info:    [FILESYSTEM-PROVISIONER-STORE]: LOADED from C:\Users\Ryoka\AppData\Roaming\Lens\lens-filesystem-provisioner-store.json +3ms
```

**Kubeconfig:**
(cant' share, but it works fine on linux)

**Additional context**
There are no noticeable errors in 'developer tools' console either. Looks like Lens can't instantiate powershell property. I tried to replace it with C:\winsows\system32\cmd.exe in user settings, but this had no effect at all. The worst is I WAS able to connect to pods in the past with some previous version of Lens/Chrome. My windows updates are disabled so I don't think it has anything to do with powershell version.

**Comment by iRyoka** [comment]
btw, the logs above are obtained already with DEBUG=true

**Comment by Nokel81** [comment]
Possible duplicate of #5305

**Comment by iRyoka** [comment]
Asaics, the problem in issue #5305 was with connecting to a cluster. Here I have a connection established and functional. I only can't connect to pods' shell. I've also looked through the similar issues here and on SO/SE, but the steps offered there like deleting Lens' temporary files didn't work for me.

**Comment by Nokel81** [comment]
Sorry I references the wrong issue. I meant to reference https://github.com/lensapp/lens/issues/5513

**Comment by iRyoka** [comment]
@Nokel81, yep this might be. The difference id that I don't have any errors in logs and Lens version is different.

**Comment by iRyoka** [comment]
More info: recently I noticed that the `console` inside the app behaves the same way. On the other hand, I can run kubectl from PowerShell perfectly fine. Thus, I guess the problem is not with connecting to a cluster, but rather simply with opening a powershell inside of the app.

**Comment by Nokel81** [comment]
Thanks, I think I will close this as a duplicate then.
