### ISSUE TITLE
Lens Kubernetes Extension in Docker Desktop is failing to install in Docker Desktop 4.9.0 for Windows.

### ISSUE THREAD

**Issue by cleygraf** [kontena/lens#5565]
**Describe the bug**
Lens Kubernetes Extension in Docker Desktop is failing to install in DD 4.9.0 for Windows.

**To Reproduce**
Use the "Add Extensions" button, select "Lens" and press "Install" fails repeatedly: A red bar with this message appears: "Failed to install extension: installation could not be completed due to: executing 'docker --context default cp b71b63e7db97aaa36de0ab250fb0ac70b8e10ce203948e17cdbb721a6b229963:/binaries/machine-id-win C:\Users\cleyg\AppData\Roaming\Docker\extensions\k8slens_lens-dd-extension\host' : exit status 1: Error: No such container:path: b71b63e7db97aaa36de0ab250fb0ac70b8e10ce203948e17cdbb721a6b229963:/binaries/machine-id-win"

**Expected behavior**
Successfull install of Lens Extension.

**Environment (please complete the following information):**
- Lens Version: 5.5
- OS: Windows 11 64bit
- Docker Desktop 4.9.0 (latest)

**Comment by jakolehm** [comment]
@cleygraf fix will be available within few hours (once the patch release is available via Docker Hub).

**Comment by cleygraf** [comment]
Thanks for the quick fix! I'm now aible to install Lens Extension in DD!
