### ISSUE TITLE
Cluster connection via forward auth broken

### ISSUE THREAD

**Issue by HartmannVolker** [kontena/lens#5578]
**Describe the bug**
We are using Lens to connect to a K8s cluster secured by pomerium (forward-auth). Since one of the last updates the connection is broken via Lens (other tools like kubectl still work). From the logs of pomerium I can see that Lens is somehow breaks the cluster domain: Our cluster is accessible via `https://auth-domain.com/cluster-name` but Lens is sending the connection requests to `https://auth-domain.com/cluster-name/cluster-name/version`.

So far we are seeing this issue only in the latest versions of Lens. Older version (e.g. 5.4.6) seem to work fine. Do we need to adjust something on our side, or is this a problem in Lens? And is there a way to download older versions of Lens?

**To Reproduce**

**Expected behavior**
Connection to the cluster works fine

**Screenshots**
-

**Environment (please complete the following information):**
- Lens Version: 5.5.3-latest.20220602.2
- OS: OSX

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    server: https://auth-domain.com/cluster-name
  name: cluster-name
contexts:
- context:
    cluster: cluster-name
    namespace: pomerium
    user: via-pomerium
  name: cluster-name
current-context: cluster-name
kind: Config
preferences: {}
users:
- name: via-pomerium
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - k8s
      - exec-credential
      - https://auth-domain.com
      command: pomerium-cli
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false


**Additional context**
Add any other context about the problem here.

**Comment by WolfspiritM** [comment]
Probably fixed in next version https://github.com/lensapp/lens/issues/5455 PR https://github.com/lensapp/lens/pull/5550

**Comment by Nokel81** [comment]
Yes @WolfspiritM is correct. 5.5.4 will be released this week.

**Comment by HartmannVolker** [comment]
Thanks a lot for the fast response! You are doing a great job, love to use the tool ❤️
