### ISSUE TITLE
Can't connect to no cluster after upgrade lens to lastest version (5.5.3)

### ISSUE THREAD

**Issue by huckandduck** [kontena/lens#5579]
After I was upgrade my lens to the latest version (5.5.3) I can no longer connect to any cluster.
 I got an Error message:
**Invalid credentials**
This problem happen to another people of my team.
Important notes:
- Os - Windows 11
- No proxy exiting in my case.

if i downgrade 5.4.6 this is working as well.

**Comment by konstantin-tkachuk** [comment]
I see a similar problem on my installation. Though in my case I cannot connect to clusters that have a socks proxy specified in the kubeconfig (kubectl works fine). Result is **Invalid credentials**. On Mac.

**Comment by WolfspiritM** [comment]
This is a known issue and should be fixed with the next version as far as I can see
https://github.com/lensapp/lens/issues/5455
