### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by nergalex** [kontena/lens#5595]
**Describe the bug**
When I use attached kubeconfig file (private key removed) 
[kubeconfig.txt](https://github.com/lensapp/lens/files/8873293/kubeconfig.txt), Lens raises an error
![Lens_error](https://user-images.githubusercontent.com/42298083/172926876-17f541b3-9761-4697-895d-cd6ba71d0e65.png)
Using kubeconfig file with kubectl, it works fine.
It worked with a previous version of Lens (19 April).

Could I access to a previous version of Lens for Windows please?

**Environment (please complete the following information):**
- Lens Version: 5.5.3.20220602.2
- OS: Windows 10 Enterprise 21H1 19043.1706
- Installation method: Lens Setup 5.5.3-latest.20220602.2.exe

**Comment by robross0606** [comment]
I am having the exact same problem.  Using the same `kubeconfigs` that I've always used with Lens, anything past 5.4.6 will not connect to my cluster.  Here is a screenshot of the two running side-by-side using the exact same set of `kubeconfig` documents:
![image](https://user-images.githubusercontent.com/2965467/173051635-fc444ad5-fd81-4e75-95d0-7254995b7829.png)

**Comment by robross0606** [comment]
I see this message in the OpenLens 5.53. Developer Console that I do not see on the fully functional Lens 5.4.6:
```
system-ca.ts:99 [WIN-CA]: Error injecting root CAs from Windows. Invalid package C:\Program Files\OpenLens\resources\electron.asar
injectSystemCAs @ system-ca.ts:99
```

I also see this in the OpenLens log files stored under my App profile:
```
info: [CLUSTER]: activate {"accessible":false,"disconnected":true,"id":"99ed1afa3e8437962eacb650aba2798c","name":"nur-int-01","online":false,"ready":false}
info: [CLUSTER]: bind events {"accessible":false,"disconnected":true,"id":"99ed1afa3e8437962eacb650aba2798c","name":"nur-int-01","online":false,"ready":false}
info: [CLUSTER]: reconnect {"accessible":false,"disconnected":true,"id":"99ed1afa3e8437962eacb650aba2798c","name":"nur-int-01","online":false,"ready":false}
error: [CLUSTER]: Failed to connect to "int": StatusCodeError: 404 - {"paths":["/apis","/apis/","/apis/apiextensions.k8s.io","/apis/apiextensions.k8s.io/v1","/apis/apiextensions.k8s.io/v1beta1","/healthz","/healthz/etcd","/healthz/log","/healthz/ping","/healthz/poststarthook/crd-informer-synced","/healthz/poststarthook/generic-apiserver-start-informers","/healthz/poststarthook/priority-and-fairness-config-consumer","/healthz/poststarthook/priority-and-fairness-filter","/healthz/poststarthook/start-apiextensions-controllers","/healthz/poststarthook/start-apiextensions-informers","/livez","/livez/etcd","/livez/log","/livez/ping","/livez/poststarthook/crd-informer-synced","/livez/poststarthook/generic-apiserver-start-informers","/livez/poststarthook/priority-and-fairness-config-consumer","/livez/poststarthook/priority-and-fairness-filter","/livez/poststarthook/start-apiextensions-controllers","/livez/poststarthook/start-apiextensions-informers","/metrics","/openapi/v2","/readyz","/readyz/etcd","/readyz/informer-sync","/readyz/log","/readyz/ping","/readyz/poststarthook/crd-informer-synced","/readyz/poststarthook/generic-apiserver-start-informers","/readyz/poststarthook/priority-and-fairness-config-consumer","/readyz/poststarthook/priority-and-fairness-filter","/readyz/poststarthook/start-apiextensions-controllers","/readyz/poststarthook/start-apiextensions-informers","/readyz/shutdown","/version"]}
```

Whereas on Lens 5.4.6 I just see this:
```
info: [CLUSTER]: refresh {"id":"a416fb2e17af0338d8aeabcc01edfa69","name":"nur-int-01","ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Comment by WolfspiritM** [comment]
https://github.com/lensapp/lens/issues/5455 https://github.com/lensapp/lens/issues/5578 https://github.com/lensapp/lens/issues/5579
PR: https://github.com/lensapp/lens/pull/5550

Fixed in next version (I'm also waiting for this to land hopefully together with a FINALLY skipable login page...)

**Comment by Nokel81** [comment]
5.5.4 has landed.
