### ISSUE TITLE
Resource quotas not showing properly MacOS 

### ISSUE THREAD

**Issue by mandowar** [kontena/lens#5598]
**Describe the bug**

**To Reproduce**
1. Pick a GKE Anthos cluster
2. Go to Config -> Resource Quotas, pick one
3. In the right panel, where it shows the info, check the Quotas bars
4. The memory quotas bars are bad scaled, it is comparing Mi againt Gi, thus showing usage ratios of tenth of thousands % and full bars
5. It's comparing different units of a magnitude as if where the same, Gi and Mi as 1 to 1, where it is  1 Gi to 1000 Mi.  So it's showing that 8349Mi is greater than 22Gi. It happens for both, requests memory and limits memory

**Expected behavior**
The metrics are properly evaluated despite the unit. So 1 Gi is 1000 times greater than 1 Mi.

**Screenshots**
![image](https://user-images.githubusercontent.com/102676707/173018377-7880b1b0-38bd-4b5f-ad10-194bf0e969f2.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.5.3-latest.20220602.2
- OS: [e.g. OSX]  MacOS Monterrey 12.4 (21F79)
- Installation method (e.g. snap or AppImage in Linux): Chocolatey, then autoupdate

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
Has this been fixed in 5.5.4?
