### ISSUE TITLE
Item list is empty

### ISSUE THREAD

**Issue by airzhe** [kontena/lens#5608]
**Describe the bug**
Add k8s config and delete item
After adding it, it will prompt Item list is empty
But you can see in Preferences

**Screenshots**
<img width="502" alt="截屏2022-06-13 下午7 25 17" src="https://user-images.githubusercontent.com/5414949/173344087-93a2ad13-e582-4704-83d5-6f396af24cb8.png">

**Environment (please complete the following information):**
- OS:  mac m1

**Comment by Nokel81** [comment]
Could you post a video of what you are seeing?

**Comment by airzhe** [comment]
video: https://youtu.be/RAOStmmFpcc

How can I reset lens，Wouldn't that be better?

**Comment by Nokel81** [comment]
I see thanks for the video. So I would assume that Lens does not think that file has any valid contexts defined in it. 

If you quit Lens from the tray icon and then run `/Applications/Lens.app/Contents/MacOS/Lens` in a terminal, can you post any log lines that have the `[KUBECONFIG-SYNC]:` prefix?

**Comment by paulo-henrique-carguero** [comment]
I'm having the same problem, running through the terminal I'm getting this log below:

![image](https://user-images.githubusercontent.com/102828390/173638456-3bed7e3c-d833-42fe-bfe9-625a0aeb3c93.png)

**Comment by Nokel81** [comment]
@paulo-henrique-carguero Can you do the same but with `DEBUG=true` enabled please?

**Comment by airzhe** [comment]
It's mine：

<img width="1440" alt="截屏2022-06-15 上午11 04 39" src="https://user-images.githubusercontent.com/5414949/173728147-924c7983-7fed-4651-a4df-9d23c9eb52dc.png">

**Comment by airzhe** [comment]
@Nokel81  i find the question:
lens add kubeconfig file, and format this file, modified the contexts field to empty array 
so cause this problem

my contexts field:

```
contexts:
- context:
    cluster: cls-***
    user: "100****37"
  name: cls***-context-default
```

**Comment by Nokel81** [comment]
@airzhe Thanks, unfortunately our default log formatter sometimes uses multiple lines so I am missing some information from that screenshot above.

Though it does look like at least one of your sync files has a valid context.

If you look at the file that contains that context, does the file also have the associated `user` and `cluster` fields?

**Comment by airzhe** [comment]
What I mean is that the lens modifies the kubeconfig file and causes the contexts field to be lost, the lens should not modify the kubeconfig file

**Comment by Nokel81** [comment]
I agree, and the code doesn't look like it modifies the code so this is rather serious.

**Comment by Nokel81** [comment]
So if you are seeing that your files are being modified, this is a duplicate of https://github.com/lensapp/lens/issues/3368 or at least related.

**Comment by airzhe** [comment]
I think it's because of this action, it prompts to delete the context, I don't know if this is normal or a bug

<img width="1097" alt="截屏2022-06-16 上午10 45 47" src="https://user-images.githubusercontent.com/5414949/173980120-68d08c0b-cd62-4000-a65b-b7c259affccc.png">

**Comment by Nokel81** [comment]
No, that is very much supposed to modify the file. It even says that it will remove the context from a specific path.

**Comment by airzhe** [comment]
Well, then I have an answer to my question, and I turned off this issue
