### ISSUE TITLE
Add Host column to Pods list of DaemonSet flyout

### ISSUE THREAD

**Issue by jcogilvie** [kontena/lens#5612]
**What would you like to be added**:
Please add a column in the Pods list of the DaemonSet flyout to indicate which host (node) every ds pod belongs to.  

**Why is this needed**:
A DaemonSet is expected to run once on every host, therefore *which* host a pod belongs to is a first-class piece of information when looking at the Pods list in the overview of a DaemonSet.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: OSX

**Comment by krlosmederos** [comment]
Hi @Nokel81, I would like to work on this task.

**Comment by Nokel81** [comment]
@krlosmederos Sure go ahead

**Comment by krlosmederos** [comment]
Hi @Nokel81, this table (pod list) is used in different views. Can I add this column and show it in every view that renders a pod list (whole app), or do I have to differentiate when the table is rendered by the daemon set's view and only show it there?

![CleanShot 2022-08-09 at 10 47 58](https://user-images.githubusercontent.com/7034429/183680207-9f7be341-6923-4ed0-ab47-a7cf45b8d1ea.png)

**Comment by Nokel81** [comment]
I think everywhere should be fine.
