### ISSUE TITLE
Update copyright year?

### ISSUE THREAD

**Issue by rittneje** [kontena/lens#5622]
There are a few places in the source code that say "(c) 2021 OpenLens Authors" or "© 2021 OpenLens Authors". Is that supposed to be updated?

https://github.com/lensapp/lens/blob/dc1f1ab7f8376474f1167477f8ad612d7de2b0df/src/extensions/npm/extensions/package.json#L6
https://github.com/lensapp/lens/blob/dc1f1ab7f8376474f1167477f8ad612d7de2b0df/LICENSE#L1
https://github.com/lensapp/lens/blob/dc1f1ab7f8376474f1167477f8ad612d7de2b0df/package.json#L8

Also a few files don't have copyright years at all.

https://github.com/lensapp/lens/blob/dc1f1ab7f8376474f1167477f8ad612d7de2b0df/src/common/system-ca.ts#L2
https://github.com/lensapp/lens/blob/dc1f1ab7f8376474f1167477f8ad612d7de2b0df/src/common/protocol-handler/router.ts#L2

IANAL, just wanted to raise the question.

**Comment by Nokel81** [comment]
Yes we should.
