### ISSUE TITLE
Preserved text in search field

### ISSUE THREAD

**Issue by riwarek** [kontena/lens#5625]
**What would you like to be added**:
Search text should be preserved after tab has been switched (eg. from pods to deployments).

**Why is this needed**:
Because when I switch the tabs I have to type filtered text over and over again.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] have no idea
- Desktop OS: Ubuntu

**Comment by Nokel81** [comment]
Duplicate of #3510
