### ISSUE TITLE
Can't open shell in Rancher clusters in 5.5.4

### ISSUE THREAD

**Issue by jason-hobbs** [kontena/lens#5628]
I have this problem with with Rancher clusters.  When I try to open a shell from a pod on a rancher cluster I get:
<img width="310" alt="Screen Shot 2022-06-13 at 9 36 22 PM" src="https://user-images.githubusercontent.com/8509501/173481764-6b0e5692-73ee-4685-bc5b-7c7ea2a354bd.png">

Any non rancher cluster works fine.  

Here is the log:
```
info: [SHELL-SESSION]: shell has exited for 0da0e43917925facc7bd1dc7a4e2d0cd:3a952ed3-4928-4b1d-ae14-0ec768dc8fa3 closed with exitcode=1
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"0da0e43917925facc7bd1dc7a4e2d0cd","name":"stage-new","online":true,"ready":true}
info: [SHELL-SESSION]: websocket for 0da0e43917925facc7bd1dc7a4e2d0cd:3a952ed3-4928-4b1d-ae14-0ec768dc8fa3 closed with code=NormalClosure(1000) {"cluster":{"accessible":true,"disconnected":false,"id":"0da0e43917925facc7bd1dc7a4e2d0cd","name":"stage-new","online":true,"ready":true}}
```

_Originally posted by @jason-hobbs in https://github.com/lensapp/lens/issues/5513#issuecomment-1154644872_

**Comment by Julescastro** [comment]
Same issue here..
