### ISSUE TITLE
Feature request/idea: Back button on Resource View

### ISSUE THREAD

**Issue by lukjaw** [kontena/lens#5638]
Hi! 

Great job with the tool we are using it on a daily basis for managing our k8s workloads! 

I have one idea / feature request. Would be great if there was a Back button on the resource view panel. For example we click on the Deployment, under deployment we click on Replicas, then under replicas we click on Pods, then under pod for example we click Secrets to see the monuted secrets, and then it would be nice to have some Back button to go to the previous shown resource without having to find them again in the workloads list. 

Sth like that: 

We click on the Deployment to view it in the resource panel:

![deployment](https://user-images.githubusercontent.com/18211802/173812056-09d8e78e-26c7-4f98-a9cb-177596317076.png)

Then we click on one of the Pods under that deployment: 

![pod with back button](https://user-images.githubusercontent.com/18211802/173812107-1f35c76a-30d6-4935-a85f-eeaae8e50fb8.png)

And we can simply go back to the previously viewed resource by clicking the Back button (visualisation of the button highlighted in red)

Keep up the good work guys and have a great day !

**Comment by jakolehm** [comment]
@lukjaw Lens already has a back button on top-left (near "home" button).

<img width="187" alt="image" src="https://user-images.githubusercontent.com/1446224/173815845-d07f5e32-f82a-4559-be65-8240fd0796f2.png">

**Comment by lukjaw** [comment]
@jakolehm oh great to know that i am blind ;) thanks, closing
