### ISSUE TITLE
Unable to exec shell in pod since latest update

### ISSUE THREAD

**Issue by burl** [kontena/lens#5658]
**Describe the bug**
Since last auto-update, no longer able to exec a shell into *remote* k8s clusters
* I'm on a Mac, and using my local docker-desktop cluster everything is still fine
* the remote clusters that I can not exec shells in are otherwise working for all other Lens operations

**Note:** i've changed ip addresses, usernames, etc. below for security reasons

**To Reproduce**
1. connect to remote cluster
2. find my pod
3. click on `⋮` and select `Shell`

**Expected behavior**
* expect shell session to ensue, as it does when using local docker-desktop cluster, or with previous version of Lens

**Screenshots**
## output when trying to launch shell
```text
hostname$ exec kubectl exec -i -t -n my-cluster mypod -c mypod-container -- sh -c "clear; (bash || ash || sh)"
error: unable to upgrade connection: error dialing backend: read tcp 192.168.33.17:55466->1.2.3.4:443: read: connection reset by peer
Terminal will auto-close in 15 seconds ...
```

**Environment (please complete the following information):**
- Lens Version:  5.5.4-latest.20220609.2
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): downloaded from [lens](https://k8slens.dev/) - and has received updates

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

## lens log output during above error:
* from `~/Library/Logs/Lens/lens.log`

```text
info: \[SHELL-SESSION]: PTY for a17bfc53877ce764aca4498dd3d18c6c:dbee8fb7-a315-4512-9203-c1de1fd4a6d3 is started with PID=57137
info: \[SHELL-SESSION]: shell has exited for a17bfc53877ce764aca4498dd3d18c6c:dbee8fb7-a315-4512-9203-c1de1fd4a6d3 closed with exitcode=1
```

## lens debug logs
```text
debug:   ▪ Set kubectl version 1.21.9 for cluster version v1.21.7 using version map +4s
debug:   ▪ Acquired a lock for 1.21.9 +565ms
debug:   ▪ Local kubectl is version 1.21.9 +885ms
debug:   ▪ \[KUBECTL]: Releasing lock for 1.21.9 +0ms
info:    ▪ [SHELL-SESSION]: PTY for a17bfc53877ce764aca4498dd3d18c6c:c6121cdb-ad3b-49e5-bfc5-db06764df75c is started with PID=63128 +591ms
debug:   ┏ E0616 07:42:08.227421   62324 proxy_server.go:147] Error while proxying request: error dialing backend: read tcp 192.168.33.17:56893->1.2.3.4:443: read: connection reset by peer
 +4s
debug:   ┃ \[ 1] {
debug:   ┃ \[ 2]   isError: true,
debug:   ┃ \[ 3]   meta: {
debug:   ┃ \[ 4]     id: 'a17bfc53877ce764aca4498dd3d18c6c',
debug:   ┃ \[ 5]     name: 'my-cluster',
debug:   ┃ \[ 6]     ready: true,
debug:   ┃ \[ 7]     online: true,
debug:   ┃ \[ 8]     accessible: true,
debug:   ┃ \[ 9]     disconnected: false
debug:   ┃ \[10]   }
debug:   ┗ [11] }
info:    ▪ [SHELL-SESSION]: shell has exited for a17bfc53877ce764aca4498dd3d18c6c:c6121cdb-ad3b-49e5-bfc5-db06764df75c closed with exitcode=1 +22ms
```

## ps output showing lens processes
```text
username$ ps auwx | grep lens
username      95473   0.0  0.0  5058308  21880   ??  S     5:58AM   0:04.61 /Applications/Lens.app/Contents/Resources/x64/lens-k8s-proxy
username      42638   0.0  0.0  4427128    864 s002  S+    7:28AM   0:00.00 grep lens
```

## KUBECONFIG envvar set by lens when launching shell for exec
```text
KUBECONFIG=/var/folders/g6/8f9__74151z6sbmwlh0gy1c80000gp/T/kubeconfig-a17bfc53877ce764aca4498dd3d18c6c
```

## netstat showing proxy listening
```text
hostname$ netstat -lan | grep 52851 | grep LISTEN
tcp4       0      0  127.0.0.1.52851        *.*                    LISTEN
```

## proxy is serving 
```text
hostname$ curl http://127.0.0.1:52851/a17bfc53877ce764aca4498dd3d18c6c/version
{
  "major": "1",
  "minor": "21",
  "gitVersion": "v1.21.7",
  "gitCommit": "1f86634ff08f37e54e8bfcd86bc90b61c98f84d4",
  "gitTreeState": "clean",
  "buildDate": "2021-11-17T14:35:38Z",
  "goVersion": "go1.16.10",
  "compiler": "gc",
  "platform": "linux/amd64"
  ```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.

## the actual kubeconfig
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    certificate-authority-data: ""
    server: REDACTED
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-username
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: my-username
  user:
    insecure-skip-tls-verify: true
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

## the kubeconfig usd by lens proxy (from envvar above)

```yaml
apiVersion: v1
kind: Config
preferences: {}
current-context: my-cluster
clusters:
  - name: my-cluster
    cluster:
      server: http://127.0.0.1:52851/a17bfc53877ce764aca4498dd3d18c6c
contexts:
  - name: my-cluster
    context:
      cluster: my-cluster
      user: proxy
users:
  - name: proxy
    user: {}
```

**Additional context**

**Comment by nergalex** [comment]
Quite same issue, difference is the output `Error from server:`
```
> kubectl exec -i -t -n alexis-sentence-non-prod nginx-apigw-7c858f6988-2km2x -c nginx-agent -- sh -c "sh"
Error from server:
```
Kubeconfig:
[kubeconfig.txt](https://github.com/lensapp/lens/files/8922095/kubeconfig.txt)

Using `kubectl `on a Linux client, it is OK:
`kubectl --kubeconfig ./kubeconfig exec -i -t -n alexis-sentence-non-prod nginx-apigw-7c858f6988-2km2x -c nginx-agent -- sh -c "clear; (bash || ash || sh)"`

**Comment by burl** [comment]
Oh, right - I should have mentioned that `I am able connect from my command line just fine` as well.

**Comment by tulanian** [comment]
Same issue on fedora v5.5.4

**Comment by Nokel81** [comment]
Related to https://github.com/lensapp/lens/issues/5628

**Comment by Nokel81** [comment]
@nergalex Is that the output within Lens?

**Comment by Nokel81** [comment]
Reproduce with a slightly different error

![Screen Shot 2022-06-17 at 2 06 56 PM](https://user-images.githubusercontent.com/8225332/174353901-d1630454-c407-4031-b5c8-be30bb91e8c0.png)

**Comment by nergalex** [comment]
> 

Yes `Error from server:` is the output from Lens
