### ISSUE TITLE
Pod tolerations number layout bug

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5659]
Pod tolerations number is sticked to the start of the line, causing text overflow.
<img width="714" alt="tolerations number bug" src="https://user-images.githubusercontent.com/9607060/174118399-838a2fa4-e6f8-4869-8e59-0e4f92162af6.png">

**Comment by aleksfront** [comment]
Presented only in https://github.com/lensapp/lens/pull/5642

**Comment by delaskoff** [comment]
Seems like this one is still here
<img width="804" alt="Screenshot 2024-03-05 at 13 18 08" src="https://github.com/lensapp/lens/assets/26123204/d9479d60-2f61-4c03-9832-216f9ce7501c">
