### ISSUE TITLE
Can't port forward a service with Lens on macOS

### ISSUE THREAD

**Issue by caoimhebyrne** [kontena/lens#5663]
**Describe the bug**
Since the latest update of Lens (`Lens-5.5.4-latest.20220609.2-arm64`), port forwarding fails no matter how you configure it.

**To Reproduce**
1. Open a cluster
2. Go to `Network` and then `Services`
3. Click on a service
4. Attempt to port forward, any settings - it doesn't matter, it will fail no matter what

**Expected behavior**
Port forwarding should succeed

**Screenshots**
<img width="973" alt="image" src="https://user-images.githubusercontent.com/71222289/174280865-c73a4420-4cd5-408d-8656-333ba8c3af81.png">

**Environment (please complete the following information):**
- Lens Version: 5.5.4-latest.20220609.2
- OS: macOS Monterey 12.4
- Installation method (e.g. snap or AppImage in Linux): DMG

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: Creating a new port-forward <redacted>:80
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"<redacted>","name":"<redacted>","online":true,"ready":true}
warn: [getPortFrom]: failed to retrieve port via /^forwarding from (?<address>.+) ->/i: 
error: [PORT-FORWARD-ROUTE]: failed to open a port-forward: Error: failed to retrieve port from stream {"namespace":"e<redacted>","port":80,"resourceName":"<redacted>","resourceType":"service"}
error: [PORT-FORWARD-ROUTE]: error stopping a port-forward {"forwardPort":0,"namespace":"<redacted>","port":80,"resourceName":"<redacted>","resourceType":"service"}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
clusters:
- name: "cluster"
  cluster:
    server: "<redacted>"

users:
- name: "cluster"
  user:
    token: "<redacted>"


contexts:
- name: "cluster"
  context:
    user: "cluster"
    cluster: "cluster"

current-context: "cluster"
```

**Additional context**
I was able to port forward on one of the previous releases of Lens, `Lens-5.4.6-latest.20220428.1-arm64`.

**Comment by jim-docker** [comment]
I can't reproduce on an intel mac, with local minikube cluster (port forwarding works as expected). From the log it looks like Lens cannot get a port from your local machine. Does port-forwarding work if you try to do it using `kubectl port-forward` directly in a terminal?

e.g. if you have Lens metrics installed in your cluster you can try 
```
kubectl port-forward service/prometheus -n lens-metrics :80
```

**Comment by tulanian** [comment]
Same problem on fedora 5.5.4. kubectl port-forward with the same kubeconfig works fine.

**Comment by caoimhebyrne** [comment]
@jim-docker Yep, `kubectl port-forward` works fine.

**Comment by jim-docker** [comment]
Are you behind a corporate proxy?

Did you enable debug when you ran from the terminal? (`DEBUG=TRUE /Applications/Lens.app/Contents/MacOS/Lens`). There may be more logs about the `kubectl port-forward` process that Lens runs.

**Comment by caoimhebyrne** [comment]
There's no proxy. I'll run it in debug again later and post the logs.

**Comment by yeldeeb** [comment]
Same with Mac. Working fine with **kubectl port-forward**?

**Comment by AlexisDucastel** [comment]
Same problem here.

The very same kubeconfig used in lens and with kubectl is working with cli kubectl port-forward, but fails with lens.
```
# kubectl cli port-foward works
> k port-forward -n default svc/helloworld 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
^C
>
```

Lens error (and yes, the port 8080 is free before to start port-forward with lens) : 
```
Error occurred starting port-forward, the local port 8080 may not be available or the service helloworld may not be reachable
```

The error we do have in lens is much more related to the local port opening with lens rather than the connection with the cluster.

We have this very same problem on Mac OS Monterey 12.4 and Windows 10. 
Lens is version 5.5.4-latest.20220609.2.

**Comment by jim-docker** [comment]
Does it happen with any cluster (minikube, AWS, ...)?

**Comment by AlexisDucastel** [comment]
It happens on following clusters : 
- Scaleway Kapsule cluster
- Rancher managed custom RKE2 cluster
- GKE regional cluster

**Comment by jim-docker** [comment]
If anybody experiencing this can provide logs (from the terminal display) by running this in the terminal it may help:
```
DEBUG=TRUE /Applications/Lens.app/Contents/MacOS/Lens
```

**Comment by caoimhebyrne** [comment]
Do you still need some debug logs @jim-docker?

**Comment by jim-docker** [comment]
> Do you still need some debug logs @jim-docker?

Thanks, no. It should be fixed in the next release.
