### ISSUE TITLE
Unable to connect to my K8s Cluster w/ latest Arm MACOS version

### ISSUE THREAD

**Issue by imoisharma** [kontena/lens#5676]
**Describe the bug**
Unable to connect to my K8s Cluster w/ latest Arm MACOS version

**To Reproduce**
1. Go to 'https://k8slens.dev'
2. Click on 'MAC OS ARM dmg'
3. Install it and try to connect any cluster.
```
0620 12:07:36.282503 87787 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

```

Till far I have only seen this error when my `aws cli` is installed via `homebrew` not as binary.

**Comment by Nokel81** [comment]
Is your `aws` cli in your PATH? If you are using homebrew did you `brew link`?

**Comment by begd001** [comment]
Hello!

Which version of Lens are you using?

I got the same error today on my Mac M1. I just reinstalled lens to the latest version (5.5.4) and everything is working now!

Good luck

**Comment by imoisharma** [comment]
@Nokel81 it is an issue w/ `aws` installing via brew. I have only experience w/ this issues since last two stable version of M1. I didn't face this issue earlier. To resolve the issue, I need to install `aws cli` via original documentation as native binary way
from here: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

And, it resolved the issue. FYI @begd001

**Comment by Nokel81** [comment]
The homebrew install should work as we try and update the environment variables from the default configured shell.

**Comment by denraf** [comment]
I have the same problem, where Lens is not respecting any PATH settings. The full path has to be configured in the kubeconfig.
PATH is shown correctly inside the Lens Terminal.

**Comment by dserodio** [comment]
Same problem here: aws-cli installed via Homebrew at `/usr/local/bin/aws`, and Lens' Terminal shows that `$PATH` contains `/usr/local/bin`, so it should work. After reading denraf's comment above, I updated my ~/.kube/config to use the full path and now it's working.

**Comment by imoisharma** [comment]
Closing this issue w/ this solution: https://github.com/lensapp/lens/issues/5676#issuecomment-1161025616

**Comment by cig0** [comment]
Hi,

I stumbled open this issue today with `OpenLens v6.5.2`; I disagree with the proposed solutions.

In my case, I install AWS - and most of my CLI tools - with the Nix package manager (similar to Homebrew, but different), and the only tool that fails to "see" the `aws` binary is Lens/OpenLens.

I understand that given the variety of ways we have to manage terminal tools, it is only fair that developers can't babysit all of them.

_However_, this kind of issue could be easily avoided by allowing to specify the full path of said tools in the application.

We can already do this with the `kubectl` binary -- why not allow for the same thing with the other external tools OpenLens/Lens depends on?

![image](https://github.com/lensapp/lens/assets/394089/394303b2-b284-4050-a6d1-3871b0b3fc56)
