### ISSUE TITLE
Main window opens too early

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5680]
Tested in dev mode, main window opened while OpenLens still loaded with splash window visible.

https://user-images.githubusercontent.com/9607060/174556068-e662845c-220a-44e7-b0bf-b2b9cf3d6db8.mov

**Comment by aleksfront** [comment]
Maybe related to #5533 and #5324

**Comment by Nokel81** [comment]
FYI I was not able to reproduce this either

**Comment by aleksfront** [comment]
Not reproducible in production environment or by running `make dev`.
