### ISSUE TITLE
Multiple Update notifications after waking Computer from Sleep

### ISSUE THREAD

**Issue by msa0311** [kontena/lens#5688]
Version: Lens: 5.6.0-alpha.2.20220615.1
OS: Mac OS 12.1

After resuming from sleep in the morning I can see 6 notifications telling me about the same update. (list ist scrollable)
![Bildschirmfoto 2022-06-21 um 08 31 53](https://user-images.githubusercontent.com/26629812/174731771-3cfa279a-1dad-41f4-b7d9-ed15e5fb3a1a.png)

**Comment by Nokel81** [comment]
This will be fixed by https://github.com/lensapp/lens/pull/5445
