### ISSUE TITLE
Workloads overview is missing donut graphs if a namespace is empty

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#5706]
**Describe the bug**

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/1446224/175216246-5267eafc-5fc4-478b-a5ff-12be551d5339.png">

**Environment (please complete the following information):**
- Lens Version: 5.6.0-alpha.3 (or master)

**Comment by Nokel81** [comment]
I cannot reproduce. I get empty donut graphs.
