### ISSUE TITLE
Tray icon not visible on GNOME

### ISSUE THREAD

**Issue by ogarcia** [kontena/lens#5713]
The GNOME bar is black and **since version 5.5** the Lens icon is also black, so the icon is not visible in GNOME.
![normal](https://user-images.githubusercontent.com/572924/175252746-80d393c6-655c-4c07-b616-6c09322d44d2.png)

If I activate the active corner to show the GNOME _expose_ it is seen that the icon is there but being black it is impossible to see it in normal operation.
![hot corner active](https://user-images.githubusercontent.com/572924/175253108-40fd6833-af22-44eb-bbbf-91a0816db07b.png)

**Comment by Nokel81** [comment]
I think this was fixed by https://github.com/lensapp/lens/pull/5567 so this should be fixed in 5.6.0

**Comment by ogarcia** [comment]
Yes, I just tested version 5.6.0-alpha.4 and it's fixed now.
