### ISSUE TITLE
Don't try to download an update that has already been downloaded

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#5747]
Currently we check for updates about every 2 hours (and manually). If the user still hasn't updated then the `electron-updater` tries to download the update again. It caches the download (so it completes very quickly) but it still emits events as if it were downloading it fresh.

We should not try to download the update if it is already downloaded so that our internal events will be consistent and will help simplify other implementations.

**Comment by jansav** [comment]
Fixed by #5781
