### ISSUE TITLE
Can't open pod shell after update to 554 from 546

### ISSUE THREAD

**Issue by lishoujun** [kontena/lens#5749]
**Describe the bug**
Can't open pod shell after update to 554 from 546

**To Reproduce**
1. Go to 'Pods'
2. Click on any pod
3. Click on 'Pod shell'
4. See error ‘Error from server:  Terminal will auto-close in 15 seconds ...’

**Expected behavior**
open pod shell

**Screenshots**
![图片](https://user-images.githubusercontent.com/8399413/176191460-89d963dd-2662-40b5-9a0e-2d5d5d0884f9.png)

**Environment (please complete the following information):**
- Lens Version:5.5.4
- OS:  OSX12.4 
- Installation method (e.g. snap or AppImage in Linux):dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
No
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
No
```

**Additional context**
```
I installed both 5.5.4 and 5.4.6, 5.4.6 is fine to open pod shell
```

https://github.com/lensapp/lens/issues/5663

**Comment by Nokel81** [comment]
Is this a rancher cluster?

**Comment by lishoujun** [comment]
> 

Yes   rancher v2.6.3 .

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"66492d8", GitTreeState:"", BuildDate:"2021-08-16T03:38:25Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rverchere** [comment]
Hello,

same issue here with Rancher v2.6.5 (no problem using direct access to the cluster)

**Comment by Nokel81** [comment]
@rverchere Yes thanks, that is what I have been able to reproduce as well.

**Comment by lishoujun** [comment]
maybe duplicate with https://github.com/lensapp/lens/issues/5628

**Comment by lishoujun** [comment]
After update to version 6, all fine~ thanks
