### ISSUE TITLE
Fails to open splash window when opening via lens://

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#5757]
**Describe the bug**
When trying to open Lens using deep linking (via the docker desktop lens extension) the following error dialog is shown instead:

![image (1)](https://user-images.githubusercontent.com/8225332/176519131-9a9a3cc0-90a1-42c7-b3e9-4e48d1d43c41.png)

**To Reproduce**
1. Start Lens
2. Close main window leaving tray icon running
1. Follow https://www.mirantis.com/blog/getting-started-with-the-mirantis-lens-kubernetes-extension-in-docker-desktop?utm_source=Press&utm_medium=Click
1. See error

**Expected behavior**
Lens should open, like it does when the tray icon is not running

**Environment (please complete the following information):**
- Lens Version: v5.5.4
- OS: Windows

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [PROTOCOL ROUTER]: routing lens://extension/lenscloud-lens-extension
info: [PROTOCOL ROUTER]: Extension lenscloud-lens-extension matched
info: [PROTOCOL ROUTER]: No handler found {"extensionName":"lenscloud-lens-extension","url":"lens://extension"}
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
info: [WINDOW-MANAGER]: Main window has reported that it has loaded
error: Loading main window failed { error: {}}
```

**Comment by jansav** [comment]
Code related to starting of application / application window has changed a lot since 5.5.4 so would be good to check if this still happens in 5.6.0 alphas.

**Comment by Nokel81** [comment]
Attempted on 5.6.0-alpha.5 and cannot reproduce, closing.
