### ISSUE TITLE
Helm Charts broken after clicking chart name

### ISSUE THREAD

**Issue by msa0311** [kontena/lens#5765]
With latest alpha (Lens: 5.6.0-alpha.5.2), it seems opening Helm charts results in a crash when clicking the name of the chart in the list. 

![Bildschirmfoto 2022-07-01 um 11 38 08](https://user-images.githubusercontent.com/26629812/176869272-8fa6d8a3-ede8-4e5a-b449-cbb5fac6d6a6.png)

**Comment by jim-docker** [comment]
confirmed that this is fixed by https://github.com/lensapp/lens/pull/5667
