### ISSUE TITLE
Workloads isn't finding anything

### ISSUE THREAD

**Issue by DAndrewShaw** [kontena/lens#5771]
**Describe the bug**
Setting up lens for the first time.
I am able to see all nodes in my environment and the CPU, memory, etc.
But, when I look at workloads it is empty
I can call, via PowerShell, to see all the pods with command below and get results but lens does not find the same info
I know others using the same solution, with same permissions and it is working fine for them so not sure if I'm missing a config option?

kubectl get pods --all-namespaces

**Screenshots**
![image](https://user-images.githubusercontent.com/99270276/176957909-3cc3c2cb-7963-41de-bf45-7a773d37c64c.png)

**Environment (please complete the following information):**
- Lens Version: 5.5.4-latest.20220609.2
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): exe

**Additional context**
Going to Azure Kubernetes Cluster, version 1.21.9

**Comment by Nokel81** [comment]
What namespace(s) did you have selected?

**Comment by DAndrewShaw** [comment]
I found the options you mentioned - thought it was all namespaces by default but it actually was defaulting to one without anything
