### ISSUE TITLE
Fresh install on Windows fails with error "Lens cannot be closed", even though it's not even installed yet

### ISSUE THREAD

**Issue by CrowhopTech** [kontena/lens#5773]
**Describe the bug**
The latest Windows installer (`Lens Setup 5.5.4-latest.20220609.2`, installer md5sum `09c75a71ba773ba182ac1f713b2423f2`) is getting most of the way through according to the progress bar and then skips back a few times, before failing with the dialog box in the screenshots ("Lens cannot be closed. Please close it manually and click Retry to continue.").

Looking through Task Manager I don't see anything immediately related to Lens running other than the installer. Clicking Retry just makes the dialog appear again.

**To Reproduce**
1. Download the latest Windows installer and run it on a system that does not yet have Lens installed
2. Run the installer
3. Let the installer run
4. See the installation fail with the above dialog

**Expected behavior**
The installation should have succeeded.

**Screenshots**
![image](https://user-images.githubusercontent.com/96402405/177019409-2bbfa736-e6aa-49e3-9f30-b54aa0f98dfa.png)

**Environment (please complete the following information):**
- Lens Version: `5.5.4-latest.20220609.2`
- OS: Windows 10 Home, Build `19043.1766`
- Installation method (e.g. snap or AppImage in Linux): Windows installer exe

**Logs:**
N/A

**Kubeconfig:**
N/A

**Additional context**
None

**Comment by jim-docker** [comment]
I haven't been able to reproduce. ~~Did you have a previous version of Lens already installed when trying to install 5.5.4?~~ Did you install for all users or just one user? Did you try restarting your system to see if the problem persists? Maybe it's to do with Windows Home...

Update: installed ok for me on Windows Home as well.

**Comment by CrowhopTech** [comment]
Ah, figured out what the issue was. I noticed later on that I actually had a completely full C:\ drive. Cleared out some space and the installer ran just fine.

Maybe worth adding an "available space" check to the installer to make the error a little clearer, but otherwise now successfully installed for me. Sorry for the false alarm!
