### ISSUE TITLE
Where can I get an alpha package

### ISSUE THREAD

**Issue by lishoujun** [kontena/lens#5780]
**What would you like to be added**:
Hi there, I want to test the mac package before it release , but I don't want to build it from src.
So I want lens add download link for alpha version in Releases page

**Why is this needed**:
I can check the fitness between alpha package and my k8s environment

**Environment you are Lens application on:**

- Kubernetes distribution: Rancher
- Desktop OS: Mac OS

**Comment by Nokel81** [comment]
You can go to user preferences and change the release channel from "stable" to "alpha".

**Comment by lishoujun** [comment]
Thanks
