### ISSUE TITLE
Download Links Not Working

### ISSUE THREAD

**Issue by tripptuttle** [kontena/lens#5785]
**Describe the bug**
On Lens website, the download links don't work.

**To Reproduce**
1. Go to '[Lens Website](https://k8slens.dev).'
2. Click on 'DOWNLOAD LENS DESKTOP'
3. Nothing Happens

**Expected behavior**
For the DMG to download

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by juanalbacar** [comment]
Tried to install it from homebrew but returned a 404 error. Also tried to download it from the website, all arch releases return a 404 error.

`This api.k8slens.dev page can’t be foundNo web page was found for the web address: https://api.k8slens.dev/binaries/latest-arm64.dmg
HTTP ERROR 404`

`This api.k8slens.dev page can’t be foundNo web page was found for the web address: https://api.k8slens.dev/binaries/latest.amd64.deb
HTTP ERROR 404`

**Comment by 0xByteLeon** [comment]
same here,What happened? I just find lens，But can't install it？

**Comment by Nokel81** [comment]
Sorry the website is currently down and our team is working to resolve this.

**Comment by Nokel81** [comment]
This should be resolved now
