### ISSUE TITLE
Pod details crash

### ISSUE THREAD

**Issue by jansav** [kontena/lens#5825]
**Describe the bug**

@msa0311 noticed crash when opening pod details. Crashes only when opening details for first time.

<img width="1119" alt="Screenshot 2022-07-11 at 15 57 33" src="https://user-images.githubusercontent.com/3083083/178274559-1bafc02b-6acc-4e15-b99c-35d0efd8224a.png">

**Comment by msa0311** [comment]
side note: Might be related to some extensions that I have installed.

**Comment by jansav** [comment]
It definitely looks like coming from extension.

**Comment by msa0311** [comment]
Solved: problem was that NODE_ENV was set to "development" for building this binary

**Comment by jansav** [comment]
Background for the future: 

Currently it seems that some extensions have own version of `react-jsx-runtime` in the compiled code. This means that we are relying of extension developer to remember compile with `webpack --mode production` or equivalent (instead of e.g. `webpack --mode development`.) 

In the future, we should prevent extensions of having their own versions of selected dependencies e.g. `react`, `react-jsx-runtime`. 

Also, in some cases we are building the extension from source code which should not be the case. We should let extension do the build because extension might have some `devDependencies` which we don't have that are required for creating the build.
