### ISSUE TITLE
Installing Helm Chart doesn't work properly

### ISSUE THREAD

**Issue by jansav** [kontena/lens#5827]
**Describe the bug**

Issues:

1. Clicking "Install" button results to "Bad Request" notification.
2. Dock tab for doesn't load properly when you have already tried to install some chart (leave dock tab open for it) and try installing second chart.
3. Clicking "View Helm Release" after installing opens the Details for Release but then quickly closes it again. After that any details for releases cannot be opened.
4. In confirmation dialog for deleting release there is missing space between "Remove" and name of release. 
5. Changing version in dock tab for installing chart doesn't work.

**Environment (please complete the following information):**
- Lens Version: 5.6.0-alpha.6.20220706.1
- OS: OSX
- Installation method: Website + auto update

https://user-images.githubusercontent.com/3083083/178434974-6dead347-9277-4511-8fa0-f1a99cd7c9ad.mov

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3083083/178438411-a9e7097c-7a4c-449f-839d-fd1e7f4f730e.png">

**Comment by jim-docker** [comment]
The release details page slides in a few extra times (sometimes it doesn't happen till ~30 seconds later)
Also, after removing a release, the release list gets redrawn a few extra times.

https://user-images.githubusercontent.com/40840436/179886185-12d84259-a518-4d9e-b434-0e908e41191d.mov
