### ISSUE TITLE
Terminal in Lens won't open, stays at Connecting, forever.. after updating to Lens 5.5.4-latest.20220609.2

### ISSUE THREAD

**Issue by lukjaw** [kontena/lens#5828]
**Describe the bug**
When trying to open Terminal in Lens, it just stays at connecting...

The same when trying to launch Pod shell.

**To Reproduce**
1. Open Lens
2. Click + and Terminal Session

**Expected behavior**
Terminal should open

**Screenshots**
![image](https://user-images.githubusercontent.com/18211802/178513091-643f7bf6-663c-4c22-8829-b5efdd43d29f.png)

**Environment (please complete the following information):**
- Lens Version: 
![image](https://user-images.githubusercontent.com/18211802/178513233-dd601486-ba21-430e-9064-b729048e9811.png)

- OS: Windows 10
- Installation method : Installer

**Logs:**
error: [SHELL-SESSION]: failed to open a local shell File not found:  {"stack":"Error: File not found: \n    at new WindowsPtyAgent (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsPtyAgent.js:78:36)\n    at new WindowsTerminal (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\windowsTerminal.js:50:24)\n    at Object.spawn (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\node_modules\\node-pty\\lib\\index.js:28:12)\n    at l.ensureShellProcess (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:317624)\n    at l.openShellProcess (C:\\Users\\xxxxx\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:318256)\n    at async l.open (C:\\xxxxx\\lukjaw\\AppData\\Local\\Programs\\Lens\\resources\\app.asar\\static\\build\\main.js:1:307554)"}

**Kubeconfig:**
Connection to the cluster works fine, the only issue is terminal
```
your kubeconfig here
```

**Additional context**
One weird thing that i saw is that Lens version window shows:
![image](https://user-images.githubusercontent.com/18211802/178514258-a1f41b8e-e392-46d9-a94a-8a6662a6b833.png)
When the actual installed Chrome is:
![image](https://user-images.githubusercontent.com/18211802/178514361-8781bc79-9ee2-4eba-94e5-3d0071d024a9.png)

**Comment by lukjaw** [comment]
The next day when i switched networks (today i was working on corporate network in the office) and now i am working from home using VPN, all is working fine... 

It could be some firewall / proxy related thing ? That on corporate network Lens cannot download some binaries for terminal to work properly ? 

Thanks

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/5870

**Comment by Nefilime** [comment]
![image](https://github.com/user-attachments/assets/95b599c4-aa40-4e5f-a59f-8d6edd1d2df9)
Same on Ubuntu 24 LTS.
Tried apt and snap result the same.
