### ISSUE TITLE
Unable to Connect Pod shell for Arc Enabled Clusters 

### ISSUE THREAD

**Issue by skri547** [kontena/lens#5829]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/68077126/178533164-4c0fbfbf-7280-49ad-8992-39ac09b339ed.png">

**Comment by jim-docker** [comment]
Similar to #5658 and #5628, which may be fixed by #5833

**Comment by skri547** [comment]
@jim-docker  by when this fix will be merged?

**Comment by skri547** [comment]
@jim-docker  can i know by when this will be merged to master?

**Comment by jim-docker** [comment]
#5833 is part of the 6.0.0 alpha (https://github.com/lensapp/lens/pull/5886), which if all goes well could be available in a few hours. @skri547 if you try it, let us know if it fixes this issue.

**Comment by skri547** [comment]
@jim-docker  How can i test this Alpha release? when i clicked for "check for updates" I didnt get anything. Also can i know when this will be part of GA release?

**Comment by avinashdesireddy** [comment]
@skri547 Under app preferences (File > Preferences > Application) you'll have an option to change the "update channel". There are 3 options in there - Stable, Beta & alpha. Please try changing that from Stable to "alpha"

**Comment by skri547** [comment]
@avinashdesireddy  This is working. But when this will be part of the Stable release?

**Comment by skri547** [comment]
cc @jim-docker

**Comment by Nokel81** [comment]
This has been released as part of stable
