### ISSUE TITLE
Not able to connect to cluster

### ISSUE THREAD

**Issue by srishtirox** [kontena/lens#5863]
**Describe the bug**
When trying to connect to cluster it shows below error :

```
SSL validation failed for https://sts.us-east-2.amazonaws.com/ [Errno 2] No such file or directory

E0721 04:05:33.559758 5476 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws failed with exit code 255

getting credentials: exec: executable aws failed with exit code 255
```

**To Reproduce**

**Expected behavior**
It should connect 

**Screenshots**
N/A

**Environment (please complete the following information):**
- Lens Version: 5.3.4
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
> getting credentials: exec: executable aws failed with exit code 255

This means that the `aws` CLI is failing which is why Lens cannot connect.

Does it work fine from the command line? If so, does running lens from the same command line resolve the issue?

**Comment by josue** [comment]
I had the same issue just now. I believe after updating my config via "`aws eks update-kubeconfig ...`", it lost my read permissions for `./kube/config` file. After adding them back it fixed my Lens Desktop.

**Add read permissions back to config file:**
```
chmod +r ~/.kube/config
```

**Comment by Nokel81** [comment]
We also made some fixes to how env sync works. So closing for the time being
