### ISSUE TITLE
Lens loads very long on Fedora 36

### ISSUE THREAD

**Issue by marcinjahn** [kontena/lens#5918]
**Describe the bug**
I installed Lens on Fedora 36 via snap.
Whenever I run Lens, the loading screen stay on the screen for around a minute until the app finally loads up. It is quite long.

**To Reproduce**
1. Just run Lens (from GUI or terminal)

**Expected behavior**
Loading time should be much shorter, in the range of seconds.

**Screenshots**
Not applicable

**Environment (please complete the following information):**
- Lens Version: 5.5.4-latest.20220609.2
- OS: [e.g. OSX] Fedora Linux 36 Workstation x64
- Installation method (e.g. snap or AppImage in Linux): snap

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

Logs when I run the app with `DEBUG=true lens`
```
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
info:    ▪ 📟 Setting Lens as protocol client for lens:// +0ms
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri, suffix _dri)
libGL error: failed to load driver: swrast
[17077:0727/074342.661703:ERROR:angle_platform_impl.cc(44)] Display.cpp:878 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17077:0727/074342.661827:ERROR:gl_surface_egl.cc(780)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17077:0727/074342.661859:ERROR:gl_surface_egl.cc(1375)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[17077:0727/074342.662071:ERROR:angle_platform_impl.cc(44)] Display.cpp:878 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[17077:0727/074342.662100:ERROR:gl_surface_egl.cc(780)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[17077:0727/074342.662121:ERROR:gl_surface_egl.cc(1375)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[17077:0727/074342.662142:ERROR:gl_initializer_linux_x11.cc(178)] GLSurfaceEGL::InitializeOneOff failed.
[17077:0727/074342.662750:ERROR:viz_main_impl.cc(162)] Exiting GPU process due to errors during initialization
info:    ▪ 📟 Protocol client register failed ❗ +11ms
debug:   ▪ [APP-MAIN] configuring packages +1ms
[17087:0727/074342.671982:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
info:    ▪ [EXTENSIONS-STORE]: LOADING from  ... +11ms
info:    ▪ [EXTENSIONS-STORE]: LOADED from /home/marcin/snap/lens/x1/.config/Lens/lens-extensions.json +6ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADING from  ... +5ms
info:    ▪ [FILESYSTEM-PROVISIONER-STORE]: LOADED from /home/marcin/snap/lens/x1/.config/Lens/lens-filesystem-provisioner-store.json +3ms
debug:   ▪ [APP-MAIN] initializing ipc main handlers +3ms
debug:   ▪ [APP-MAIN] Lens protocol routing main +0ms
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: https://53.32.23.32
  name: gke_ci
- cluster:
    certificate-authority-data: [redacted]
    server: https://43.43.43.41
  name: gke_pro
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.3.1.51:6443
  name: onprem-ci
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.2.13.3:6443
  name: onprem-pro
contexts:
- context:
    cluster: gke_ci
    user: gke_ci
  name: gcp-ci
- context:
    cluster: gke_pro
    user: gke_pro
  name: gcp-pro
- context:
    cluster: onprem-ci
    user: onprem-ci-credentials
  name: onprem-ci
- context:
    cluster: onprem-pro
    user: onprem-pro-credentials
  name: onprem-pro
current-context: onprem-ci
kind: Config
preferences: {}
users:
- name: gke_ci
  user:
    auth-provider:
      config:
        access-token: [redacted]
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib64/google-cloud-sdk/bin/gcloud
        expiry: "2022-07-26T14:28:08Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_pro
  user:
    auth-provider:
      config:
        access-token: [redacted]
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib64/google-cloud-sdk/bin/gcloud
        expiry: "2022-07-26T14:28:08Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: onprem-ci-credentials
  user:
    token: [redacted]
- name: onprem-pro-credentials
  user:
    token: [redacted]

```

**Additional context**
None

**Comment by jim-docker** [comment]
Does this still happen in Lens 6.0.0?

**Comment by marcinjahn** [comment]
> Does this still happen in Lens 6.0.0?

Hi, is it available via Snap?

**Comment by marcinjahn** [comment]
Alright, I see it is available on the Lens website. I downloaded it and installed. Unfortunately, there is no improvement in startup. The only difference I noticed at the moment is that when I launch the app, the Loader is the only window that gets opened. Previously, two windows would pop up - the loader and the main window of the app (grey until loader finishes spinning). Now, right after loader finishes doing its thing, the main window appears. No difference in the speed department though.

**Comment by jim-docker** [comment]
Is that the entirety of the logs in the terminal? (last line is `debug:   ▪ [APP-MAIN] Lens protocol routing main +0ms`?)

How did you download it from the Lens site? Did you try the AppImage, and that still gives you the long startup time? (We don't manage/support the snap installer)

**Comment by marcinjahn** [comment]
I downloaded snap from https://api.k8slens.dev/binaries/Lens-6.0.0-latest.20220728.2.amd64.snap, it seems to be official.
I installed AppImage distribution now, it starts much faster! I will use that version from now on.
Yeah, the logs I posted were all I got.

**Comment by jim-docker** [comment]
My mistake, apparently we still release an "unsigned" snap package, but we stopped publishing to the snap store a while ago due to technical reasons. Closing this since you have a workaround. Opening another issue because I found more problems with this package.

**Comment by marcinjahn** [comment]
I suggest looking at flatpak, maybe it would be less problematic than snap?
