### ISSUE TITLE
UI for scaling ReplicaSets 

### ISSUE THREAD

**Issue by jansav** [kontena/lens#5924]
1. Order of +/- buttons is weird
2. Missing space in the header

**Screenshots**
<img width="519" alt="image" src="https://user-images.githubusercontent.com/3083083/181225959-3db11022-cbe5-4c07-a853-0a0e43eb6187.png">

**Comment by krlosmederos** [comment]
Hi @jansav  I would like to work on this issue.

**Comment by jansav** [comment]
> Hi @jansav I would like to work on this issue.

Hey! Thanks, we appreciate it a lot. Ask if you need any help.
