### ISSUE TITLE
HPA list no getting current usage

### ISSUE THREAD

**Issue by rgtoffolo** [kontena/lens#5942]
**Describe the bug**
Lens HPA list is not showing the current resources usage. It is doubling the resource limit.
e.g.: for a deployment configured with 40% average cpu Lens is showing 40%/40% in the HPA list.

**To Reproduce**
1. Go to 'Config'
2. Click on 'HPA'
3. Check list HPA list (column Metrics)

**Expected behavior**
HPA list should show the "current utilization/metric value" in the Metrics column

**Screenshots**
![image](https://user-images.githubusercontent.com/17582729/181615841-1e2e830e-b482-46aa-86c7-79efea9ab139.png)

**Environment (please complete the following information):**
- Lens Version: 6.0.0-Latest-20220728.2
- OS: Windows 11
- Installation method: Lens Auto update

**Comment by bradam12** [comment]
Same here on Mac 12.3.1 with Lens Auto Update, and also deleted and redownloaded app manually.
Lens: 6.0.0-latest.20220728.2

Hitting edit to view the yaml config shows currentMetrics with correct specs.

**Comment by sanidhyam** [comment]
how do I roll back to the previous version?
I can't use this version until this HPA bug is resolved

**Comment by ben5556** [comment]
+1 need this bug fixed

**Comment by seanhamlin** [comment]
Same issue for me, the UI incorrectly reports the current utlisation

<img width="473" alt="image" src="https://user-images.githubusercontent.com/10605846/183525025-5f00956d-1509-44f2-8537-5fa225f9b9a3.png">

Editing the HPA shows the current usage 

```
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        currentAverageUtilization: 10
        currentAverageValue: 2m
```
