### ISSUE TITLE
subscription bug

### ISSUE THREAD

**Issue by maxpain** [kontena/lens#5947]
![image](https://user-images.githubusercontent.com/5875582/181661720-00ccd0bc-34ac-4009-a248-19b9bd08d318.png)

Hello. I bought the annual subscription, but nothing appeared.
My email: m@csgo.com

**Comment by msa0311** [comment]
Hello,

we are really sorry for the circumstances. We identified the problem already and we will reach out to you in a couple of minutes by mail. 

Will close this ticket here because its not the perfect place to discuss this ;-) 

Best Regards,
Mario
