### ISSUE TITLE
Can't connect to the WSL minikube cluster on windows

### ISSUE THREAD

**Issue by Tushar255** [kontena/lens#5953]
I was trying to connect to my local minikube cluster and this error is occuring again and again :-

 **E0729 17:15:41.907846 8512 proxy_server.go:147] Error while proxying request: dial tcp 127.0.0.1:50669: connectex: No connection could be made because the target machine actively refused it.

dial tcp 127.0.0.1:50669: connectex: No connection could be made because the target machine actively refused it.**

![Screenshot (178)](https://user-images.githubusercontent.com/98146176/181752431-75204f03-9257-476e-9085-e1144411b186.png)

Whenever I'm trying to connect it:-

![Screenshot (179)](https://user-images.githubusercontent.com/98146176/181752442-4b25f2b1-7c37-41e9-bcc3-da2ecd6c9918.png)

Then after sometime:-

![Screenshot (180)](https://user-images.githubusercontent.com/98146176/181752443-aa996e29-9b94-4d2b-9365-94cf4e7127ec.png)

Why this error is occuring and how to resolve it?

**Comment by Nokel81** [comment]
Can you access minikube via kubectl? I get this error sometimes after I have rebooted and forgotten to restart minikube

**Comment by Tushar255** [comment]
> Can you access minikube via kubectl? I get this error sometimes after I have rebooted and forgotten to restart minikube

Yes I can access it via kubectl.
See :-

![Screenshot (182)](https://user-images.githubusercontent.com/98146176/181771686-bf147817-36ca-43a3-873b-1e00fcbd9b6d.png)

**Comment by Nokel81** [comment]
That looks like you have minikube running within WSL and not directly within windows. Is that correct?

**Comment by Tushar255** [comment]
Yes! 
Actually when I was running _minikube start_ in Windows Powershell then it was not running.
See :-

![Screenshot (183)](https://user-images.githubusercontent.com/98146176/181789080-8a106648-a8d7-46b8-90ec-0e6be09bcd1a.png)

**Comment by Nokel81** [comment]
Are you able to use `kubectl` in powershell to access the WSL minikube?

**Comment by Tushar255** [comment]
You mean by using this command `kubectl cluster-info` ?

**Comment by Tushar255** [comment]
Issue is solved now, actually I had started the cluster through ubuntu and that's why I was not able manage it via windows.

I've deleted the cluster and then started it via Windows and now it's working.

**Comment by Tushar255** [comment]
Thank you for your help :)
