### ISSUE TITLE
Lens updates frequency

### ISSUE THREAD

**Issue by ghost** [kontena/lens#5963]
Hi,

It's great that lens is constantly improving, but it seems a little bit weird to get an update announcement almost every day while being on stable channel. It makes a negative impression about the stability and distrust in the quality of the product. Lens is a great tool, but it's not a MMORPG game that needs daily content updates.

Please consider to provide either automatic update process in background or rethink how often stable channel should get the updates.

Thanks

**Comment by Nokel81** [comment]
What version are you on? And by "update announcement" what do you mean? In Lens 6 we did a lot of improvements towards auto update and removed all of the notifications.
