### ISSUE TITLE
Version 6.0.0 HPA current stats not showing correctly

### ISSUE THREAD

**Issue by poojamalik02** [kontena/lens#5971]
**Describe the bug**
With version 6.0.0 the current memory / cpu usage for HPA is not correct. My teammate is using 5.4.5 version. The stats are showing correctly there.

**To Reproduce**
For any HPA, using Lens version 6.0.0, compare the current /target memory / cpu values. The tool is showing target as current in the new version.
![image](https://user-images.githubusercontent.com/75506264/182460443-5328d55d-5163-4e1a-92ff-80e7dd4a821d.png)

PFB the screenshot of the stats for the same HPA with Lens tool version 5.4.5
![image](https://user-images.githubusercontent.com/75506264/182461081-08e24467-84d5-4d8b-b7a3-de4910971392.png)

**Expected behavior**
The cpu / memort stats should be correct.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: windows
- Installation method (e.g. snap or AppImage in Linux): download from lens.dev

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by bradam12** [comment]
#5942

**Comment by brandongallagher-tag** [comment]
It's great to hear that I'm not the only one experiencing this.
<img width="158" alt="Screen Shot 2022-08-03 at 10 54 37 AM" src="https://user-images.githubusercontent.com/97307237/182639963-0164767b-9670-4db5-802f-4dfc45b167e3.png">

**Comment by sanidhyam** [comment]
how do I roll back to the previous version?
I can't use this version until this HPA bug is resolved

**Comment by 880831ian** [comment]
me too

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/5942
