### ISSUE TITLE
Auto expand of long elements (eg: image name) no longer works.

### ISSUE THREAD

**Issue by jvandervelden** [kontena/lens#5975]
**Describe the bug**
When the image value for a pod's container is to long to display, an ellipsis is shown (usual behaviour). Before the update to v6, when you click the image value it would expand into multiple lines showing the whole value.

The helper text when hovered doesn't help since it shows the image SHA, and not the image TAG.

**To Reproduce**
1. Go to Pods under workloads and click on a pod
2. Click on the image value

**Expected behavior**
Expands to show the whole value.

**Screenshots**

![image](https://user-images.githubusercontent.com/7331813/182617685-f6ec1678-ee2d-47ee-a26e-1f4a4c42ad0a.png)

Clicking does not show the rest of the value.

![image](https://user-images.githubusercontent.com/7331813/182618179-852c385b-d977-4f03-afcb-6ff58e3d4683.png)

Hovering over the value shows the SHA not the TAG.

**Environment (please complete the following information):**

![image](https://user-images.githubusercontent.com/7331813/182618474-e2b56fe1-0765-41e3-b776-4b447dffecac.png)

- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): MSI

**Additional context**
Hover text always showed the SHA, and clicking the value was the only way to see the deployed TAG.

**Comment by Nokel81** [comment]
This was fixed by #5911
