### ISSUE TITLE
Latest Download Link

### ISSUE THREAD

**Issue by turowicz** [kontena/lens#6005]
Please introduce the following download URL scheme for machine automation so the scripts always install latest Lens on new computers:

`https://discord.com/api/download?platform=linux&format=deb`

We can then go and

`wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb" && dpkg -i discord.deb`

**Comment by jakolehm** [comment]
@turowicz Lens IDE (k8slens.dev) provides an api for this:  `https://api.k8slens.dev/binaries/latest.deb`.

**Comment by turowicz** [comment]
@jakolehm the link returns `FORBIDDEN`.

**Comment by jakolehm** [comment]
@turowicz it should work, just tested the response with curl:
```
curl -I https://api.k8slens.dev/binaries/latest.deb
HTTP/2 302 
x-powered-by: Express
vary: Origin, Accept, Accept-Encoding
location: https://downloads.k8slens.dev/ide/Lens-6.0.1-latest.20220810.2.deb
content-type: text/plain; charset=utf-8
content-length: 88
date: Tue, 16 Aug 2022 10:44:34 GMT
x-envoy-upstream-service-time: 69
server: envoy
```

**Comment by turowicz** [comment]
@jakolehm No it doesn't work, you get a successful redirect but later the request fails:

```
wget https://api.k8slens.dev/binaries/latest.deb
--2022-08-16 12:55:19--  https://api.k8slens.dev/binaries/latest.deb
Resolving api.k8slens.dev (api.k8slens.dev)... 54.78.39.141, 34.248.78.39, 52.208.193.102
Connecting to api.k8slens.dev (api.k8slens.dev)|54.78.39.141|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.k8slens.dev/ide/Lens-6.0.1-latest.20220810.2.deb [following]
--2022-08-16 12:55:19--  https://downloads.k8slens.dev/ide/Lens-6.0.1-latest.20220810.2.deb
Resolving downloads.k8slens.dev (downloads.k8slens.dev)... 18.64.79.17, 18.64.79.103, 18.64.79.69, ...
Connecting to downloads.k8slens.dev (downloads.k8slens.dev)|18.64.79.17|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-08-16 12:55:19 ERROR 403: Forbidden.
```

![image](https://user-images.githubusercontent.com/1055391/184863113-5b38a316-c077-45b3-9ec0-1155a315bb17.png)

**Comment by panuhorsmalahti** [comment]
https://api.k8slens.dev/binaries/latest.amd64.deb should work

**Comment by turowicz** [comment]
@panuhorsmalahti it does 👍🏻
