### ISSUE TITLE
Lens does not display UI on Mac

### ISSUE THREAD

**Issue by urbanoctet** [kontena/lens#6009]
After installing 5.4.6 or 6.0.0 Lens does not open the UI.

I had Lens 4.x working on Mac BigSur 11.6.4.

Uninstalled it, installed 5.4.6 or 6.0.0, but both behave the same way. That is, when launched, the icon bounces in the task bar for a while, stops and nothing happens. The process is left running.

It does not create any files under /Library/Logs/Lens nor /Library/Application Support/Lens

No errors anywhere.

I have removed the kubeconfig file to clear that concern. Not really sure what is expected on the kubectl part.

I have restarted before and after installation also.

Any ideas where I can get more info on what is going on?

I thought it could be a permission issue, because it does not even create the expected directories.

**Environment (please complete the following information):**
- Lens Version: 5.4.6 or 6.0.0
- OS: [e.g. OSX] BigSur 11.6.4
- Installation method (e.g. snap or AppImage in Linux): dmg

**Comment by Nokel81** [comment]
If you installed it normally you should be able to run it from the command line. What happens if you run `﻿﻿/Applications/Lens.app/Contents/MacOS/Lens` in the terminal?

**Comment by urbanoctet** [comment]
I installed it normally. Using the dmg. 

When executed from command line the same thing happens. Only difference is that the process has no icon in Activity Monitor.

**Comment by Nokel81** [comment]
No logs?
