### ISSUE TITLE
lens spins infinitely viewing certain helm releases

### ISSUE THREAD

**Issue by mipearson** [kontena/lens#6031]
**Describe the bug**
Clicking on the details of a helm release causes lens to show the pane and a "loading" spinner infinitely.

Issue is present in 6.0.0 & 6.0.1, but not 5.x.x.

This doesn't occur for all helm releases: it seems specific to helm releases from our internal charts. eg, opening the helm release from a community datadog chart works fine.

The error log below reports that it can't load certain resources, but I can load them just fine with lens if I track down the resource manually (confirmed by opening up `guru-web-app-staging-reverse-proxy-configmap` and viewing its contents). Suspect a namespace issue of some kind ..

The RBAC role in use has no restrictions around secrets, resources, etc.

**To Reproduce**

1. Click on "Helm -> Releases"
2. Click on a release
3. Wait

**Expected behavior**

Helm release information is shown

**Screenshots**

![image](https://user-images.githubusercontent.com/97317/184527133-e62a6f6a-9712-4db9-b4bf-22e2a78b6b9f.png)

**Environment (please complete the following information):**
- Lens Version: OpenLens (6.0.1-latest.1660302598735)
- OS: OSX 12.3.1 ARM
- Installation method: .dmg download from https://github.com/MuhammedKalkan/OpenLens/releases/tag/v6.0.1

Note that I observed this behaviour as well with the 6.0.0 binary downloaded via k8slens.dev.

**Logs:**
```
BrowserConsole.js:41 [KUBE-API] watch (secret-1) started /api/v1/secrets?watch=1&resourceVersion=140771938
BrowserConsole.js:47 Orphan promise rejection encountered JsonApiErrorParsederror: "Error from server (NotFound): serviceaccounts \"guru-web-app\" not found\nError from server (NotFound): configmaps \"guru-web-app-staging-reverse-proxy-configmap\" not found\nError from server (NotFound): services \"guru-web-app\" not found\nError from server (NotFound): deployments.apps \"guru-web-app\" not found\nError from server (NotFound): horizontalpodautoscalers.autoscaling \"guru-web-app\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-internal\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-external\" not found\n"isUsedForNotification: falsemessages: Array(1)0: "Error from server (NotFound): serviceaccounts \"guru-web-app\" not found\nError from server (NotFound): configmaps \"guru-web-app-staging-reverse-proxy-configmap\" not found\nError from server (NotFound): services \"guru-web-app\" not found\nError from server (NotFound): deployments.apps \"guru-web-app\" not found\nError from server (NotFound): horizontalpodautoscalers.autoscaling \"guru-web-app\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-internal\" not found\nError from server (NotFound): ingresses.networking.k8s.io \"guru-web-app-external\" not found\n"length: 1[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}[[Prototype]]: ObjectisAborted: (...)[[Prototype]]: Object
__webpack_modules__.1246.BrowserConsole.log @ BrowserConsole.js:47

```

**Comment by Nokel81** [comment]
Thanks for the bug report, unfortunately your proposed fix doesn't quite work since it will fail to load helm releases that are spread across several namespaces.

Would you be able to provide something similar to "our internal helm charts" for testing?

**Comment by mipearson** [comment]
Create a helm chart that does not specify the namespace in its manifests, then apply it with helm using --namespace on the helm CLI.

Have you confirmed that specifying the namespace with --namespace on kubectl overrides the `namespace:` bit in the manifest itself?

**Comment by mipearson** [comment]
Yep, confirmed with a bit of local testing, with a chart that works with lens 6:

```
the namespace from the provided object "datadog-system" does not match the namespace "default". You must pass '--namespace=datadog-system' to perform this operation.
```

`--all-namespaces` also doesn't work if the namespaces aren't supplied in the manifest:

```
no namespace set on resource /v1, Resource=serviceaccounts "persona-app"
```

Can we roll back to the 5.x behaviour (which was fine, tbh) if namespaces aren't supplied or if the resources aren't otherwise available?

It's a bit off that it just hard locks if the kubectl invocation doesn't work :(

**Comment by mipearson** [comment]
Cooked up a workaround in the above PR & confirmed it locally with our charts: the resources don't display, but at least it doesn't break the client when trying to view a release.

Also realised that this bug could manifest in a different way: if you roll out a helm release, and then remove one of its resources outside of helm (ie: drift), you'd get the same issue regardless of namespaces as the resource wouldn't be found.

Could also potentially be the problem described at https://k8slens.slack.com/archives/C1U90NQN8/p1660579038627939 - if you're viewing a release mid-deployment and the resources don't actually exist yet.

**Comment by darkpixel** [comment]
I think I'm hitting the same issue.
If a release is in the 'default' namespace, I can open it.
If it's in any other namespace, it just spins.

**Comment by Nokel81** [comment]
@darkpixel Would you mind sharing which helm chart you tried to install?

**Comment by darkpixel** [comment]
Sure.   One is "chatwoot" and another is "rocketchat" from their respective repos:

```
https://chatwoot.github.io/charts
https://rocketchat.github.io/helm-charts
```

**Comment by panteparak** [comment]
I too experiencing this problem. The chart that i used is Rook Ceph.
`https://charts.rook.io/release`

Do note that the version that is currently deploy is `1.8.3` for `rook-ceph` and `rook-ceph-cluster`

**Comment by boothb** [comment]
If still of value here is the chart that is producing the same problem in my case.

`https://helm.traefik.io/traefik`

Other charts are taking a bit long but working.

**Comment by sd-f** [comment]
Feedback to fix https://github.com/lensapp/lens/pull/6088. Everything seems to work with namespace support! Thanks to @jansav. Looking forward to release.
