### ISSUE TITLE
Cannot check for updates

### ISSUE THREAD

**Issue by cachila** [kontena/lens#6062]
**Describe the bug**
When clicking the **Lens** -> **Check for updates** nothing happens. Nothing shows up at the Network / Console tab.

**To Reproduce**
1. Go to **Lens** -> **Check for updates**
2. Check nothing happens

**Expected behavior**
Either a _No updates available_  or _Update available_ appears.

**Environment (please complete the following information):**
- Lens Version: 6.0.1-latest.20220810.2
- OS: OSX 12.4
- Installation method: Installed from .dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Not really sure how to do this.
```

**Comment by Nokel81** [comment]
Does the tray menu icon change when you check for updates?

**Comment by cachila** [comment]
Yes, it does for a really short time. Hadn't paid attention to it before.

**Comment by Nokel81** [comment]
Okay so the checking for updates does seem to function correctly. We made some changes to the UX to make checking for updates less obnoxious, especially on startup.

**Comment by teebu** [comment]
I switched from Stable to Alpha and nothing happens.

**Comment by Nokel81** [comment]
What version are you currently on @teebu? If you are on 6.0.1 then that also wouldn't do anything because there is no current alpha release.

**Comment by teebu** [comment]
Latest Stable 6.0.1. I guess there is no Beta either.

**Comment by Nokel81** [comment]
Not currently no
