### ISSUE TITLE
Lens 6.0.1 and Windows 7

### ISSUE THREAD

**Issue by sebjan44** [kontena/lens#6064]
**Describe the bug**
Since the update to version 6.0.1 of Lens, I no longer have the "Shell" and "Logs" menus.

The complete reinstallation from the executable does not change anything.

Is this latest version still compatible with Windows 7?

**Screenshots**
These menus have disappeared
<img width="85" alt="Lens6" src="https://user-images.githubusercontent.com/111515910/185623137-a8184d72-4757-4a4a-84fc-db960e8dcb0a.png">

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX] : Windows 7
- Installation method (e.g. snap or AppImage in Linux): update first (from 5.5.4) then EXE

**Comment by Nokel81** [comment]
Yes the latest version is compatible with windows 7. If you quit lens from the tray menu and run it via powershell do you see any logs about failing to load the extensions? 

Another option would be to delete the `%appdata%\Lens\node_modules` folder while Lens is not running, does that solve this issue?

**Comment by sebjan44** [comment]
Hello Nokel81

Via Powershell, some errors :

_←[31merror←[39m:   ←[31m←[2mÔöÅ←[22m←[0m ←[0m[EXTENSIONS-LOADER]: activation extension error←[3m←[2m +302ms←[22m←[23m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  1]←[22m {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  2]←[22m   ext: {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  3]←[22m     id: ←[32m'C:\\Users\\USER\\AppData\\Roaming\\Lens\\node_modules\\lens-desktop-kube-lens-extension\\package.json'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  4]←[22m     absolutePath: ←[32m'D:\\Lens\\resources\\extensions\\lens-desktop-kube-lens-extension\\lens-desktop-kube-lens-extension-6.0.1-l
atest.20220810.2.tgz'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  5]←[22m     manifestPath: ←[32m'C:\\Users\\USER\\AppData\\Roaming\\Lens\\node_modules\\lens-desktop-kube-lens-extension\\package.json'←
[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  6]←[22m     manifest: {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  7]←[22m       name: ←[32m'lens-desktop-kube-lens-extension'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  8]←[22m       version: ←[32m'6.0.1-latest.20220810.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[  9]←[22m       description: ←[32m'Lens Desktop Kube'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 10]←[22m       main: ←[32m'dist/main.js'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 11]←[22m       renderer: ←[32m'dist/renderer.js'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 12]←[22m       files: [ ←[32m'dist/'←[39m, ←[32m'lima.tar.gz'←[39m, ←[32m'lens-vm-lima.yaml'←[39m, ←[32m'lens-vm-wsl.json'←[39m ],
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 13]←[22m       engines: { lens: ←[32m'^6.0.0'←[39m, node: ←[32m'>=14 <17'←[39m },
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 14]←[22m       scripts: {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 15]←[22m         prestart: ←[32m'npm run download-lima'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 16]←[22m         start: ←[32m'npm run start:dev'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 17]←[22m         ←[32m'start:dev'←[39m: ←[32m'webpack --watch'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 18]←[22m         prepack: ←[32m'run-script-os'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 19]←[22m         ←[32m'prepack:default'←[39m: ←[32m'exit 0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 20]←[22m         ←[32m'prepack:darwin'←[39m: ←[32m'if [ ! -z ${CSC_LINK} ]; then ./scripts/codesign ; fi && tar -czv -f lima.tar.gz lima'←[3
9m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 21]←[22m         build: ←[32m'npm run clean && npm run webpack && npm run download-lima && npm pack'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 22]←[22m         ←[32m'download-lima'←[39m: ←[32m'run-script-os'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 23]←[22m         ←[32m'download-lima:default'←[39m: ←[32m'exit 0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 24]←[22m         ←[32m'download-lima:darwin'←[39m: ←[32m'npm run download-lima:darwin-amd64 && npm run download-lima:darwin-arm64'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 25]←[22m         ←[32m'download-lima:darwin-amd64'←[39m: ←[32m'bash -c "[[ -f ./lima/x64/bin/limactl ]]" || (mkdir -p lima/x64 && cd lima/x6
4 && curl -slL https://github.com/rancher-sandbox/lima-and-qemu/releases/download/v1.24/lima-and-qemu.macos.tar.gz | tar -xz)'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 26]←[22m         ←[32m'download-lima:darwin-arm64'←[39m: ←[32m'bash -c "[[ -f ./lima/arm64/bin/limactl ]]" || (mkdir -p lima/arm64 && cd lim
a/arm64 && curl -slL https://github.com/rancher-sandbox/lima-and-qemu/releases/download/v1.24/lima-and-qemu.macos-aarch64.tar.gz | tar -xz)'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 27]←[22m         ←[32m'download-lima:linux'←[39m: ←[32m'bash -c "[[ -f ./lima/x64/bin/limactl ]]" || (mkdir -p lima/x64 && cd lima/x64 && cu
rl -slL https://github.com/rancher-sandbox/lima-and-qemu/releases/download/v1.24/lima-and-qemu.linux.tar.gz | tar -xz)'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 28]←[22m         ←[32m'postdownload-lima'←[39m: ←[32m'run-script-os'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 29]←[22m         ←[32m'postdownload-lima:default'←[39m: ←[32m'exit 0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 30]←[22m         ←[32m'postdownload-lima:darwin:linux'←[39m: ←[32m'tar -czv -f lima.tar.gz lima'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 31]←[22m         clean: ←[32m'rm -rf lima* && rm -rf dist'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 32]←[22m         webpack: ←[32m'webpack'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 33]←[22m         lint: ←[32m'eslint --ext ts,tsx --max-warnings=0 .'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 34]←[22m         ←[32m'lint:fix'←[39m: ←[32m'npm run lint -- --fix'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 35]←[22m         prettier: ←[32m'prettier --check "**/*.{js,ts,tsx}"'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 36]←[22m         ←[32m'prettier:fix'←[39m: ←[32m'prettier --write "**/*.{js,ts,tsx}"'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 37]←[22m         ←[32m'check:type'←[39m: ←[32m'tsc -p tsconfig.json --noEmit'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 38]←[22m         test: ←[32m'jest'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 39]←[22m         ←[32m'test:watch'←[39m: ←[32m'npm run test -- --watch'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 40]←[22m         limactl: ←[32m'./scripts/limactl'←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 41]←[22m       },
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 42]←[22m       author: ←[32m'Mirantis Inc'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 43]←[22m       license: ←[32m'UNLICENSED'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 44]←[22m       devDependencies: {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 45]←[22m         ←[32m'@emotion/react'←[39m: ←[32m'^11.8.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 46]←[22m         ←[32m'@emotion/styled'←[39m: ←[32m'^11.8.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 47]←[22m         ←[32m'@k8slens/extensions'←[39m: ←[32m'file:../../src/extensions/npm/extensions'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 48]←[22m         ←[32m'@k8slens/lens-platform-extension-sdk'←[39m: ←[32m'2.0.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 49]←[22m         ←[32m'@swc/core'←[39m: ←[32m'^1.2.163'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 50]←[22m         ←[32m'@swc/jest'←[39m: ←[32m'^0.2.20'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 51]←[22m         ←[32m'@testing-library/dom'←[39m: ←[32m'^8.13.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 52]←[22m         ←[32m'@testing-library/jest-dom'←[39m: ←[32m'^5.14.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 53]←[22m         ←[32m'@testing-library/react'←[39m: ←[32m'^12.1.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 54]←[22m         ←[32m'@types/checksum'←[39m: ←[32m'^0.1.33'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 55]←[22m         ←[32m'@types/decompress'←[39m: ←[32m'^4.2.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 56]←[22m         ←[32m'@types/jest'←[39m: ←[32m'^27.4.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 57]←[22m         ←[32m'@types/js-yaml'←[39m: ←[32m'^4.0.5'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 58]←[22m         ←[32m'@types/lodash'←[39m: ←[32m'^4.14.182'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 59]←[22m         ←[32m'@types/node'←[39m: ←[32m'^14.16.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 60]←[22m         ←[32m'@typescript-eslint/eslint-plugin'←[39m: ←[32m'^5.17.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 61]←[22m         ←[32m'@typescript-eslint/parser'←[39m: ←[32m'^5.6.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 62]←[22m         checksum: ←[32m'^1.0.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 63]←[22m         conf: ←[32m'^7.1.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 64]←[22m         decompress: ←[32m'^4.2.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 65]←[22m         electron: ←[32m'^15.5.7'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 66]←[22m         eol: ←[32m'^0.9.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 67]←[22m         eslint: ←[32m'^8.11.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 68]←[22m         ←[32m'eslint-config-airbnb'←[39m: ←[32m'^19.0.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 69]←[22m         ←[32m'eslint-config-prettier'←[39m: ←[32m'^8.5.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 70]←[22m         ←[32m'eslint-import-resolver-typescript'←[39m: ←[32m'^3.1.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 71]←[22m         ←[32m'eslint-plugin-import'←[39m: ←[32m'^2.25.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 72]←[22m         ←[32m'eslint-plugin-jsx-a11y'←[39m: ←[32m'^6.5.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 73]←[22m         ←[32m'eslint-plugin-prettier'←[39m: ←[32m'^4.0.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 74]←[22m         ←[32m'eslint-plugin-react'←[39m: ←[32m'^7.29.4'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 75]←[22m         ←[32m'eslint-plugin-react-hooks'←[39m: ←[32m'^4.3.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 76]←[22m         ←[32m'eslint-plugin-unused-imports'←[39m: ←[32m'^2.0.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 77]←[22m         got: ←[32m'^11.8.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 78]←[22m         ←[32m'human-format'←[39m: ←[32m'^1.0.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 79]←[22m         jest: ←[32m'^27.5.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 80]←[22m         ←[32m'js-yaml'←[39m: ←[32m'^4.1.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 81]←[22m         lodash: ←[32m'^4.17.21'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 82]←[22m         mobx: ←[32m'^6.5.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 83]←[22m         ←[32m'mobx-react'←[39m: ←[32m'^7.3.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 84]←[22m         prettier: ←[32m'^2.5.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 85]←[22m         react: ←[32m'^17.0.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 86]←[22m         ←[32m'react-dom'←[39m: ←[32m'^17.0.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 87]←[22m         ←[32m'run-script-os'←[39m: ←[32m'^1.1.6'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 88]←[22m         ←[32m'swc-loader'←[39m: ←[32m'^0.1.15'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 89]←[22m         systeminformation: ←[32m'^5.12.2'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 90]←[22m         tempy: ←[32m'1.0.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 91]←[22m         ←[32m'ts-loader'←[39m: ←[32m'^8.0.14'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 92]←[22m         ←[32m'tsconfig-paths-webpack-plugin'←[39m: ←[32m'^3.5.1'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 93]←[22m         typescript: ←[32m'^4.6.3'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 94]←[22m         webpack: ←[32m'^5.72.0'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 95]←[22m         ←[32m'webpack-cli'←[39m: ←[32m'^4.9.2'←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 96]←[22m       }
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 97]←[22m     },
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 98]←[22m     isBundled: ←[33mtrue←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[ 99]←[22m     isEnabled: ←[33mtrue←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[100]←[22m     isCompatible: ←[33mtrue←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[101]←[22m   },
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[102]←[22m   error: Error: spawn wsl.exe ENOENT
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[103]←[22m   ←[90m    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[104]←[22m   ←[90m    at onErrorNT (node:internal/child_process:480:16)←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[105]←[22m   ←[90m    at processTicksAndRejections (node:internal/process/task_queues:83:21)←[39m {
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[106]←[22m     errno: ←[33m-4058←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[107]←[22m     code: ←[32m'ENOENT'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[108]←[22m     syscall: ←[32m'spawn wsl.exe'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[109]←[22m     path: ←[32m'wsl.exe'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[110]←[22m     spawnargs: [ ←[32m'--list'←[39m, ←[32m'--verbose'←[39m, ←[32m'--all'←[39m ],
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[111]←[22m     cmd: ←[32m'wsl.exe --list --verbose --all'←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[112]←[22m     stdout: ←[32m''←[39m,
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[113]←[22m     stderr: ←[32m''←[39m
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöâ←[22m←[0m ←[0m←[2m[114]←[22m   }
←[2m←[31merror←[39m←[22m:   ←[31m←[2mÔöù←[22m←[0m ←[0m←[2m[115]←[22m }_

Unfortunately, delete the %appdata%\Lens\node_modules folder while Lens is not running, not solve this issue.

**Comment by Nokel81** [comment]
In that same powershell window what does `spawn wsl.exe` do?

**Comment by sebjan44** [comment]
Hello
command spawn is unknown

+ spawn <<<<  wsl.exe
    + CategoryInfo          : ObjectNotFound: (spawn:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Nokel81** [comment]
If you reinstall lens does this issue go away?

**Comment by Nokel81** [comment]
This has been resolved with the latest release by how we bundled extensions.
