### ISSUE TITLE
Lens create space forebidden resource

### ISSUE THREAD

**Issue by m-dbr** [kontena/lens#6087]
Hello,
Im not sure why I get ,,forbidden resorce'' after I want create space when connecting to a specific cluster

![image](https://user-images.githubusercontent.com/42658277/186109679-1b1490f5-93bc-49fc-a29e-b10c31d4c4cb.png)

**Comment by ntrehout** [comment]
Same here ! 

Lens: 6.0.1-latest.20220810.2
Electron: 15.5.7
Chrome: 94.0.4606.81
Node: 16.5.0

**Comment by Preen** [comment]
+1
