### ISSUE TITLE
Can't see the Shell or logs in Pods menu

### ISSUE THREAD

**Issue by hk-toucha** [kontena/lens#6097]
**Describe the bug**
From the Pods's ... menu, there is no options for Shell or Logs.

**To Reproduce**
1. Go to Pods dots menu '...'
2. There is no options for Attach Pod, Shell and Logs

Tried a couple of times of the following but still have the same problem
a. uninstall the Lens 
b. remove the %appdata%/Roaming/Lens, %appdata%\Local\Program\Lens and C:\Users\<user>\.k8slens
c. re-install Lens

**Expected behavior**
The Attach Pod, Shell and Logs should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/21221528/186479233-d30acd86-523e-4fb0-be5d-b8a6de02af3a.png)

**Environment (please complete the following information):**
- Lens Version: 
![image](https://user-images.githubusercontent.com/21221528/186479726-8848041f-4303-4d21-bb5a-4a14c71c0bff.png)

- OS: [e.g. OSX] Windows 11
- Installation method (e.g. snap or AppImage in Linux): "Downloads\Lens Setup 6.0.1-latest.20220810.2.exe"

**Additional context**
I can confirm there is no error in loading the lens-pods-menu extension
![image](https://user-images.githubusercontent.com/21221528/186480864-47ee5716-c514-4ede-9f22-50128877d049.png)

**Comment by Nokel81** [comment]
Thanks for the report. This is interesting, so the extensions are enabled but then not used...

**Comment by skakkar** [comment]
similar issue is happening on MAC OS - Monterey

**Comment by CarlosDomingues** [comment]
I'm also having this issue in Windows 11.

![lens](https://user-images.githubusercontent.com/11181378/193667668-e73dc223-8bf4-43e4-908d-f3bb584a6837.png)

**Comment by Nokel81** [comment]
@CarlosDomingues If you run Lens from the command line, do you see any errors?

**Comment by CarlosDomingues** [comment]
@Nokel81 no errors

**Comment by Nokel81** [comment]
Can you open up the dev tools and filter the console for `[EXTENSION]: enabled`? How many entries do you see? Does it include `lens-pod-menu`?

**Comment by CarlosDomingues** [comment]
It does not include `lens-pod-menu`. Here's the entire list:

![lens2](https://user-images.githubusercontent.com/11181378/193695546-f1269a3a-3cb9-4ac5-b621-b0167460e359.png)

**Comment by skakkar** [comment]
After the latest update of LENS (Mac OS Monterey) it's working for me.

Thank you
*~Sachin*

**Comment by Nokel81** [comment]
@CarlosDomingues Interesting, you shouldn't have both 6.0.1 and 6.0.2 versions... If you clear out `%AppData%/Lens/node_modules` after quitting Lens from the tray menu and then restarting, does that fix the issue?

**Comment by CarlosDomingues** [comment]
@Nokel81 I reinstalled Lens earlier and the issue is gone.

**Comment by Nokel81** [comment]
We are working to make sure this won't happen in the future. But thanks for reporting back anyway.
