### ISSUE TITLE
Visual Bug - White Square

### ISSUE THREAD

**Issue by ofirsalem1** [kontena/lens#6123]
![image](https://user-images.githubusercontent.com/89575154/187080500-3b3a3d0b-93e1-4756-9b8f-c989439fc8ba.png)

**Comment by nrao-optumserve** [comment]
We suddenly see this too. Not sure if it's trying to connect to some HTTP endpoint but our Lens sits in a heavily locked / restricted environment with no egress network access.

**Comment by aleksfront** [comment]
Duplicate of #6069. Partially fixed in 6.0.2. since iframes would have transparent background.
