### ISSUE TITLE
When editing HPA on a k8s 1.24 cluster, instead of autoscaling/v2 editor shows autoscaling/v2beta1

### ISSUE THREAD

**Issue by galtonova** [kontena/lens#6168]
When editing HPA on a k8s 1.24 cluster, editor shows `autoscaling/v2beta1` instead of `autoscaling/v2`. However if I run `kubectl edit` autoscaling/v2 is shown correctly. Big issue is, autoscaling/v2 has some extra fields and when converted to autoscaling/v2beta1, they are lost (eg. behavior field of HPA)

**To Reproduce**
- On a kubernetes 1.24+ cluster go to Config > HPA
- From the three dot menu or from detail page, click Edit
- You will see autoscaling/v2beta1

**Expected behavior**
YAML in the editor should be autoscaling/v2

**Environment (please complete the following information):**
- Lens Version: 6.0.1-latest.20220810.2
- OS: OSX 12.5.1 M1 Pro

**Comment by Nokel81** [comment]
closed by #4406

**Comment by Nokel81** [comment]
Removing since the above is more of an enhancement request. The proper fix for this is to update which API versions we auto pick from.

**Comment by Nokel81** [comment]
And the fix will also have to include supporting the older beta forms as well.
