### ISSUE TITLE
Unable to connect to my K8s Cluster 

### ISSUE THREAD

**Issue by PeterPetrov1517** [kontena/lens#6238]
Describe the bug
Unable to connect to my K8s Cluster 

To Reproduce

Go to 'https://k8slens.dev/'
Install it and try to connect any cluster.

See error
```
0620 12:07:36.282503 87787 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

**Comment by jim-docker** [comment]
Did you try restarting your computer? https://github.com/lensapp/lens/issues/5672#issuecomment-1206550387

**Comment by Nokel81** [comment]
Do you ever see a notification about failing to sync shell env?

**Comment by PeterPetrov1517** [comment]
Yes.

**Comment by Nokel81** [comment]
What platform are you on? Can you provide log files?

**Comment by PeterPetrov1517** [comment]
This happens on both clusters I have. They are production clusters. I did everything right - use aws config and aws eks commands.
<img width="868" alt="Screenshot 2022-10-04 090424" src="https://user-images.githubusercontent.com/110815108/193746218-a166c1a2-ae6a-4f97-a476-69ee7ac2704c.png">

**Comment by Shivankur25** [comment]
re-check your config file

**Comment by A13xs** [comment]
Try downloading [kubelogin](https://github.com/Azure/kubelogin) and putting it in the lens installation folder.

**Comment by erickD83** [comment]
I had the same issue while connecting to AKS cluster in azure, but after updating the lens version to "6.1.12" today, I was able to connect to the cluster again. I also used `kubelogin` in macos.

**Comment by YevheniiPokhvalii** [comment]
Re-installation of Lens helped.

**Comment by Nokel81** [comment]
Thanks. I will close this issue as I think we have resolved it with recent bug fixes

**Comment by izi-p** [comment]
> Try downloading [kubelogin](https://github.com/Azure/kubelogin) and putting it in the lens installation folder.

I confirm that installing kubelogin fixed the issue for me

**Comment by michaelmeirsman** [comment]
Under Windows I had to put kubelogin.exe in C:\Program Files\Lens\resources\cli\bin to make it work

**Comment by cpwood** [comment]
I also had to put kubelogin.exe in C:\Program Files\Lens\resources\cli\bin to make it work. Additionally, I needed to completely kill off Lens in Task Manager and restart it for it to start working.
