### ISSUE TITLE
Lens does not see CronJobs in a Kind cluster

### ISSUE THREAD

**Issue by victor-sudakov** [kontena/lens#6245]
**Describe the bug**
`kubectl get cronjobs.batch` shows a cron job present, but in the Lens GUI, in the same namespace, I see "Cron Jobs (0)" and an orange triangle with "The server could not find the requested resource" message.

**To Reproduce**
Install Kind v0.15.0 (uses the kindest/node:v1.25.0 image)
Install Lens 6.0.1
Create a Kind cluster with default parameters.
Connect to the cluster from Lens and see the orange triangle with the error message.

**Expected behavior**
Lens should show Cron Jobs and should not show the error.

**Environment (please complete the following information):**
- Lens Version:  6.0.1-latest.20220810.2-20220810.2
- OS: Ubuntu 22.04.1 LTS
- Installation method (e.g. snap or AppImage in Linux): Deb package (lens/now 6.0.1-latest.20220810.2-20220810.2 amd64)
- Kubernetes in Kind: 
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0

**Screenshot**
![lens1](https://user-images.githubusercontent.com/12457866/190068918-60472787-e30d-4940-b1d1-712f3f4416d4.png)

**Workaround**
Create a Kind cluster with `--image kindest/node:v1.24.4` . There is probably some incompatibility of Lens with  kindest/node:v1.25.0, but kubectl works all right.

**Comment by hufon** [comment]
In fact cronjob are now in batch/v1 api version in old k8s version it was batch/v1beta.
Source of the problem : https://github.com/lensapp/lens/blob/bab1b1331762696cbe89a63c20638582d66785da/src/common/k8s-api/endpoints/cron-job.api.ts#L76

**Comment by victor-sudakov** [comment]
I always use in the manifest:
```
apiVersion: batch/v1
kind: CronJob
```
both in Kind 1.24 and 1.25

**Comment by PurpleBooth** [comment]
> I always use in the manifest:
> 
> ```
> apiVersion: batch/v1
> kind: CronJob
> ```
> 
> both in Kind 1.24 and 1.25

Yup, and those get translated to a URL when calling kubernetes, so lens is calling '/apis/batch/v1beta1/cronjobs' which doesn't exist in 1.25, it should be calling '/apis/batch/v1/cronjobs'

**Comment by orsted-stto** [comment]
I have this issue as well. Lens version 5.5.0-beta. Is this something that can only be fixed by updating Lens version?
