### ISSUE TITLE
v6 UI is very slow compared with v5 ui, 

### ISSUE THREAD

**Issue by IJOL** [kontena/lens#6248]
The UI takes seconds to respond to ANY interaction, wherever  the place, object menus, general menu, object tabs... it takes seconds to respond  just used v5 for many months maybe years, and worked quickly and flawlessly for years.....

I use Ubuntu 20.04 gnome i could up some screncasts for the issue, but they are bigger than admitted here, i'm trying to upload them at any suitable place, i will add url later if asked for..

**Comment by petergaultney** [comment]
agreed. in particular, our cluster frequently goes from an 'idle' state (~50 pods) to a 'busy' state (hundreds or thousands of pods), and Lens goes from being totally usable to completely unusable when the cluster gets busy. It was not previously like this.

**Comment by lagnat** [comment]
6.0.1 is fine.  6.0.2 is where the problem was introduced.

**Comment by samar-elsayed** [comment]
does anyone know where I can download 6.0.1 ?

**Comment by lagnat** [comment]
https://api.k8slens.dev/binaries/Lens-6.0.1-latest.20220810.2.dmg
https://api.k8slens.dev/binaries/Lens%20Setup%206.0.1-latest.20220810.2.exe

**Comment by lujiajing1126** [comment]
> https://api.k8slens.dev/binaries/Lens-6.0.1-latest.20220810.2.dmg https://api.k8slens.dev/binaries/Lens%20Setup%206.0.1-latest.20220810.2.exe

Thanks for the links. But how to disable auto update?

**Comment by IJOL** [comment]
Well, glad to see people agreeing with the issue, but i must add that i see this behaviour with a pretty small number of pods, and in a very very stable cluster that runs smoothly but with only about 200 pods and doesn't have a great deal of activity, mostly stable pods that runs for days if not weeks, and a set of backups and batch jobs very small, that runs in a cron setting every few hours, a very modest cluster i must say..

**Comment by IJOL** [comment]
i've tried to download the v6.0.1 but i did find the deb version from the posted urls...

**Comment by IJOL** [comment]
Confirmed, 6.0.1 does not behaves bad, UI continues to be responsive ten minutes after loading, as an aside 6.0.2 didnt have problems just after start the problems developed after having the app open for a few minutes  but not at start, 6.0.1 doesnt seem to have the same problems, i routinely have lens opened throughout days if not months... sooo

**Comment by esatterwhite** [comment]
I can confirm. 6.0.2-latest.20220908.1 is virtually unusable. I've gone back to using kubectl commands.

**Comment by thehung111** [comment]
yep same for me, 6.0.2 totally freezes everything

**Comment by esatterwhite** [comment]
related #6247

**Comment by n3wc** [comment]
can confirm 6.0.2 is unusable by downgrading to 6.0.1 (really appreciate the links) it works again. this is on a 1000+ pod cluster
edit: i'm using a mac

**Comment by esatterwhite** [comment]
related #6265

**Comment by esatterwhite** [comment]
On linux (arch) there doesn't seem to be a way to run a previous version easily. The appimage auto updates to the most recent. And I could not get the snap image to install without errors.

**Comment by lagnat** [comment]
You might try to remove write access to the app.  That works on macOS to stop the auto-updater.

**Comment by esatterwhite** [comment]
Can the lens folks just make the last release the `latest` release. This one is currently unstable and shouldn't be put in front of end users.

**Comment by panuhorsmalahti** [comment]
This is likely duplicate of https://github.com/lensapp/lens/issues/6265. Fix is being worked on.

**Comment by panuhorsmalahti** [comment]
`2022.9.231310-alpha` is now available with a fix. It can be updated if "Update Channel" in App Preferences is set to "Alpha". Can you try if it resolves the issue?

**Comment by kuldeepjain** [comment]
@panuhorsmalahti I just updated to `2022.9.231310-alpha`, it does not help. On connecting to Cluster the UI is still frozen.

**Comment by panuhorsmalahti** [comment]
@kuldeepjain do you have a large number of pods? What about the number of different images in the pods? And was Lens 6.0.0/6.0.1 fast for you, but 6.0.2 slow?

**Comment by esatterwhite** [comment]
Production clusters have upwards of

* 500 nodes
* 10,000 pods 2-3 images / containers per pod
* 200 images

**Comment by panuhorsmalahti** [comment]
Can you try `2022.9.271220-alpha` release available in the alpha channel?

**Comment by chrisxaustin** [comment]
The performance is truly terrible for me now. If I leave Lens running for a few hours then any click takes 5+ seconds to register, e.g. clicking into the search bar under pods doesn't even register for awhile, which means I need to restart it several times a day. My cluster has 66 nodes and 866 pods currently.

This is on a macbook w/ m1max and 64g ram.

**Comment by panuhorsmalahti** [comment]
Can you try again with the latest release?

**Comment by chrisxaustin** [comment]
> Can you try again with the latest release?

It seems much better today so far.

**Comment by CaueP** [comment]
> Can you try again with the latest release?

I just updated to `2022.10.181357-latest` and it is much better!

**Comment by Nokel81** [comment]
Closing as we also just fixed a memory leak
