### ISSUE TITLE
Web compilation error after bumping lens and k8lens/extension latest version

### ISSUE THREAD

**Issue by pmdawood** [kontena/lens#6256]
**Describe the bug**
Web compilation error after bumping lens and k8lens/extension latest version

i have bumped the version
```
-  “@k8slens/extensions”: “5.4.4",
+  “@k8slens/extensions”: “6.0.2",
“engines”: {
-  “lens”: “^5.0.0”
+  “lens”: “^6.0.0”
  }
```

after compilation i am getting the following errors

```
ERROR in ui/lens/node_modules/@k8slens/extensions/dist/src/main/catalog/entity-registry.d.ts
  [tsl] ERROR in ui/lens/node_modules/@k8slens/extensions/dist/src/main/catalog/entity-registry.d.ts(5,15)
     TS1005: ‘,’ expected.
  ERROR in lens/node_modules/@k8slens/extensions/dist/src/main/catalog/entity-registry.d.ts
  [tsl] ERROR lens/node_modules/@k8slens/extensions/dist/src/main/catalog/entity-registry.d.ts(5,36)
     TS1005: ‘,’ expected.
  ERROR in ui/lens/node_modules/@k8slens/extensions/dist/src/extensions/renderer-api/components.d.ts
  [tsl] ERROR in ui/lens/node_modules/@k8slens/extensions/dist/src/extensions/renderer-api/components.d.ts(42,29)
     TS1005: ‘,’ expected.
    import { type IComputedValue, type IObservableArray } from “mobx”;  - > entity-registry.d.ts(5,15) - throwing error saying ‘,’ expected 
```

**To Reproduce**
 bump the version in package.json
```
-  “@k8slens/extensions”: “5.4.4",
+  “@k8slens/extensions”: “6.0.2",
“engines”: {
-  “lens”: “^5.0.0”
+  “lens”: “^6.0.0”
  }
```
and run the webpack command
**Expected behavior**
should compile successfully and generate dist folder with renderer.js and main.js

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.0.2
- OS: MAC
- Installation method (e.g. snap or AppImage in Linux): auto upgrade from 5.4.4. to 6.0.2

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by Nokel81** [comment]
You need to also upgrade your typescript version to something greater than 4.5 (https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names)
