### ISSUE TITLE
Lens 6.0.2 freeze on pod list display

### ISSUE THREAD

**Issue by uplg** [kontena/lens#6265]
**Describe the bug**
While connecting to an EKS Cluster (other clusters works great), overview loads, but if I go to pods or somewhere else, the cluster iframe gets stuck and I can't do anything except disconnect / reconnect (and freeze again).

I tried to use "OpenLens" (checking out master (6.1.0 alpha) or v6.0.2) it works fine (compile with yarn run build:mac => output mac-arm64 arch bin)

I also tried with @jim-docker on Slack to disable team work on Lens (6.0.2-latest), nothing changes, still get frozen.

I get some "ipcRenderer.invoke timeouts" and Abort errors in the console.

If I break while cluster iframe is frozen, it breaks into the screenshot given below.

**To Reproduce**
1. Go to the cluster
2. Click on pods

(Might be related to arm64, I use a Mac Studio with an M1 Max)

**Expected behavior**
Pod list showing up and no freeze

**Screenshots**

![Screenshot 2022-09-16 at 18 04 45](https://user-images.githubusercontent.com/5880133/190687213-64dbda56-b76c-455d-9e39-95e174d1a458.png)

**Environment :**
- Lens Version: 6.0.2-latest.20220908.1
- OS: macOS Monterey 12.6
- Installation method : brew cask

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Checking for update
info:    ▪ [KUBECONFIG-SYNC]: starting requested syncs +490ms
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +1ms
info:    ┗ [1] { filePath: '/Users/leonard/Library/Application Support/Lens/kubeconfigs' }
info:    ┏ [KUBECONFIG-SYNC]: starting sync of file/folder +0ms
info:    ┗ [1] { filePath: '/Users/leonard/.kube' }
info:    ▪ [KUBECONFIG-SYNC]: ignoring '/Users/leonard/Library/Application Support/Lens/kubeconfigs/.DS_Store' due to ignore glob: .DS_Store +1ms
Update for version 6.0.2-latest.20220908.1 is not available (latest version: 6.0.2-latest.20220908.1, downgrade is disallowed).
info:    ┏ [CLUSTER]: activate +4s
info:    ┃ [1] {
info:    ┃ [2]   id: 'xx',
info:    ┃ [3]   name: 'arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: bind events +0ms
info:    ┃ [1] {
info:    ┃ [2]   id: 'xx',
info:    ┃ [3]   name: 'arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ┏ [CLUSTER]: reconnect +1ms
info:    ┃ [1] {
info:    ┃ [2]   id: 'xx',
info:    ┃ [3]   name: 'arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1',
info:    ┃ [4]   ready: false,
info:    ┃ [5]   online: false,
info:    ┃ [6]   accessible: false,
info:    ┃ [7]   disconnected: true
info:    ┗ [8] }
info:    ▪ [KUBE-AUTH-PROXY]: found port=55435 +24ms
[ELECTRON-SYNC-STORE]: 2022-09-16T16:38:15.116Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-09-16T16:38:15.116Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2022-09-16T16:38:15.117Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ▪ [CONTEXT-HANDLER]: using operator as prometheus provider for clusterId=04a7ef928f5ddbd35a3d8ad6840296ff +1s
info:    ┏ [CLUSTER]: refresh +29s
info:    ┃ [1] {
info:    ┃ [2]   id: 'xx',
info:    ┃ [3]   name: 'arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: xxx
      server: https://eks.amazonaws.com/
    name: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
contexts:
  - context:
      cluster: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
      user: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
    name: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
current-context: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:eu-central-1:cluster/k8s-eu-central-1
    user: {token: longtoken}
```

**Additional context**

**Comment by antoineandrieu** [comment]
Getting the same error with an x86_64 proc.

**Comment by akashkrishnan** [comment]
Same. UI is very slow now.

**Comment by Joldnine** [comment]
Same issue. Very slow and not usable with 10k pods.

**Comment by lujiajing1126** [comment]
It's strange. Everything works fine if I build v6.0.2 tag by myself.

Similar environment as @m1m1s1ku on Mac Studio w/ M1 Ultra.

**Comment by lujiajing1126** [comment]
![image](https://user-images.githubusercontent.com/2568208/190974712-742006a9-b1f8-47fc-a7f0-1340c218dd5c.png)

After some profiling, I found the most CPU time is spent on this method. 

```
/Users/megrez/Library/Application Support/Lens/node_modules/oci-image-lens-extension/dist/renderer.js:formatted:29623 (after reformat by Chrome DevTool)
```

![image](https://user-images.githubusercontent.com/2568208/190974664-8da69565-e07a-418d-9915-8877aad2661a.png)

However, this project seems to be a private one. I guess nothing we can do from the perspective of the community.

**Comment by uplg** [comment]
💪 @lujiajing1126 

Stacktrace that I shared shows the same place in Lens (somewhere after handling a state action and loading images).

Looks linked to a lib that applies this spec : https://github.com/opencontainers/image-spec/blob/main/spec.md

**Comment by rkettelerij** [comment]
Same here, CPU spikes significantly. Only seeing this recently.

- Lens: 6.0.2-latest.20220908.1
- macOS 12.5.1 (21G83)
- MBP 2,2 GHz 6-Core Intel Core i7

**Comment by Bukashk0zzz** [comment]
I had the same issue. Then I decided to compile all from sources, and now all work super fast, like on a version 4 before all this fancy stuff.

**Comment by elisemorysc** [comment]
Same Here. started after upgrading to 6.0.2
v2022.9.201328-latest (9/20/2022)
Linux x86, Ubuntu 20.04.3 LTS

**Comment by mrnonz** [comment]
Try to rollback to v6.0.1 and it's work fine !

**Comment by panuhorsmalahti** [comment]
Can you try the latest Lens release and see if that helps with the performance issue?

**Comment by uplg** [comment]
@panuhorsmalahti exact same issue using `Lens: 2022.9.211442-latest`

**Comment by rkettelerij** [comment]
Rollback to v6.0.1 works indeed.

**Comment by panuhorsmalahti** [comment]
Thanks for the additional information, we're working on a fix.

**Comment by panuhorsmalahti** [comment]
`2022.9.231310-alpha` is now available with a fix. It can be updated if "Update Channel" in App Preferences is set to "Alpha". Can you try if it resolves the issue?

**Comment by elisemorysc** [comment]
Latest resolved the issue for me. Thanks!

**Comment by uplg** [comment]
Same issue for me using `Lens: 2022.9.231310-alpha` so not resolved.

**Comment by panuhorsmalahti** [comment]
@m1m1s1ku can you tell roughly how many pods and how many images in those pods are in your cluster? And was Lens 6.0.0/6.0.1 fast for you, but 6.0.2 slow?

**Comment by mrnonz** [comment]
> @m1m1s1ku can you tell roughly how many pods and how many images in those pods are in your cluster? And was Lens 6.0.0/6.0.1 fast for you, but 6.0.2 slow?

For me more than > 1,000 pod in cluster

**Comment by uplg** [comment]
> @m1m1s1ku can you tell roughly how many pods and how many images in those pods are in your cluster? And was Lens 6.0.0/6.0.1 fast for you, but 6.0.2 slow?

~ 120 Pods in this cluster.
Nothing really fast or slow, but 6.0.2 just freeze when I access the pod list, as explained in the OP.

Also, it works perfect with OpenLens, so probably something with the "Proprietary" Lens stuff

**Comment by matti** [comment]
https://user-images.githubusercontent.com/3893/192258259-e7ac199e-a1cc-41c0-a7bb-121fecec64e3.mp4

Lens: 2022.9.260655-latest
Extension API: 6.1.1
Electron: 19.0.17
Chrome: 102.0.5005.167
Node: 16.14.2
© 2022 Mirantis, Inc.

Lens is unusable with 5000 pods in creation - terminal doesn't work etc.

**Comment by panuhorsmalahti** [comment]
Can you try `2022.9.271220-alpha` release available in the alpha channel?

**Comment by uplg** [comment]
Same issue using `Lens: 2022.9.271220-alpha` (but a little bit better, frozen, but I can scroll the incomplete pod list (same as video given by @matti)

**Comment by panuhorsmalahti** [comment]
Thanks, we're still investigating the issue.

@m1m1s1ku did you have the performance issue with Lens 6.0.0/Lens 6.0.1?

**Comment by uplg** [comment]
@panuhorsmalahti I don't think so, but I can't downgrade except by compiling OpenLens (who works, no matter the version)

**Comment by uplg** [comment]
Same issue using : `Lens: 2022.10.31204-alpha`

**Comment by panuhorsmalahti** [comment]
Can you try again with the latest release?

**Comment by uplg** [comment]
@panuhorsmalahti Same issue using : `Lens: 2022.10.70653-latest` (Can scroll but nothing else)

**Comment by Nokel81** [comment]
@m1m1s1ku We also just fixed a memory leak recently. If you upgrade to the latest is it better?
