### ISSUE TITLE
Support viewing and managing VPA

### ISSUE THREAD

**Issue by Cliftonz** [kontena/lens#6278]
**What would you like to be added**:
I would like to see VPA management added to the Config dropdown in lens.

**Why is this needed**:
We are working on setting up vpas to support pod right sizing in out clusters. We would like to be able to see and manage VPAs just like we can for HPAs.

**Environment you are Lens application on:**
- Kubernetes distribution: AKS
- Desktop OS: Windows

**Comment by jim-docker** [comment]
@Cliftonz VPAs currently exist as CRDs so you can see and manage them from the Custom Resources tab in the cluster sidebar:
![Screen Shot 2023-01-11 at 6 24 50 PM](https://user-images.githubusercontent.com/40840436/211940070-d12f58b3-0f68-4490-908f-015aa5312d38.png)

Is there more functionality than this you are looking for? Of course it would be better if VPAs were "first class citizens", alongside HPAs, and show more fields on the details page.

**Comment by Nokel81** [comment]
Fixed by #7004
