### ISSUE TITLE
Can't open Lens on mac

### ISSUE THREAD

**Issue by DmitriyEsin** [kontena/lens#6292]
**Describe the bug**
Can't open Lens on Mac. MacOS 12.6 (21G115)
When I try to open it I see 
![image](https://user-images.githubusercontent.com/75484466/192540360-0a747c36-e090-434a-8cc2-f86c073dabe8.png)
Here I cant approve it too
![image](https://user-images.githubusercontent.com/75484466/192540432-76eff358-5184-4578-b33d-5fbd83540a6f.png)

**To Reproduce**
1. Download package for intel chip from Lens website
2. Install it
3. Try to open

**Expected behavior**
Lens opens properly

**Environment (please complete the following information):**
- Lens Version: 2022.9.260655-latest
- OS: MacOS 12.6 (21G115)
- Installation method (e.g. snap or AppImage in Linux): via dmg installer

**Additional context**
What solved my problem: `xattr -r -d com.apple.quarantine /Applications/Lens.app`

**Comment by floverdevel** [comment]
I have the same issue ✋🏻

**Comment by DmitriyEsin** [comment]
> I have the same issue ✋🏻

@floverdevel try this as temporary solution:
`xattr -r -d com.apple.quarantine /Applications/Lens.app`

**Comment by jim-docker** [comment]
We are looking into this with high priority. 

@DmitriyEsin @floverdevel Is this a first time or clean install? Can you try to start from a terminal and copy logs from the console?

`DEBUG=true /Applications/Lens.App/Contents/MacOS/Lens`

**Comment by gsiawGH** [comment]
same thing. 

bash-3.2$ DEBUG=true /Applications/Lens.App/Contents/MacOS/Lens
Killed: 9

**Comment by inglkruiz** [comment]
This just happened to me but I did succeed after authorizing Lens from Security and Privacy settings. It happened after upgrading Lens using `brew cask`

**Comment by DmitriyEsin** [comment]
@jim-docker Yep it is first clean install on my new Mac.
My logs are the same as @gsiawGH 
`dmitriy$ DEBUG=true /Applications/Lens.App/Contents/MacOS/Lens
Killed: 9`

**Comment by jakolehm** [comment]
I believe this is now fixed (just download the latest package from https://k8slens.dev)
