### ISSUE TITLE
Automatic image security scanning or Scan All / Multi

### ISSUE THREAD

**Issue by thnk2wn** [kontena/lens#6293]
**What would you like to be added**:
Automatic image security scanning - either an option to do automatically do it for every image periodically or a button to scan all etc.

**Why is this needed**:
Security scanning is nice but with a lot of images it's very tedious to scan one image at a time. My initial expectation was it did this automatically. It also defeats some of the intent as it's not entirely useful to have up to date vulnerabilities but then require manually scanning one at a time.

Also the security scanning is featured in release notes and websites and shows screenshots and such but not how to actually access and use the feature.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
- Desktop OS: Mac OS 12.6 (21G115)

**Comment by panuhorsmalahti** [comment]
Hi, the manual scanning feature is described here:
https://docs.k8slens.dev/main/extensions/images/#manual-scanning

As for the automatic scanning you can install the operator following these steps:
https://docs.k8slens.dev/main/extensions/images/#automated-scanning-with-the-trivy-operator-tool

**Comment by thnk2wn** [comment]
Thanks. It'd be helpful if pages like this referenced those docs: https://k8slens.dev/security.html?utm_source=app&utm_medium=banner&utm_campaign=6&utm_content=welcome_banner_03.html
