### ISSUE TITLE
unable to install and access lens on AWS EC2 instance

### ISSUE THREAD

**Issue by shettypriy** [kontena/lens#6350]
**What would you like to be added**:

I am trying to install Lens IDE on AWS EC2 instance. I downloaded the rpm package from the Lens website and installed it, however, I am currently unable to access the Lens IDE. Could you please let me know the detailed steps on how to install Lens IDE on AWS Ec2. 

[root@ip-172-31-42-62 applications]# whereis lens
lens: /usr/bin/lens

[root@ip-172-31-42-62 applications]# /usr/bin/lens
/usr/bin/lens: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory

I have installed libasound.so.2 and it still shows the same error

**Why is this needed**:
This is need for my organisation for managing EKS cluster

**Environment you are Lens application on:**
AWS Ec2 instance running on Amazon Linux 2 

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] EKS
- Desktop OS: <the OS Lens app runs on in your case> Amazon Linux 2 on AWS EC2

**Comment by Nokel81** [comment]
Lens is a desktop application and as such not something that should be installed on a cluster itself.
