### ISSUE TITLE
Doesn't work with conda anymore

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [kontena/lens#6399]
**Describe the bug**
Ditto to title. Before that there is no issue, but since idk which update now whenever I started a terminal session a small black screen pops up and that didn't print anything, so it's obvious why the `Invoke-Expression` command was failing. This means kubectl and helm aren't loaded either due to early termination making it unusable.

**Expected behavior**
It just works.

**Screenshots**
![image](https://user-images.githubusercontent.com/112843587/195245815-23c6a7f5-3531-434c-be9f-e2d24e2f5529.png)

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/112843587/195245867-5f52b0df-8051-4b48-a273-4121f2103fa6.png)

**Comment by svdang999** [comment]
Am having same issue after Lens upgraded to newest version today when calling kubectl command . Powershell terminal alone itself stills able call the kubectl command properly, but not in Lens

**Comment by Nokel81** [comment]
Duplicate of #6401 fix is in progress
