### ISSUE TITLE
Problem with kubectl command

### ISSUE THREAD

**Issue by peter-hst** [kontena/lens#6401]
**Describe the bug**
The version of the Lens software I installed is Lens Setup **2022.10.111653-latest.exe**, but there is a problem with the kubectl command

**Expected behavior**
When I execute the shell of the POD the kubectl command is not used

**Environment (please complete the following information):**
- Lens Version: 2022.10.111653-latest
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux):
exe in Windows 10
**Logs:**
```
PS C:\Users\sumit> kubectl exec -i -t -n default gus-kube-state-metrics-75b4df5c94-fm9z7 -c kube-state-metrics -- sh -c "clear; (bash || ash || sh)"
kubectl : The term 'kubectl' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ kubectl exec -i -t -n default gus-kube-state-metrics-75b4df5c94-fm9z7 ...
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (kubectl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by gdlx** [comment]
Same here. Seems to be happening since updating to 6.1.10 (from 6.0.3, I didn't try 6.0.9)
Same with 6.1.11.

**Comment by tathamitra** [comment]
Got the same issue in OpenLens

**Comment by audain-dg** [comment]
> Same here. Seems to be happening since updating to 6.1.10 (from 6.0.3, I didn't try 6.0.9) Same with 6.1.11.

same here

**Comment by Nokel81** [comment]
When in the terminal, can you do `$env:PATH`?

**Comment by audain-dg** [comment]
the terminal opened with lens 

$env:PATHC:\\Users\\abbas\\AppData\\Roaming\\Lens\\binaries\\kubectl\\1.22.6\\kubectl\\1.22.6;C:\\Program Files\\Lens\\resources\\x64;C:\\Users\\abbas\\AppData\\Roaming\\Lens\\binaries\\kubectl\\1.22.6\\kubectl\\1.22.6;C:\\Program File  
s\\Lens\\resources\\x64;

error message when i do the command kubectl

kubectl : Le terme «kubectl» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe,   
vérifiez que le chemin d'accès est correct et réessayez.  
Au caractère Ligne:1 : 1  
\+ kubectl  
\+ ~~~~~~~  
   + CategoryInfo          : ObjectNotFound: (kubectl:String) \[\], CommandNotFoundException  
   + FullyQualifiedErrorId : CommandNotFoundException

But if i open a classic terminal  (so not in lens) the command  kubectl will work

PS C:\\Users\\abbas> kubectl  
kubectl controls the Kubernetes cluster manager.

Find more information at: https://kubernetes.io/docs/reference/kubectl/

Basic Commands (Beginner):  
 create          Create a resource from a file or from stdin  
 expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service  
 run             Run a particular image on the cluster  
 set             Set specific features on objects

Basic Commands (Intermediate):

etc ....

**Comment by Nokel81** [comment]
Interesting... Thanks. Does `C:\Users\abbas\AppData\Roaming\Lens\binaries\kubectl\1.22.6\kubectl\1.22.6` exist? Or does only `C:\Users\abbas\AppData\Roaming\Lens\binaries\kubectl\1.22.6` exist?

**Comment by audain-dg** [comment]
C:\Users\abbas\AppData\Roaming\Lens\binaries\kubectl\1.22.6\kubectl\1.22.6 exist
![](https://user-images.githubusercontent.com/35590376/195348053-2011c1e4-bcad-4a22-8889-a3d47c3adf23.png)

**Comment by audain-dg** [comment]
I have 1.22.6 and 1.23.3

![](https://user-images.githubusercontent.com/35590376/195348689-4b9161c6-4876-44d1-8072-e800a518f594.png)

**Comment by Nokel81** [comment]
Does the command work if you use `kubectl.exe` instead of just `kubectl`?

**Comment by audain-dg** [comment]
If I do The kubectl.exe with the theminal opend with lens the kubectl.exe open an external terminal and then will close quickly

**Comment by audain-dg** [comment]
![](https://user-images.githubusercontent.com/35590376/195352470-388c4900-b047-447b-9530-412439449c0a.png)

**Comment by lingwooc** [comment]
This would be less acute if you made previous version's binaries available so we could roll back.

**Comment by Nokel81** [comment]
@lingwooc For the time being, the previous version can be downloaded from https://lens-binaries.s3.eu-west-1.amazonaws.com/ide/Lens+Setup+2022.10.70653-latest.exe

**Comment by Nokel81** [comment]
I am currently working on a fix. This is very high priority.

**Comment by mloskot** [comment]
A temporary workaround to make the `kubectl` work is to switch from the default `powershell.exe` to `cmd.exe` as here:

![image](https://user-images.githubusercontent.com/80741/195400653-1df40c72-b68c-43fd-b870-2ef1f8916652.png)

**Comment by Nokel81** [comment]
FYI this has been published as v2022.10.131529-latest

**Comment by BDARNELLFL** [comment]
@Nokel81 thank you! kubectl works from powershell.exe again in the Terminal after I updated to v2022.10.131529-latest

**Comment by mloskot** [comment]
I also confirm the fix works.  Thank you very much @Nokel81 !

**Comment by robertosantaolalla** [comment]
Great job!!
I just upgraded to v2022.10.131529-latest and all kubectl and kubent commands now work for me.

**Comment by peter-hst** [comment]
Thank you very much for your fast support!

**Comment by doug62** [comment]
+1 - Can confirm that updating to current does resolve this bug - THANKS!
