### ISSUE TITLE
Unknown error has occurred

### ISSUE THREAD

**Issue by fabioaraujopt** [kontena/lens#6416]
**Describe the bug**
Can't access some clusters, some times it works other it does not. 
The error is always the same `Unknown error has occurred`, sometimes I restart lens (by terminating the process in activity monitor) other it does not (there is no consistency). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Have an EKS cluster with kubeconfig with the following config style (generated using the command) `aws eks update-kubeconfig --region XXX --name XXX --profile XXX`
```
- name: arn:aws:eks:XXXX
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - XXXXX
      command: aws
      env:
      - name: AWS_PROFILE
        value: XXXX
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
2. Open lens, try to access one of the clusters
3. Sees  error `Unknown error has occurred`

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:

If I run the the app through terminal, and I have the AWS creds exported before running the command (using awsume for example) the access to the cluster works.

```
,"apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401} +7s
debug:   ┏ Unknown error has occurred +0ms
debug:   ┃ [ 1] {
debug:   ┃ [ 2]   isError: true,
debug:   ┃ [ 3]   meta: {
debug:   ┃ [ 4]     id: 'XXXX',
debug:   ┃ [ 5]     name: 'arn:aws:eks:us-east-1:XXXX',
debug:   ┃ [ 6]     ready: false,
debug:   ┃ [ 7]     online: false,
debug:   ┃ [ 8]     accessible: false,
debug:   ┃ [ 9]     disconnected: false
debug:   ┃ [10]   }
debug:   ┗ [11] }
info:    ┏ [CLUSTER]: refresh +8s
info:    ┃ [1] {
info:    ┃ [2]   id: 'XXXX',
info:    ┃ [3]   name: 'XXXX',
info:    ┃ [4]   ready: true,
info:    ┃ [5]   online: true,
info:    ┃ [6]   accessible: true,
info:    ┃ [7]   disconnected: false
info:    ┗ [8] }
```

**Comment by Nokel81** [comment]
Has this been resolved by a recent update?
