### ISSUE TITLE
Pod logs should be scrollable via keyboard

### ISSUE THREAD

**Issue by alan-marcinkowski** [kontena/lens#6451]
**What would you like to be added**:
The pod log view pane only seems scrollable via mouse wheel or scroll bar. No keys I could find would scroll it. It'd be nice to have some sort of scroll.

**Why is this needed**:
I find the mouse scrolling on very large logs to be tediously imprecise.

**Environment you are Lens application on:**

- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...] AKS
- Desktop OS: <the OS Lens app runs on in your case> Windows 10

**Comment by matti** [comment]
#177

**Comment by Nokel81** [comment]
Closing in favour of https://github.com/lensapp/lens/issues/7583 as one unified request
