### ISSUE TITLE
🐞 Can't pass initial loading screen

### ISSUE THREAD

**Issue by tgotwig** [kontena/lens#6459]
**Describe the bug**
I'm new to the project and can't pass the initial loading screen, I followed https://docs.k8slens.dev/contributing/development.

**To Reproduce**
1. Run `make dev`

**Expected behavior**
It passes the initial loading screen.

**Screenshots**
<img width="612" alt="image" src="https://user-images.githubusercontent.com/30773779/197486636-8d0c363c-836d-4bce-b96b-270fd6ed9d73.png">

**Environment (please complete the following information):**
- Lens Version: 6.2.0-alpha.0
- OS: OSX
- Installation method: make

**Logs:**
```shell
[dev:*renderer] + 28 modules
[dev:*renderer] lens-app-renderer (webpack 5.74.0) compiled successfully in 33732 ms
[dev:*renderer] No issues found.
[0] error:   ▪ [LENS-PROXY]: Could not find cluster for upgrade request from url=/ws +22s
[0] info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded +5s
[0] info:    ┏ APP:ACTIVATE +17s
[0] info:    ┗ [1] { hasVisibleWindows: true }
[0] info:    ┏ APP:ACTIVATE +54m
[0] info:    ┗ [1] { hasVisibleWindows: true }
```

**Comment by Nokel81** [comment]
You should be able to go to the tray menu and click "Open Lens" which will open the main window bypassing the readiness checks.

**Comment by tgotwig** [comment]
Somehow it works now 🚀🙌🎉 And seems that the error message from the log doesn't relates to the initial loading screen which was hanging for me 😯
