### ISSUE TITLE
Status show disconnected even when connected to the cluster.

### ISSUE THREAD

**Issue by GavinLi88** [kontena/lens#6479]
Lens version: 2022.10.181357-Latest

issue:
show disconnected status even when connected to a cluster, and actually we can browser all the cluster resource, except the status show disconnected and can't disconnected.

**Comment by Nokel81** [comment]
Duplicate of https://github.com/lensapp/lens/issues/5241

This has been fixed in the latest beta and a stable release should be happening soon.

**Comment by GavinLi88** [comment]
@Nokel81 Hello, just wondering if there any workaround before the stable version release?

**Comment by Nokel81** [comment]
There is. The bug is caused by overlapping kubeconfig sync settings. So for the time being I would make sure that you are syncing individual files that are covered by a folder sync setting.
