### ISSUE TITLE
the  Node shell dont work,

### ISSUE THREAD

**Issue by jiangyixuan1998** [kontena/lens#6480]
the node shell pod likes runing, but i cannt use it for connect  my node 
the terminal status is also 

Connecting ...

**Comment by Nokel81** [comment]
1. What platform are you on?
2. What version are you running?
3. Can you post some logs
4. Please fill out the bug template next time.

**Comment by mcasviper** [comment]
I had the same problem on MacOS with 6.1.14 but with the newer ones it works again.
