### ISSUE TITLE
Can not install Lens

### ISSUE THREAD

**Issue by MohamadTahir** [kontena/lens#6482]
Hello, I am trying to install lens on my ubuntu machine and none of the installation ways mentioned [here](https://docs.k8slens.dev/getting-started/install-lens/#install-lens-desktop-on-linux) are working.

going to [this](https://downloads.k8slens.dev/ide/Lens-5.4.6-latest.20220421.1.amd64.deb)  gives me the following error

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>RQ4Q1CMN61FRTMPZ</RequestId>
<HostId>1Wgw7g/3S39wSAwlXTiykH2PXksuHHBHJiAb8Lum3enqtgAy7rusTpm1khuAIPRzxfsyv1nf738=</HostId>
</Error>
```

I can't find lens on snap and the AppImage gives me a similar error as above.
What am I missing? do I need permission or something?

Besides that, what is the version naming policy?  the link above has `Lens-5.4.6-latest.20220421.1.amd64.deb` so what if I wanted to download the 6.1.13?

**Comment by Nokel81** [comment]
Thanks for pointing this out. The latest version can be downloaded from https://downloads.k8slens.dev/ide/Lens-2022.10.181357-latest.amd64.deb.

We will update the documentation.
