### ISSUE TITLE
Cluster not showing after temporarily removed it

### ISSUE THREAD

**Issue by emanuelegorga** [kontena/lens#6485]
**Describe the bug**
After having added a kube config file, removed it and added it back the cluster is not being shown.

**To Reproduce**
1. Add a cluster and select "Sync your kubeconfig"
2. Delete the cluster
3. Add back the cluster the same way 
4. The cluster is not shown. It appears in the "Kubeconfig Syncs" in settings but won't show on the page of Clusters.

**Expected behavior**
I expected to see the cluster available in the clusters page.

**Screenshots**
<img width="456" alt="Screenshot 2022-10-28 at 15 47 44" src="https://user-images.githubusercontent.com/40179292/198656733-a6a23374-5838-49ba-87b2-2f5a9665279d.png">

**Environment (please complete the following information):**
- Lens Version: 2022.10.181357-latest
- OS: macOS Monterey 12.6.1
- Installation method (e.g. snap or AppImage in Linux): `brew`

**Additional context**
The same kubeconfig was used during step `1` and the cluster showed up. Also, I tried the same with a different kubeconfig cluster and it showed the first time, then I deleted the cluster and added the kubeconfig back and this time Lens won't show the cluster again.

**Comment by Nokel81** [comment]
By "delete a cluster" do you mean you deleted the file or that you modified the file?

**Comment by emanuelegorga** [comment]
Hi, I mean deleting the cluster from Lens Clusters page and the file from "Kubeconfig Syncs" in Lens preferences/Kubernetes page.

**Comment by Nokel81** [comment]
Do you mean you did the following?

![Screen Shot 2022-10-28 at 12 12 10 PM](https://user-images.githubusercontent.com/8225332/198683844-9cbeddbc-0e7d-42c1-b09a-3f9bbbd2894d.png)

and then

![Screen Shot 2022-10-28 at 12 11 16 PM](https://user-images.githubusercontent.com/8225332/198683901-3527bcd2-e271-412a-afd9-f3a6c32f6dce.png)

because then we actually modified the file.

**Comment by emanuelegorga** [comment]
Yes, I deleted the cluster as shown on the screenshots above. Then I readded the same kube config file to Lens and it won't list anymore on Lens, however, it is listed in Lens > Preferences > Kubernetes > Kubeconfig Syncs

**Comment by Nokel81** [comment]
Can you please verify that the context entry within the kubeconfig for that cluster exists?

**Comment by emanuelegorga** [comment]
It actually does not, it has an empty `contexts` array and a `current-context` with the value. The same kube config file was used the same way before and it could work. It just won't show, as mentioned above, when you add it, delete it and then try to add it again. The file will however show on the Preferences `Kubeconfig syncs` section.

**Comment by Nokel81** [comment]
Yes so that is writing as intended. When you did the "remove cluster" action (as above) the file was modified to remove that context. Therefore it is not there to sync anymore.

**Comment by emanuelegorga** [comment]
Checking the file I can now see that what you have described is indeed what happened. Thanks a lot for the help 🙇
