### ISSUE TITLE
Unable to display PODs

### ISSUE THREAD

**Issue by devrivne** [kontena/lens#6508]
**Describe the bug**
Unable to display PODs

**To Reproduce**
1. Connect to any EKS cluster.

**Expected behavior**
All pods are displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7127333/199711303-cbe88412-640a-4fa9-8dad-3b816bfa4834.png)
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/7127333/199711369-1ee5ff03-c6aa-488c-bce0-154f80ba765e.png">

**Environment (please complete the following information):**
Lens: 2022.10.311317-latest
Extension API: 6.1.14
Electron: 19.0.17
Chrome: 102.0.5005.167
Node: 16.14.2
© 2022 Mirantis, Inc.
Mac OC

**Comment by Nokel81** [comment]
Those abort errors are slightly misleading. They mean that you changed the `namespaces` it should display or switch views.

Are there any other logs?

**Comment by devrivne** [comment]
I will provide all the needed logs if you share how.
Also, I tried different namespaces and different clusters.

**Comment by Nokel81** [comment]
Logs should exist in `~/Library/Logs/Lens`

**Comment by devrivne** [comment]
```
info: [CLUSTER]: reconnect {"accessible":false,"disconnected":true,"id":"bea693ed401a85a66620c1430f8d3150","name":"test-prod","online":false,"ready":false}
info: [KUBE-AUTH-PROXY]: found port=53882
info: APP:ACTIVATE {"hasVisibleWindows":true}
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"bea693ed401a85a66620c1430f8d3150","name":"test-prod","online":true,"ready":true}
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"bea693ed401a85a66620c1430f8d3150","name":"test-prod","online":true,"ready":true}
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"bea693ed401a85a66620c1430f8d3150","name":"test-prod","online":true,"ready":true}

info: APP:ACTIVATE {"hasVisibleWindows":true}
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"bea693ed401a85a66620c1430f8d3150","name":"test-prod","online":true,"ready":true}
```

Overview(PODs) and PODs view still empty
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/7127333/199998882-15fee3a8-24d6-4de6-9cc2-cc1028a96a9d.png">

**Comment by Nokel81** [comment]
Can you also give more detailed logs from the devtools?

**Comment by devrivne** [comment]
For the `Overview` view
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/7127333/200000223-4c11aeba-f5fd-4ff2-ab7e-be8a404cd1f0.png">

Switching to the PODs view
![image](https://user-images.githubusercontent.com/7127333/200000705-b06d1f49-657f-4f49-a0db-093a13d4c077.png)
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/7127333/200000822-9aeb36bc-a969-4374-94e5-67f637d36286.png">

**Comment by devrivne** [comment]
Any updates?

**Comment by Nokel81** [comment]
Do other resources load correctly?

**Comment by devrivne** [comment]
Not sure. They are sometimes displayed only partly.
At the same time, kubectl works smoothly.
