### ISSUE TITLE
lens hogs a ton of memory and the cluster webview crashes / hangs

### ISSUE THREAD

**Issue by matti** [kontena/lens#6518]
<img width="2170" alt="image" src="https://user-images.githubusercontent.com/3893/200004266-d894fd56-9f64-4d58-b4f0-0fd6319f8784.png">

Happens every day when lens running on the background.

**Comment by Nokel81** [comment]
Thanks for reporting this. This is indeed bad. Would you be able to provide a heap snapshot from the devtools?

**Comment by Nokel81** [comment]
I am getting about 30kB/s of heap growth with Lens idling....

**Comment by matti** [comment]
can you give me instructions on how to heap snapshot properly?

I can grow memory usage by scaling up some nodes and pods. 500 pods / 1000 nodes. but it doesnt even have to work this way, just letting lens sit on the background while pods etc are being recreated eventually hits the memory limits

**Comment by Nokel81** [comment]
Ah thanks. Even scaling nginx causes my heap to grow by about 700Kb/S when viewing pods

**Comment by Nokel81** [comment]
The devtools has a "Memory" section which allows you to pick the iframe related to your cluster and then do an "allocation timeline snapshot"

**Comment by matti** [comment]
yeh, but is it even needed now? to me it looks like you already have enough of things to investigate on your machine?

**Comment by Nokel81** [comment]
Yes
