### ISSUE TITLE
Apple M1 chip - pod shell not working

### ISSUE THREAD

**Issue by dnltech2020** [kontena/lens#6521]
When trying to access a pod shell, the terminal starts then terminates with no reason.

lense properties:
Lens: 2022.11.41813-latest
Extension API: 6.1.15
Electron: 19.1.4
Chrome: 102.0.5005.167
Node: 16.14.2

I have tested exec to pod using just a terminal and it works just fine with the terminal

**Comment by Nokel81** [comment]
If you open a local shell terminal within Lens and then execute `kubectl exec -it -n <namespace> <pod-name>` what happens?

**Comment by dnltech2020** [comment]
@Nokel81 When I try the following
> kubectl exec -it <podName> sh it works from local terminal in lense.  When I try the shell icon in lense it would show the exec command breifly then it would terminate the terminal window.

I just tried the shell icon in lense today and it seems to be working now for a couple of my pods. For now it looks to be resolved.  I did not make any changes except to reboot a couple times.
