### ISSUE TITLE
Keyboard shortcut for saving resource

### ISSUE THREAD

**Issue by fabiocastagnino-horsa** [kontena/lens#6559]
**What would you like to be added**:
Add a keyboard shortcut for saving resource manifest (Ctrl + S)
![image](https://user-images.githubusercontent.com/116292883/201314960-fc3ca01c-7c16-484e-97ce-c2c6ffaac6b7.png)

**Environment you are Lens application on:**
- Kubernetes distribution: any
- Desktop OS: any

**Comment by Nokel81** [comment]
Thanks for the suggestion. We will consider this in the future.

**Comment by Nokel81** [comment]
Closing in favour of https://github.com/lensapp/lens/issues/7583 as one unified request
