### ISSUE TITLE
terminating object must not be disabled

### ISSUE THREAD

**Issue by matti** [kontena/lens#6560]
<img width="876" alt="image (1)" src="https://user-images.githubusercontent.com/3893/201361621-9ab619b7-48b6-408e-8b3d-d729b78f2f87.png">

When an object is terminating, it must not be disabled because the object still exists and has events etc that are currently not accessible because the details pane can not be opened. workaround: use kubectl and not lens.

**Comment by Nokel81** [comment]
I believe that this is only happening for namespaces. Is that correct?
