### ISSUE TITLE
No longer possible to create a Job from a CronJob

### ISSUE THREAD

**Issue by mdufourneaud** [kontena/lens#6564]
**Describe the bug**
It is no longer possible to create a Job from a CronJob through the CronJob details panel.

**To Reproduce**
1. Open a CronJob details panel
2. The button for creating a Job from the CronJob is missing

**Expected behavior**
It was possible to create a Job from a CronJob by clicking a button of the CronJob details panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/3235175/201648793-1ced106b-2c32-4d4e-98ca-9dfe7fd6a7fe.png)

**Environment (please complete the following information):**
- Lens Version: 2022.11.101953-latest
- OS: Windows 11 Pro / 22H2 / 22623.891
- Installation method: .exe

**Comment by Nokel81** [comment]
If you quit Lens (from the Tray menu) and then run it from powershell, do you see any logs relating to a failure to load "pod-menu-extension"?

**Comment by vasilevp** [comment]
Same thing for me on MacOS using brew, started several days ago with the latest Lens version (2022.11.101953). No mention of "pod-menu-extension" in the logs when running from terminal.

**Comment by avivshafir** [comment]
Same thing for me on MacOS
version `2022.11.101953-latest`


I reverted to previous version by reinstalling
`https://downloads.k8slens.dev/ide/Lens-2022.11.92045-latest.dmg`
and it does have the trigger button

**Comment by filzonemafin** [comment]
same for me on MacOs
version: Lens: 2022.11.101953-latest

**Comment by advissor** [comment]
The trigger button has disappeared

**Comment by CumpsD** [comment]
Same on Windows 2022.11.101953-latest

**Comment by CumpsD** [comment]
Is there a workaround for this btw?

**Comment by CumpsD** [comment]
Seems to be followed up in https://github.com/lensapp/lens/issues/6572 with a fix in https://github.com/lensapp/lens/pull/6581

**Comment by Nokel81** [comment]
Thanks for pointing me to this issue too. Yes these two issues are duplicates and I will choose this over in favour of that one.
