### ISSUE TITLE
No longer able to see CronJobs

### ISSUE THREAD

**Issue by mikk150** [kontena/lens#6565]
**Describe the bug**
After 6.1.19 I am no longer able to see CronJobs on Kubernetes 1.20

**To Reproduce**
1. Run Kubernetes 1.20
2. Go to Workloads->CronJobs

**Expected behavior**
List of CronJob objects

**Screenshots**
![image](https://user-images.githubusercontent.com/4953629/201656669-bae2a102-8c21-4632-982e-582b2a56db44.png)

**Environment (please complete the following information):**
- Lens Version: 6.1.19
- OS: Manjaro
- Installation method (e.g. snap or AppImage in Linux): AUR

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**
presumably works perfectly on cronjobs with `apiVersion: batch/v1`

**Comment by filzonemafin** [comment]
also got this bug, Lens version 2022.11.101953-latest, macOs

k8s version 1.23.x
