### ISSUE TITLE
Option to manually trigger cronjobs not visible

### ISSUE THREAD

**Issue by tpdewolf** [kontena/lens#6572]
**Describe the bug**
Previously it was possible to manually trigger a cronjob. I don't see that option anymore

**Environment (please complete the following information):**
- Lens Version: Lens: 2022.11.101953-latest
- OS: [e.g. OSX]: MacOS 12.3
- Installation method (e.g. snap or AppImage in Linux): Mac DMG

**Comment by floghiade** [comment]
I can confirm that I have the same problem on Windows 11 22H2

**Comment by meingraham** [comment]
Same issue on Windows 10 Enterprise 21H2

**Comment by Nokel81** [comment]
Thanks for the report. I have reproduced this locally and a fix should be up shortly
