### ISSUE TITLE
EvalError: Possible side-effect in debug-evaluate

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#6599]
Any statement written in DevTools console shows error which blocks app view.

https://user-images.githubusercontent.com/9607060/202462882-5c0acaa3-c58d-49b3-9b8c-ad436940aea7.mov

**Comment by Nokel81** [comment]
Sounds like a bug in chromium which might have already been fixed https://chromium.googlesource.com/v8/v8/+/ac5096a0daa6bd7cb3b8aa350eaddc3a67f3480e

**Comment by Nokel81** [comment]
This will be fixed the next time we upgrade electron's major version.

Workaround is listed https://github.com/playcanvas/editor/issues/785
