### ISSUE TITLE
CronJob trigger buttons gone?

### ISSUE THREAD

**Issue by Tsopic** [kontena/lens#6610]
![image](https://user-images.githubusercontent.com/3941909/202655362-522af334-ab8f-492b-8c1b-9f0443c2344b.png)

Where did the trigger and suspend buttons go from Cron Jobs?

Seems the Lens is getting worse with every update.

**Comment by Nokel81** [comment]
Duplicate of #6572 Please look for other issues before making new ones. This has already been fixed
