### ISSUE TITLE
GKE Cluster won't show config, workloads, or anything at all...

### ISSUE THREAD

**Issue by caeus** [kontena/lens#6645]
**Describe the bug**
I created an autopilot GKE cluster, and everything is working like a charm
I knew of lens, and started using it. Works with minikube, and docker-desktop, but my GKE cluster, although it connects, everything is just empty.

**To Reproduce**
1. Create an autopilot cluster `gcloud container clusters create-auto hello-cluster --region=us-west-1`
2. Get kubeconfig configured `gcloud container clusters get-credentials hello-cluster --region us-west1`
3. Open Lens and connect to cluster (add some pods, if necessary)
4. No error, no loading visuals, just empty

**Expected behavior**
Lens works as expected, and show workloads, config, and well, everything

**Screenshots**
<img width="1512" alt="Screen Shot 2022-11-24 at 6 23 19 PM" src="https://user-images.githubusercontent.com/5459862/203873797-7ea24a37-34ae-486b-8bc1-f59f5d010674.png">

**Environment (please complete the following information):**
- Lens Version: 2022.11.241650-latest
- OS:  OSX
- Installation method: downloaded .dmg file

**Logs:**
No logs AT ALL

**Comment by RomanLis-GBI** [comment]
For me same happened after latest update.

**Comment by RomanLis-GBI** [comment]
For me same happened after latest update.

![lens](https://user-images.githubusercontent.com/85894345/203893612-a56060c7-fa5a-4093-a61c-d14547d64067.png)

OS: Windows 11.

uninstall/Install applications won't helps.

**Comment by layerlre** [comment]
Same
<img width="274" alt="Screenshot 2565-11-25 at 11 43 34" src="https://user-images.githubusercontent.com/5457378/203902938-3c8c9930-bf84-4caf-b687-821aa66c773d.png">
macOS Ventura 13.0.1

**Comment by kenrickles** [comment]
You could possibly try to delete kubeconfig and run your cloud again and see if that works?

**Comment by ahkui** [comment]
same here

![image](https://user-images.githubusercontent.com/14049597/203910363-ff597b73-7a92-483e-b063-6038e7787c17.png)

**Comment by DavidHsaiou** [comment]
same here
![image](https://user-images.githubusercontent.com/96435631/203911632-f8112aad-3113-4d83-84a5-2463c8f3f551.png)

**Comment by bingwei-hong-partior** [comment]
It seems an issue with latest version, I was able to see everything after uninstall and use a older version.

**Comment by ruebenacker** [comment]
+1 with macOS Ventura 13.0.1 and latest lens version
![image](https://user-images.githubusercontent.com/16401415/203923847-92d2d500-8f29-41dd-8ee6-a11ee14c15d2.png)

Edit: reinstalled the previous version from Time Machine backup, works without any issue.

**Comment by Kr0n0** [comment]
+1 with macOS BigSur 11.7.1
<img width="296" alt="imagen" src="https://user-images.githubusercontent.com/560991/203928113-3f35d372-d7d3-4d71-bd90-a1f765830584.png">

EDIT: Downloaded the previous version from https://api.k8slens.dev/binaries/Lens-2022.11.101953-latest.dmg and replaced the application without updating, everything works correctly.

**Comment by Ansen** [comment]
+1 with openlens 

6.2.2 Does not work

**I install 6.2.1 and it works**

![image](https://user-images.githubusercontent.com/676412/203946918-1c902a71-272f-492c-8c40-0a4070901cfe.png)

![image](https://user-images.githubusercontent.com/676412/203946973-151b39cb-e116-4b0f-9494-b11e3c43b820.png)

**Comment by pinceladasdaweb** [comment]
+1 using macOS BigSur 11.7

<img width="400" alt="Captura de Tela 2022-11-25 às 07 05 04" src="https://user-images.githubusercontent.com/814325/203957135-3f9a5d56-d420-49c1-b146-7e111bdd88e7.png">

**Comment by shaifymehta** [comment]
Can someone share pervious link for windows to download?

**Comment by shaifymehta** [comment]
> +1 with macOS BigSur 11.7.1 <img alt="imagen" width="296" src="https://user-images.githubusercontent.com/560991/203928113-3f35d372-d7d3-4d71-bd90-a1f765830584.png">
> 
> EDIT: Downloaded the previous version from https://api.k8slens.dev/binaries/Lens-2022.11.101953-latest.dmg and replaced the application without updating, everything works correctly.

Can you please share the previous link for windows if you know ?

**Comment by kenrickles** [comment]
I went to their slack and let them know. They are looking into it right now. 

if you want to compile on your own: 
https://github.com/lensapp/lens/releases/tag/v6.2.1

If you cannot wait for the team to fix it, There's someone running an Openlens
https://github.com/MuhammedKalkan/OpenLens/releases

I don't know Kalkan but looking at his code and workflows, it looks okay.

**Comment by markhc** [comment]
Same here 

![image](https://user-images.githubusercontent.com/11592227/203980035-9d577b1e-9702-4344-b27c-1533ea63cbd1.png)
![image](https://user-images.githubusercontent.com/11592227/203980078-fb379c20-2926-4a64-b793-66d88691f8e9.png)

**Comment by markounikau** [comment]
Same here (macos 13.0.1). **Please provide an easy way to revert to older Lens versions for exactly this sort of issues.** Building from sources is not an easy way, for the record.
 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/51440239/203987773-5fc6439d-015e-44b0-b4b5-4b766a3b2d26.png">

**Comment by voodoo-dn** [comment]
+1 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/5621571/203992320-f368fe04-5ff2-4c91-a887-16a13c6152a6.png">

**Comment by VanTudor** [comment]
Ran into this too. Downgraded to `2022.11.210737-latest`, which works fine. 

Quick way to revert back to a usable version for mac users (via homebrew):

- remove lens (from Applications and run `rm -rf ~/Library/Application\ Support/Lens`)
- download [this file](https://raw.githubusercontent.com/Homebrew/homebrew-cask/0ca7c95665e4e43a706beab9c2c269cf77452f15/Casks/lens.rb) and save it as `lens.rb` somewhere. It's just the [cask file for a prev version](https://github.com/Homebrew/homebrew-cask/blob/0ca7c95665e4e43a706beab9c2c269cf77452f15/Casks/lens.rb)
- navigate your terminal in the same folder
- run `HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask lens.rb` (no_update flag for speed)

cc @markounikau

**Comment by VanTudor** [comment]
BTW, I was able to reproduce this on the Windows client too (same version).

**Comment by kingkong0905** [comment]
They fixed the issue. I have updated to latest version Lens: 2022.11.251411-latest and it solved.

**Comment by Nokel81** [comment]
This has been fixed with the recent version.
