### ISSUE TITLE
Lens icon disappears from cmd+tab switcher

### ISSUE THREAD

**Issue by matti** [kontena/lens#6653]
mac m1 ventura

Lens not visible in mac "cmd+tab" switcher:

<img width="2053" alt="image" src="https://user-images.githubusercontent.com/3893/204085494-49994dc7-614b-40b3-a289-83a4ae776c5e.png">

**Comment by matti** [comment]
also top menu disappeared, maybe a ventura bug

**Comment by thomasjachmann** [comment]
I also had this but updating to the most current version (OpenLens 6.2.5) fixed it.

**Comment by aleksfront** [comment]
Fixed in https://github.com/lensapp/lens/pull/6770
