### ISSUE TITLE
Lens 2022.11.251411-latest broke extension top bar item layout

### ISSUE THREAD

**Issue by stefcameron** [kontena/lens#6658]
**Describe the bug**

After getting auto-upgraded to this version of Lens, the MCC Extension's top bar button layout has changed.

Here's what it is now (bad):
<img width="162" alt="image" src="https://user-images.githubusercontent.com/2855350/204357831-c0c59452-64c6-47a3-b6fc-4f5de4fca8b7.png">

Here's what it was before (good):
https://github.com/Mirantis/lens-extension-cc/blob/master/README.md#adding-your-first-management-cluster
<img width="259" alt="image" src="https://user-images.githubusercontent.com/2855350/204359343-63f0cd31-7dba-45b2-97fc-8139c3d5af5f.png">

Something in the CSS resulted in an issue with the width of the item such that we now have to set a hard width on our item, whereas we didn't before. Setting `width: 130px` on our item resolves the problem.

**To Reproduce**
1. Upgrade Lens to `2022.11.251411-latest`
2. Install [MCC Extension](https://github.com/Mirantis/lens-extension-cc)
3. Observe the top bar item.

**Environment (please complete the following information):**
- Lens Version: `2022.11.251411-latest`
- OS: macOS 12.6.1
- Installation method (e.g. snap or AppImage in Linux): dmg

**Comment by Nokel81** [comment]
@aleksfront Do you know what could have caused this?

**Comment by aleksfront** [comment]
> @aleksfront Do you know what could have caused this?

This line was the reason https://github.com/lensapp/lens/pull/6437/files#diff-68eb2d03cc30a79b22e879596d9ac1df6eca6ddc2914bb43640156c769ca0503R31

**Comment by stefcameron** [comment]
@aleksfront Thank you for the fix!
