### ISSUE TITLE
App not starting: missing files on latest/stable Snap package (version: 2022.12.11410-latest)

### ISSUE THREAD

**Issue by dvalvezon** [kontena/lens#6697]
**Describe the bug**
The latest stable Snap release `2022.12.11410-latest` (185) is missing resource files that prevent the application from properly starting.

**To Reproduce**
1. Install the Lens application according to the instructions provided in the documentation:
    `sudo snap install kontena-lens --classic`
2. Click on the App icon to start the application.
3. Some processes start in the background but nothing else happens, no interface or error messages are shown.

OR
1. Install the Lens application according to the instructions provided in the documentation:
    `sudo snap install kontena-lens --classic`
2. Run the application through command line:
    `/snap/kontena-lens/185/kontena-lens`
3. See the error message.

**Expected behavior**
The application processes should start and the interface should be displayed.

**Screenshots**
Error message:
![image](https://user-images.githubusercontent.com/4681610/205402104-bb83ec45-36b0-4f53-b668-902539b8086f.png)
Snap Version:
![image](https://user-images.githubusercontent.com/4681610/205402722-58171d8f-f7f8-46b4-a30b-a1e0dfcd8584.png)
Missing files are present in an outdated version (179):
![image](https://user-images.githubusercontent.com/4681610/205403293-645ea525-e301-4001-a35d-98e4e14bde09.png)
But the current version (185) 'resources' files are missing:
![image](https://user-images.githubusercontent.com/4681610/205403424-d8807968-c3fe-4b1e-b07c-e1a71789fc3c.png)

**Environment (please complete the following information):**
- Lens Version: v6.2.4 (Snap package 2022.12.11410-latest)
- OS: Ubuntu 22.04
- Installation method (e.g. snap or AppImage in Linux): Snap

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
(node:32339) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `kontena-lens --trace-deprecation ...` to show where the warning was created)
info:    ▪ [CLUSTER-STORE]: LOADING from  ... +0ms
info:    ▪ [CLUSTER-STORE]: LOADED from /home/dvalvezon/.config/Lens/lens-cluster-store.json +3ms
info:    ▪ 🔌 Starting LensProxy +4ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:42491 +2ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ [USER-STORE]: LOADING from  ... +3ms
info:    ▪ [USER-STORE]: LOADED from /home/dvalvezon/.config/Lens/lens-user-store.json +7ms
info:    ▪ ⚡ LensProxy connection OK +12ms
warn:    ▪ No suitable icon found for task bar. +7ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /snap/kontena-lens/185/resources/static/splash.html... +0ms
error:   ┏ [CREATE-ELECTRON-WINDOW]: Failed to load window "splash" +38ms
error:   ┗ [1] { code: -6, desc: 'ERR_FILE_NOT_FOUND' }
(node:32339) electron: Failed to load URL: file:///snap/kontena-lens/185/resources/static/splash.html with error: ERR_FILE_NOT_FOUND
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///snap/kontena-lens/185/resources/static/splash.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
    at EventEmitter.emit (node:events:538:35)
    at EventEmitter.emit (node:domain:475:12)
    at emitter.emit (/snap/kontena-lens/185/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:119:20)
(node:32339) UnhandledPromiseRejectionWarning: Error: ERR_FILE_NOT_FOUND (-6) loading 'file:///snap/kontena-lens/185/resources/static/splash.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
    at EventEmitter.emit (node:events:538:35)
    at EventEmitter.emit (node:domain:475:12)
    at emitter.emit (/snap/kontena-lens/185/resources/app.asar/node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js:119:20)
(node:32339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +93ms
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
N/A
```

**Additional context**
N/A

**Comment by mimre25** [comment]
Same problem here on Ubuntu 20.04

**Comment by ikholodkov** [comment]
++

**Comment by alexandrumoraru-tomtom** [comment]
I am encountering the same issue on Ubuntu 20.04

**Comment by Liamso** [comment]
Also seeing on 22.04

```
[CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /snap/kontena-lens/184/resources/static/splash.html
[CREATE-ELECTRON-WINDOW]: Failed to load window "splash"
```

**Comment by Liamso** [comment]
While we wait for an update; this fixed it for me: 

```
killall kontena-lens 

snap refresh kontena-lens --channel=latest\candidate

kontena-lens
```

Will give you an older version, but at least it will launch (and even better this version doesn't require you to log in).

**Comment by maikfr** [comment]
Same here under Ubuntu 18.04.6 LTS (though I guess it's not dependent on the OS version). Candidate channel works so far, thanks for that hint.

**Comment by Nokel81** [comment]
I have found the problem. A fixed release should be out today

**Comment by Nokel81** [comment]
We have merged the fix and the release tomorrow will include it along with other bug fixes.

**Comment by dvalvezon** [comment]
@Nokel81 Are we supposed to see a new Snap version?
So far nothing has changed:
![image](https://user-images.githubusercontent.com/4681610/206580745-77e7e8c6-a559-4e77-b3f8-1e4eb0e2abed.png)
