### ISSUE TITLE
Helm Release Values not being updated after initial load

### ISSUE THREAD

**Issue by NC-JSJE** [kontena/lens#6721]
When going to Releases in the Helm section to read the helm values, you are able to load the values one time, and every load after that displays the values from the initial load no matter what release you are trying to get the values from.

1) Open the application and go to the helm releases
2) Click on "A" -> Displays values of "A"
3) Click on "B" -> Displays values of "A", but changes the Resoureces to values of "B"
4) Click on "C" -> Displays values of "A", but changes the Resoureces to values of "C"

Note: Clicking upgrade shows the correct helm.

A: 
![image](https://user-images.githubusercontent.com/114979428/206672497-64fbe93f-b22c-4a0f-b5fb-262b59b2bda9.png)

B: 
![image](https://user-images.githubusercontent.com/114979428/206672612-be4ddf28-a8c0-4b29-bdef-d63f0e4af55f.png)

C: 
![image](https://user-images.githubusercontent.com/114979428/206672730-801a015a-27d6-41e6-a1ec-55eae6abe5ce.png)

**Environment (please complete the following information):**
- Lens Version: Tried 6.2.1 to 6.2.5
- OS: Win10

**Comment by Nokel81** [comment]
Similar to https://github.com/lensapp/lens/issues/6197
