### ISSUE TITLE
No UI refresh after deleting CRDs

### ISSUE THREAD

**Issue by infected-engineer** [kontena/lens#6738]
**Describe the bug**
Whenever I delete any custom resource using lens it is deleted successfully but it is still shown in lens if I check on the Kubernetes dashboard then I don't find the same custom resource.

**To Reproduce**
1. Go to 'Custom Resource Definitions
2. Delete any existing Custom Resource
3. It should be present in the lens as it is but deleted in the Kubernetes dashboard

**Expected behavior**
Once I delete any custom resource using the lens and it got deleted successfully then it should not be shown in the list i.e. UI should be refreshed.

**Environment (please complete the following information):**
- Lens Version: 
![lens](https://user-images.githubusercontent.com/115975678/207235700-41cd8733-a2c2-41e8-b7fa-1fcbb0d4d411.PNG)
- OS: Windows 10
- Installation method: using the installer

**Comment by aleksfront** [comment]
I can confirm that is still an issue in 6.4.0.

**Comment by Nokel81** [comment]
This is no longer even an issue in 6.4.0. Closing.
