### ISSUE TITLE
Lens disappears from dock and menus on MacOS

### ISSUE THREAD

**Issue by alex-hempel** [kontena/lens#6756]
**Describe the bug**
When closing the active window, Lens disappears from the MacOS Dock and menu bar.

When opening another window via the menu bar icon, Lens does not appear in the Dock, and the application menus do not show in the menu bar.

**To Reproduce**
1. With Lens running, close the active window
2. Click on the menu bar icon and select 'Open Lens'

Lens does not show in the dock, and no menus are available in the menu bar.

**Expected behavior**
After step 2 above, I expect Lens to show up in the MacOS Dock, and also for its application menus to show in the menu bar.

**Screenshots**
Screenshot 1: After normal start
![image](https://user-images.githubusercontent.com/6581307/207779912-1fbc15f2-1d5e-4a10-b8eb-5e7001712a17.png)

Screenshot 2: After closing and reopening as described
![image](https://user-images.githubusercontent.com/6581307/207780023-99b1087a-5051-4cc6-9edf-5a02aa3afb03.png)

**Environment (please complete the following information):**
- Lens Version: 2022.12.121519-latest (This also happens with OpenLens 6.2.5)
- OS: MacOS 13.0.1 (ARM)
- Installation method: from zip file

Quitting the app and restarting fixes the issue, until the next time the main window is closed.

**Comment by matti** [comment]
saw this today also

**Comment by matti** [comment]
and again

**Comment by aleksfront** [comment]
A regression from https://github.com/lensapp/lens/pull/6528/files#diff-3db17cf3ccf1f977bff6722ed348e0cdc2d2fba7d0d322a0394ed6e6eab5dee7
