### ISSUE TITLE
Save & Close should wait the result before closing the tab

### ISSUE THREAD

**Issue by relip** [kontena/lens#6785]
**What would you like to be added**:
Save & Close should wait the result before closing the tab

**Why is this needed**:
Currently when `Save & Close` is clicked, the resource tab closes regardless of its result and I have to rewrite config from the scratch if there are mistakes in config.

This behavior made me copying new config to another editor before clicking `Save & Close` or sometimes clicking `Save` instead of `Save & Close` then manually close the tab. I feel this kind of behavior makes `Save & Close` button unusable in almost every case.

**Environment you are Lens application on:**
- Desktop OS: Windows

**Comment by faisal6621** [comment]
Then instead of naming the button `Save & Close` that should be renamed to `Apply & Close`. And if `apply` fails then this must not be closed.
