### ISSUE TITLE
"ERROR: Helm >= 3.9.0 is required" even though helm 3.10.3 is installed on the system

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#6809]
I tried to install the latest Traefik chart (20.4.1) through Lens and got an error:

```
Error: INSTALLATION FAILED: execution error at (traefik/templates/deployment.yaml:3:8):
ERROR: Helm >= 3.9.0 is required
```

![Screenshot from 2022-12-21 08-50-08](https://user-images.githubusercontent.com/158380/208961690-d42b53ab-2ec3-4dc4-a4de-4512aced95ca.png)

My box does have a newer version installed:
```
$ helm version
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
$ 
```

I'm not sure if Lens has it's own bundled version of Helm that might be out-of-date, or if this is actually an issue with the Traefik chart.

My copy of helm is in /usr/local/bin and in the path.

Lens Version: Lens-2022.12.201157-latest.x86_64.AppImage
OS: Linux (Mint 20.3)

**Comment by jakolehm** [comment]
> I'm not sure if Lens has it's own bundled version of Helm that might be out-of-date, or if this is actually an issue with the Traefik chart.

Lens has it's own bundled version, currently 3.7.2.

**Comment by nscriptdotgo** [comment]
I am running into this same issue as well, will there be a way for us to set our own version of Helm or allow us to install a particular version of helm for Lens specifically? Thanks!

**Comment by si458** [comment]
im having the same issue here but with openlens, have submitted a PR as i think the old PR missed openlens!
