### ISSUE TITLE
Lens doesn't show HPA for autoscaling/v2 api version

### ISSUE THREAD

**Issue by abalalaev** [kontena/lens#6817]
**Describe the bug**
We use autoscaling/v2 api version for our HPA deployments:
`$ kubectl get hpa/app-hpa -n default -o yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler`

But it looks like lens trying to use autoscaling/v2beta1 only

In our k8s version
`$ kubectl version --short
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.4`
we don't have v2beta1 api version
`$ kubectl api-versions | grep autoscaling
autoscaling/v1
autoscaling/v2
autoscaling/v2beta2`

**To Reproduce**
1. Go to Config/HPA
2. See error in the orange triangle

**Expected behavior**
Trying to use actual api versions

**Screenshots**
![image](https://user-images.githubusercontent.com/87458443/209062624-f061551b-b876-4243-973e-86d78804d048.png)

**Environment (please complete the following information):**
- Lens Version: 2022.12.201157
- OS: Ubuntu 20.04.5 LTS
- Installation method (e.g. snap or AppImage in Linux): deb package

**Comment by armujahid** [comment]
For me HPA v2 are showing but I am facing a slightly different issue https://github.com/lensapp/lens/issues/6827

**Comment by Nokel81** [comment]
Related to #6168 as well.
