### ISSUE TITLE
Page refresh is broken in development mode

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#6818]
![image](https://user-images.githubusercontent.com/9607060/209078465-8203abbc-d34c-4ecd-9344-36428dfecb41.png)

Hitting `Cmd+R` in dev mode shows blank page. Both main and cluster frames affected by this.

**Comment by jakolehm** [comment]
Regression from https://github.com/lensapp/lens/pull/6046

**Comment by jakolehm** [comment]
```ts
      if (req.url === "/" || !req.url || !req.url.startsWith("/build/")) {
        req.url = `${publicPath}/index.html`;
      }
```

fixes it (in `devStaticFileRouteHandlerInjectable`).
