### ISSUE TITLE
v6.3.0 cannot build binary with extensions

### ISSUE THREAD

**Issue by ogarcia** [kontena/lens#6819]
I'm [Arch Linux AUR package mantainer](https://aur.archlinux.org/packages/lens).

Since upgrading to version 6.3.0 I am not able to build the open-lens binary with the extensions.

I used to build the extensions with the `make build-extensions` command as follows:
```sh
make node_modules
yarn download:binaries
yarn run build:tray-icons
make build-extensions
yarn dist:dir
```

But in this latest update the command `make build-extensions` has been removed.

I have tried to do the following:
```sh
make node_modules
yarn download:binaries
yarn run build:tray-icons
make build-npm
yarn dist:dir
```

This leaves me with the binary in the `dist/linux-unpacked` directory, but does not include the extensions.

**Comment by msa0311** [comment]
The in-tree extensions have been removed from with 6.3.0, see the following issues / PRs that explain the background:

- https://github.com/lensapp/lens/issues/6749
- https://github.com/lensapp/lens/pull/6715
- https://github.com/lensapp/lens/pull/6775

**Comment by ogarcia** [comment]
@msa0311 Yes, I know, I saw those changes. But supposedly (if I understand correctly) with #6715 the extensions like node-menu and pod-menu are already included in the package.

What happens to me is that since this change I don't see the buttons to open a shell in the pod or see its logs, something that before appeared thanks to the extensions.

**Comment by jakolehm** [comment]
#6715 was the first bigger change related to improvements but it still had one major drawback that was cyclic dependency within the`lensapp/lens` repository (in-tree extensions pointing to `@k8slens/extensions` and `lensapp/lens` package.json pointing to in-tree extensions).

**Comment by ogarcia** [comment]
That is, if I understand correctly, with version 6.3.0 the options to open a shell in the pods or to see the logs have been lost (among others).

**Comment by msa0311** [comment]
It's no longer part of this repository. The functionality is still available in the Lens Desktop distribution that can be downloaded from here: https://k8slens.dev

**Comment by ogarcia** [comment]
Ok. It is unfortunate that this decision was made. Surely the number of users will drop and possibly we will stop updating the package in Arch. 

In any case, thank you very much for your help.

**Comment by lingwooc** [comment]
I'd have a lot more respect for you if you admitted you'd taken the decision to take core functionality closed source for commerical reasons.

**Comment by szinn** [comment]
That's extremely unfortunate. It essentially makes the tool useless. You can see something isn't running, but have to now resort to a command-line or another tool to understand why.

**Comment by jkroepke** [comment]
> It's no longer part of this repository. The functionality is still available in the Lens Desktop distribution that can be downloaded from here: [k8slens.dev](https://k8slens.dev)

Where is the source code repository for the Lens Desktop distribution?
