### ISSUE TITLE
Version 6.3.0 - Windows - Cluster and Node views with missing Prometheus data

### ISSUE THREAD

**Issue by trombini77** [kontena/lens#6824]
**Describe the bug**

**To Reproduce**
1. Having the previous release 6.2.6 with "@kubescape/lens-extension", "lens-certificate-info", "lens-extension-network-policy-viewer" extensions
2. Update to 6.3.0 and open (Print 1)
3. Downgrade to 6.2.5 and reinstall 6.3.0 shows but with failed Prometheus metrics in the cluster view and *only memory for nodes view (Print 2 and 3)

**Expected behavior**
Only update without a black dashboard

**Screenshots**
Print 1
![image](https://user-images.githubusercontent.com/13336060/209154147-c8719ff3-54b4-45dc-8b1f-3c31c2938407.png)

Print 2
![image](https://user-images.githubusercontent.com/13336060/209167720-d844711a-05b1-4aef-ad4d-8ededdfd91fa.png)

Print 3
![image](https://user-images.githubusercontent.com/13336060/209167417-a6af45a9-1e7c-41c2-a72f-1f823561018e.png)

**Environment (please complete the following information):**
- Lens Version: 6.3.0
- OS: Windows 10 Enterprise
- Installation method: from .exe installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.

the kubeconfig didn´t have changes so I think is not necessary

**Additional context**

**Comment by odedonato** [comment]
same as https://github.com/lensapp/lens/issues/6820
ctrl + r will reload and some things are showed but other problems are present

**Comment by trombini77** [comment]
> same as #6820 ctrl + r will reload and some things are showed but other problems are present

After a downgrade and reinstall 6.3.0 the dashboard back to shows something but now the Prometheus metrics from nodes are not processing right.

**Comment by msa0311** [comment]
Thanks for reporting this, we just added it to the next patch milestone and will start looking into it!

**Comment by tbertenshaw** [comment]
not sure if related or a separate issue, but after refreshing to see the page, it seems the view logs option is no longer present for pods etc.

**Comment by UmarFKhawaja** [comment]
I can't install Prometheus metrics on a new cluster. The extension is missing. I also have to force reload the window after startup, because I get a blank window.

**Comment by trombini77** [comment]
I'm testing 6.4.0-alpha.4 on Windows 10 and it was better.
The first started after installing the 6.4.0-alpha.4 over the 6.2.6, some columns (CPU, DISK) and the same metrics in the right Pod modal were missing, but after some minutes late, the metrics appeared.

**Comment by Nokel81** [comment]
@trombini77 Thanks for reporting back, sometimes Prometheus take a little time to pick up the metrics. Will mark this is fixed in the upcoming 6.4.0 release.
