### ISSUE TITLE
Kubeconfig sync not working as expected

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#6834]
Kubeconfig sync in Preferences does not update changes. Shows only 1 synced folder `/Users/user/kube` even if it was removed or any other files added.

![catalog clusters](https://user-images.githubusercontent.com/9607060/209639480-ad561972-28db-40e1-b65f-40c92c372e33.png)
![synced items](https://user-images.githubusercontent.com/9607060/209639482-82643dac-c5da-4c43-99d2-5cad382c85f3.png)

### To reproduce:
1. Note clusters in `Catalog`
2. Go to Preferences -> Kubernetes -> Kubeconfig Syncs
3. Remove or add any entries
4. Close Preferences
5. See same clusters
6. If you go back to `Kubecongif Sync` you'll see `/Users/user/kube` as the only 1 item

**Comment by andreosipov** [comment]
have the same problem
