### ISSUE TITLE
Namespace details does not open

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#6836]
**Describe the bug**
Clicking a namespace does not open namespace details.

**Environment (please complete the following information):**
- Lens Version: 6.3.0 (also current master branch)

**Comment by aleksfront** [comment]
As observed, `autoRegistrationEmitter.on("kubeApi")` event doesn't trigger only for `NamespaceApi`. Console logs `legacyRegisterApi` calls inside `kube-api.ts` and warnings is what triggered in `autoRegistrationEmitter`.

![Screenshot 2022-12-28 at 14 45 00](https://user-images.githubusercontent.com/9607060/209807340-3c038971-0af8-4ea7-80c9-164de0a51b42.png)

**Comment by aleksfront** [comment]
It is clear that there is a race condition happened between `NamespaceApi` newly created instance and `autoRegistrationEmitter` event listeners placed in https://github.com/lensapp/lens/blob/master/src/renderer/before-frame-starts/runnables/setup-auto-registration.injectable.ts#L66

#### The problem:

`NamespaceApi` at the very start of cluster frame opening calls `legacyRegisterApi()` function which executes `autoRegistrationEmitter.emit("kubeApi", api);` https://github.com/lensapp/lens/blob/master/src/common/k8s-api/kube-api.ts#L237

This call happened **before** event listeners created in `setup-auto-registration.injectable.ts`.

This causes a chain of consequences (like namespace store not being added to the store list) and eventually leads do invisible Namespace details panel.

A workaround might be to wrap `autoRegistrationEmitter.emit("kubeApi", api)` into `setImmediate`:

```
setImmediate(() => autoRegistrationEmitter.emit("kubeApi", api));
```

#### The bigger problem
The main issue is unclear way to determine the order of running injectables right after cluster frame starts. `setup-auto-registration.injectable.ts` uses
```
injectionToken: beforeClusterFrameStartsSecondInjectionToken
```
and the order is defined in `start-frame.injectable.ts` https://github.com/lensapp/lens/blob/master/src/renderer/start-frame/start-frame.injectable.ts. One of the questions is why we have 2 different injection tokens `beforeClusterFrameStarts`?

@Nokel81 Can please check if there's some other solution besides of using `setImmediate`? Maybe move contents from `setup-auto-registration.injectable.ts` right into `kube-api.ts` to avoid race condition?
