### ISSUE TITLE
[BUG][v6.3.0] GKE Cluster - No UI displayed when connected to a GKE Cluster

### ISSUE THREAD

**Issue by KillianH** [kontena/lens#6852]
**Describe the bug**

On the latest release v6.3.0 when I connect to my GKE cluster I don't see any menu displayed and I got this in the logs : 

```
[AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="#####" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution
```

Pretty much on all namespace that Lens detects I guess.

**To Reproduce**
1. Try to connect to a GKE Cluster
2. No UI displayed

**Expected behavior**
Should see the standard menu and access ressources

**Screenshots**
![image](https://user-images.githubusercontent.com/8064210/210083364-5c49e42f-618c-4879-9c3d-2994e5b7a296.png)

**Environment (please complete the following information):**
- Lens Version: v6.3.0
- OS: Ubuntu 20.04.5 LTS
- Installation method (e.g. snap or AppImage in Linux): Local build of the open source repo on v6.3.0 tag

**Logs:**
```
[AUTHORIZATION-NAMESPACE-REVIEW]: allowing all resources in namespace="#####" due to incomplete SelfSubjectRulesReview: webhook authorizer does not support user rule resolution
```

**Kubeconfig:**
No Kubeconfig will be provided. Working fine with lens v6.2.5 / v6.2.6

**Additional context**
GKE extension installed. Tried to connect to both detected cluster from the GKE extension and the GKE cluster in my kubeconfig file created by gcloud cli.

**Kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12-gke.1600", GitCommit:"5b5d8c9b3bf9c7e4b50c276f4d165d176e310dfe", GitTreeState:"clean", BuildDate:"2022-10-13T09:30:22Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
```

**PR Related**
Probably this one #6657

**Comment by HenrikDK** [comment]
Same problem with all our private AKS clusters, reverted to 6.1.19 since that version seems stable

![no ui in lens 6 3 0](https://user-images.githubusercontent.com/1023686/210207275-4182667c-e03a-40fe-a785-eadbee83c1c3.PNG)

**Comment by davidreis97** [comment]
Same on EKS on my side.

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/6835
