### ISSUE TITLE
Document how to bundle extensions with the new extension loading process

### ISSUE THREAD

**Issue by alebcay** [kontena/lens#6855]
**What would you like to be added**:
Explain/document how to include/bundle extensions at build time of the OpenLens/Lens Core app itself.

**Why is this needed**:
Now that the bundled extensions have been removed from this repository, there is no documentation available, either in prose or code, about how to include an extension as part of the application bundle itself. This includes details such as:
- Where in the build tree one would put bundled extensions in order to have the build system pick them up
- What changes, if any, are needed in `package.json` or other configuration files
- What changes, if any, are needed to the extension to be bundled that may be different from the "usual" extension format/anatomy as described at https://api-docs.k8slens.dev/v6.0.1.

On another note, the docs at that link don't appear to have been updated for a while. They should be updated to ensure that vendors and the community can continue to produce and maintain extensions that are compatible and provide the best possible experience to end users of Lens Desktop and other Lens Core-based applications.

**Environment you are Lens application on:**

- Kubernetes distribution: GKE/k3s
- Desktop OS: macOS

**Comment by Nokel81** [comment]
Fixed by #7359
