### ISSUE TITLE
How to go back from pod to replicaset/deployment?

### ISSUE THREAD

**Issue by IAkumaI** [kontena/lens#6862]
Hi,
if I click on some deployment and after that click on a replicaset in the popup window and then click on a pod in the popup, how can I go back to the parent of this pod?

Of course, I can just close popup and click on deployment to find the replicaset, but it's too long path, isn't it? I thought there is some shorter way to do it. But there is no "back button" in the popup window.

How it suppose to work?

**Comment by Nokel81** [comment]
Yes you can, you can us the arrows in the top left to go forwards and back (as well as the `CMD+RIGHT` and `CMD+LEFT` shortcuts)

**Comment by IAkumaI** [comment]
Oh my! There ARE arrows, I've never seen it. Thank you :)

Btw, it's CMD + [ and CMD + ] instead of arrows on MacOS
