### ISSUE TITLE
Restructure to monorepo

### ISSUE THREAD

**Issue by jakolehm** [kontena/lens#6873]
Lets restructure this repo to be a "monorepo" where we can host multiple npm packages. This will allow to split the current monolith core/app into more manageable units (packages with dependencies) and it will also allow to bring back removed in-tree extensions (as packages in the monorepo).

**Comment by jansav** [comment]
This is actually something that we have already been drafting for a bit since the our future ambitions require distinguishing stuff like applications, libraries and features from each other with the idea that any of them can be published individually. 

That being said, love it.
