### ISSUE TITLE
OpenLens 6.25 not able to show cluster CPU and Memory after eks upgraded to 1.24

### ISSUE THREAD

**Issue by xyfleet** [kontena/lens#6887]
**Describe the bug**
Before eks upgrade, lens worked fine with my eks clusters. It can show the cluster CPU and Memory usage. In the Node section, it also shows the cpu, memory and disk usage of each instance. After upgrading the eks from 1.22 to 1.24, all these metrics disappeared. No longer see these usages. 
**screenshot: before the eks upgrade**

![Screenshot2023_01_07_202501](https://user-images.githubusercontent.com/113627389/211180458-6f75a434-6306-4204-8ead-7d34dd3a0e4f.jpg)

**screenshot: after the eks upgrade**
<img width="935" alt="image" src="https://user-images.githubusercontent.com/113627389/211180472-c1ee7887-e908-473d-b0f0-e0abade54011.png">

Tried to upgrade the OpenLens to 6.3.0, then all of the cluster information are missing. Same issue as this ticket https://github.com/lensapp/lens/issues/3891

**To Reproduce**
1. upgrade eks from 1.22 to 1.24
2. upgrade aws and update-kubeconfig
3. reconnect the new eks cluster by lens

**Expected behavior**
Still can see the cluster CPU, memory usages. In the Node section, will be able to see the usage of each node's CPU, memory and disk. 

**Environment (please complete the following information):**
- Lens Version: 6.25
- OS: Mac

**Comment by Nokel81** [comment]
This seems to be a known bug with Kubernetes 1.24

https://github.com/kubernetes/kubernetes/issues/111077

So closing from our side.
