### ISSUE TITLE
Kubeconfig sync from the Catalog doesn't work

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#6905]
### Steps to reproduce
1. Go to Catalog
2. Choose `Sync kubeconfigs(s)` from blue button
3. Select any file
4. Selected config would not get synced.  To confirm go to preferences and see old list of kubeconfigs.

https://user-images.githubusercontent.com/9607060/211742212-a8c7b679-5753-47fc-8a7d-c9bcca0d7323.mov

![old kubeconfig syncs](https://user-images.githubusercontent.com/9607060/211742249-a6dfd2d9-5818-415d-8bc2-ea6b325a2a56.png)

**Comment by srMarquinho** [comment]
I was just about to open this issue. 👍

**Comment by srMarquinho** [comment]
It also disappears once the config is reloaded.

**Comment by Nokel81** [comment]
What version is this on @aleksfront ?

**Comment by rusenask** [comment]
it's quite strange, I didn't even update the app and got into this after a restart :crying_cat_face:

**Comment by Nokel81** [comment]
@rusenask sounds like a more specific problem. Can you paste some application logs?

**Comment by lehuyv** [comment]
> What version is this on @aleksfront ?

For me, I can reproduce the bug on version 6.3.0

**Comment by Nokel81** [comment]
But not on 6.2.6?

**Comment by lehuyv** [comment]
> But not on 6.2.6?

I don't know for 6.2.6, but not on 6.2.5.

**Comment by Nokel81** [comment]
Thanks for the report we will continue to investigate

**Comment by diptripa** [comment]
+1

**Comment by 1junechung** [comment]
+1

**Comment by prabhapoojary** [comment]
+1

**Comment by juanjocop** [comment]
+1

**Comment by xcrystalz42** [comment]
Hi! I have the same sutuation on 6.5.2

**Comment by mamu-reply** [comment]
Hi! i'm using this Lens version
```
Lens: 2024.1.300751-latest
Extension API: 6.10.33
Electron: 27.2.4
Chrome: 118.0.5993.159
Node: 18.17.1
```
and actually i have the same problem, when i add a new kubeconfig or a folder to sync lens do nothing. Exist a way to refresh the cluster list or to force this sync?

Thanks

**Comment by navik86** [comment]
I have the same problem. version 6.5.2

**Comment by ashutoshSce** [comment]
I have the same problem

OpenLens: 6.5.2-366
Extension API: 6.5.2
Electron: 22.3.3
Chrome: 108.0.5359.215
Node: 16.17.1
© 2023 OpenLens Authors
