### ISSUE TITLE
Missing Menuitems for specific cluster provider

### ISSUE THREAD

**Issue by dark0ni** [kontena/lens#6928]
**Describe the bug**
For the cluster zukcb3.c4.gra.k8s.ovh.net where are missing menu items in the gui. I have access to all areas like deployment, secrets etc

Deployments, DaemonSets, StatefulSets, Endpoints, Ingress and more are missing. I tested with another tool and there i have access to this areas. 

I suspect that the provider OVH for this location has a problem with Lens.

**To Reproduce**
Not possible without rent a cluster there

**Expected behavior**
Show all Menuitems there i have access to for example "Deployments"

**Screenshots**
Here the normal view of a provider there works everything fine:
![image (3)](https://user-images.githubusercontent.com/4546899/212093804-f7dbcdeb-0e3f-46dc-81d8-f2277448bc68.png)

Here my current view for c4.gra.k8s.ovh.net:
![image (2)](https://user-images.githubusercontent.com/4546899/212093835-ad70fde0-bbff-4286-a359-624b604afdf5.png)

**Environment (please complete the following information):**
- Lens Version: 2023.1.110749-latest
- OS: Windows 11

**Comment by Nokel81** [comment]
Similar to https://github.com/lensapp/lens/issues/6858 but you are using OpenLens 6.2.6. Please try the next alpha when it comes out.

**Comment by brezuicabogdan-emag** [comment]
Same problem here
![image](https://user-images.githubusercontent.com/96478474/222443215-359cd74c-fa55-4cc1-a193-8b32d06053e6.png)

Happened after updating to latest version of Lens.

**Comment by Nokel81** [comment]
@brezuicabogdan-emag What kind of kube cluster are you connecting too?

**Comment by Nokel81** [comment]
This has been fixed. Please upgrade to the latest version
