### ISSUE TITLE
CronJobs missing from sidebar in OpenLens 6.3.0 and 6.4.0-alpha.2

### ISSUE THREAD

**Issue by benwbooth** [kontena/lens#6931]
**Describe the bug**

**To Reproduce**
1. Open OpenLens
2. CronJobs section is missing

**Expected behavior**

I can still get to the cronjob page by clicking into the Jobs section and clicking the CronJob link in the job, but there should be a clickable CronJob link in the sidebar underneath the "Jobs" link.

**Screenshots**
![image](https://user-images.githubusercontent.com/75972/212207800-9756a50c-b638-475a-93aa-9bb488fa7253.png)

**Environment (please complete the following information):**
- Lens Version: 6.3.0 and 6.4.0-alpha.2
- OS: NixOS Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage install

**Comment by Nokel81** [comment]
Similar to https://github.com/lensapp/lens/issues/6858. What sort of cluster are you connecting too?

**Comment by vovtz** [comment]
I can still not see _CronJobs_ in _OpenLens_ 6.4.0 on ‘serious’ K8s clusters (admittedly, these are running version 1.19.x, so actually semi-serious 😢). I *do* see them for the K8s running in _Docker Desktop_ and with _Rancher Desktop_ (_K3s_), though (but everyone is admin there I guess, so RBAC will hardly be enforced?).

**Comment by Nokel81** [comment]
Thanks for reporting this.

**Comment by benwbooth** [comment]
It's a k3s cluster. I have three clusters. In the two clusters running v1.20.5 and 1.20.6, I do NOT see the CronJob menu in the sidebar. However, in the third cluster which is running v1.25.6 I DO see the CronJob menu.

**Comment by benwbooth** [comment]
I notice that the CronJob spec was updated from version `batch/v1beta1` to `batch/v1` between K3s version 1.20 to 1.25. Could the problem be that the Lens code is searching for the CronJob with `batch/v1` spec? Is there a way to also search for version `batch/v1beta1`?

**Comment by Nokel81** [comment]
@benwbooth Looking at the code in `packages/core/src/common/k8s-api/endpoints/cron-job.api.injectable.ts`. The `CronJobApi` is configured to look for the preferred version from the sever. Let me see if I can reproduce on a 1.20 cluster

**Comment by Nokel81** [comment]
Reproduced.
