### ISSUE TITLE
Upgrade to lens breaks ability to connect to eks clusters: E0112

### ISSUE THREAD

**Issue by JeffreyGarrett** [kontena/lens#6932]
**Describe the bug**
When upgrading to latest lens (required upgrade now) the connection to clusters no longer works at all.  There is now a E0112 error. 

```
E0112 16:41:52.132276 16677 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.
```

**To Reproduce**
1. install old lens and connect to an eks cluster 
2. upgrade lens and reconnect to cluster....
3. get error

**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/8009595/212211198-24e21d39-a54b-45ab-86a6-3f7c47127e36.png)

**Environment (please complete the following information):**
- Lens Version:
![image](https://user-images.githubusercontent.com/8009595/212211231-aa3bf21e-ff35-447e-8d8a-3d2bdeed58e1.png)

- OS: OSX
- Installation method (e.g. snap or AppImage in Linux): dmg

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
there was no change in the kubeconfig. 
```

**Additional context**
This only happens with lens.  Terminal and kubectl work fine.  Lens is completely broken here.

**Comment by Nokel81** [comment]
What shell are you using? Is it configured as your default shell? Do you see a notification about "Shell env sync" failing?

**Comment by jaydeland** [comment]
I am also getting this error

```sh
It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

E0116 16:18:15.646610 31603 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

getting credentials: exec: executable aws not found
```

**Comment by Nokel81** [comment]
@jaydeland Can you answer the questions above for yourself?

**Comment by jaydeland** [comment]
I am using zsh - kubectl commands work as expected, as does the VS Code Kubernetes Plugin

**Comment by Nokel81** [comment]
Do you see that notification?

**Comment by jaydeland** [comment]
I don't see that noticiation. The lens log has this:
```
error: [CLUSTER]: Failed to connect to "arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test": StatusCodeError: 500 - "getting credentials: exec: executable aws not found\n"
debug: getting credentials: exec: executable aws not found
 {"isError":true,"meta":{"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}}
info: [CLUSTER]: activate {"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}
info: [CLUSTER]: bind events {"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}
debug: Starting connection ... {"isError":false,"meta":{"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}}
info: [CLUSTER]: reconnect {"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}
debug: [KUBE-AUTH]: stopping local proxy {"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}
debug: Authentication proxy started {"isError":false,"meta":{"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}}
info: [KUBE-AUTH-PROXY]: found port=62072
debug: Refreshing connection status ... {"isError":false,"meta":{"accessible":false,"disconnected":false,"id":"ca04dcb6180b9dcdbf1a8b4c89ef4fb6","name":"arn:aws:eks:us-east-1:AWS-Account:cluster/internal-test","online":false,"ready":false}}
```

**Comment by Nokel81** [comment]
Do you see anything about shell env or shell sync failing?

**Comment by jaydeland** [comment]
Nope - anywhere else I should look?

**Comment by Nokel81** [comment]
`SHELL-SYNC` is the prefix, you should see `[SHELL-SYNC]: Synced shell env` if it worked.

**Comment by barkerja** [comment]
I am seeing the same error after upgrading Lens. If there's any information I can provide from my environment to assist, please let me know!

**Comment by Nokel81** [comment]
@barkerja what OS are you running lens on? What version of lens are you using and if you look at the logs do you see something about `SHELL-SYNC`

**Comment by barkerja** [comment]
@Nokel81 

OS: macOS 13.2
Lens: 2023.1.110749-latest

As for logs, I assume those are viewed by `View > Toggle Developer Tools`? If so, I see no logs that contain `SHELL-SYNC`

**Comment by Nokel81** [comment]
@barkerja No I mean the main ones. You can get them by do `Help > Export Support Logs`

**Comment by barkerja** [comment]
> @barkerja No I mean the main ones. You can get them by do `Help > Export Support Logs`

I do see two lines for `SHELL-SYNC`

**Comment by barkerja** [comment]
Has anyone found a resolution for this? Still experiencing this in the latest version `2023.3.71735-latest `

**Comment by Nokel81** [comment]
Do you see any notification about failing to sync env vars?

**Comment by barkerja** [comment]
> Do you see any notification about failing to sync env vars?

Not that I can tell. But I do run fish as my main shell, and the logs make a lot of `zsh` references. But no failures as far as I can tell.

**Comment by Nokel81** [comment]
Have you used `chsh` to switch to `fish` or set your "Default Shell" setting to `fish`?

**Comment by barkerja** [comment]
> Have you used `chsh` to switch to `fish` or set your "Default Shell" setting to `fish`?

I used `chsh -s` to set fish as my default shell.

**Comment by Nokel81** [comment]
If you do the following:

```
$ node
> os.userInfo().shell
```

Is the output `/bin/fish`? If so, can you please check your settings within Lens to make sure that it wasn't previously set to `zsh`

**Comment by barkerja** [comment]
```shell
> os.userInfo().shell
'/opt/homebrew/bin/fish'
```

<img width="1231" alt="Screenshot 2023-03-10 at 14 08 41" src="https://user-images.githubusercontent.com/6124/224404755-10f1e1bc-d4dd-4c8e-9eab-96754d1a1c59.png">

**Comment by barkerja** [comment]
Changing the shell path in Lens seems to have fixed my issue! Thanks for the tip to look at that, I'm not sure I would have ever thought to check that as it was something I never changed/configured.

I was rather complexed because I have two Macs that both run fish as their default shell, but one machine Lens stopped working after a Lens update (and I never updated Lens on the other for fear of it not working).

**Comment by Nokel81** [comment]
The only thing that I can think of is that somewhere along the line that setting got set which causes this issue.

I know that you have been responding more than OP. But I am going to close this as fixed.

**Comment by barkerja** [comment]
Thanks again for your assistance!

**Comment by 76creates** [comment]
using MacOS, had very long uptime, restarting system worked the trick for me ✅

**Comment by ego93** [comment]
I'm having this issue with the latest version of lens `2023.11.81519-latest`
Was not an issue in the previous version
