### ISSUE TITLE
Can't change the width of the columns

### ISSUE THREAD

**Issue by emoxam** [kontena/lens#6980]
Can't change the width of the columns

**To Reproduce**
1. Go to 'Workloads'
2. Click on 'Overview'
3. Try to 'change any columt
4. See the cursor not changing to needed

**Expected behavior**
Cursor must changes to needed view

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2023.1.110749-latest
- OS: Windows 11 22h2

**Comment by Nokel81** [comment]
Duplicate of #601
