### ISSUE TITLE
 Lens automatically updates on reopen 

### ISSUE THREAD

**Issue by dcole-gsn** [kontena/lens#6982]
**Describe the bug**
Lens is automatically updating itself upon reopening, happened from 6.25 -> 6.3. Can this please get fixed? As 6.3 is doesn't work for us, it connects but doesn't show any information about the connected cluster.

**Environment (please complete the following information):**
- Lens 6.25 & 6.3
- OS: Windows & Mac

This ticket essentially is a duplicate of https://github.com/lensapp/lens/issues/2216
But 2216 was closed and not fixed.
Thanks.

**Comment by Nokel81** [comment]
At this time we are not supporting disabling auto updates.

As for your bug it has been fixed in 6.4.0-alpha.4
