### ISSUE TITLE
Helm charts blank

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#6985]
**Describe the bug**
Installing a new helm chart gives a blank text box or hangs "spinning".

**To Reproduce**
1. Open Lens
2. Connect to a cluster
3. Click on "Charts"
4. Find any random chart and click it.
5. Click "Install"
6. See hanged, empty text box
7. Try changing the chart version to something else
8. See neverending spiiner
9. At this point, Lens won't cleanly exit.

**Screenshots**
Screenshot:
![Screenshot from 2023-01-19 16-40-27](https://user-images.githubusercontent.com/158380/213594035-4b38e54b-51c8-4757-91e4-f3c93ebc3cee.png)

Video:
https://user-images.githubusercontent.com/158380/213594126-36ac583c-633b-4eed-940c-4bf7409da039.mp4

- Lens Version: Lens-2023.1.110749-latest.x86_64.AppImage
- OS: Linux

**Comment by bykof** [comment]
got this problem too on Mac Ventura (13.1 22C65)

**Comment by Nokel81** [comment]
This has been fixed by https://github.com/lensapp/lens/pull/6782 and will be part of the next release of Lens Desktop.
