### ISSUE TITLE
Unable to launch lens on Ubuntu 20.4

### ISSUE THREAD

**Issue by Amrish-Sharma** [kontena/lens#6986]
Dear All,

I have followed the steps mentioned in  https://docs.k8slens.dev/getting-started/install-lens/ to add the repo, update and install lens also created lens.desktop with content mentioned

But when I am trying to launch the lens I get below error. I have tried google search along with issues search but couldn't find any related issue hence posting. Thank you much in advance for help!!

```
codebuzz@item :applications$ lens
(node:10492) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `lens --trace-deprecation ...` to show where the warning was created)
[10492:0120/125939.250575:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[10492:0120/125939.250780:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
Aborted
```

**Comment by Nokel81** [comment]
Are you trying to install Lens on a headless Linux server? That will not work as Lens Desktop is a desktop GUI application that is installed on your local machine and then is pointed at your cluster.

**Comment by Amrish-Sharma** [comment]
yes, it was deployed on WSL2(windows subsystem for linux) that didn't worked. Lens installed on windows working fine for me
