### ISSUE TITLE
Kube config files/directories not syncing/being parsed when Bitnami is blocked?

### ISSUE THREAD

**Issue by djk** [kontena/lens#6994]
Running OpenLens in an environment where most outbound internet traffic is blocked, an error appears stating that it's been unable to contact Bitnami. If you add the location of kube config files it seems like the settings do not save as if you navigate out of preferences and back again, the changes to the location of kube config files (or directories) have reverted. The only way to get a cluster added was to copy/paste the contents of .kube/config, which is not ideal. 

Even though the default setting for kube configs should be fine as it's looking at a directory with a kube config file with cluster details in there, it seems like it doesn't get parsed. 

**To Reproduce**
1. On a network where accesss to bitnami is restricted go to the Lens preferences
2. An error will likely pop up saying that bitnami is inaccessible. Add a location of a kube config file or sync a directory.
3. Close preferences. Note that no clusters are added. 
4. Go back to preferences, see that the kube config/directory sync options have reverted to default.

**Expected behavior**
I would expect the kube configs to be parsed even if Bitnami isn't accessible. 

**Environment (please complete the following information):**
- Lens Version: OpenLens 6.3.0, 6.4.0-alpha.3, 6.4.0-alpha.4
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux):
https://github.com/MuhammedKalkan/OpenLens

**Kubeconfig:**
Can't get kubeconfig from this remote machine.

**Comment by Nokel81** [comment]
That should have been fixed be fixed by #6837....

Will need to re-verify.
