### ISSUE TITLE
Namespaces tab is completely unresponsive

### ISSUE THREAD

**Issue by rittneje** [kontena/lens#6996]
**Describe the bug**
When I go to the Namespaces tab, it lists the namespaces, but clicking on each namespace does nothing. Also clicking the dots does nothing.

**To Reproduce**
1. Go to the Namespace tab.
2. Try to click on a namespace.
3. Try to click on the dots next to a namespace.

**Expected behavior**
Clicking a namespace should show an overlay for it.
Clicking the dots should open a menu.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 6.3.0
- OS: macos
- Installation method (e.g. snap or AppImage in Linux): `make build`

Note: Downgrading to v6.2.6 resolves the issue.

**Comment by aleksfront** [comment]
Fixed by https://github.com/lensapp/lens/pull/6865
