### ISSUE TITLE
Editor and terminal fonts not loaded properly in 6.4.0

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#7008]
<img width="730" alt="broken monaco fonts" src="https://user-images.githubusercontent.com/9607060/214489969-8c8d6519-8dec-4b6f-a13f-73b36e66dae0.png">

To reproduce open terminal or any of the monaco editor instances.

**Comment by Nokel81** [comment]
I believe this is only an issue when running in dev mode within this repo. Marking as p1 and moving to 6.4.1

**Comment by rahul-theorem** [comment]
I also noticed this when installing the app after building it from scratch locally (MacOS Ventura 13, arm64).

**Comment by paxlo** [comment]
The same on Fedora 36. 6.3.0 looked fine

![Screenshot from 2023-01-31 14-00-45](https://user-images.githubusercontent.com/5142290/215729153-6f1370fe-ae01-4130-a70c-9d2664032c4b.png)

**Comment by justdan96** [comment]
The workaround for me was to install one of the fonts in the Terminal preferences menu. On Mac you can install a few of them at the same time through Homebrew:
```
brew install --cask homebrew/cask-fonts/font-source-code-pro homebrew/cask-fonts/font-anonymous-pro homebrew/cask-fonts/font-ubuntu-mono homebrew/cask-fonts/font-red-hat-mono
```
