### ISSUE TITLE
helm chart install but get empty value

### ISSUE THREAD

**Issue by yimiaoxiehou** [kontena/lens#7046]
i try to install app by helm chart but after click install , the default value file is empty.
![image](https://user-images.githubusercontent.com/27064164/215318243-039324aa-5cd9-459a-9f3f-ef2b5297a620.png)

![image](https://user-images.githubusercontent.com/27064164/215318137-451acbd9-27da-400e-ba0c-df58ffa8b6ab.png)
![image](https://user-images.githubusercontent.com/27064164/215318138-547bde69-6900-42d9-8527-bda4eacd7da8.png)

click install with empty value, will get bad request
![image](https://user-images.githubusercontent.com/27064164/215318255-b421e68a-c4a6-4c20-8967-62e0b9b1da0d.png)

**Comment by yimiaoxiehou** [comment]
![image](https://user-images.githubusercontent.com/27064164/215318298-86312037-ef6d-4ca8-804c-50d72fcedae8.png)

**Comment by Nokel81** [comment]
This was fixed by #6318 and will be part of the next release

**Comment by JustDoItSascha** [comment]
And when will this release come? And can we (Mac users) download the beta maybe? If yes, where?

**Comment by Nokel81** [comment]
A beta hopefully should be out today

**Comment by JustDoItSascha** [comment]
And how can I download it? Just switching the channel to beta in the preferences does nothing :( Or is there currently no beta?

**Comment by Nokel81** [comment]
Yes that will be how, and it is currently not out yet.

**Comment by yimiaoxiehou** [comment]
thanks @Nokel81

**Comment by JustDoItSascha** [comment]
@Nokel81 I still didn't get any beta update... Is the beta not out yet or is the update mechanism broken? Because if I click "Check for updates" I get no message at all. Nothing happens. Is this normal? I would assume that there is a popup saying something like "No update available"...

**Comment by yimiaoxiehou** [comment]
@Nokel81  i try to click "Check for updates ",  but not things happen. the dev tools panel also have no any network request . is it ok ?

**Comment by JustDoItSascha** [comment]
The same on my side...

**Comment by JustDoItSascha** [comment]
Any updates on this? Thought it would be faster to publish a beta version...
