### ISSUE TITLE
Allow extension to specify storeName

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/lens#7052]
If extension's package.json specifies `storeName` property which is set to a truthy value, use it for persisting data (e.g. extension stores and extension data) instead of the extension `name`.

This allows extension to be renamed without losing data.

**Comment by panuhorsmalahti** [comment]
Note that extension can set the storeName also in an injectable (using `bundledExtensionInjectionToken`).

**Comment by Nokel81** [comment]
It is the opinion of the core team that using a field within the `package.json` would be preferable.
