### ISSUE TITLE
Mouse cursor wonky and interface partially frozen after updating helm charts

### ISSUE THREAD

**Issue by darkpixel** [kontena/lens#7056]
I just tried to update an app I have installed, and the interface kinda "hanged".
I can still pick options from the burger menu--including quit, but the rest of the interface is unresponsive to clicks.

I can consistently reproduce it.

![Screenshot from 2023-01-30 11-54-17](https://user-images.githubusercontent.com/158380/215582069-a96671c0-1898-4d60-9baf-2b416e5a8e8b.png)

The screenshot isn't super helpful, but I don't have the time to take a video and blur out a handful of things...
![Screenshot from 2023-01-30 11-54-04](https://user-images.githubusercontent.com/158380/215582110-6fcdc3e9-8e9d-4667-8d34-5ee0aadd7deb.png)

I'm not sure if this also happens when installing new charts, but it definitely happens when I try to upgrade any existing charts.

**Comment by Nokel81** [comment]
Maybe related to https://github.com/lensapp/lens/issues/7068?

**Comment by darkpixel** [comment]
Could be...I wasn't messing with namespaces outright, but the charts are all outside of the default namespace.
I was able to reproduce it consistently after restarting Lens...but fast forward until today and I can't reproduce it.
Since I can't provide any better detail or reproduce it, I'm going to close the bug.
