### ISSUE TITLE
Dependencies are duplicated in bundles

### ISSUE THREAD

**Issue by jansav** [kontena/lens#7065]
**Describe the bug**
Current size of "open-lens" renderer -bundle is over 60 MB. There's duplicated instances of dependencies.
There must be something wrong with current setup.

**core/static/build/renderer.js**
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/3083083/215991613-beab434c-bb65-4dbf-bd9b-0a22ef4cea84.png">

**Comment by jansav** [comment]
There’s multiple things that need to be fixed in order to make it work properly.

1. Library package core needs to make all of it’s dependencies external, which means that they are not included in the bundle.
2. OpenLens monorepo needs to be changed to use Yarn/NPM workspaces which means that all dependencies are hoisted to root level. This ensures that there’s only one instance of a dependency. Without this, there’s e.g. react installed in packages/core/node_modules and packages/open-lens/node_modules .
3. The second bullet leads to unknown amount of stuff that needs to be fixed, because it seems that building core doesn’t work properly with workspaces  being enabled.

**Comment by Nokel81** [comment]
Moving to 6.5.0 since the rest of this work can be delayed until after 6.4.0
