### ISSUE TITLE
Resource templates missing

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#7125]
Try to open a "Create Resource" tab:

![Screen Shot 2023-02-08 at 5 21 12 PM](https://user-images.githubusercontent.com/40840436/217664642-a50aa0c0-49b5-437f-b44c-ab9b967ffd96.png)

happens on dev (`npm run dev`) with latest master

**Comment by jweak** [comment]
Also in the alpha build

**Comment by yimiaoxiehou** [comment]
me too，after upgrade.
![image](https://user-images.githubusercontent.com/27064164/218398923-f19de5b5-bf76-4efb-ac79-da0e4123c046.png)
![image](https://user-images.githubusercontent.com/27064164/218399011-eadcf2d6-d3c3-4107-8cc3-978dc1fa51d1.png)

**Comment by Nokel81** [comment]
This has been fixed.
