### ISSUE TITLE
Extension does not finish installing

### ISSUE THREAD

**Issue by jim-docker** [kontena/lens#7141]
**Describe the bug**
When specifying an extension by URL the install just spins. Tried with @nevalla/kube-resource-map and @mirantis/lens-extension-cc

**Screenshots**
This happened trying to install after doing other operations, including extension management, in lens: 
![Screen Shot 2023-02-10 at 5 57 45 PM](https://user-images.githubusercontent.com/40840436/218222653-0e42f283-3fa5-40dd-8400-f3b884ed72c7.png)

This happened trying to install right after launch:
![Screen Shot 2023-02-10 at 6 30 54 PM](https://user-images.githubusercontent.com/40840436/218222931-11165925-1175-4f68-8790-d5bfc2ea3c51.png)

**Environment (please complete the following information):**
- Lens Version:  2023.2.101253-alpha
- OS: OSX

**Comment by Nokel81** [comment]
This is even worse than expected. It isn't that it fails to install (it will eventually), but instead it seems to hard lock the renderer which entirely freezes
