### ISSUE TITLE
Failure to launch after February update

### ISSUE THREAD

**Issue by agrondemiraj** [kontena/lens#7142]
Lens 6 fails to load after the update of 9th of February.
Application gets stuck in the Loading page.

Is there any log file being generated in Windows where I can see any possible issue?

**Comment by Nokel81** [comment]
Which version specifically are you talking about?

**Comment by agrondemiraj** [comment]
Version installed is: 2023.1.110749-latest on a Windows 10
Installed on 2/9/2023

**Comment by Nokel81** [comment]
Would you be able to share some logs or a screenshot please?

**Comment by agrondemiraj** [comment]
I was actually looking where can I find some logs to troubleshoot but couldn't find.

Due to security reasons I can not upload a screenshot, but basically it is stuck at this page as this issue here:
https://github.com/lensapp/lens/issues/1195

**Comment by jhajjaarap** [comment]
also on mac mini m1
[error message](https://1drv.ms/u/s!And1Pali3UZrg5Bgx5GvXytK-4vbqQ?e=fcLtqY)

**Comment by Nokel81** [comment]
Logs can be found under `~/Library/Logs/Lens`

**Comment by agrondemiraj** [comment]
I ran `C:\Users\{user}\AppData\Local\lens-updater\installer` once and it finally started.
I could not find `~/Library/Logs/Lens`

However, this is a very weird issue, I could not manage my cluster for 3 days !
