### ISSUE TITLE
Blank screen after installation

### ISSUE THREAD

**Issue by neeldview** [kontena/lens#7173]
**Describe the bug**

installed Lens and connected with my EKS 1.24 but after that is showing a blank screen, using version 6.3 and in Mac m1
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/118246710/219278168-2511d1fa-1b4c-4d7e-b402-71194235b555.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/118246710/219278187-55d5a1db-347f-4910-b5e4-743d48ed0e08.png">

**Comment by kinyat** [comment]
https://github.com/lensapp/lens/issues/6940
This is probably the same issue. I have also reported that EKS has the same issue.

**Comment by neeldview** [comment]
closing it
