### ISSUE TITLE
PodSecurityPolicy deprecates

### ISSUE THREAD

**Issue by matti** [kontena/lens#7190]
* What is changing?
PodSecurityPolicy (PSP) was deprecated [1] in Kubernetes version 1.21 and has been removed in Kubernetes version 1.25 [2]. If you are using PSPs in your cluster, then you must migrate from PSP to the built-in Kubernetes Pod Security Standards (PSS) or to a policy as code solution before upgrading your cluster to version 1.25 to avoid interruption to your workloads.

**Comment by Nokel81** [comment]
This has been completed as part of the release of the new UI
