### ISSUE TITLE
Lens doen't display HPA and PDB configuration

### ISSUE THREAD

**Issue by mykolaichuk** [kontena/lens#7208]
1. Go to the Config menu
2. Click on HPA / Pod Disruption Budget
3.  See errors:
![image](https://user-images.githubusercontent.com/7926159/220568669-dd7ca0e5-1bac-40ee-8e59-908d6a5ec915.png)
![image](https://user-images.githubusercontent.com/7926159/220568733-f0abafb0-48f6-4a2b-b5ff-9fab96844853.png)

On the clusters, we have HPA with autoscaling/v2 API version and for PDB apiVersion: policy/v1.

Lens version: 2023.1.110749-latest which is installed on Windows 11.

**Comment by Nokel81** [comment]
This is fixed by #6906
