### ISSUE TITLE
Show "No Updates Available" after manually checking for updates

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#7228]
**What would you like to be added**:
Show something like the following:

<img width="277" alt="Lens-Update-Dialog" src="https://user-images.githubusercontent.com/8225332/220932091-ec066280-5b63-49e8-9049-f70217ba40de.png">

when the user manually checks for updates and no updates are found.

**Why is this needed**:
Current behaviour feels like something is broken because only the tray icon updates and only for a short while so it seems like nothing has been done.

**Environment you are Lens application on:**

- Kubernetes distribution: all
- Desktop OS: all

**Comment by gabriel-mirantis** [comment]
Would it make more sense to use a notification rather than a popup?  

Looking over the existing usage in the code it seems that we use `showMessagePopup` with only the about window, 
but use the `show[Error|Info|Success]Notification` about 50 times.

**Comment by Nokel81** [comment]
Someone can check for notifications even if the main window is closed. I guess we could show the main window first and then show a notification.... but since all the logic for checking for updates is already on `main` that seems like a lot of extra effort.

**Comment by gabriel-mirantis** [comment]
For the case that the main window is closed we want it to open the main window and show the update status in the same way that the about window will trigger the main window to be shown?

**Comment by Nokel81** [comment]
I don't think we want to open the main window if no update is found (as is the current behaviour). I think showing a pop up is fine.
