### ISSUE TITLE
How to download the open source version ?

### ISSUE THREAD

**Issue by pptfz** [kontena/lens#7249]
How to download the open source version, I am for personal use, there is no need to use the paid version

<img width="556" alt="iShot_2023-03-01_15 32 57" src="https://user-images.githubusercontent.com/44946546/222073710-6f81f71e-122e-4cfe-8263-9d738aa25ffb.png">

![iShot_2023-03-01_15 33 10](https://user-images.githubusercontent.com/44946546/222073818-fbafd9b7-c624-4480-959b-2e79fa60d4e8.png)

I download it here, but after opening it appears the interface above which needs to be logged in. I have downloaded it before, and it can be opened directly after installation without landing

![iShot_2023-03-01_15 36 46](https://user-images.githubusercontent.com/44946546/222074102-779c1835-da34-401f-80e4-d86e96f203c2.png)

**Comment by pptfz** [comment]
I am prompted that I have not selected a valid subscription

<img width="571" alt="iShot_2023-03-01_15 43 41" src="https://user-images.githubusercontent.com/44946546/222075616-cf4de19c-6bd0-4bbc-ad83-09c31d9f8ffe.png">

**Comment by alebcay** [comment]
The fully OSS version is available from https://github.com/MuhammedKalkan/OpenLens.

**Comment by pptfz** [comment]
> 完整的 OSS 版本可从https://github.com/MuhammedKalkan/OpenLens获得。
Ok, thank you.
