### ISSUE TITLE
Attach to Pod, Pod Shell, Pod Logs buttons are missing in 6.4.0

### ISSUE THREAD

**Issue by MobsMao** [kontena/lens#7268]
**Describe the bug**
When open a pod detail, Attach to Pod, Pod Shell, Pod Logs buttons are missing. While in 6.2.5 are there.

**To Reproduce**
1. open a pod detail
2. Attach to Pod, Pod Shell, Pod Logs buttons are missing

**Expected behavior**
Buttons are there.

**Screenshots**
![image](https://user-images.githubusercontent.com/9639541/222627126-9f6293fc-4ab4-40fb-9e46-1ad125302553.png)

**Environment (please complete the following information):**
- Lens Version: 6.4.0
- OS: OSX
- Installation method (e.g. snap or AppImage in Linux):

**Comment by mfriess2** [comment]
I have the same problem on MacOS (6.4.1) and these 3 buttons are my main reason to use Lens!
Quick fixing would be appreciated very much.
On the meanwhile I think I have to downgrade once more.

**Comment by smmathews-cision-us** [comment]
same problem on MacOS (6.4.2). Have to revert to a usuable version.

**Comment by ps68060** [comment]
Same issue on Windows 10

**Comment by kappa8219** [comment]
Funny, v6.4.0-alpha.4, v6.4.0-beta.17. 21 PRE-versions and such a bug.

**Comment by Jeansen** [comment]
> same problem on MacOS (6.4.2). Have to revert to a usuable version.

Same here but on Linux. No Log or Shell buttons in 6.4.2.

**Comment by alebcay** [comment]
Per the project maintainers, this is intended and not a bug. See earlier discussion and workaround in https://github.com/lensapp/lens/issues/6823.

**Comment by Jeansen** [comment]
@alebcay Thank you for the hint and your extension. Anyway , it evades me why such a crucial extension is not an official extension and an extension, after all. It feels like a care with optional wheels ....

**Comment by kyleli666** [comment]
Add below plugin name in extensions tab
**@alebcay/openlens-node-pod-menu**

**Comment by kappa8219** [comment]
It would be also nice to have kubectl debug extension for distroless images. 
I'v found forgotten one https://github.com/pashevskii/debug-pods-lens-extension for 5th, 4th versions. 
If somebody knows supported alternative, please advise.
