### ISSUE TITLE
CPU, memory and disk metrics cannot be displayed.

### ISSUE THREAD

**Issue by aaluopy** [kontena/lens#7269]
**Describe the bug**
CPU, memory and disk metrics cannot be displayed.

**To Reproduce**
1. Install version 2023.3.21002-latest.
2. Add my k8s cluster.
3. Click on My K8S Cluster--> Settings--> Metrics --> PROMETHEUS select  `Prometheus Operator` --> PROMETHEUS SERVICE ADDRESS select  `monitoring/prometheus-k8s:9090` --> ESC（I am using kube-prometheus）
4. `Metrics are not available due to missing or invalid Prometheus configuration. Open cluster settings`
5. It doesn't work even after following [lens/custom-prometheus](https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md#kube-prometheus). 

**Expected behavior**
Metrics to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/121002916/222626175-b854eac4-a6bc-45ae-8c2e-2a20a699fe2e.png)
![image](https://user-images.githubusercontent.com/121002916/222626299-a2bc5c19-570d-493d-a4b9-3d177133ed52.png)
![image](https://user-images.githubusercontent.com/121002916/222627817-e891d23f-5fd8-49cb-b924-00b50307f41b.png)
![image](https://user-images.githubusercontent.com/121002916/222626413-c2b52796-f480-4542-8647-ec52d8b237ed.png)
![image](https://user-images.githubusercontent.com/121002916/222626754-a7e91ae0-dc98-4320-9e95-f26c6f1023f8.png)
![image](https://user-images.githubusercontent.com/121002916/222626622-d2b59054-927e-4030-bd65-5d988ffd306a.png)

**Environment (please complete the following information):**
- Lens Version: 2023.3.21002-latest
- K8s Version: v1.25.2
- Prometheus Version: v2.41.0
- Node-exporter: v1.5.0
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by manfredipist** [comment]
Same issue on v 2023.3.31330-latest, before updating it was working

**Comment by michelefa1988** [comment]
Following, same issue here, Any workarounds / dates when it will be fixed?

**Comment by Preen** [comment]
+1

**Comment by yinyu985** [comment]
+1

**Comment by yinyu985** [comment]
me too

**Comment by Nokel81** [comment]
Thanks for the details. Though I will close this as a duplicate of #7264

**Comment by sunxunkang** [comment]
I have the same problem，version 2022.11.251411-latest,I try to update to  v2023.3.71735-latest (2023/3/8), it does not work still.

**Comment by sunxunkang** [comment]
> 我有同样的问题，版本2022.11.251411-latest，我尝试更新到v2023.3.71735-latest (2023/3/8)，还是不行。

and I have tried all the promethes configure methods
