### ISSUE TITLE
[Windows]After updating the latest version,i cannot see all the pods

### ISSUE THREAD

**Issue by randychen2046** [kontena/lens#7270]
**Describe the bug**
[Windows]After updating the latest version,i cannot see all the pod

**To Reproduce**
1、Go to update Lens in application.

 
**Screenshots**
![image](https://user-images.githubusercontent.com/29883352/222627692-d9af2720-d088-4edb-8763-d8a71af0e299.png)

**Comment by weixiao800** [comment]
same issue for MAC

**Comment by faisal6621** [comment]
I had the same issue. Once quit the Lens app (from the system tray icon in windows) and then try again.

**Comment by phantomk** [comment]
same issue Mac

Lens: 2023.3.21022-latest
Extension API: 6.4.0
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2
© 2023 Mirantis, Inc.

error: 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/3520021/222684788-d6a060a0-bbc4-4891-8cc5-f35920cecf81.png">

**Comment by jrsimmons-trevipay** [comment]
Same issue!! 
On Mac
Lens: 2023.3.31330-latest
Extension API: 6.4.1
Electron: 19.1.9
Chrome: 102.0.5005.167
Node: 16.14.2
© 2023 Mirantis, Inc.

Missing menu items:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/122472927/222781545-4ac10831-2447-4625-823f-6f24df15fbb9.png">

Security Center also not loading:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/122472927/222781645-3e673a10-db9f-4158-a4a6-ef689a695eca.png">

**Comment by Nokel81** [comment]
Could you please post the whole object of those `failedToLoad` errors? Thanks

**Comment by Nokel81** [comment]
Also do you see any namespaces in the namespace dropdown?

**Comment by jrsimmons-trevipay** [comment]
Where would I get the whole object? That's all that's displayed on the screen.

As for namespaces, there isn't any:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/122472927/222808829-222ccad5-2406-4b7a-a8a0-6abf4ddd5084.png">

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/122472927/222808775-f95cfc84-c9b3-4608-a87a-6f7f72377e70.png">

**Comment by Nokel81** [comment]
@jrsimmons-trevipay If you open up the devtools console it should be there.

**Comment by Nokel81** [comment]
Would you be able to provide the output of the following?

```
kubectl proxy
```

and then in a different terminal (changing the namespace for whatever namespace you have access to)

```
curl -H "Content-Type: application/json" -X POST 127.0.0.1:8001/apis/authorization.k8s.io/v1/selfsubjectrulesreviews --data '{ "apiVersion": "authorization.k8s.io/v1", "kind": "SelfSubjectRulesReview",  "spec": { "namespace": "default" }}'
```
 
This would be very helpful.

**Comment by jrsimmons-trevipay** [comment]
FWIW, it works locally. It just can't access any of my remote instances in my AWS k8s cluster.

Logs attached trying to connect to one of the remotes namespaces:
[lens.app-1677872304836.log](https://github.com/lensapp/lens/files/10885599/lens.app-1677872304836.log)


```
$ curl -H "Content-Type: application/json" -X POST 127.0.0.1:8001/apis/authorization.k8s.io/v1/selfsubjectrulesreviews --data '{ "apiVersion": "authorization.k8s.io/v1", "kind": "SelfSubjectRulesReview",  "spec": { "namespace": "default" }}'
{
  "kind": "SelfSubjectRulesReview",
  "apiVersion": "authorization.k8s.io/v1",
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {

  },
  "status": {
    "resourceRules": [
      {
        "verbs": [
          "create"
        ],
        "apiGroups": [
          "authorization.k8s.io"
        ],
        "resources": [
          "selfsubjectaccessreviews",
          "selfsubjectrulesreviews"
        ]
      },
      {
        "verbs": [
          "*"
        ],
        "apiGroups": [
          "*"
        ],
        "resources": [
          "*"
        ]
      }
    ],
    "nonResourceRules": [
      {
        "verbs": [
          "get"
        ],
        "nonResourceURLs": [
          "/api",
          "/api/*",
          "/apis",
          "/apis/*",
          "/healthz",
          "/livez",
          "/openapi",
          "/openapi/*",
          "/readyz",
          "/version",
          "/version/"
        ]
      },
      {
        "verbs": [
          "*"
        ],
        "nonResourceURLs": [
          "*"
        ]
      },
      {
        "verbs": [
          "get"
        ],
        "nonResourceURLs": [
          "/healthz",
          "/livez",
          "/readyz",
          "/version",
          "/version/"
        ]
      }
    ],
    "incomplete": false
  }
}
```

Also, not sure if this is helpful but all my connections are listed mulitple times (some are different numbers but most are repeated 4 or 5 times):
<img width="200" alt="image" src="https://user-images.githubusercontent.com/122472927/222812361-738e0429-1630-463d-b8ea-e8a47d0b79cc.png">

**Comment by Nokel81** [comment]
@jrsimmons-trevipay Thanks for the information. About those duplicates. Are they listed with the same "file" label or different ones?

**Comment by jrsimmons-trevipay** [comment]
Ok, they are different files. Thanks for that. I couldn't see the full file path because there's no way to adjust the column width (hint hint feature request lol). Once I widened my entire window I could see more of the name.  For some reason it's reading my backup files that I make from time to time. I name them like config.bku.20220823 so it must be just looking for any file starting with `config`. I don't remember it doing that before. I moved them and now only have the actual current connections from `.kube/config`.

**Comment by Nokel81** [comment]
You should be able to scroll horizontally within that column for the time being

**Comment by Nokel81** [comment]
We by default read all the files in `~/.kube`. You can change this by going to the "Kubeconfig sync" settings under your user settings page.

**Comment by dgodfrey206** [comment]
After updating there's no more information about my cluster. Pods, deployments, StatefulSets, etc. Everything's gone:

![image](https://user-images.githubusercontent.com/916261/222872928-c32be2c0-e0aa-41f9-b690-ba250adf01d8.png)

**Comment by mehradsadeghi** [comment]
Same issue here.

Every time I update Lens a new headache starts...

**Comment by mehrdadep** [comment]
same issue with debian

**Comment by randychen2046** [comment]
when will this be fixed?@Nokel81

**Comment by msa0311** [comment]
@randychen2046 we are working hard on a fix, will be solved hopefully in a couple of hours. Sorry for the circumstances.

**Comment by Nokel81** [comment]
This has been fixed and released

**Comment by jrsimmons-trevipay** [comment]
Thank you for working through this issue!

**Comment by dgodfrey206** [comment]
> This has been fixed and released

![image](https://user-images.githubusercontent.com/916261/223508043-1088916c-53ac-46a7-bd6f-ddc7c95df37c.png)
