### ISSUE TITLE
[Windows] lens keep forgetting last selected namespace after recent update

### ISSUE THREAD

**Issue by faisal6621** [kontena/lens#7271]
**Describe the bug**
After latest update of lens app `2023.3.21022-latest` the cluster browser do not remember the last selected namespace. 
![image](https://user-images.githubusercontent.com/1015900/222679089-caa7fa86-f085-4606-aa92-2739e49296cc.png)

**To Reproduce**
1. Update the Lens app to latest `2023.3.21022-latest`.
2. Browse any local cluster.
3. Select any `Workloads` or `Config` and chose a namespace (other than `All namespaces`)
4. Quit the Lens app and repeat step `2` and `3` above. But this time in step `3` last selected namespace should be used instead of `All namespaces` again.

**Expected behavior**
As described in Step 4 of Steps to reproduce above.

**Environment (please complete the following information):**
- Lens Version: 2023.3.21022-latest
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Installer

**Comment by alexplavan** [comment]
Same with

- OpenLens: 6.4.0
- Extension API: 6.4.0
- Electron: 19.1.9
- Chrome: 102.0.5005.167
- Node: 16.14.12

**Comment by Nokel81** [comment]
Would you be able to provide the output of the following?

```
kubectl proxy
```

and then in a different terminal (changing the namespace for whatever namespace you have access to)

```
curl -H "Content-Type: application/json" -X POST 127.0.0.1:8001/apis/authorization.k8s.io/v1/selfsubjectrulesreviews --data '{ "apiVersion": "authorization.k8s.io/v1", "kind": "SelfSubjectRulesReview",  "spec": { "namespace": "default" }}'
```
 
This would be very helpful.

**Comment by saad-littera** [comment]
+1

**Comment by Nokel81** [comment]
This will be fixed by https://github.com/lensapp/lens/pull/7279

**Comment by Nokel81** [comment]
This has been fixed and released
