### ISSUE TITLE
Cannot get real configmap data, if configmap's data have same Key name.

### ISSUE THREAD

**Issue by kyleli666** [kontena/lens#7295]
**Describe the bug**
Cannot get real configmap content, if configmaps having same Key name.

**To Reproduce**
1. create some configmaps with same key names but different value
![image](https://user-images.githubusercontent.com/93997542/223298617-572af34c-9487-4fd5-a774-479bd910e571.png)

2. Click on a configmap to see its data content
3. Switch to another configmap to see that data content, but you'll see the content is still the first configmap's

**Expected behavior**
See the real content of the configmap I click on.

**Environment (please complete the following information):**
- Lens Version: lens 2023.3.62352, extension api 6.4.3
- OS:  Windows
- Installation method (e.g. snap or AppImage in Linux): windows installation

**Comment by jw-maynard** [comment]
Any timeline on this bug? It could be a dangerous bug if you were to save the wrong configmap back using the save button in the UI.

**Comment by UnleashSpirit** [comment]
Hello,
I confirm the bug, really disturbing as you don't see it the firsts times

**Comment by Noksa** [comment]
Encountered the same.
Does it work as expected in one of old versions? Or this bug exists in all versions?

**Comment by hardenchant** [comment]
I confirm it too. Had a dumb moments with that bug :((

**Comment by kyleli666** [comment]
> Encountered the same. Does it work as expected in one of old versions? Or this bug exists in all versions?

It works in extension api 6.2.5

**Comment by plevart** [comment]
I have already lost some important config data because of this bug. Very dangerous. I had to add comments to the top of the entries to remind me which content I'm actually observing. You have to close connection to k8s cluster and re-open it to flush the cache and get correct content. Please fix this. Thanks.

**Comment by plevart** [comment]
Update: It seems that 6.5.0-alpha.3 fixes this. No mention in the CHANGES files though.

**Comment by philbert101** [comment]
config map bug 6.4.3  GUI  property not matches  yaml file

**Comment by tomer-ds** [comment]
Big +1!!!! Very disturbing and dangerous 
👍🏼

**Comment by Noksa** [comment]
In the name of all that's holy, why hasn't this been fixed yet?

**Comment by tomer-ds** [comment]
There is clearly an alpha with a fix... just hoping beyond hope that it is released quickly

**Comment by kukkjanos** [comment]
This is a serious error that would be treated as a high priority.

**Comment by aleksfront** [comment]
Until bugfix created: there is a workaround using page reload `cmd+r` to clear up stale values. Also, it relates to details panel:

* if the details open, then toggling between the config-maps displays the correct information
* if the details closed in-between viewing the config-maps, that we are "stuck" in the last shown `ConfigMap` even on latest version (6.5.0)


https://user-images.githubusercontent.com/9607060/228225021-a8d6a633-765c-4b69-a0b9-42eac5706519.mov

**Comment by plevart** [comment]
So this bug is not important to you and so it was removed from further milestones?

I'm trying to use 6.5alpha3, but it keeps self-updating back to 6.4.xx releases each time I restart the app. Very painful. Is it possible to stop this nonsense? 6.5 should not auto-downgrade to 6.4 regardless of release status. Please!

**Comment by kyleli666** [comment]
@plevart you can set the update channel to Alpha in preference.
![image](https://user-images.githubusercontent.com/93997542/230521974-d9058cfe-c0ea-4809-a5cf-e510d6871a8e.png)
Even 6.5alpha3 still sometimes has bug in this issue, and I also found the pod log view is not stable.

**Comment by panuhorsmalahti** [comment]
Reproduced on 2023.4.141316-latest

**Comment by panuhorsmalahti** [comment]
I couldn't reproduce this on 6.5.0-alpha.6.

**Comment by aleksfront** [comment]
@kyleli666 Can you elaborate pod log view is not stable?

**Comment by kyleli666** [comment]
Hi @aleksfront 
In 6.5.0-alpha.3, the pod log view is usually visible, but when looking through the logs this screen flashes out from time to time.
![image](https://user-images.githubusercontent.com/93997542/232504054-f5087557-ea78-4b66-8f81-d1ce4dc462e9.png)

**Comment by panuhorsmalahti** [comment]
Closing this issue, lets re-open if it occurs on a Lens release with 6.5.0.
