### ISSUE TITLE
Lens Metrics get wrong values of CPU, RAM

### ISSUE THREAD

**Issue by karkill** [kontena/lens#7299]
**Describe the bug**
I use the m6i.large instance (AWS), it is in the general purpose family with 2 vCPUs, 8.0 GiB RAM but in Lens I see it double (4 vCPUs, 15.265 GiB RAM)
**Screenshots**
![image](https://user-images.githubusercontent.com/44264041/223310776-f1ff058f-86f0-4517-9f22-253e007502e5.png)
![image](https://user-images.githubusercontent.com/44264041/223311457-f5ca11e8-c94e-47df-9f5b-b3f019999225.png)

**Environment (please complete the following information):**
- Lens Version: 2023.3.21022-latest
- OS: MACOS

**Comment by Nokel81** [comment]
Do you have multiple prometheus installations installed on this cluster?

**Comment by karkill** [comment]
I have only one prometheus installed by [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

**Comment by massimeddu-sj** [comment]
Hi have a similar problem with POD memory metric.

At pod level I see the the double of the real value, while at container level I see the right value. (The pod has just one container). See attached screenshot. I also have a Prometheus stack installed with [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).


![image (12)](https://user-images.githubusercontent.com/118254552/224035116-30b1548d-b203-4873-80c1-e0bc6bbe0dc8.png)
![image (13)](https://user-images.githubusercontent.com/118254552/224035120-cd2abecf-50b2-437d-970d-2b3d593993ac.png)

Lens version: 2023.3.71735-latest
OS: Linux

It looks a regression with the latest version of Lens, because with older version of Lens I see the correct value.

**Comment by kyleli666** [comment]
@jweak my Prometheus is bitnami/kube-prometheus chartVesion8.3.12 appVersion0.63.0
I have POD memory metric doubled, while container memory is correct. Node metrics are also correct.
My cluster is EKS v1.24
this bug happen with all deployments
the metrics were correct in Lens Extension API v6.2.5

**Comment by andrezaycev** [comment]
+1

<img width="279" alt="image" src="https://user-images.githubusercontent.com/9984761/224540885-7c17fe48-8e5e-49f7-819c-1f472c19bcdd.png">

**Comment by saad-littera** [comment]
+1

**Comment by centromere** [comment]
These are the values being summed together:

<img width="1785" alt="Screenshot 2023-03-22 at 12 21 47" src="https://user-images.githubusercontent.com/543423/226973322-74ebc008-1fef-4f63-9fbe-9aa6c6e81edc.png">

Related code: https://github.com/lensapp/lens/blob/4b1d740d6154d06b655cc106b09b5a39aad2703a/packages/core/src/main/prometheus/operator-provider.injectable.ts.ts#L79-L80

The problem may have been introduced in [this commit](https://github.com/lensapp/lens/pull/6679/commits/923a9884eeba33a2eb5a4eedc3e0b58ecb202bb1).

**Comment by Nokel81** [comment]
@centromere Thanks for this. I will add a way to specify which version to use.

**Comment by jseletz-rave** [comment]
+1 - I am seeing double the CPU and Memory requests for containers than what are actually requested.

**Comment by 7wingfly** [comment]
I've noticed that it starts off with the correct metrics when the nodes are created but then suddenly doubles everything after a few minutes
![image](https://user-images.githubusercontent.com/13077550/235696425-b6592520-b985-4ad3-8d8c-914bcdcf5a30.png)

**Comment by vilianvenkov** [comment]
+1 
<img width="1029" alt="Screenshot 2023-05-10 at 18 34 04" src="https://github.com/lensapp/lens/assets/22633227/f2f01887-5307-4991-a1b2-c706d5bd95d8">

**Comment by jweak** [comment]
Hey guys, I'm unable to reproduce this issue with https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack installed. Could you guys share a bit more about your setup?

What kube version are you using? Which version of the kube-prometheus-stack are you using? Does this bug happen with all deployments?  Are you all having both node and pod metrics doubled? 

No need to post anything sensitive but some example would go a long way fixing, thanks!

**Comment by jseletz-rave** [comment]
I am running with the "Builtin Metrics Provider" automatically installed by Lens via the cluster settings.  K8s 1.23.  All deployments.  Both Node and pod metrics are doubled.

![image](https://github.com/lensapp/lens/assets/116828076/9e00a0fc-b98c-46f6-8c32-0f61cfa5b950)

**Comment by lghinet** [comment]
hello, 
I have kube-prometheus-stack-45.26.0 installed on a new AKS 1.26.3 (running 
mcr.microsoft.com/oss/kubernetes/metrics-server:v0.6.3 in 2 replicas  )

pod memory is doubled

**Comment by karkill** [comment]
Hello bro,
I use `kube-prometheus-stack` version **45.4.0** (app version v0.63.0) in EKS 1.23.
Errors: CPU, RAM of nodes is doubled.
Lens: **2023.5.120950-latest**
I have metrics-server run with 2 replicas but I try scale to 1 but still errors.
![image](https://github.com/lensapp/lens/assets/44264041/c72414a3-7679-4cc9-aa7b-fdc193a1d059)

**Comment by AleksuKey** [comment]
Same problem here!

**Comment by jweak** [comment]
Alright, I think there are two different issues. One with double pod metrics which is from the referred commit and double node metrics which is something different.  We will probably have a setting that let's you change the query described in this PR https://github.com/lensapp/lens/pull/7777 

The node double metrics is still a bit unclear why this happens. The query has not changed in a while.

**Comment by JaySeletz** [comment]
Any progress on this?  It's been broken for quite a while?

**Comment by gavinclarkeuk** [comment]
Not sure if it is relevant, but I'm seeing an issue where the requests for Succeeded pods (e.g. from Jobs) are being included in the Node level metrics. This means the node level graphs are always overstating the current usage.

**Comment by karkill** [comment]
Today, when I checked `kube_node_status_capacity` in prometheus, I saw another data from **kubecost**. After uninstalling it, everything was back to normal. I'll close this issuses now. Thank for help.
![image](https://github.com/lensapp/lens/assets/44264041/be02811f-db6a-425e-ac54-f9cfdc9b2552)

**Comment by sawaca96** [comment]
Maybe if I use metrics-server and kube-state-metrics together, it will double?

**Comment by tonyemiliano** [comment]
I’m using Lens 2023.9.290703-Latest, Kube-Prometheus-stack version: 51.2.0
appVersion: v0.68.0
Im using GKE 1.24.15-gke.1700

I installed in the "monitoring" namespace Kube-Prometheus-stack, I’m having problems only in the visualization of the graphics of the nodes. Doesn’t seem to double the value, doesn’t make much sense to me.

All nodes there have the wrong memory value relative to the graph when we click on the node that is where it seems to be right.

![image](https://github.com/lensapp/lens/assets/3487566/09b9d020-97f5-444f-aed2-8bfb32682988)


I’ve removed everything from namespaces that had other Prometheus installations. Everything seems to work perfect. Minus the memory graphics on the nodes page.

Strange that in my other staging cluster with the same settings is working.

**Comment by catemiko** [comment]
> I’m using Lens 2023.9.290703-Latest, Kube-Prometheus-stack version: 51.2.0 appVersion: v0.68.0 Im using GKE 1.24.15-gke.1700
> 
> I installed in the "monitoring" namespace Kube-Prometheus-stack, I’m having problems only in the visualization of the graphics of the nodes. Doesn’t seem to double the value, doesn’t make much sense to me.
> 
> All nodes there have the wrong memory value relative to the graph when we click on the node that is where it seems to be right.
> 
> ![image](https://user-images.githubusercontent.com/3487566/272625779-09b9d020-97f5-444f-aed2-8bfb32682988.png)
> 
> I’ve removed everything from namespaces that had other Prometheus installations. Everything seems to work perfect. Minus the memory graphics on the nodes page.
> 
> Strange that in my other staging cluster with the same settings is working.

That issue may occur when you have more than one **kube-prometheus** **kubelet** in namespace **kube-system**. You can see all services in **kube-system** by running `kubectl -n kube-system get service -o wide`

**Comment by hyp3ri0n-ng** [comment]
Anyone know why this issue is marked as closed? I'm still seeing the same on my lens installation version 2024.3.70925-latest) with a desktop pro subscription. In fact it seems when I close and open lens everything has doubled again.... one of my pods is now using 90GB of memory (it's actually using 6-9)...

Would be good to know if there is anything that's being worked on with this issue. If not I'm going to have to cancel that subscription :-/ and I really don't want to. Lens has all the info I need and it's presented REALLY nicely. The big problem is that it just uhh, doesn't work....
