### ISSUE TITLE
Cronjob tab missing from OpenLens 6.4.0+

### ISSUE THREAD

**Issue by JustMaris** [kontena/lens#7301]
**Describe the bug**
OpenLens 6.2.5 was functionally the best version yet. Many issues that were with OpenLens 6.3.0 have been addressed in 6.4.0, but there is still a problem with the Cronjob tab missing.

**To Reproduce**
Install OpenLens 6.4.0+

**Expected behaviour**
The cronjob tab is present

**Screenshots**

![image](https://user-images.githubusercontent.com/24903212/223366978-be620224-3ff1-4dd4-b707-cc6912487093.png)
**Environment (please complete the following information):**
- Lens Version: 6.4.0 - 6.4.3
- OS: Ubuntu 22.10
- Installation method (e.g. snap or AppImage in Linux): deb image

**Comment by dvdgitman** [comment]
Is it possible to downgrade the version on windows?  - having the same issue

**Comment by Nokel81** [comment]
Fixed by https://github.com/lensapp/lens/pull/7303
