### ISSUE TITLE
trackpad scrolling stops

### ISSUE THREAD

**Issue by matti** [kontena/lens#7310]
mac, using alpha channel latest (just updated)

scrolling from right works, trackpad doesn't. relaunching lens helps

https://user-images.githubusercontent.com/3893/223501745-c543bac7-13c9-4ceb-bb73-8b8bf4f32d26.mp4

**Comment by janosmiko** [comment]
It occurs when you change the cluster and change back to the previous one. The only way to fix this issue is to restart Lens.

Lens version:
Lens: 2023.3.100736-latest
Extension API: 6.4.6

**Comment by turbosnail** [comment]
scroll stoped when i just change screen of resources in one cluster but i have 2 connected clusters. disconnect from one cluster is fixing issue

**Comment by jakolehm** [comment]
Fixed in https://github.com/lensapp/lens/pull/7349
