### ISSUE TITLE
Add override for AWS config location

### ISSUE THREAD

**Issue by stefan-matic** [kontena/lens#7320]
**What would you like to be added**:
Ability to override the location of the `~/.aws/config` and `~/.aws/credentials` the same way we override kubeconfig

**Why is this needed**:

When the location of the AWS config file is in a non-default localtion (`~/.aws/config`) Lens is not able to connect to the cluster, therefore forcing to keep all the configs for different environments in that single config on that specific location.

**Environment you are Lens application on:**
- Kubernetes distribution: AWS EKS (1.24/1.25)
- Desktop OS: KDE Neon 5.27.2

**Comment by Nokel81** [comment]
Is it possible for you to specify a file path that is relative to the kubeconfig path?

**Comment by stefan-matic** [comment]
@Nokel81 in my specific use case yes. It would be `../.aws/config`.
Is there a possibility to edit this somewhere in Lens or supply it in the kubeconfig itself?

**Comment by Nokel81** [comment]
You should be able to just supply it directly in the kubeconfig. We set the `CWD` env var when executing out `kubectl proxy` to the directory containing the kubeconfig,

**Comment by stefan-matic** [comment]
Got it, thanks @Nokel81 !

I've managed to get it working after supplying the following to the kubeconfig env object:

```
- name: AWS_CONFIG_FILE
  value: ../.aws/config
```

Unfortunately I haven't found a way to directly supply this when running the `aws eks update-kubeconfig` command.
According tot the [AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html), it cannot be done:

> AWS_CONFIG_FILE
> Specifies the location of the file that the AWS CLI uses to store configuration profiles. The default path is ~/.aws/config.
> 
> You can't specify this value in a named profile setting or by using a command line parameter.

The only workaround that comes to mind is using `sed` to inject the above block into the all the contexts of the kubeconfig. Here's the command that worked for me:

`sed -i '/^      env:.*/a\      - name: AWS_CONFIG_FILE\n        value: ../.aws/config' .kube/config`

The spaces are needed for the right indent. There's probably a less "dirty" way of doing this injection but it still appears to work fine and doesn't cause issues
