### ISSUE TITLE
Scrolling is broken

### ISSUE THREAD

**Issue by ReggieCarey** [kontena/lens#7322]
**Describe the bug**

Using Lens on MacOS, I need to scroll to see the resources.  For some reason, scrolling becomes broken in one or all of the open view areas.  Basically, I cannot scroll through the visible resources.  My only recourse is to kill the application and restart.  

Also, I'd like to point out that I can no longer use the "Support" button in the lower right hand corner.

I have multiple k8s clusters.  The broken scrolling is broken differently per k8s cluster being viewed.

Refreshing the page with "CTRL-R" does not fix the problem.
Switching to another k8s cluster does not fix the problem (in the original viewed k8s cluster).

In this particular experiment, closing connections to the other k8s clusters appears to have cleared the problem (temporarily)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by krishna2vinayak** [comment]
I found with the latest 6.4.6 version, the scrolling bar gets stuck when two or more clusters are opened simultaneously. When I connect to the second cluster, the first cluster page will get the scrolling stuck. However, I can stroll by manual dragging the scroll bar. When I disconnect the second cluster page, the scroll gets back to normal.
