### ISSUE TITLE
Important Upgrade - Deprecation of "k8s.gcr.io" used in kube-state-metrics

### ISSUE THREAD

**Issue by nikos445** [kontena/lens#7337]
**What would you like to be added**:
According to official [announcement](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/) the `k8s.gcr.io` repository will be deprecated soon. Please update the `k8s.gcr.io` of `kube-state-metrics`, that lens uses to deploy metrics, to the new image repository "registry.k8s.io".

The new image url can be: `registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1`  (I have tested on a HA kubeadm cluster and this works fine)

**Why is this needed**:
`k8s.gcr.io` will freeze on `3rd of April 2023`

**Environment you are Lens application on:** 
`any`

- Kubernetes distribution: **All**
- Desktop OS: **Ubuntu 22.04 - 64bit**

**Comment by DanRStevens** [comment]
Any updates on this? I noticed we're now past the registry freeze date.

**Comment by Nokel81** [comment]
This has been fixed

**Comment by DanRStevens** [comment]
Looks like this was fixed a while back. Add links to relevant PRs in case anyone else was interested:
- https://github.com/lensapp/lens/pull/7338
- https://github.com/lensapp/lens/pull/7373

Thank you for the fix.
