### ISSUE TITLE
HPA Custom metrics not shown

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#7343]
There are messages from the community stating that some of the custom metrics not visible in the HPA list as well as in details panel. However, it is visible in `k9s` and most likely in `kubectl` output.

Example metrics which isn't shown: 
```
resource memory on pods (as a percentage of request)
```

**Comment by panuhorsmalahti** [comment]
Testing on 6.5.0-alpha.6: I can see the memory metrics.

kubectl:
```
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  1043800% (10688512) / 60%
  resource cpu on pods  (as a percentage of request):     0% (1m) / 60%
```

Kube details:
```
Resource memory on Pods
1042000% / 60%
Resource cpu on Pods
0% / 60%
```

**Comment by panuhorsmalahti** [comment]
<img width="1364" alt="Screenshot 2023-04-19 at 10 13 01" src="https://user-images.githubusercontent.com/2162413/232996439-80e927ea-71ae-4016-a2aa-0e2bd12a9188.png">

Custom metrics also seem to work fine.

**Comment by panuhorsmalahti** [comment]
Closing this issue, lets reopen if it occurs on 6.5.0.
