### ISSUE TITLE
Uninstalling Helm release via Lens creates DoS on API server

### ISSUE THREAD

**Issue by ghost** [kontena/lens#7376]
**Describe the bug**
When uninstalling a Helm release through Lens, for large clusters, a huge amount of load is placed on the API server, possibly leading to the control plane going partially or totally offline. The same does not occur when using the Helm CLI.

**To Reproduce**
1. Create a Kubernetes cluster
2. Create a large number of Helm revision secrets in the cluster; in my testing, I used ~5,500 Helm revision secrets from ~240 releases across ~75 namespaces
3. Go to the Lens view for Helm releases and select all namespaces
4. Uninstall a Helm release using the Lens UI
5. Observe massive growth in API server memory utilization, in my testing I was easily able to observe 10–20GB growth and in production this caused one API server replica to exhaust resources on the node and crash

**Expected behavior**
Same behavior as when uninstalling via the Helm CLI

**Screenshots**

API server experiencing severe memory growth when I uninstalled a Helm release in my testing cluster:

![1](https://user-images.githubusercontent.com/69264599/228602969-a3daabe3-8182-4cde-b16a-8bfa6a77874b.png)

Same issue in production, causing one api server replica to go offline when a developer uninstalled a Helm release using Lens:

![2](https://user-images.githubusercontent.com/69264599/228603011-09e366db-d185-4814-b0aa-6ca7cafb59ee.png)

API server audit log from uninstalling in testing cluster, showing that Lens is generating ~30 **un-namespaced** requests to list all secrets in the cluster in roughly 30 seconds. Given the number of secrets in our cluster, that produces a sustained load of **4,700 secrets per second** retrieved, which is obviously inappropriate.

![3](https://user-images.githubusercontent.com/69264599/228603029-c197c36c-a4b3-4f7d-8750-058f7ac193fd.png)

Lens command-line log showing that it is running a huge number of `helm list --all --all-namespaces` commands in parallel, generating the traffic we see in the audit log:

<img width="1920" alt="4" src="https://user-images.githubusercontent.com/69264599/228603067-ca17525b-01a9-4f4f-9b5e-d10386771db0.png">

Audit log from production:

![5](https://user-images.githubusercontent.com/69264599/228603106-4b2357ce-2a14-4f40-817f-1a06b0e2098f.png)

Slow query logs from api server demonstrating that the huge number of concurrent secret list requests are mostly timing out after 60 seconds - these logs are the only thing out of the ordinary for the api server at the time of the incident, and are immediately followed by an out-of-memory crash:

![6](https://user-images.githubusercontent.com/69264599/228603138-7eb5b244-f017-48b7-9347-dc2b3d96a77f.png)

Based on logs and my intuition, I am guessing that the problem occurs because Lens iterates over the 30 secrets (Helm keeps the 30 most recent revisions as secrets in the cluster) to delete them, but each deletion triggers an interface refresh on the frontend, leading to Lens to perform another full list command. It does not seem that there is any frontend rate limiting, or if there is, it does not properly apply to this view.

**Environment:**
- Lens Version: 6.4.6
- OS: macOS 13.2.1
- Installation method: OpenLens

**Logs:**
https://gist.github.com/raxod502-plaid/b1c5b75068aa9d9a41efd234fc19e211

**Kubeconfig:**
```yaml
- cluster:
    server: https://api.redacted
  name: redacted
- context:
    cluster: redacted
    user: iam-redacted
  name: redacted
- name: iam-redacted
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - redacted
      command: aws-iam-authenticator
      env: null
      provideClusterInfo: false
```

**Additional context**
-

**Comment by ghost** [comment]
Confirmed that this still happens (although maybe not as dramatically) even when you don't delete the release through the Lens UI. Simply having Lens open while a single release is uninstalled results in way more traffic than should be generated:

<img width="1141" alt="7" src="https://user-images.githubusercontent.com/69264599/228603579-7e4124b3-ba0c-45aa-ba10-919bcedcb60c.png">

**Comment by Nokel81** [comment]
Thanks for this very detailed report. We will certainly act on this quickly.

**Comment by panuhorsmalahti** [comment]
We could not reproduce this issue anymore on Lens 2024 beta.

**Comment by ghost** [comment]
@panuhorsmalahti What did you change in the code?

**Comment by panuhorsmalahti** [comment]
It's probably related to changes (=fixes) with the table component and refreshing logic. If this bug can be reproduced on Lens 2024 beta we can open the issue.
