### ISSUE TITLE
Download all logs not always working

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#7391]
There is an error after clicking `Download -> All logs`.

```
No logs to download
```

**Comment by aleksfront** [comment]
Update: this happens only for pods which have more than 1 containers.

**Comment by clrothmann** [comment]
Lens: 2023.3.171731-latest
I could reproduce on staging by try downloading keycloak pod log files. Screen attached:

<img width="1441" alt="Bildschirm­foto 2023-03-21 um 13 20 34" src="https://user-images.githubusercontent.com/108513124/226607008-aa15c749-e7cd-4b88-8fa8-f539b4622023.png">


@chenhunghan provided similar screen:

<img width="1459" alt="Screenshot 2023-03-21 at 13 56 19" src="https://user-images.githubusercontent.com/108513124/226605990-a847e122-6344-4cc0-83f9-35eb86d30af0.png">
