### ISSUE TITLE
quitting causes a failure

### ISSUE THREAD

**Issue by marafa-sugarcrm** [kontena/lens#7436]
**Describe the bug**
Whenever i quit openlens 6.4.11 i get a popup saying it quit unexpectedly. even tho i clicked on quit!

**To Reproduce**
1. Go to '...' the file menu and click on "quit"

**Expected behavior**
lens quits nices

**Screenshots**
![Screenshot 2023-03-30 at 8 00 37 AM](https://user-images.githubusercontent.com/69474017/228829392-ca8c2e9b-06a2-4bc6-8ff4-0abdb135a424.png)

**Environment (please complete the following information):**
- Lens Version: 6.4.11
- OS: [e.g. OSX] osx 13.2
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

**Comment by jim-docker** [comment]
Thanks, fix is being worked on
