### ISSUE TITLE
Configmap edit window doesn't refresh content 

### ISSUE THREAD

**Issue by hodolomax** [kontena/lens#7527]
**Describe the bug**
In configmaps page, the data field (editor) doesn't refresh.

**To Reproduce**
1. Select one of the configmap
2. Edit pane opens at the right of the window.
3. Then select another configmap
4. Right edit windows Data (content) section doesn't refresh. Still show previous configmap content.

**Screenshots**

https://user-images.githubusercontent.com/1038861/230558585-2c374d82-ade3-42d6-abd4-f6993549e18a.mp4

---
**Environment (please complete the following information):**
- Lens Version: 2023.4.60821-latest
- Linux Mint 21.1 (Vera)
- Installation method: debian package

**Comment by kyleli666** [comment]
Same issue here in #7295

**Comment by aleksfront** [comment]
Fixed in 6.5.0
