### ISSUE TITLE
Lens Proxy Error when start Lens

### ISSUE THREAD

**Issue by mr-another-username** [kontena/lens#7551]
**Describe the bug**
Got error when start Lens: Lens Proxy Error: Failed connection test d: request to http://127.0.0.1:29633/version failed, reason: self signed certificate

**To Reproduce**
1. Launch Lens application
4. Got error

**Expected behavior**
Application launch correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/100317239/231978964-b91c1d49-aedd-48e1-bf08-be675db8b241.png)

**Environment (please complete the following information):**
- Lens Version: Lens Setup 2023.4.60821-latest.exe
- OS: Windows 10 21H2 19044.1415
- installed from binary file

**Logs:**
info:    ▪ 🔌 Starting LensProxy +0ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:29633 +6ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ [LENS-USER-STORE]: LOADING ... +9ms
info:    ▪ [LENS-USER-STORE]: LOADED from C:\Users\altikhonov\AppData\Roaming\Lens\lens-user-store.json +10ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADING ... +0ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADED from C:\Users\altikhonov\AppData\Roaming\Lens\lens-cluster-store.json +3ms
error:   ▪ 🛑 LensProxy: failed connection test: d: request to https://127.0.0.1:29633/version failed, reason: self signed certificate +789ms

**Kubeconfig:**
Not started without any config

**Additional context**
- Some time earlier, everything worked correctly. After receiving an error, I tried to completely delete the application and cleaning the AppData\Local\Programs\Lens\ and AppData\Roaming\Lens\
The error continues to reproduce
- Has no incorrect records in hosts file, only correct map 127.0.0.1 localhost
- tried version 5.5.4 - starts fine
- curl -v https://127.0.0.1:29633/version
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 29633 (#0)
* schannel: SSL/TLS connection with 127.0.0.1 port 29633 (step 1/3)
* schannel: checking server certificate revocation
* schannel: using IP address, SNI is not supported by OS.
* schannel: sending initial handshake data: sending 162 bytes...
* schannel: sent initial handshake data: sent 162 bytes
* schannel: SSL/TLS connection with 127.0.0.1 port 29633 (step 2/3)
* schannel: failed to receive handshake, need more data
* Operation timed out after 300984 milliseconds with 0 out of 0 bytes received
* Closing connection 0
* schannel: shutting down SSL/TLS connection with 127.0.0.1 port 29633
* schannel: clear security context handle
curl: (28) Operation timed out after 300984 milliseconds with 0 out of 0 bytes received

**Comment by Nokel81** [comment]
Is this the first time that you have launched Lens?

**Comment by mr-another-username** [comment]
No, i use it before, but in one day, i got this error. Maybe after update.

**Comment by Nokel81** [comment]
Could you try quitting Lens from the tray icon and then launching again and seeing if that resolves this issue?

**Comment by mr-another-username** [comment]
Sorry, problem was in corporate DLP.

**Comment by ghandour-ab787** [comment]
_**Got error when start Lens: Lens Proxy Error: Failed connection test d: request to [http://127.0.0.1](http://127.0.0.1:......**_

Solution:
This issue appears to be reproducible when I have the _HTTP Debugger v9.12_ application open and running. However, upon closing the HTTP DEBUGGER application and attempting to reopen Lens, it functions properly.
