### ISSUE TITLE
Lens freezes on namespace selection for cluster with 20k namespaces

### ISSUE THREAD

**Issue by jpastoor** [kontena/lens#7590]
Hi,

For our cluster we are running 20k different namespaces. Most of Lens runs perfectly fine with it, but the namespace dropdown is causing the application to lag considerably or even become unresponsive. I understand this might be a niche usecase having so many namespaces. This makes Lens not usable for us in production,  so hopefully this is resolvable. Thanks in advance!

**Comment by Nokel81** [comment]
Thanks for reporting this, we will certainly take a look at improving this.

**Comment by jpastoor** [comment]
Thanks a lot for fixing this. I'll be wearing my Lens shirt the next time I go to the office to celebrate
