### ISSUE TITLE
The error toast message vanishes very quickly. It should not auto-dismiss.

### ISSUE THREAD

**Issue by kcak11** [kontena/lens#7591]
**What would you like to be added**:
The error toast message should not be dismissed automatically and should wait for the user to close it.

**Why is this needed**:
When doing certain operations e.g.: a release upgrade, sometimes there is a failure and LENS displays the error message in the form of a toast message at the top-right corner. However, this toast message is auto-dismissed **_within less than 5 seconds_** and the user cannot even read the error message properly. 

The suggestion here is that the error toast messages (red toasts) should **not** get dismissed automatically and instead wait for user interaction. 

The success toast messages (green toasts) can continue to be dismissed automatically.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS, GKE & OpenShift
- Desktop OS: MacOS Ventura 13.3.1 (22E261)

**Comment by Nokel81** [comment]
Note for the time being, if you mouse over the notification that delays the auto-closing of them.

**Comment by kcak11** [comment]
> Note for the time being, if you mouse over the notification that delays the auto-closing of them.

Ahh, good to know!

I would still suggest that this item be considered as an enhancement, because the user might be in a different window (a different app) and might not even be aware that there was an error such that when the user returns to the LENS window, the error toast would have already been auto-dismissed. 

So having a user to **manually dismiss** an error toast would be a better UX in my opinion.

**Comment by Nokel81** [comment]
This has been resolved by #7599. Error notifications now don't auto close by default.

**Comment by kcak11** [comment]
Thank you @Nokel81

**Comment by kcak11** [comment]
The issue is still not resolved i.e., the error toast message disappears in less than 5 seconds automatically without allowing the user to read the error message/content.

LENS Version Details:
<img width="259" alt="image" src="https://github.com/lensapp/lens/assets/703559/7b6568a5-4298-49cd-9a99-3488a9206b11">

@Nokel81 fyi.
