### ISSUE TITLE
docs are for yum-config-manager, not dnf

### ISSUE THREAD

**Issue by unusualevent** [kontena/lens#7602]
**Describe the bug**
Your docs specify instructions for yum-config-manger, when DNF is newer

**To Reproduce**
1. follow the docs at https://docs.k8slens.dev/getting-started/install-lens/#rpm
2. command isn't on modern Fedora setups

**Expected behavior**
Instructions for modern Fedora & legacy setups

**Environment (please complete the following information):**
- Lens Version: latest?
- OS: Fedora 37
- Installation method (e.g. snap or AppImage in Linux): RPM

**Comment by SD-13** [comment]
@unusualevent thanks for reporting this, I also faced the same issue. To make it work, I used

> sudo dnf config-manager --add-repo https://downloads.k8slens.dev/rpm/lens.repo

to add the repo in fedora 37.

**Comment by Nokel81** [comment]
FYI @jim-docker
