### ISSUE TITLE
App crash opening Helm release

### ISSUE THREAD

**Issue by aleksfront** [kontena/lens#7617]
```
TypeError: Cannot read properties of undefined (reading 'notes')
    at get notes [as notes]
```

How to reproduce:
1. Install `aspnet-core` Helm Chart.
2. Open associated release

https://user-images.githubusercontent.com/9607060/234199200-9cc7b1a0-eb86-41b2-a80c-025b2e681914.mov

**Comment by aleksfront** [comment]
Reproduced it also with arbitrary helm charts, not only with `aspnet-core`

**Comment by clrothmann** [comment]
To reproduce on Lens: 2023.4.252057-internal as well
