### ISSUE TITLE
Problem with building after switching branches

### ISSUE THREAD

**Issue by Nokel81** [kontena/lens#7693]
**Describe the bug**
If there is package X on branch X' and you have run `npm run build` while X' is checked out and you checkout branch Y' which does not include package X and you try to run `npm run build` again, it will fail due to missing that package.

**Comment by Nokel81** [comment]
For instance the `@k8slens/list-layout` package sometimes is complained about when switching between a branch that has it and a branch that doesn't/

**Comment by Nokel81** [comment]
or
```
Error: Did not find package @k8slens/react-testing-library-discovery in lockfile, please use 'add' command to add it explicitly.
```

**Comment by Nokel81** [comment]
Current workaround is:
```
npm run clean
npm run clean:node_modules
npm run ci
```

The "nx cache" might also have to be cleared.

**Comment by jansav** [comment]
Might be solved by latest DX improvements e.g. https://github.com/lensapp/lens-desktop-monorepo/pull/97 https://github.com/lensapp/lens-desktop-monorepo/pull/69
