### ISSUE TITLE
main window empty after connect

### ISSUE THREAD

**Issue by matti** [kontena/lens#7710]
Connection spinner was running as usual and then:

<img width="1919" alt="image" src="https://github.com/lensapp/lens/assets/3893/01daf004-809a-42b9-a21a-0fe100851321">

**Comment by lekspyl** [comment]
Getting similar issue with v2023.5.100746-latest. Tried reinstalling the app, did not help. 
<img width="1920" alt="Screenshot 2023-05-11 at 00 46 13" src="https://github.com/lensapp/lens/assets/31690776/dc4b5a5c-6945-4582-b356-fa868fcd1b95">

**Comment by made-terry** [comment]
I got the same issue as @lekspyl after updating to. 2023.5.100746-latest Main screen is just blank

**Comment by msa0311** [comment]
@matti it looks like you are you on alpha, is this correct?
@made-terry @lekspyl we are looking into this!

**Comment by made-terry** [comment]
> @matti it looks like you are you on alpha, is this correct? @made-terry @lekspyl we are looking into this!

@msa0311 The latest update solved it for me.

**Comment by matti** [comment]
@msa0311 yes, forgot about it. now on stable and it works

**Comment by Nokel81** [comment]
This issue has been fixed by a change in one of the private bundled extensions and the next alpha will contain the fix. Closing now.
