### ISSUE TITLE
Unable to Enable Lens CLI in Settings under MacOs, Toggle Switch Inactive

### ISSUE THREAD

**Issue by jkuehnemundt** [kontena/lens#7751]
**Describe the bug**
When attempting to enable the Lens CLI in the settings, the toggle switch does not change its state, and users are unable to utilize the CLI functionality. This bug prevents users from accessing and utilizing the Lens CLI functionality, limiting their ability to perform command-line operations and automation tasks.

**To Reproduce**

1. Open the Lens application.
2. Go to the Settings menu.
3. Navigate to the "Apps" section.
4. Locate the option to enable the Lens CLI.
5. Attempt to toggle the switch to the "on" position.

**Expected behavior**
The toggle switch should change its state to indicate that the Lens CLI has been enabled successfully.

**Environment (please complete the following information):**
- Lens Version: 2023.5.120950-latest
- OS: MacOs
- Installation method (e.g. snap or AppImage in Linux): brew install --cask lens and .dmg installation

**Comment by panuhorsmalahti** [comment]
Could you try the alpha release, we've made some fixes for CLI install in it.

**Comment by jkuehnemundt** [comment]
Thank you! 
Lens: 2023.5.251645-alpha fixed the issue.
