### ISSUE TITLE
Cannot build 6.5.0

### ISSUE THREAD

**Issue by ogarcia** [kontena/lens#7793]
Arch Linux packager here.

To package lens on Arch Linux we only need the output of `dist/linux-unpacked`, previously we could create this by simply running the following:
```shell
yarn
yarn run build
cd packages/open-lens
yarn run build:dir
```

With the 6.5.0 update I can't find the equivalent method to ONLY create `dist/linux-unpacked` as if I use `yarn run build:app` it tries to create all the packages and fails due to Debian dependencies.

What would be the actual method to ONLY create `dist/linux-unpacked`?

**Comment by Jeansen** [comment]
Same here. Building 6.4.x worked just fine, all the time. 6.5 won't build, anymore.

**Comment by agologan** [comment]
The project was switched from yarn to npm #7115

To build use this:
```
npm install -g npm@^9.6.7
npm install
npm run build
npm run build:app
```

To avoid other issues remove `node_modules` when switching from **yarn** to **npm**.

**Comment by ogarcia** [comment]
> The project was switched from yarn to npm #7115
> 
> To build use this:
> 
> ```
> npm install -g npm@^9.6.7
> npm install
> npm run build
> npm run build:app
> ```

Ok, but `npm run build:app` builds all binaries. We only need `dist/linux-unpacked` to avoid rpm and deb dependencie failures

**Comment by agologan** [comment]
Sorry, misunderstood **build:dir** was `npm run compile && electron-builder --dir`
Removed here: f2247adfdbf4a67083bcfb269a63771259b431ea

**Comment by ogarcia** [comment]
> Sorry, misunderstood **build:dir** was `npm run compile && electron-builder --dir` Removed here: [f2247ad](https://github.com/lensapp/lens/commit/f2247adfdbf4a67083bcfb269a63771259b431ea)

Yes, I've seen that too and it doesn't make it clear to me how you can now do what you used to do with that command.

**Comment by jakolehm** [comment]
@ogarcia try `npm run build:app -- --scope=open-lens -- --dir`.

**Comment by ogarcia** [comment]
> @ogarcia try `npm run build:app -- --scope=open-lens -- --dir`.

Thanks! That command did the trick!

**Comment by tracure1337** [comment]
@ogarcia  would you package openlens too? That'd be so nice.
