### ISSUE TITLE
Endless Couldn't refresh your subscription for Lens ID ERROR Reactivate loop

### ISSUE THREAD

**Issue by sre-data-engineer** [kontena/lens#7838]
**Describe the bug**
Endless loop with
> Lens Desktop is Running Now. Enjoy!
and
> Couldn't refresh your subscription for Lens ID

**To Reproduce**
1. Logined with Github
2. Selected FREE Plan and CONFIRMed it

**Expected behavior**
Running Lens

**Screenshots**
[Application window](https://i.imgur.com/ij1Beuz.png)

**Environment (please complete the following information):**
- Lens Version: 2023.5.310801-latest
- OS: Windows 10 Pro 22H2 10.0.19045.2965
- Installation method (e.g. snap or AppImage in Linux): .exe with UAC and admin rights

**Comment by sre-data-engineer** [comment]
FIXED with Activation code CopyPaste

**Comment by binyellow** [comment]
I also encountered this problem, how did you solve it?
