### ISSUE TITLE
Outdated information about Lens Metrics and Lens Security in the documentation

### ISSUE THREAD

**Issue by alexrubtsov** [kontena/lens#7843]
**Describe the bug**
The content of https://docs.k8slens.dev/cluster/cluster-settings/ is different from current structure of menu.

**Actual behavior**
The documentation desribes the following structure of the menus:
- Cluster settings > Extensions > Lens Metrics
- Cluster settings > Extensions > Lens Security

**Expected behavior**
The documentation should describe the flat structure of the menus and their new names:
- Cluster settings > Builtin Metrics Provider
- Cluster settings > Lens Security Center

**Screenshots**
![image](https://github.com/lensapp/lens/assets/11317372/37429d7d-eb6d-44d8-9d3e-d5c89177bd2e)

**Environment**
- Lens Version: 2023.5.310801-latest
- OS: Windows
- Installation method: exe file from the website

**Comment by dzhigzhitzhapov** [comment]
@alexrubtsov updated the following pages to reflect the latest Lens Desktop UI:
- https://docs.k8slens.dev/cluster/cluster-settings/
- https://docs.k8slens.dev/security-center/advanced-settings/
