### ISSUE TITLE
Helm release update windows contains old cached values, results in reverting user-values to old settings

### ISSUE THREAD

**Issue by richard-fairthorne** [kontena/lens#7850]
**Describe the bug**
After clicking on a "helm release" from the releases list, the editor in the side-overlay shows old, cached values. Updating from this window will undo any changes you have made.

**To Reproduce**
1. Create a release
2. Wait for release to deploy
3. Click on the release
4. Use "upgrade button"
5. Change some values in editor at bottom of screen.
6. Wait for deploymnent
7. Click on the release again but do not click "upgrade"
8. In the editor displayed at the side, the data is old, and will result in your values reverting.
9. You can update them by toggling the "user-supplied-values" button.

**Expected behavior**
Values displayed should be up to date, not old cached data.

**Screenshots**
<img width="716" alt="Screenshot 2023-06-16 at 9 39 52 AM" src="https://github.com/lensapp/lens/assets/1225460/48916d77-d48d-4956-b55f-a48441b43622">
This screenshot shows old cached data. It can be updated by toggling the User-supplied values only checkbox.

**Environment (please complete the following information):**
- Lens Version: 2023.5.310801-latest
- OS: osx
- Installation method (e.g. snap or AppImage in Linux): brew (followed by automatic updates)

**Comment by clrothmann** [comment]
Thx @richard-fairthorne for reporting. Fix will be included in our next release
