### ISSUE TITLE
Metrics doesn't work for every container in POD with few containers

### ISSUE THREAD

**Issue by kruchkov-alexandr** [kontena/lens#7854]
**Describe the bug**
After upgrading to new version the metrics are not displayed for each individual container within a pod when there are multiple containers. For PODs with one container there are not issues.

**To Reproduce**
1. Go to Workloads ->PODs-> choose any POD with 2 or more containers
2. Click on it 
3. Scroll down to information about each container `Containers`
4. See error ` Metrics not available at the moment`
5. (Optional) Click on the `memory` and back to `CPU`

**Expected behavior**
CPU/Memory/Filesystem metrics 

**Screenshots**
<img width="1192" alt="image" src="https://github.com/lensapp/lens/assets/24195493/50b2bff2-6689-4169-8fa3-11dbc5921282">

**Environment:**
- Lens Version: lens 2023.5310801-latest
- OS: Latest MacOS + Windows 11
- Installation method (e.g. snap or AppImage in Linux): Download from https://k8slens.dev/

**Comment by wand2016** [comment]
+1

6.4.15 works.

**Comment by JaySeletz** [comment]
+1 - I am experiencing this on the latest Lens (2023.5.310801-latest) using the built in Metrics Provider
