### ISSUE TITLE
The Lens window only opens in full screen on Windows 11

### ISSUE THREAD

**Issue by kashirin-dm** [kontena/lens#7868]
**Describe the bug**
The Lens window only opens in full-screen mode and cannot be moved between monitors. I can only either minimize the window entirely or close the program. This problem has arisen relatively recently.

Unfortunately, this is all the information I can provide.

**To Reproduce**
1. Just run Lens.

**Environment (please complete the following information):**
- Lens Version: Latest
- OS: Windows 11

**Comment by jobaeurle** [comment]
was this fixed @kashirin-dm in some version?
I have installed latest openlens (6.5.2-366) but on windows 10 it still just opens in full screen and I always have to click "Toggle Full Screen" in order to drag it around the screens...

**Comment by maxpain** [comment]
The same problem on macOS
<img width="383" alt="image" src="https://github.com/lensapp/lens/assets/5875582/3e845342-7ee1-41c1-8bc9-c4e5a3de76f0">
