### ISSUE TITLE
Error on MacOs after update to lates version

### ISSUE THREAD

**Issue by bogdanioanliviu** [kontena/lens#7889]
**Describe the bug**

**To Reproduce**
1. Update from a preview version to last
4. See error:
```
Error stack:

Error: Tried to get a composite but encountered non-unique ids: "sidebar-item-aquasecurity--trivy-operator-lens-extension"
    at https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:116105:15
    at https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:171584:43
    at trackDerivedFunction (https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:372769:18)
    at ComputedValue.computeValue_ (https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:372569:13)
    at ComputedValue.trackAndCompute (https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:372555:25)
    at ComputedValue.get (https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:372524:18)
    at https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:669543:49
    at Array.map (<anonymous>)
    at https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:669543:22
    at trackDerivedFunction (https://4538563f3ddfc6a45748dd9b33b3aa43.lens.app:53353/build/lens.js?0c672a6d489bd2c3ee45:372769:18)
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 2023-8-31525
- OS: [e.g. OSX] macOS Ventura 13.4.1
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
your kubeconfig here
```

**Additional context**

workaround is to disable the Trivy extension. once disabled lens works again. enable the trivy extension same error appear.

**Comment by jameswald** [comment]
This issue is probably happening to anyone who enabled the trivy integration on the latest stable release of Lens. Most of my team has this problem right now as well.

**Comment by jameswald** [comment]
Here's a screenshot of the workaround mentioned by @bogdanioanliviu. Go to Lens > Extensions and disable the trivy extension:

![Screenshot 2023-08-09 at 3 45 56 PM](https://github.com/lensapp/lens/assets/875535/109f7bcb-12ba-4daa-a2ce-73cbfcd8592c)

**Comment by Nokel81** [comment]
A fix has been made and will be part of the next Lens Desktop release
